### ISSUE TITLE
File Field not working on action

### ISSUE THREAD

**Issue by Pro-Empresa** [laravel/nova-issues#3555] opened 2021-09-15 11:33 UTC
- Laravel Version: 8.53.1
- Nova Version: 3.28.0
- PHP Version: 7.4.3
- Database Driver & Version:
- Operating System and Version: ubuntu 20.04
- Browser type and version: firefox
- Reproduction Repository: https://github.com/###/###

### Description:

File field not working on action and the path saved is something like /tmp/phpN4B6Ab

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a new action and create a file field on fields function and try to get de file path name on handle function using dd()

**Comment by crynobone** [comment] 2021-09-15 11:36
Duplicate of #3508

**Closed by crynobone** 2021-09-15 11:36 UTC
