### ISSUE TITLE
Nova 2.0.5: HasMany, BelongsToMany and HasOne relationships get data from server, but not render grid view in details

### ISSUE THREAD

**Issue by wemersonrv** [laravel/nova-issues#1629] opened 2019-05-26 13:45 UTC
- Laravel Version: 5.8.17
- Nova Version: 2.0.5
- PHP Version: 7.2.11
- **Operating System and Version: Windows 10 64 bits has the issue**
- **Operating System and Version: Ubuntu Server 18.04 64 bits WORKS FINE**
- Browser type and version: Google Chrome 74.0.3729.157
- Reproduction Repository: https://github.com/wemersonrv/nova-relation-issues/blob/f7c8c7698cb87ffb2bb2a504f73ffbff9e073b72/app/Nova/Usuario.php#L158

### Description:
Nova relationship fields `HasOne`, `HasMany`, `BelongsToMany`  views are not rendering the grid view with related data.

The fields are fine, they recover the right related data from server-side but not render the view. see image below, that the related data is fine, but view not render.

Everything works fine before, but after upgrading to the new 2.0.5 these issues starts. 

**Important update**: This issue is fine in **Linux**, only in Windows it happens. Test in windows 10... try to remove vendor and composer.lock and `composer update` again... republish the assets and to all agan.... not works in windows!

![related](https://user-images.githubusercontent.com/2028673/58382306-13c95500-7f9f-11e9-9673-f56882084407.png)

### Steps To Reproduce:

1. Add the first user with administrator privileges, using custom command `php artisan user:new` 
![admin](https://user-images.githubusercontent.com/2028673/58382368-acf86b80-7f9f-11e9-80de-bb0275503d73.png)

2. Go to `Usuario` resource and Add a `Usuario` with a valid Brazilian CPF. And set all boolean options to `true`, save him and go to his detail page.

* Use the service https://www.4devs.com.br/gerador_de_cpf to generate a valid Brazilian CPF

3. Create new `Informações do(a) Cliente`  and `Informações do(a) Veterinário(a)`  **HasOne** related data...

At this point you will see the view not render fine, but the data recovered from server-side not works.

**Comment by wfeller** [comment] 2019-05-26 14:11
I've got the same issue, the data is retrieved from the server, but then sometimes gets displayed, and sometimes doesn't (keeps showing the loading animation).

- Laravel Version: 5.8.18
- Nova Version: 2.0.5
- PHP Version: 7.3.4
- Operating System and Version: macOS Mojave 10.14.5
- Browser type and version: Safari 12.1.1 (14607.2.6.1.1)

**Comment by wemersonrv** [comment] 2019-05-26 17:16
> I've got the same issue, the data is retrieved from the server, but then sometimes gets displayed, and sometimes doesn't (keeps showing the loading animation).
> 
> * Laravel Version: 5.8.18
> * Nova Version: 2.0.5
> * PHP Version: 7.3.4
> * Operating System and Version: macOS Mojave 10.14.5
> * Browser type and version: Safari 12.1.1 (14607.2.6.1.1)

Yep @wfeller this is happening a lot, and in my case; it's slow too... **very slow**. A request to show a index resource with only 3 records that takes less than 3 to 5 seconds before, now is taking about 30secs... even 50 secs and sometimes with timeout.

Talked a lot via email with nova support about this (and other) 2.0.5 issue about 10 days ago from now. So they know about this... I opened this issue here to mantain it documented.... And support does not respond to me for **5 days**, since I emailed them some code samples to verify! **So i believe they are working hard in a fix to this problems**

**Comment by tumispro** [comment] 2019-05-28 09:04
Same issue. It happens in every browser sometimes. When it happens to a user, he or she often can't get it to work again and has to switch to another browser temporarily. Clearing cookies doesn't seem to help. It then starts working again at random, the next day for example.

**Comment by FaridAghili** [comment] 2019-05-30 06:02
Same here
Laravel Version: 5.8.17
Nova Version: 2.0.5
PHP Version: 7.2.11

I guess this on occurs on Windows (10?) cause when I moved to exact code to an Ubuntu system it works.

**Comment by wemersonrv** [comment] 2019-05-30 10:42
> Same here
> Laravel Version: 5.8.17
> Nova Version: 2.0.5
> PHP Version: 7.2.11
> 
> I guess this on occurs on Windows (10?) cause when I moved to exact code to an Ubuntu system it works.

Yep, same to me. In linux server works. This really is an windows issue!

**Comment by wemersonrv** [comment] 2019-05-30 21:02
More details now, i think this is not a laravel nova issue. But with PHP embed server...

Works in a couple of servers in linux and windows, nginx, apache, etc.. not works with **embed php server** when uses `php artisan serve`... See below working fine even in windows when not use embed php server: 

![image](https://user-images.githubusercontent.com/2028673/58664337-d3523a00-8304-11e9-8557-4f61c27e7bc7.png)

**Comment by tumispro** [comment] 2019-05-30 22:39
I’m using neither php artisan serve nor Windows and do experience the issue, although irregularly. It happens since 2.0.5, I do think it’s related to the update. For me this issue definitely isn’t closed.

**Comment by FaridAghili** [comment] 2019-05-31 00:41
I don't use php server, I'm using nginx and I don't think it's server related, because as said in first post, the is retrieved in browser, but it doesn't render the view.

**Comment by wemersonrv** [comment] 2019-05-31 00:48
> I don't use php server, I'm using nginx and I don't think it's server related, because as said in first post, the is retrieved in browser, but it doesn't render the view.

Yep.. retrieve data from the server.. both in embed php server with artisan, and nginx server... 

**But**...  See the image below: Same code, same files... just differente servers pointing the same project... both retrieving data, but one works, other nope. Soo i thing even in view it's server related because the views are loaded in server too.

https://user-images.githubusercontent.com/2028673/58664337-d3523a00-8304-11e9-8557-4f61c27e7bc7.png

**Comment by FaridAghili** [comment] 2019-05-31 00:57
Same environment, same web server (nginx), same database (mysql), same everything (!), version 2.0.5 of Nova doesn't work, earlier versions work.

Closing the issue and ignoring doesn't solve the problem, this is a bug existing out there.

**Comment by wemersonrv** [comment] 2019-05-31 01:23
> Same environment, same web server (nginx), same database (mysql), same everything (!), version 2.0.5 of Nova doesn't work, earlier versions work.
> 
> Closing the issue and ignoring doesn't solve the problem, this is a bug existing out there.

Farid, i **really** think the problem is with nova... that conflicts with some servers... and other observation: with embed php server with artisan the result is toooooo slow... but so much slow!

I close the issue because it was pointed to others... but i will let it open again... Its my interest that laravel nova staff see it and resolve. of couse.

**Comment by jonowat** [comment] 2019-05-31 09:19
I'm getting this too, running on Windows with `artisan serve`.  The issue appears to be that the loading state of the card is not being reset after fetching the resources.

Within the `resources\js\views\Index.vue` file:

There seems to be a slight discrepancy with the timings that the getResources executes between a resource index and as a relationship table, so the `getLenses` is setting `this.loading = true` after `getResources` has already finished and set `this.loading = false`.

The fix I have found is to rearrange the `getLenses` :
From:
```
getLenses() {
            this.lenses = []
            this.loading = true
            
            if (this.viaResource) {
                return
            }
            ....
}
```


To:

```
getLenses() {
            this.lenses = []
            if (this.viaResource) {
                return
            }
            this.loading = true
            ....
}
```

**Comment by wemersonrv** [comment] 2019-05-31 10:44
For me o solve by not use embed server. So install nginx.

**Comment by davidgabbay** [comment] 2019-06-01 19:40
same problem, relationship does not show. its forever loading with Chrome. however when using Firefox its working well. im using Xampp on Win10 and Microsoft SQL server, Laravel 5.8 and nova 2.05

**Comment by pktharindu** [comment] 2019-06-02 03:47
Related to #1608 and #1610.
I guess we'll have to wait for the Nova 2.0.6 version.

**Comment by DanielDarrenJones** [comment] 2019-06-05 14:16
Can also confirm this issue, happens on macOS running Laravel Valet.

Downgrading to nova 2.0.3 fixed for me, but I haven't tested in 2.0.4.

This feels like a race condition issue, and is likely tied to Vue.

**Comment by wemersonrv** [comment] 2019-06-05 23:17
@pktharindu i guess laravel nova staff does not care about theyur paid customers. I buy single and pro licences, sent them email about this a couple of weeks ago and after some emails, about update issues; i show them the problem and **they nerver answered me**. this scares me because i pay for a product to receive support, or at least some information about informations i've sent to them. but they don't give a minimum consideration... This issue has 10 days now, and i've email support again and tell about this specific issue related to the email i've sent them before. BUT NO ONE ANSWER ME FOR SOME WEEKS. And i pay for the product... This is very bad considering the price of the licenses and the negligence of not giving us more information and ignoring the emails of paid customers.

Other information... Guys, forget what i'm say about embed php server versus nginx or apache server... see the prints below, that not works on each server i've try... sometimes works, sometimes nope!!!! See below some prints of same screen after a F5 refresh... works, not works, works again. Sometimes i need to refresh page 10 times to get all relations working... 

![image](https://user-images.githubusercontent.com/2028673/58996333-18c3ab00-87ce-11e9-8c88-9aeca262e1d5.png)

![image](https://user-images.githubusercontent.com/2028673/58996354-2f6a0200-87ce-11e9-81c4-e1c12e812b6d.png)

![image](https://user-images.githubusercontent.com/2028673/58996394-63452780-87ce-11e9-82b2-c48dbc78f07b.png)


![image](https://user-images.githubusercontent.com/2028673/58996434-91c30280-87ce-11e9-8ad8-64659281bf0e.png)

**Comment by tharindu-abans** [comment] 2019-06-06 09:48
My company brought the license on my recommendation and now they are trying to bite my head off for this. I reported this bug 20 days ago (#1608) and it was marked as closed the very next day. But no new releases have been released so far.

I got nothing but love for the Nova. But I strongly feel that these type of issues should be addressed way sooner as it renders the whole app unusable.

**Comment by preliot** [comment] 2019-06-06 09:54
In another bug report, it's stated this is fixed in 2.0.6. However, this is not yet released.

(I'm luckely still in production with my application, but indeed, i too find updating to slow.)

**Comment by pehbehbeh** [comment] 2019-06-06 10:28
We also love Nova for the most parts but things like that destroy the overall picture. 😞 

I can not believe this has been fixed for almost three weeks now and still no release... https://github.com/laravel/nova-issues/issues/1608#issuecomment-493686855

Issues like that should be hotfixed ASAP because Nova is unusable right now.

We are basically forced to use an older release which also has it's own annoying bugs (e.g. pagination #1514) ... which are fixed in an even more broken release. 😑

Would really appreciate an ETA from @davidhemphill on this.

It is hard to explain this to anybody. I have to assume there are some good reasons behind this and IMHO the Nova team owes an explanation to all paying customers.

**Comment by wemersonrv** [comment] 2019-06-10 17:29
> We also love Nova for the most parts but things like that destroy the overall picture. 😞
> 
> I can not believe this has been fixed for almost three weeks now and still no release... [#1608 (comment)](https://github.com/laravel/nova-issues/issues/1608#issuecomment-493686855)
> 
> Issues like that should be hotfixed ASAP because Nova is unusable right now.
> 
> We are basically forced to use an older release which also has it's own annoying bugs (e.g. pagination #1514) ... which are fixed in an even more broken release. 😑
> 
> Would really appreciate an ETA from @davidhemphill on this.
> 
> It is hard to explain this to anybody. I have to assume there are some good reasons behind this and IMHO the Nova team owes an explanation to all paying customers.

Today they release the 2.0.6 version, but nothing about this issue yet! I believe this is scheduled to next version and hope it will be fixed soon!

**Comment by DanielDarrenJones** [comment] 2019-06-10 19:47
@wemersonrv have you testing to see if this fixes the issue?

**Comment by wemersonrv** [comment] 2019-06-11 00:43
> @wemersonrv have you testing to see if this fixes the issue?

Nope because 2 reasons: 

1. It's not in release changelog
2. I don't have time, this issue (and others) take me a lot of time and i need to make some releases to my customers first before take adventures by testing new nova releases... 

For now, 2.0.3 it's my oficial version till i test, test, test, test and test again because i like nova although the new team does not care about us!!! So this is my PRODUCTION release for now!

**Comment by preliot** [comment] 2019-06-11 11:41
Just downloaded 2.0.6 and tested it in my application. Now related resources are visible again.

@wemersonrv If you have time, test it with a seperate branch. Easy to rollback.

**Comment by wemersonrv** [comment] 2019-06-11 18:03
@DanielDarrenJones and @preliot Updated one project to test first and it showing all relations, both in nginx/apache server and in PHP embed server via `php artisan serve`... The only issue is that with embed server is **slow**, but i believe it's a php problem not by laravel framework or laravel nova.

Just to be sure, I removed the `vendor` folder and `composer.lock` file, updated the composer and reinstall all packages again. Apparently everything is ok so far, no more such problems. I did refresh the screens about 20 times and it always worked OK!

**Comment by pehbehbeh** [comment] 2019-06-13 09:48
Seems to be working fine with `2.0.6`. Don't forget to `artisan nova:publish` the assets. 😉

**Comment by davidhemphill** [comment] 2019-06-28 19:41
This issue seems fixed. If the issue is persisted in recent versions, please open a new issue.

**Closed by davidhemphill** 2019-06-28 19:41 UTC

**Comment by incraigulous** [comment] 2019-08-28 23:43
This is still happening for me on the latest version using Valet. Absolutely not fixed yet.

**Comment by Lippur** [comment] 2020-01-02 18:09
This still happens almost every time when viewing a resource, even after clearing all caches. Loading some of the panels fails, sometimes giving a toast of "Unauthenticated", sometimes not.

**Comment by Lippur** [comment] 2020-01-10 13:47
So the fix appears to be to use a **non thread safe** build of PHP on Windows. So far, it has resolved the issue.

**Comment by 4devs-net-br** [comment] 2021-10-02 18:21
https://4devs.net.br/gerador-cpf
