### ISSUE TITLE
Uri and Label Customizing Dashboards

### ISSUE THREAD

**Issue by codegor** [laravel/nova-issues#2978] opened 2020-10-20 16:00 UTC
- Laravel Version: 8.1
- Nova Version: 3.12.1
- PHP Version: 7.4.2
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://nova.laravel.com/docs/3.0/customization/dashboards.html

### Description:
- PreviousNova Version: 3.8.3

Customizing Dashboards:
public static function label()
public static function uriKey()

can you revert to previus non static variant?

public function label()
public function uriKey()

### Detailed steps to reproduce the issue on a fresh Nova installation:

This method was but it was not STATIC! in version 3.8.3 it was non static, which made it possible to dynamically assign url and label.

I have a single class, which create dashboard for every admin in my app, and when I create dashboard in NovaServiceProvider I only assign email and id (from email and id I generate url and label for dashboard) of admin and I have receive an instance of dashboard for each admin (admins is variable, I dont know who will be admin in future)

After I have updated to v3.12.1 that methods became static and today I cannot dynamic generate dashboards for each admin.

Can You help with this? Can you return to non static methods?

Code below was worked before update, but after not, so it is very sad...

```
use App\User;
use Illuminate\Support\Str;
use Laravel\Nova\{AuthorizedToSee, Element, Metable, Makeable, ProxiesCanSeeToGate};
use App\Nova\Metrics;

class AdminDashboard extends Element {
        use AuthorizedToSee, Metable, Makeable, ProxiesCanSeeToGate;
	
	public $name = null;
	public $admin= null;
	public $email = null;
	
	public function setAdmin($Admin) {
		$this->admin= $Admin;
		return $this;
	}
	
	public function setName($name) {
		$this->name = $name;
		return $this;
	}
	
	public function setEmail($email) {
		$this->email = $email;
		return $this;
	}
	
	/**
	 * Get the cards for the dashboard.
	 *
	 * @return array
	 */
	public function cards() {
		return [
                   (new Metrics\....),
                   ......
		];
	}
	
	/**
	 * Get the displayable name of the dashboard.
	 *
	 * @return string
	 */
	public function label() {
		return $this->$name;
	}
	
	/**
	 * Get the URI key for the dashboard.
	 *
	 * @return string
	 */
	public function uriKey() {
		return Str::slug($this->label(), '-', null).'-'.str_replace('@', '_', strtolower($this->email));
	}

}



use Laravel\Nova\NovaApplicationServiceProvider;

class NovaServiceProvider extends NovaApplicationServiceProvider {

    .........

    /**
	 * Get the extra dashboards that should be displayed on the Nova dashboard.
	 *
	 * @return array
	 */
	protected function dashboards() {
		$admins = User::admins()->get();
		$res = [];
		foreach ($admins as $admin) {
			$res[] = (new AdminDashboard)->setEmail($admin->email)->setAdmin($admin->uuid)->setName($admin->firstname);
		}
		
		return $res;
	}
}
```

After update I have received this error 
https://i.imgur.com/YHO8nZz.png 
https://i.imgur.com/KoUEbYv.png

**Comment by davidhemphill** [comment] 2020-10-26 15:29
Duplicate of #2971

**Closed by davidhemphill** 2020-10-26 15:29 UTC
Labels: request

**Comment by alberto-bottarini** [comment] 2021-01-05 17:09
Take a look at: https://github.com/laravel/nova-issues/issues/3151
