### ISSUE TITLE
Attach Event is not store correctly in the Actions Events - Target Attribute is wrong

### ISSUE THREAD

**Issue by ronnytorresmtz** [laravel/nova-issues#2106] opened 2019-11-01 23:12 UTC
- Laravel Version: 6.4.0
- Nova Version: 2.5.0
- PHP Version: 7.2
- Database Driver and Version: MySQL 5.7.24
- Operating System and Version: Windows 10
- Browser type and version: Chrome

### Description

Attach Event is not store correctly in the Actions Events Table - Target Attribute is wrong

### Steps To Reproduce

I have a many to many relationship after I create an attach, the Action Event store the Target attribute incorrectly.

The Deatach Action store the target attribute correctly (OK)

Regards,

**Comment by jbrooksuk** [comment] 2019-11-07 15:36
This appears to be a duplicate of https://github.com/laravel/nova-issues/issues/1959

**Closed by jbrooksuk** 2019-11-07 15:36 UTC
