### ISSUE TITLE
Repeatable fields not working in Action fields

### ISSUE THREAD

**Issue by mateusgalasso** [laravel/nova-issues#5758] opened 2023-07-28 15:23 UTC
- Laravel Version: 10
- Nova Version: 4
- PHP Version: 8.1

### Description:
Repeatable fields not working in Action fields

### Detailed steps to reproduce the issue on a fresh Nova installation:

Error on browser console 
<img width="1166" alt="image" src="https://github.com/laravel/nova-issues/assets/3990028/bb1ccd44-b8f1-435c-9553-33ea39e20dd7">

```php
class OrcamentoUtilizacaoItem extends Repeatable
{
    /**
     * Get the fields displayed by the repeatable.
     *
     * @param  NovaRequest  $request
     * @return array
     */
    public function fields(NovaRequest $request)
    {
        return [
            Text::make('Descrição', 'descricao'),
        ];
    }
}
```

Action Class: 
```php
public function fields($request)
    {
        return [
            Repeater::make('Line Items')
                ->repeatables([
                    \App\Nova\Repeater\OrcamentoUtilizacaoItem::make(),
                ]),
        ];
    }
```

**Comment by crynobone** [comment] 2023-07-28 23:13
Duplicate of #5718

**Closed by crynobone** 2023-07-28 23:13 UTC
