### ISSUE TITLE
Changing redirect after resource update

### ISSUE THREAD

**Issue by giojkd** [laravel/nova-issues#1570] opened 2019-05-04 23:04 UTC
Hi all, I have to redirect browser after updating any resource to a given url, until some status on the user logged changes, any suggestion?

**Comment by bolechen** [comment] 2019-05-04 23:50
Duplicate of #538

**Comment by davidhemphill** [comment] 2019-05-10 04:09
This has been added and will be included in the next release. 👍

**Closed by davidhemphill** 2019-05-10 04:09 UTC

**Comment by tumispro** [comment] 2019-05-19 22:03
So where do we configure this?

**Comment by tumispro** [comment] 2019-05-19 23:03
Was this added in 2.0.5? How do you configure it?

**Comment by jbrooksuk** [comment] 2019-10-01 09:45
Yes, you may override the `redirectAfterUpdate` method in your Resource.

**Comment by katieben** [comment] 2019-10-01 11:38
Ooh that is awesome, got it :D Thank you!!

**Comment by bolechen** [comment] 2019-12-23 01:07
```
    /**
     * Return the location to redirect the user after creation.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Laravel\Nova\Resource  $resource
     * @return string
     */
    public static function redirectAfterCreate(NovaRequest $request, $resource)
    {
        return '/resources/'.static::uriKey().'/'.$resource->getKey();
    }

    /**
     * Return the location to redirect the user after update.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Laravel\Nova\Resource  $resource
     * @return string
     */
    public static function redirectAfterUpdate(NovaRequest $request, $resource)
    {
        return '/resources/'.static::uriKey().'/'.$resource->getKey();
    }
```

**Comment by marcuschristiansen** [comment] 2020-01-16 06:49
I've tried to redirect to the next resource like this:

```
public static function redirectAfterUpdate(NovaRequest $request, $resource)
    {
        $nextResource = $resource->getKey() + 1;
        return '/resources/'.static::uriKey().'/'.$nextResource.'/edit';
    }
```

This changes the URL successfully but the form still contains the values from the previous resource. Any reason for this?
