### ISSUE TITLE
BelongsToMany Pivot Fields break when upgrading to Nova 3.12+

### ISSUE THREAD

**Issue by 949mac** [laravel/nova-issues#2980] opened 2020-10-21 06:13 UTC
- Laravel Version: 8.x
- Nova Version: 3.12+
- PHP Version: 7.4
- Operating System and Version: OSX Catalina
- Browser type and version: Chrome

### Description:

Pivot fields are lost when viewing/editing an attached record via BelongsToMany,

👉 Everything works as expected in Nova 3.11 ✅

**Nova 3.11**
![image](https://user-images.githubusercontent.com/23151962/96679506-a30ba100-1328-11eb-8e9b-fc42a122aaf7.png)

👉 Upgrading to Nova 3.12 breaks feature. ❗

**Nova 3.12**

![image](https://user-images.githubusercontent.com/23151962/96679609-d817f380-1328-11eb-8ef2-4c7c33cdfed8.png)

> :warning: Pivot fields are now missing from `viaResource` edit screen.
> :warning: Chrome Console is angry too.

![image](https://user-images.githubusercontent.com/23151962/96679632-e2d28880-1328-11eb-94e1-c3804ffe09f3.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a BelongsToMany w/ pivots Fields
2. Attach a record to the BelongsToMany in Nova
3. Observe attaching contains all fields as expected
4. Finally edit the attached row, and observe the error shown above.

**Comment by crynobone** [comment] 2020-10-21 06:20
@949mac Can you provide a reproducing code to trigger above exception. laravel/nova#1002 PR was made to fix similar issue based on `tests/Browser/UpdateAttachedPolymorphicTest.php` tests so I assume there might be some use-case that we haven't properly covered.

**Comment by anditsung** [comment] 2020-10-26 08:44
i think this is the same for belongsto. the issue is start from 3.11
on 3.10 it will fill the value when create from viaResource.
i have to go back to 3.10 from 3.13 to use this feature

**Comment by crynobone** [comment] 2020-10-26 09:29
@anditsung I unable to reproducing the error, would appreciate if anyone can share exactly how to reproduce the error.

**Comment by anditsung** [comment] 2020-10-26 10:02
> @anditsung I unable to reproducing the error, would appreciate if anyone can share exactly how to reproduce the error.

please check this https://github.com/anditsung/nova-issue-2967
already update with belongsto problem

Step
- add new people
- on people detail create new employee
- it will fill the value when using nova 3.10

update the nova 3.13 the value will not be fill

**Comment by crynobone** [comment] 2020-10-26 13:58
@anditsung I test your repo against latest Laravel Nova (unreleased) and unable to get any of the error as mention above.

**Comment by crynobone** [comment] 2020-10-26 14:18
Can confirmed that this has been fixed in 3.13.0

### 3.12.x
![image](https://user-images.githubusercontent.com/172966/97183697-0b4efc80-17d9-11eb-9b5d-3a644d07f9fa.png)

### 3.13.0
![image](https://user-images.githubusercontent.com/172966/97183788-2457ad80-17d9-11eb-8d96-35dde3741ea2.png)

**Closed by crynobone** 2020-10-26 14:18 UTC
Labels: needs more info

**Comment by anditsung** [comment] 2020-10-27 01:23
i dont think that was the problem

the problem i was referring to was this https://streamable.com/0eh549
the belongsto field doesnt get fill after using nova 3.11
but it working on nova 3.10

**Comment by crynobone** [comment] 2020-10-27 01:30
@anditsung if you have different issue don't hijack another issue. It become hard to debug what's actually is wrong.

**Comment by anditsung** [comment] 2020-10-27 01:58
i dont hijack other issue. i think my issue belongsto should be the same as the author.
im using the same repositories to show the issue

what you reply https://github.com/laravel/nova-issues/issues/2980#issuecomment-716576793 is my other issue not the same as i describe here https://github.com/laravel/nova-issues/issues/2980#issuecomment-716442985

**Comment by crynobone** [comment] 2020-10-27 02:30
Yes because I'm trying to reproduce error based on describe by the original poster. Please create a new issue for your problem.
