### ISSUE TITLE
Problem with CSV Export of Lenses using group by

### ISSUE THREAD

**Issue by kazak71** [laravel/nova-issues#5108] opened 2022-11-22 12:08 UTC
- Laravel Version: 9.x
- Nova Version: 4.x
- PHP Version: 8.1

### Description:
Hi, thank you for your Great NOVA!
I found a strange thing when I export Lenses with query containing group by clause.
Export works but only exports records when all resources are selected.
If records are manualy selected (e.g. Select Page) export produces an empty file.

Thanks in advance.

**Comment by crynobone** [comment] 2022-11-22 12:13
Possible duplicate of https://github.com/laravel/nova-issues/discussions/5020

Otherwise you need to submit reproducing code in order for us to debug it further.

**Comment by kazak71** [comment] 2022-11-22 12:44
Yes It is. It https://github.com/laravel/nova-issues/discussions/5020 sloves my problem. Thanks!!!

**Closed** 2022-11-22 12:57 UTC
