### ISSUE TITLE
Peeking popup problem

### ISSUE THREAD

**Issue by denniselsinga** [laravel/nova-issues#4980] opened 2022-10-27 18:35 UTC
- Laravel Version: 9.37.0
- Nova Version: 4.17.1
- PHP Version: 8.1.4
- Database Driver & Version:  -
- Operating System and Version: Mac OS Ventura (13.0)
- Browser type and version: Brave
- Reproduction Repository: -

### Description:

When using `->peekable()` the label text goes over the value (depending on the size of the label in characters)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Make a user (or anything with a long label name)  `->peekable()` (see screenshot)
<img width="362" alt="Scherm­afbeelding 2022-10-27 om 20 32 49" src="https://user-images.githubusercontent.com/23448484/198371016-5270076b-96d0-477b-8a8b-39430ac41a0d.png">

**Comment by crynobone** [comment] 2022-10-27 22:13
Duplicate of #4916

**Closed by crynobone** 2022-10-27 22:13 UTC
