### ISSUE TITLE
Inverse BelongsTo field

### ISSUE THREAD

**Issue by sgittel** [laravel/nova-issues#2843] opened 2020-09-08 15:09 UTC
It would be great, if there was a HasOne field that would behave like the BelongsTo field and be displayed inline instead of getting its own Panel with an index table with only one element. Even more so, if it was searchable and you could directly create inline relations as with the BelongsTo field. Basically, that would be an inverse BelongsTo field.

**Comment by davidhemphill** [comment] 2020-09-08 17:36
Duplicate of #2753

**Closed by davidhemphill** 2020-09-08 17:36 UTC

**Comment by sgittel** [comment] 2020-09-08 20:40
@davidhemphill This is not a duplicate, but a different approach. The solution you mentioned in #2753 is a Panel showing the details of the related entity. That seems to pollute the details view even more imho.
What I suggest is to have the HasOne behave like a BelongsTo showing only a link to the related entity on index and details and having a select dropdown on forms.

**Comment by khaledElnagar** [comment] 2022-09-13 17:38
any updates on this ?
