### ISSUE TITLE
How to translate flatpickr

### ISSUE THREAD

**Issue by victorpfm** [laravel/nova-issues#673] opened 2018-09-24 23:03 UTC
I want to translate flatipickr. How should I do it?

Had to edit /nova/resources/js/components/DateTimePicker.js:

```
import {Portuguese} from 'flatpickr/dist/l10n/pt.js'

(...)

mounted() {
        this.$nextTick(() => {
            this.flatpickr = flatpickr(this.$refs.datePicker, {
                (...)
                locale: Portuguese
            })
        })
    },

```
And recompile Nova. I believe I should override the definition of the date-time-picker component but don't know how.

**Comment by dillingham** [comment] 2018-09-25 01:45
Duplicate https://github.com/laravel/nova-issues/issues/343

**Comment by alexbowers** [comment] 2018-09-25 08:14
Duplicate of #343

**Closed by alexbowers** 2018-09-25 08:14 UTC
Labels: question

**Comment by isma907** [comment] 2019-11-21 14:25
**The correct way to translate the FlatPickr is:**

### NgModule file:
import { FlatpickrModule } from 'angularx-flatpickr';
import { Spanish } from 'flatpickr/dist/l10n/es.js';

`
@NgModule({
  declarations: [ ...  ],
  imports: [
         FlatpickrModule.forRoot({
            locale: Spanish
     }),
  ]
`


### Component Html File:
` 
<input class="form-control" type="text" mwlFlatpickr
                                    [formControl]="myControl" [enableTime]="true"
                                    [dateFormat]="'d/m/y H:i'">
`


![image](https://user-images.githubusercontent.com/7232299/69346224-376d0f80-0c51-11ea-814a-639eb9518c44.png)

**Comment by DIM29** [comment] 2019-11-21 14:28
> 
> 
> **The correct way to translate the FlatPickr is:**
> ### NgModule file:
> 
> import { FlatpickrModule } from 'angularx-flatpickr';
> import { Spanish } from 'flatpickr/dist/l10n/es.js';
> 
> `@NgModule({ declarations: [ ... ], imports: [ FlatpickrModule.forRoot({ locale: Spanish }), ]`
> ### Component Html File:
> 
> ` <input class="form-control" type="text" mwlFlatpickr [formControl]="myControl" [enableTime]="true" [dateFormat]="'d/m/y H:i'">`
> 
> ![image](https://user-images.githubusercontent.com/7232299/69346224-376d0f80-0c51-11ea-814a-639eb9518c44.png)

Thank you so much
