### ISSUE TITLE
Symfony \ Component \ HttpKernel \ Exception \ HttpException No message

### ISSUE THREAD

**Issue by rodwin** [laravel/nova-issues#718] opened 2018-09-27 22:21 UTC
This only happens when the environment is set to production

![image](https://user-images.githubusercontent.com/208163/46177743-27d18f80-c308-11e8-93d5-4859d6d662ff.png)

**Comment by bonzai** [comment] 2018-09-27 22:31
#707

**Comment by alexbowers** [comment] 2018-09-29 21:54
Duplicate of #707 which has a solution

**Closed by alexbowers** 2018-09-29 21:54 UTC
