### ISSUE TITLE
Currency field doesn't work on Windows because of money_format() incompatibility

### ISSUE THREAD

**Issue by Inquisitor** [laravel/nova-issues#1896] opened 2019-09-05 23:38 UTC
- Laravel Version: 5.8.35
- Nova Version: 2.2.0
- PHP Version: 7.1
- Database Driver and Version: MySQL 5.7
- Operating System and Version: Windows 10
- Browser type and version: Firefox 69

### Description

Hi! It seems that `Currency` field won't work on Windows, because it uses `money_format()` function that is undefined on Windows.
A quote from [the docs](
https://www.php.net/manual/en/function.money-format.php):

>**Note:**
>The function **money_format()** is only defined if the system has strfmon capabilities. For example, Windows does not, so **money_format()** is undefined in Windows.

In my case, it crashed on the resource's index page:

```[2019-09-05 23:17:53] local.ERROR: Call to undefined function money_format() {"userId":300,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function money_format() at D:\\Stan\\PokerUp\\www\\Nova\\src\\Fields\\Currency.php:27)```

### Steps To Reproduce

- Set up a project on Windows
- Add Currency field to a resource
- Go to resource's index page

**Comment by davidhemphill** [comment] 2019-09-06 15:39
Duplicate of #508
Duplicate of #1062

**Closed by davidhemphill** 2019-09-06 15:39 UTC

**Comment by dkulyk** [comment] 2019-09-09 10:30
@davidhemphill  money_format will be deprecated in 7.4
