### ISSUE TITLE
BelongsTo should allow an option to hide 'create relation' button

### ISSUE THREAD

**Issue by davi5e** [laravel/nova-issues#2370] opened 2020-02-20 17:42 UTC
- Laravel Version: 6.16.0
- Nova Version: v2.11.1 
- PHP Version: 7.3
- Database Driver & Version: PostgreSQL 12
- Operating System and Version: Docker PHP 7.3 FPM Alpine
- Browser type and version: Firefox 73.0 64-bits

### Description:

There should be a way to fully hide `CreateRelationButton` component in a BelongsTo field.

The same component is used both in `resources/js/components/Form/BelongsToField.vue` and `resources/js/components/Form/MorphToField.vue`, so I'd think this issue happens in a MorphTo field as well.

### Steps To Reproduce:

Create any BelongsTo field in a model which has creation enabled and is *not* readonly.

### Opinion:

Adding another configurable `field` and changing `canShowNewRelationModal()` should solve the problem:

```diff
diff --git a/nova/resources/js/components/Form/BelongsToField.vue b/nova/resources/js/components/Form/BelongsToField.vue
index fe22328..ea848a1 100644
--- a/nova/resources/js/components/Form/BelongsToField.vue
+++ b/nova/resources/js/components/Form/BelongsToField.vue
@@ -352,6 +352,7 @@ export default {
 
     canShowNewRelationModal() {
       return (
+        !this.field.hide &&
         !this.shownViaNewRelationModal &&
         !this.isLocked &&
         !this.isReadonly &&
```

**Comment by BenWalters** [comment] 2020-02-21 20:58
Was just about to create a ticket for this myself!

This feature, which was much needed came in are part of https://github.com/laravel/nova/pull/697. However it is clear, in my opinion, that there are scenarios where you should have the option to disable this.

**Comment by davidhemphill** [comment] 2020-02-22 20:03
Duplicate of #2348

**Closed by davidhemphill** 2020-02-22 20:03 UTC
