### ISSUE TITLE
Laravel Nova issue when creating Resource with BelongsTo relationship

### ISSUE THREAD

**Issue by jjelicDev** [laravel/nova-issues#3721] opened 2022-01-31 15:09 UTC
- Laravel Version: 8.42
- Nova Version: 3.23
- PHP Version: 8.0
- Database Driver & Version: MySQL
- Browser type and version: Chrome 97.0.4692.99

### Description:
Hello, there is an issue with BelongsTo relationship when you want to create new resource. Follow the example.

Let's say we have a Product and Category. 
Product belongs to only one Category (foreign key is 'category_id' in table 'product'). It is required field.
Inverse relationship is HasMany, meaning Category can have connection with zero or more Product(s).

In Laravel Nova, Resource class Product has "BelongsTo::make(Category, category, Category::class),".
Now when I want to create new Product and link it to some Category, the Select field is empty. No data at all. There are categories in table 'category'. 

My opinion is that BelongsTo relationship only looks for connected data(category that is connected with product), it doesn't allow you to have all categories from database when creating Product. You want to assign one category from Select field.

I hope you follow me.
Please fix this.

**Comment by crynobone** [comment] 2022-02-01 05:05
Please provide reproducing code such as https://github.com/nova-issues in order for us to follow the issue, what you describing is unclear at the moment.

> Now when I want to create new Product and link it to some Category, the Select field is empty. No data at all. There are categories in table 'category'.

The select field would show all categories by default if you have any, there are different outputs depending on how you configure `BelongsTo` field

> My opinion is that BelongsTo relationship only looks for connected data(category that is connected with product), it doesn't allow you to have all categories from database when creating Product. You want to assign one category from Select field.

When creating a product, category usually already exists but product doesn't hold `category_id` value yet since it is yet to be created. I don't understand what you want here and best to create a reproducing code repository with examples for us to debug the issue. 

p/s: This sound more like a feature request insteads of bug report at the moment.

**Comment by jjelicDev** [comment] 2022-02-01 10:54
Issue is quite simple, not need for reproducing code. 

> The select field would show all categories by default if you have any, there are different outputs depending on how you configure BelongsTo field

This doesn't work, I don't have any categories in select field. Simple as that. I have categories in database.
If there is advance documentation for BelongsTo please provide it. 
I followed official documentation from [Laravel nova Documentation](https://nova.laravel.com/docs/3.0/resources/relationships.html#belongsto)

This is not a feature.

Please remove **needs more info** label.

**Comment by crynobone** [comment] 2022-02-01 11:10
I can't reproduce what you describing, and without a reproducing code we wouldn't able to understand the problem and can't fix it. 

Do aware that we have an extensive dusk tests covering the usage and we would have caught if it really happening right now.

**Comment by davidhemphill** [comment] 2022-02-01 19:33
@jjelicDev I'm closing this. This feature is well-tested and without further context into your setup, we are unable to go further.

Please provide the reproducing behavior in a bare Laravel repository with a fresh Nova install. 

Also, please consider there are humans on the other side when choosing your tone. Being curt or rude will not get you what you want.

**Closed by davidhemphill** 2022-02-01 19:33 UTC
Labels: needs more info
