### ISSUE TITLE
Placement of resource names in translations

### ISSUE THREAD

**Issue by v1nk0** [laravel/nova-issues#412] opened 2018-09-03 13:37 UTC
I can translate static words of for example buttons (e.g. "Create" or "Update"), but I can't determine the position of the resource name in the translation itself.

For example the button to create a resource Post.
In English, this button is called "Create Post", because the resouce name is Post and my **en.json** contains:
`"Create": "Create",`

Works like a charm for English, but there are languages where this does not work.
For example German. The word "create" translate to "erstellen".
In my **de.json** I therefore have:
`"Create": "Erstellen",`

The button for German is now: **Erstellen Post**.
But this doesn't work for German. In German, the resource name comes first, therefore the button should be **Post erstellen**.
There are many other languages, like Dutch, where this also applies.

This could be easily fixed by adding the resource to the translations, e.g.:
English: `"Create": "Create :resource",`
German: `"Create": ":resource erstellen",`

_There is already one line in the json that already does it like this_:
`"No :resource matched the given criteria.": "No :resource matched the given criteria."`
The only problem with German here, is that resource name is forced into _all-lowercase_ (also when `label()` and `singlularLabel()` have the first char as uppercase on the resource) although a resource name in for example German should **always** (this applies to all nouns) start with a capital char.

**Comment by cannect** [comment] 2018-09-13 15:48
Any news on this one?

**Comment by alexbowers** [comment] 2018-09-29 18:07
Duplicate of #203

**Closed by alexbowers** 2018-09-29 18:07 UTC
Labels: request
