### ISSUE TITLE
On navigating to a Tool, vertical scroll disappears..

### ISSUE THREAD

**Issue by the-alichemist** [laravel/nova-issues#4293] opened 2022-05-20 22:14 UTC
- Laravel Version: Latest
- Nova Version: 4.6.1
- PHP Version: 8.1.4
- Database Driver & Version: 10.4.24-MariaDB
- Operating System and Version: Windows 11
- Browser type and version: Version 101.0.4951.67 (Official Build) (64-bit)
- Reproduction Repository: Private

### Description:
I traced the issue to vendor\laravel\nova\resources\js\layouts\MainHeader.vue. The said component watches mainMenuShown state in Vuex store. This state on navigation to a resource is set to false. However, on navigation to a Tool, mainMenuShown is set to true and the watcher in MainHeader.vue adds class 'overflow-y-hidden' to the html body which prevents vertical scrolling. 

### Detailed steps to reproduce the issue on a fresh Nova installation:
-Create a custom tool. 
-Navigate to the tool

**Comment by crynobone** [comment] 2022-05-21 02:18
Duplicate of #4281 and will be fixed on the next release.

**Closed by crynobone** 2022-05-21 02:18 UTC
