### ISSUE TITLE
External Links With Method Don't Work In UserMenu

### ISSUE THREAD

**Issue by jjjrmy** [laravel/nova-issues#4443] opened 2022-06-17 02:18 UTC
- Nova Version: 4.9.0

I'd like to have a Team switcher, I tried this and no request is being sent when you click the buttons in the User Menu.

```php
$request->user()->teams->each(fn($team) =>
    $menu->append(
       MenuItem::externalLink($team->name, route("current-team.update"))
           ->method('PUT', data: ['team_id' => $team->id])
           ->withBadgeIf('✅', 'success', fn()=>$request->user()->currentTeam->id===$team->id)
    )
);
```

**Comment by jjjrmy** [comment] 2022-06-17 02:21
Also it would be nice to to use Hero Icons in the badge or HTML

**Comment by crynobone** [comment] 2022-06-17 02:50
Duplicate of #4433

**Closed by crynobone** 2022-06-17 02:50 UTC
