### ISSUE TITLE
Cancel button in create form not redirect to index page if validation failed before

### ISSUE THREAD

**Issue by giangnh13579** [laravel/nova-issues#5581] opened 2023-05-28 09:15 UTC
- Laravel Version: Laravel Framework 9.27.0
- Nova Version: 4.18.2
- PHP Version: 8.1.8

### Description:
- Cancel button in create form not redirect to index page if validation failed before

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create a resource, called `Card`, with some field has validation rules
- Goto `Card` resource index, then goto create form by clicking Create resource button
- Fill out the form so that when creating it will cause validation errors
- Then press `Create` button or `Create & Add Another` => create failed due to fail validation
- Press `Cancel` button
=> Page not redirect to `Card` index page. It redirects to kind of pages loaded before going to `Card` index page (sometime is other `Card` detail page, sometime is another resource index page)

Is this desired behavior or is there any special logic for this behavior ?

**Comment by crynobone** [comment] 2023-05-28 13:06
Duplicate of #5521

**Closed by crynobone** 2023-05-28 13:06 UTC

**Comment by DenysRudenko2** [comment] 2025-02-20 11:36
The same issue.
After failed validation on create form,
Cancel button redirection on some previos successful page, not on the index page of the resource that i m trying to create
