### ISSUE TITLE
403 error page upon deleting a resource

### ISSUE THREAD

**Issue by ekmillard** [laravel/nova-issues#6069] opened 2023-11-28 14:32 UTC
### Description:
I just put our companies Laravel nova project on a new server, and I have never had an issue like this, but when I try and delete a resource it throws a 403 error page. I can create and edit just fine. It seems to be just deleting. 

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a resource, and attempt to delete the resource.
![image](https://github.com/laravel/nova-issues/assets/15122003/b2c485af-32f9-4bb5-9cc6-d7dd0b787f17)
![image](https://github.com/laravel/nova-issues/assets/15122003/067409e3-98ba-4e50-bd77-a82d7792eb4e)
![image](https://github.com/laravel/nova-issues/assets/15122003/bc49d611-175e-4f2b-86c2-a569d40adafd)

**Comment by ekmillard** [comment] 2023-11-28 17:57
Here is the what is happening, this is a brand new set up.

![image](https://github.com/laravel/nova-issues/assets/15122003/1773412f-5e76-4a8f-9908-e8a58d1969bb)
![image](https://github.com/laravel/nova-issues/assets/15122003/ed218a47-0824-447c-a342-2dfa55c1268e)

**Comment by ekmillard** [comment] 2023-11-28 17:59
Is there any specific apache configurations that need to be enabled/disabled for nova to delete a resource?

**Comment by ekmillard** [comment] 2023-11-28 18:00
`<?php

namespace App\Policies;

use App\Models\ExpenseReport;
use App\Models\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class ExpenseReportPolicy
{
    public $key = 'expense report';

    use HandlesAuthorization;

    public function view(User $user, ExpenseReport $expenseReport)
    {
        return $user->id === $expenseReport->user_id || $user->isServiceManager();
    }

    public function update(User $user, ExpenseReport $expenseReport)
    {
        return $user->id === $expenseReport->user_id || $user->isServiceManager();
    }

    public function delete(User $user, ExpenseReport $expenseReport)
    {
        if ($user->isServiceManager())
            return true;
        return $user->id == $expenseReport->user_id;
    }

    public function create(User $user) {
        if ($user->isServiceManager())
            return true;
        return $user->id == auth()->user()->id;
    }

    public function attachAnyChoice()
    {
        return false;
    }

}
`

Here is the policy I have set for the resource.

**Comment by crynobone** [comment] 2023-11-28 22:23
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment] 2023-12-21 08:21
Hi there, this issue has been marked as fixed and done based on above description, reproducing code and test done on our side. If you still have a problem please create a [New Issue](https://github.com/laravel/nova-issues/issues/new?assignees=&labels=&template=1_Bug_report.md) with full description on how to reproduce the issue based on your use case.

**Closed by crynobone** 2023-12-21 08:21 UTC
Labels: needs more info
