### ISSUE TITLE
Relation fields doesn't load after update

### ISSUE THREAD

**Issue by tharindu-abans** [laravel/nova-issues#1608] opened 2019-05-17 09:13 UTC
- Laravel Version: 5.8.17
- Nova Version: 2.0.5
- PHP Version: 7.2
- Operating System and Version: Windows 10
- Browser type and version: Chrome 74.0.3729.131

### Description:
I recently updated Nova from 2.0.0 to 2.0.5. Now, whenever I add more than one relational field to `Ùser` resource, it keeps loading the relationships fields indefinitely. When I rollback the files changed by the update, it starts working again. 
![image](https://user-images.githubusercontent.com/48512374/57915573-b18d9780-78ae-11e9-9d60-2072e4433192.png)

### Steps To Reproduce:
Add 4-5 relationships to `User` resource and update Laravel Nova to 2.0.5 from 2.0.0

**Comment by dillingham** [comment] 2019-05-17 12:58
php artisan nova:publish

**Comment by goyote** [comment] 2019-05-17 23:03
The brake was introduced in 2.0.4, you can upgrade to 2.0.3 meanwhile someones posts a guide to fix.

**Comment by pktharindu** [comment] 2019-05-18 05:50
@goyote Thanks, I'll try that. Hope this will get fixed soon!

**Comment by davidhemphill** [comment] 2019-05-18 15:49
Duplicate of #1610. Fixed in next release. 👍

**Closed by davidhemphill** 2019-05-18 15:49 UTC
