### ISSUE TITLE
Filterable Fields cannot have Default Values

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/nova-issues#6427] opened 2024-06-14 14:42 UTC
- Laravel Version: 10.48.12
- Nova Version: 4.34.2
- PHP Version: 8.2.13

### Description:

When using `->filterable()` on a field, I would expect the default value to be the default filter applied. That doesn't appear to be the case. As I've been looking into it further, it doesn't appear that there's any way to have a default filter value on filterable fields.

I understand that traditional filters support adding the `default()` method to them, which supplies a default value, but doing the same for a field with `->filterable()` chained on to it doesn't have the same effect.

I've been trying to find a workaround on my end, and it needs very difficult to do without modifying Nova source code.

### Exploration:

In `Nova\Fields\Filters\Filter`, I added a `default` method override, like so:

```php
public function default()
{
    return $this->field->resolveDefaultValue(app(NovaRequest::class));
}
```

I don't have any way to jack into the filter that a field produces, so I'm very limited in user-land regarding the workarounds I can explore.

**Comment by tylernathanreed** [comment] 2024-06-14 14:54
I was able to find a workaround by doing what feels like a hack:

```php
public function filters(NovaRequest $request)
{
    return [
        with(
            Fields\Badge::make('Status')
                ->enum(ActiveStatus::class)
                ->filterable()
                ->exceptOnForms()
                ->default(ActiveStatus::Active),
            function (Field&FilterableField $field) use ($request) {
                return $field
                    ->resolveFilter($request)
                    ->withMeta([
                        'currentValue' => $field->resolveDefaultCallback($request),
                    ]);
            },
        ),
    ];
}
```

This code takes my initial field declaration, converts it into a filter, and then overrides the filter's default value by abusing the `->withMeta()` functionality to overriding the internal `currentValue` attribute that's in the JSON serialization.

I filter produced in this manner works as expected. However, this is far more verbose than I would like.

**Comment by tylernathanreed** [comment] 2024-06-14 15:36
I was able to simplify some of the workaround with a macro:

```php
public function filters(NovaRequest $request)
{
    return [
        Fields\Badge::make('Status')
            ->enum(ActiveStatus::class)
            ->filterable()
            ->exceptOnForms()
            ->default(ActiveStatus::Active)
            ->filterWithDefault(),
    ];
}
```

```php
/** @mixin Field */
class FilterableMixin
{
    /** @return Closure():static */
    public function filterWithDefault(): Closure
    {
        return function (): Filter {
            /** @var Field $this */
            if (! $this instanceof FilterableField) {
                throw new RuntimeException(sprintf(
                    'Macro [filterWithDefault] not supported for [%s] fields.',
                    get_class($this),
                ));
            }

            $request = resolve(NovaRequest::class);

            if (! $this->filterableCallback) {
                $this->filterable();
            }

            return $this
                ->resolveFilter($request)
                ->withMeta([
                    'currentValue' => $this->resolveDefaultCallback($request),
                ]);
        };
    }
}
```

However, I'm still not happy that this has to be defined in `filters()`. I would prefer to define this in `fields()`, as that's where the original field definition lives.

**Comment by tylernathanreed** [comment] 2024-06-14 15:46
Adding this to the `Nova\Fields\Filterable` trait would work:

```php
public function withFilter(Closure $filterCallback): static
{
    $this->filterCallback = $filterCallback;
}

public function resolveFilter(NovaRequest $request): ?Filter
{
    $filter = $this->filterableCallback) ? $this->makeFilter($request) : null;

    if ($filter && $this->filterCallback) {
        ($this->filterCallback)($filter, $request, $this);
    }

    return $filter;
}
```

Then I could do this instead:

```php
Fields\Badge::make('Status')
    ->enum(ActiveStatus::class)
    ->default(ActiveStatus::Active)
    ->filterable()
    ->withFilter(function (Filter $filter, NovaRequest $request, Field $field) {
        $filter->withMeta([
            'currentValue' => $field->resolveDefaultCallback($request)
        ]);
    });
```

Granted, this still relies on the `withMeta` hack.

**Comment by crynobone** [comment] 2024-06-14 23:55
Duplicate of https://github.com/laravel/nova-issues/discussions/5845

**Closed by crynobone** 2024-06-14 23:55 UTC
