### ISSUE TITLE
CreateRelationModal.vue not use props viaResource, viaResourceId, viaRelationship

### ISSUE THREAD

**Issue by vaslv** [laravel/nova-issues#3562] opened 2021-09-22 13:42 UTC
- Laravel Version: 8.61.0
- Nova Version: 3.29.0
- PHP Version: 7.4.15
- Operating System and Version: macOS 11.5.2
- Browser type and version: Chrome 93.0.4577.82

### Description:

Modals/CreateRelationModal.vue does not pass properties to component views/Create.vue

![image](https://user-images.githubusercontent.com/1648799/134352403-d69fa09a-02a9-49b7-9c5b-579a920fd4d0.png)
![image](https://user-images.githubusercontent.com/1648799/134352550-2c64759c-7006-4be0-8020-ef41070adb18.png)

After the following changes everything works as expected.

![image](https://user-images.githubusercontent.com/1648799/134353715-d6ee1bb2-10e9-4fd0-a806-60d6c0bb4fcb.png)
![image](https://user-images.githubusercontent.com/1648799/134353745-1a03e910-cb16-4687-afbb-a5eb7cf87ed9.png)

```
<Create
    mode="modal"
    @refresh="handleRefresh"
    @cancelled-create="handleCancelledCreate"
    :resource-name="resourceName"
    :resource-id="resourceId"
    :via-resource="viaResource"
    :via-resource-id="viaResourceId"
    :via-relationship="viaRelationship"
/>
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
I am creating a custom card and using the CreateRelationModal.vue component to create a resource belonging to the current resource in a modal window.

**Comment by crynobone** [comment] 2021-09-22 14:16
Duplicate of #3335

**Closed by crynobone** 2021-09-22 14:16 UTC

**Comment by vaslv** [comment] 2021-09-23 09:01
Not quite like that. If I understood correctly, in #3335 we are talking about attaching a model to a model that does not yet exist. I also describe the problem with passing parameters when creating a model that belongs to an already created model. I also attach screenshots illustrating the presence of the problem and its solutions. 

Please check the correctness of using the Create component in the CreateRelationModal.vue file.

```
<Create
    mode="modal"
    @refresh="handleRefresh"
    @cancelled-create="handleCancelledCreate"
    :resource-name="resourceName"
    resource-id=""
    via-resource=""
    via-resource-id=""
    via-relationship=""
/>
```

You must pass the props viaResource, viaResourceId and viaRelationship to the component 'Create'.

**Comment by davidhemphill** [comment] 2021-09-23 10:38
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment] 2021-09-23 10:40
Marking this as a request. Nova typically handle code used directly by Nova and it would be hard to maintain code that we don't use or later on understand.
