### ISSUE TITLE
Data missing when using SQL Server Date

### ISSUE THREAD

**Issue by armadillo-matt** [laravel/nova-issues#1796] opened 2019-08-05 19:30 UTC
- Laravel Version: 5.8
- Nova Version: 2.0.9
- PHP Version: 7.3
- DB Version: MSSQL 2016

### Description:

Resource index will not load when trying to add Date or DateTime field to a resource. Error says 'Data missing':

```
[2019-08-05 12:26:42] production.ERROR: Data missing {"userId":2,"exception":"[object] (InvalidArgumentException(code: 0): Data missing at /home/forge/.../vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:563)
[stacktrace]
#0 /home/forge/.../vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(585): Carbon\\Carbon::rawCreateFromFormat('Y-m-d H:i:s.v', '2019-08-05 08:0...', NULL)
#1 /home/forge/.../vendor/laravel/framework/src/Illuminate/Support/DateFactory.php(216): Carbon\\Carbon::createFromFormat('Y-m-d H:i:s.v', '2019-08-05 08:0...')
#2 /home/forge/.../vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Support\\DateFactory->__call('createFromForma...', Array)
#3 /home/forge/.../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(811): Illuminate\\Support\\Facades\\Facade::__callStatic('createFromForma...', Array)
#4 /home/forge/.../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(361): Illuminate\\Database\\Eloquent\\Model->asDateTime('2019-08-05 08:0...')
#5 /home/forge/.../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(319): Illuminate\\Database\\Eloquent\\Model->getAttributeValue('updated_at')
#6 /home/forge/.../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1546): Illuminate\\Database\\Eloquent\\Model->getAttribute('updated_at')
#7 /home/forge/.../vendor/laravel/framework/src/Illuminate/Support/Arr.php(148): Illuminate\\Database\\Eloquent\\Model->offsetExists('updated_at')
#8 /home/forge/.../vendor/laravel/framework/src/Illuminate/Support/helpers.php(524): Illuminate\\Support\\Arr::exists(Object(Spatie\\Activitylog\\Models\\Activity), 'updated_at')
#9 /home/forge/.../vendor/laravel/nova/src/Fields/Field.php(215): data_get(Object(Spatie\\Activitylog\\Models\\Activity), Array, Object(stdClass))
#10 /home/forge/.../vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Laravel\\Nova\\Fields\\Field->resolve(Object(Spatie\\Activitylog\\Models\\Activity))
#11 /home/forge/.../vendor/laravel/framework/src/Illuminate/Support/Collection.php(475): Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Laravel\\Nova\\Fields\\DateTime), 5)
#12 /home/forge/.../vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->each(Object(Closure))

...
```

### Fix:

Adding this to the Eloquent model works:

```php
protected $dateFormat = 'Y-m-d H:i:s';
```

But third party models (like Laravel\Nova\Action\ActionEvent or Spatie\Activitylog\Models\Activity) cannot be overridden without a lot of extra work.

**Comment by jbrooksuk** [comment] 2019-08-07 09:55
I'm just installing MSSQL so that I can try replicating this 🙂

**Comment by jbrooksuk** [comment] 2019-08-07 10:11
Confirmed.

**Comment by orrd** [comment] 2019-08-13 18:00
Duplicate of #1508?

**Comment by armadillo-matt** [comment] 2019-08-13 19:07
My issue might be fixed if there was a way to set the $casts or the $dateFormat of an underlying Eloquent model from a Resource at run time.

> But third party models (like Laravel\Nova\Action\ActionEvent or Spatie\Activitylog\Models\Activity) cannot be overridden without a lot of extra work.

I'm still dipping my toes into IoC, but maybe this a good candidate for a service provider: 

1. Extend the third party class
```php

use Spatie\Activitylog\Models\Activity

class MyActivity extends Activity {
...
    protected $dateFormat = 'Y-m-d H:i:s'

```
}

2. Extend it in a service container:

```php

class MyServiceProvider extends ServiceProvider {

    public function boot() {
        $this->app->extend(Activity::class, function ($activity) {
            return new MyActivity($activity);
        });
    }
}

```
3. Nova resolves to MyActivity::class - This only work if Nova is resolving Activity out of the service container with ``` app()->make(Activity::class)```. But I think it does. I'll have a look.

**Closed** 2019-08-19 09:27 UTC
Labels: bug, pending
