### ISSUE TITLE
Metic Dropdown size fixed width causing selected value to be cut off

### ISSUE THREAD

**Issue by RhysLees** [laravel/nova-issues#4960] opened 2022-10-21 17:10 UTC
- Laravel Version: 9.36.4
- Nova Version: 4.16.1
- PHP Version: 8.0 | 8.1
- Database Driver & Version: Mysql
- Operating System and Version: Win 11 / WSL2 
- Browser type and version: Chrome Latest

### Description:

![image](https://user-images.githubusercontent.com/43909932/197251137-34a3956a-5001-4de7-84f3-b6023b0fab7c.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a metric and select an option
Observe value cut off

**Comment by crynobone** [comment] 2022-10-24 01:33
Duplicate of https://github.com/laravel/nova-issues/discussions/4251

**Closed by crynobone** 2022-10-24 01:33 UTC

**Comment by RhysLees** [comment] 2022-10-24 14:27
@crynobone @davidhemphill Any reason why this is not planned? With the default options provided/suggested by Nova Docs, they are cut off by the dropdown width width,

**Comment by crynobone** [comment] 2022-10-24 14:30
It's marked as duplicate.
