### ISSUE TITLE
Date field pickerFormat format wrong date

### ISSUE THREAD

**Issue by cent89** [laravel/nova-issues#2060] opened 2019-10-17 16:06 UTC
- Laravel Version: 6.3.0
- Nova Version: 2.4.0
- PHP Version: 7.2
- Database Driver and Version: MariaDB 10.4.8
- Operating System and Version: Zorin OS 15
- Browser type and version: Firefox

### Description

In resource page, the pickerFormat function show wrong date.
For example, if the date is '2019-10-30', `pickerFormat('d/m/Y')` shows '20/10/2019'.
It seems take the first two years digit as day of the month.
The format() functions works well:

`
Date::make('Data di inserimento', 'data_inserimento')->pickerFormat('d/m/Y')->format('DD/MM/YYYY')
`

**Comment by jbrooksuk** [comment] 2019-10-22 13:50
Duplicate of https://github.com/laravel/nova-issues/issues/1889

**Closed by jbrooksuk** 2019-10-22 13:50 UTC

**Comment by cent89** [comment] 2019-10-28 16:33
Hi,
with the issue linked I can't solve my problem. I have update flatpickr to 4.6.3 version (latest).
Which files I have to edit to solve the bug?

Thanks

**Comment by david-kristin** [comment] 2020-01-16 21:22
It still is the issue. How to solve that?

**Comment by cent89** [comment] 2020-01-17 08:06
It is embarrassing that Nova does not provide assistance with a bug to their product.
I chose to use this component, which replaces Nova's DateTime:

https://packagist.org/packages/techouse/intl-date-time

**Comment by trollfalgar** [comment] 2020-01-22 19:33
> 
> 
> It is embarrassing that Nova does not provide assistance with a bug to their product.
> I chose to use this component, which replaces Nova's DateTime:
> 
> https://packagist.org/packages/techouse/intl-date-time

It works like a charm!!! Perfect!
