### ISSUE TITLE
sortable() on Date field doesn't work if the field name is 'date'

### ISSUE THREAD

**Issue by DonDiegoAA** [laravel/nova-issues#396] opened 2018-09-02 15:15 UTC
I tore my hair out for hours on this problem, before trying to rename the 'date' field to 'document_date', and all of a sudden, it works.

**Comment by treeStoneIT** [comment] 2018-09-02 15:56
Interesting, i tried the above but it didn't work for me... do you have date or datetime field?

**Comment by Saymecode** [comment] 2018-09-02 16:48
Me too

**Comment by DonDiegoAA** [comment] 2018-09-02 18:13
@treeStoneIT : Initially I had a date field (named date), I tried to convert to DateTime (timestamp in migration), but the sortable problem was present in both case. 
Then I rename the field in database, and both Date and DateTime are now sortable.

**Comment by cloudstudio** [comment] 2018-09-04 14:50
+1 this could be fixed ? is a really problem...

**Comment by mizmiz** [comment] 2018-09-05 02:29
Duplicate of #133

**Comment by davidhemphill** [comment] 2018-09-17 17:54
This has been fixed and will be included in an upcoming release.

**Closed by davidhemphill** 2018-09-17 17:54 UTC
