### ISSUE TITLE
JSON fields doesn't work in the Boolean field.

### ISSUE THREAD

**Issue by dkulyk** [laravel/nova-issues#598] opened 2018-09-18 20:54 UTC
Nova 1.017

Required to fix #596 

If use 'field->option' attributes Field doesn't resolve value in the Boolean field.

[Reproducible code example](https://github.com/dkulyk/nova-issues/tree/json_fields_2)

**Comment by victorpfm** [comment] 2018-09-20 14:35
It doesn't work in Nova 1.0.19 either. If I use a Text field, it displays true, but Boolean displays always false.

**Comment by alexbowers** [comment] 2018-09-29 17:39
Have you tested this against the latest version?

**Comment by dkulyk** [comment] 2018-09-29 20:40
The v1.1.3 has a the bug

**Comment by ragingdave** [comment] 2018-09-29 20:45
Based on the code example I believe you want the cast type to be object, not json. Based on the framework code, json and array are the same, and are then treated like an array.

**Comment by dkulyk** [comment] 2018-09-30 00:46
Exactly.

> Based on the code example I believe you want the cast type to be object, not json. Based on the framework code, json and array are the same, and are then treated like an array.

**Comment by ragingdave** [comment] 2018-09-30 00:49
So....you have your app configured incorrectly.....and it's not a bug?

**Comment by dkulyk** [comment] 2018-09-30 09:07
Why? JSON - is a text format. Exactly i mean type [casting to array](https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L489-L491). 
Actually this bug fixed in the #596 . But in the Boolean field resolving the value is incorrect:
```php
class Field
{
    protected function resolveAttribute($resource, $attribute)
    {
        return data_get($resource, str_replace('->', '.', $attribute));
    }
}
```
But Boolean override this method
```php
class Boolean extends Field
{
    protected function resolveAttribute($resource, $attribute)
    {
        return data_get($resource, $attribute) == $this->trueValue ? true : false;
    }
}
```

**Comment by nickels** [comment] 2018-10-30 20:06
on my model I have:

```
    protected $casts = [
        'options' => 'array'
    ];
```

In the nova resource I'm trying to have a Boolean field:

```
Laravel\Nova\Fields\Boolean::make('Club Members Only', 'options.clubmembers'),
```

It renders correctly, however can't update the value to true or false.

Data is stored in the db using a `jsonb` field like so:

`{"clubmembers": "1"}`

Thoughts?

**Comment by tobz-nz** [comment] 2018-10-31 10:10
I'm having the same issue - with text/number fields. data is displayed correctly but there's a js error when trying to save.

`Unhandled promise rejection TypeError: "e.t0.response is undefined; can't access its "status" property"`

**Comment by bonzai** [comment] 2018-11-29 22:09
This has been fixed and will be included in the next release.

**Closed by bonzai** 2018-11-29 22:09 UTC
Labels: needs-details

**Comment by StanAngeloff** [comment] 2018-12-13 12:08
Confirmed solved in v1.2.1 Orion released December 12, 2018.
