### ISSUE TITLE
Looking to change the 'per_page' filter from default to my custom number

### ISSUE THREAD

**Issue by keyur5390** [laravel/nova-issues#1396] opened 2019-02-27 13:25 UTC
* Laravel Version: 5.7.19
* Nova Version: 1.1.3

Nova default gives an per page count `25` and filter option of 25, 50, 100.
In my case I want to change this values as I have thousands of records in my 2 modules, so I am fine with default per page result on other pages but I want to change per page number on my these two modules. So how could I change these default per page to my modules?

**Comment by dkulyk** [comment] 2019-02-27 15:30
Duplicate of #72

**Closed by dkulyk** 2019-02-27 15:30 UTC

**Comment by keyur5390** [comment] 2019-02-28 06:29
I still wondering about the solution. This is not fit to my requirement. This is to change the pagination on to relationship data, and I am looking on to main page listing

**Comment by bolechen** [comment] 2019-03-01 13:18
+1
