### ISSUE TITLE
Dynamic relatable methods don't work with Tag field

### ISSUE THREAD

**Issue by riptin** [laravel/nova-issues#5979] opened 2023-10-20 14:29 UTC
- Laravel Version: 10.10
- Nova Version: 4.27.3
- PHP Version: 8.1

Dynamic relatable methods don't work with `Tag` field. It works with the `BelongsToMany` field in details view when I attach a new resource, but when adding a relationship from the `Tag` field in edit view It still shows **all** of the relatable resource instances.

Project Model:
```
public function cast()
{
    return $this->belongsToMany(Cast::class, 'project_cast');
}
```

Cast Model:
```
public function projects()
{
    return $this->belongsToMany(Project::class, 'project_cast');
}
```

Project Resource:
```
public static function relatableCasts(NovaRequest $request, $query)
{
    return $query->where('active', 1);
}

BelongsToMany::make('cast'), // Filters the cast
Tag::make('Cast', 'cast') // Doesn't filter the cast
    ->preload()
    ->displayAsList()
    ->withPreview()
    ->showCreateRelationButton(),
```

**Comment by crynobone** [comment] 2023-10-22 22:53
Duplicate of https://github.com/laravel/nova-issues/discussions/5097

**Closed by crynobone** 2023-10-22 22:53 UTC
