### ISSUE TITLE
Searchable() is not working

### ISSUE THREAD

**Issue by ImJustToNy** [laravel/nova-issues#2808] opened 2020-08-20 10:47 UTC
- Laravel Version: 7.25.0
- Nova Version: 3.8.3
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 5.7
- Operating System and Version: macOS 10.13.6
- Browser type and version: Chrome 84

### Description:
searchable() on field won't work even though it works in global search ($search variable is defined). I am not using scout.
![image](https://user-images.githubusercontent.com/5730766/90760618-71536b00-e2e2-11ea-963c-24ffa3422c0b.png)
![image](https://user-images.githubusercontent.com/5730766/90760635-787a7900-e2e2-11ea-805b-eaf36e3931b4.png)
app/Nova/User.php:
![image](https://user-images.githubusercontent.com/5730766/90760729-98aa3800-e2e2-11ea-9e2a-121b1db5edb0.png)
app/Nova/Article.php:
![image](https://user-images.githubusercontent.com/5730766/90760825-c3948c00-e2e2-11ea-924c-8e4400e445fc.png)
app/Article.php:
![image](https://user-images.githubusercontent.com/5730766/90760957-f0e13a00-e2e2-11ea-883c-b860b24806f7.png)
No JS errors in console, no ajax requests.

**Comment by morphsteve** [comment] 2020-08-20 11:05
Probably same issue as #2807

**Comment by davidhemphill** [comment] 2020-08-20 20:58
Duplicate of #2807

**Closed by davidhemphill** 2020-08-20 20:58 UTC
