### ISSUE TITLE
Avatar in global search result doesn't follow the preview method

### ISSUE THREAD

**Issue by leo108** [laravel/nova-issues#1752] opened 2019-07-16 15:49 UTC
- Laravel Version: 5.8.28
- Nova Version: 2.0.9
- PHP Version: 7.3
- Operating System and Version: macOS 10.14.5
- Browser type and version: Chrome 75

### Description:

I'm using `preview` method in Avatar field:

```
Avatar::make('Avatar', 'avatar_url')->readonly()->maxWidth(100)->preview(function ($value) {
      return $value;
});
```

And it works well in detail page, but breaks in global search result.

![image](https://user-images.githubusercontent.com/1551716/61308919-d907ce80-a823-11e9-9c77-b841158b1429.png)

**Comment by jbrooksuk** [comment] 2019-07-31 08:52
Duplicate of https://github.com/laravel/nova-issues/issues/1368

**Closed by jbrooksuk** 2019-07-31 08:52 UTC
Labels: bug
