### ISSUE TITLE
Laravel nova action doesn't work for 'Select All Matching' 

### ISSUE THREAD

**Issue by Fawzanm** [laravel/nova-issues#1087] opened 2018-12-04 14:51 UTC
- Laravel Version: 5.7.*
- Nova Version: 1.2.0
- PHP Version:

### Description:
I have a custom action which allows the user download all the attachments from the post model. It works fine for manually selected entries. But when I pick `Select All Matching (n)` and runs the action, nova ignores the action and show the message `The action ran successfully`. 

### Steps To Reproduce:
1. Create custom action
2. Click the select button on the resource index page
3. Pick `Select all Matching (n)` and run the action

**Comment by davidhemphill** [comment] 2018-12-04 15:45
Duplicate of #326

**Closed by davidhemphill** 2018-12-04 15:45 UTC
