### ISSUE TITLE
Trix field icons don't look updated for the dark theme

### ISSUE THREAD

**Issue by amcfarlane** [laravel/nova-issues#4885] opened 2022-10-10 13:13 UTC
- Laravel Version: 9.19
- Nova Version: 4.15.2
- Operating System and Version: macOS Monterey 12.6
- Browser type and version: Chrome Version 106.0.5249.103 (Official Build) (x86_64)

### Description:

The icons on the Trix field are black on a dark background. It could be a design choice, but it looks like they have been forgotten in the dark theme. Either way, they are hard to see in dark mode.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Add a default Trix field in a new resource and view in dark mode.

<img width="1140" alt="Screenshot 2022-10-10 at 15 12 25" src="https://user-images.githubusercontent.com/2536236/194874547-41d311a5-dd77-4db0-8d0b-77825df6a262.png">

**Comment by crynobone** [comment] 2022-10-10 13:43
Duplicate of https://github.com/laravel/nova-issues/discussions/3955

**Closed by crynobone** 2022-10-10 13:43 UTC
