### ISSUE TITLE
Allow metric cards to be linkable

### ISSUE THREAD

**Issue by rodrigoreyes79** [laravel/nova-issues#1908] opened 2019-09-09 22:35 UTC
The following package provides this functionality, but it is broken right now:

https://novapackages.com/packages/saintsystems/nova-linkable-metrics

It would be great if Nova could provide it out of the box.

**Comment by jbrooksuk** [comment] 2019-09-24 14:49
Duplicate of https://github.com/laravel/nova-issues/issues/759

**Closed by jbrooksuk** 2019-09-24 14:49 UTC
