### ISSUE TITLE
Error using null datetime with the Nova DateTime field

### ISSUE THREAD

**Issue by amcfarlane** [laravel/nova-issues#2215] opened 2019-12-11 10:41 UTC
- Laravel Version: 5.8.35
- Nova Version: 2.9.0
- PHP Version: 7.2.15

### Description:

When trying to edit a Nova resource with a 'NULL' datetime and a DateTime field I receive a **'DateTime field must cast to 'datetime' in Eloquent model'** error. When I edit a resource with a datetime already set it works as expected.

http://localhost:8080/no/va/resources/tiles/842/edit > No error, '2019-12-02 12:00:00' datetime set in database already
http://localhost:8080/no/va/resources/tiles/1290/edit > Error, [null] in database

### Steps To Reproduce:

**nova resource (Nova/Tile)**

```
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Title')->readonly(),
            DateTime::make('Featured At', 'featured_at')
                ->nullable(),
        ];
    }
```

**model (App/Tile)**

```
/**
     * The attributes that are dates by default
     *
     * @var array
     */
    protected $dates = [
        'published_at',
        'featured_at',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'featured_at' => 'datetime',
    ];
```

**Error**

http://localhost:8080/nova-api/tiles/1290/update-fields?editing=true&editMode=update&viaResource=&viaResourceId=&viaRelationship=

```
public function __construct($name, $attribute = null, $resolveCallback = null)
    {
        parent::__construct($name, $attribute, $resolveCallback ?? function ($value) {
            if (! $value instanceof DateTimeInterface) {
                throw new Exception("DateTime field must cast to 'datetime' in Eloquent model.");
            }
 
            return $value->format('Y-m-d H:i:s');
        });
    }
```

**Comment by sirikkoster** [comment] 2019-12-11 13:17
There is already an issue reported : https://github.com/laravel/nova-issues/issues/2212

**Comment by amcfarlane** [comment] 2019-12-11 13:21
@sirikkoster Sorry, I spend 4 hours Googling that issue and didn't find that. That's exactly the issue. I'm new here, what should I do with this? close it?

**Comment by sirikkoster** [comment] 2019-12-11 13:57
@amcfarlane, I think the issue is clear and that the fix is release shorty, so closing this issue is ok.

**Closed** 2019-12-11 14:20 UTC

**Comment by FBDK** [comment] 2020-07-06 14:00
8 month later no fix and still buggy. Datetime/pivot is a nightmare. The DateTimeInterface is obviously not working correctly. Why can't this be fixed? And why can't i add NULL to a DateTime resource? @jbrooksuk @
