### ISSUE TITLE
scroll to top after go through link or redirect

### ISSUE THREAD

**Issue by jarda256sparktech** [laravel/nova-issues#1262] opened 2019-01-22 12:13 UTC
- Laravel Version: 5.7.31
- Nova Version: 1.3.1
- PHP Version: 7.2

### Description:
After clicking on link to another resource (where ever) or redirect (after create or update). You remain in same part of page (if you have many resource). So after redirecting you should se top of page, but you see just part of menu on left and nothing else, but you should be on top of page.

**Comment by bonzai** [comment] 2019-01-22 12:33
Duplicate of #1194

**Closed by bonzai** 2019-01-22 12:33 UTC
