### ISSUE TITLE
Boolean field implementing dependsOn doesn't work properly on edit page

### ISSUE THREAD

**Issue by kazak71** [laravel/nova-issues#5335] opened 2023-02-18 15:32 UTC
- Laravel Version: 9,10
- Nova Version: 4.22.0
- PHP Version: 8.1
- Database Driver & Version: MySQL 8
- Operating System and Version: Ubuntu Linux
- Browser type and version: Chrome, Firefox, Safari

### Description:
I have described this problem in my comment on [#5183](https://github.com/laravel/nova-issues/issues/5183) and I think they are related.

**Comment by crynobone** [comment] 2023-02-20 04:51
Duplicate of #5279 and will be available on the next release.

**Closed by crynobone** 2023-02-20 04:51 UTC
