### ISSUE TITLE
dependsOn Does not work in Actions

### ISSUE THREAD

**Issue by thettler** [laravel/nova-issues#4448] opened 2022-06-18 20:57 UTC
- Laravel Version: 9.2
- Nova Version: 4.9.2
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version: Mac
- Browser type and version: Chrome & Firefox Tested 

### Description:
The `dependsOn()` does not work on fields that are used inside of an Action. No ajax call is made from the frontend to the backend.  

### Detailed steps to reproduce the issue on a fresh Nova installation:
Just copy the `dependsOn()` example from the docs inside an action. 

```php
<?php

namespace App\Nova\Actions;

use Illuminate\Bus\Queueable;
use Laravel\Nova\Fields\FormData;
use Laravel\Nova\Fields\Select;
use Laravel\Nova\Actions\Action;
use Illuminate\Support\Collection;
use Laravel\Nova\Fields\ActionFields;
use Illuminate\Queue\InteractsWithQueue;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;

class DependsOnAction extends Action
{
    use InteractsWithQueue, Queueable;

    public function handle(ActionFields $fields, Collection $models)
    {
        return Action::danger('Bla');
    }

    public function fields(NovaRequest $request)
    {
        return [
            Select::make('Purchase Type', 'type')
                ->options([
                    'personal' => 'Personal',
                    'gift' => 'Gift',
                ]),

            Text::make('Recipient')
                ->readonly()
                ->dependsOn(
                    ['type'],
                    function (Text $field, NovaRequest $request, FormData $formData) {
                        if ($formData->type === 'gift') {
                            $field->readonly(false)->rules(['required', 'email']);
                        }
                    }
                ),
        ];
    }
}
```

**Comment by crynobone** [comment] 2022-06-19 05:05
Duplicate of https://github.com/laravel/nova-issues/discussions/3931

**Closed by crynobone** 2022-06-19 05:05 UTC
