### ISSUE TITLE
attribute name for validation rule

### ISSUE THREAD

**Issue by dormadekhin** [laravel/nova-issues#1374] opened 2019-02-17 17:00 UTC
how to set attribute name for validation rule message?
on text field used label and not always right, but for Select displaying  column name from db
![image](https://user-images.githubusercontent.com/32381310/52916283-f6397f00-330f-11e9-87c3-33e5b3f6bfe1.png)

**Comment by kirya-dev** [comment] 2019-03-04 13:09
+1

**Comment by davidhemphill** [comment] 2019-03-04 18:14
Duplicate of #556

**Closed by davidhemphill** 2019-03-04 18:14 UTC

**Comment by davidhemphill** [comment] 2019-03-04 18:15
Duplicate of #346

**Comment by dev-lav** [comment] 2019-03-26 02:56
@dormadekhin @kirya-dev  You can override method `validatorForCreation` and `validatorForUpdate` in your resource.
reference:  https://medium.com/dot-lab/my-first-project-using-laravel-nova-9b24ddf19d7b
