### ISSUE TITLE
Re-populate field when other value changes

### ISSUE THREAD

**Issue by jordyvandomselaar** [laravel/nova-issues#1470] opened 2019-03-22 14:42 UTC
It would be great if there was a way to re-populate certain fields when a value changes.

**Usecase:**

We have 2 `belongsToMany`: `categories` and `tags`, we populate the `tags` field based on what `categories` are selected. It would be amazing if there was a way to automatically update the `tags` field's possible options whenever the `categories` field changes.

**Comment by davidhemphill** [comment] 2019-04-04 16:14
Duplicate of #223, #821, etc...

**Closed by davidhemphill** 2019-04-04 16:14 UTC
Labels: request

**Comment by jordyvandomselaar** [comment] 2019-04-04 19:44
Except we don't need dependent filters, we need input fields.

**Comment by davidhemphill** [comment] 2019-04-04 20:26
That's precisely what a dependent filter is.

**Comment by jordyvandomselaar** [comment] 2019-04-11 11:31
Doesn't work out of the box though, I had to implement the ajax call myself; the input has to make an ajax call to obtain new data.
