### ISSUE TITLE
HasOne and MorphOne fields allow user to create more than one related record

### ISSUE THREAD

**Issue by sirikkoster** [laravel/nova-issues#1816] opened 2019-08-12 11:19 UTC
- Laravel Version: 5.8.30
- Nova Version: 2.0.10
- PHP Version: 7.2.1
- Database Driver and Version: MySQL 5.6.38
- Operating System and Version: Mac OS X 10.14.5
- Browser type and version: Safari 12.1.1

### Description
When using the HasOne and MorphOne fields it should be prohibited to add another record, starting from the presumption that we should only have one record.

### Steps To Reproduce

1.  Add a HasOne or MorphOne field and click on "Create Resource" 
2. When filling in the fields click on "Create & Add Another"

And you will see that it is allowed to add another record

**Comment by henryavila** [comment] 2019-09-11 22:55
I have the same issue. 
In my case, when click on "Create & Add Another" The screen loads with no fields.

**Comment by preliot** [comment] 2019-11-15 11:06
Same issue. My nova version is 2.6.1.

Expect the 'Create & Add Another' to be removed with a hasOne (or morphOne).

**Comment by BenWalters** [comment] 2020-01-29 09:44
We have the same issue and now on version 2.9.4.
Is there a roadmap as to when we can expect a fix for this?

**Closed** 2020-02-04 18:06 UTC
Labels: pending

**Comment by BenWalters** [comment] 2020-02-04 18:55
@davidhemphill does this mean we can expect a fix in the next Nova release?

**Comment by BenWalters** [comment] 2020-02-05 08:25
For anyone viewing this thread, I can confirm that this is fixed in the latest version - v2.10.0 👍

**Comment by vincenzoraco** [comment] 2020-02-24 11:35
That update has fixed the HasOne relationship, but broke everything else too..

I submitted a PR to fix that - https://github.com/laravel/nova/pull/805 - please merge as soon as possible.

**Comment by Quantiversal** [comment] 2021-09-22 11:50
This seems to be a problem is v3 again. Using `MorphOne`
