### ISSUE TITLE
Key Persons becoming Key Keople

### ISSUE THREAD

**Issue by ziming** [laravel/nova-issues#2278] opened 2020-01-13 12:38 UTC
- Laravel Version: 6.10.1
- Nova Version: 2.9.3
- PHP Version: 7.3.10
- Database Driver & Version: 8.0.18 for osx10.14 on x86_64
- Operating System and Version: osx10.14 on x86_64
- Browser type and version: Chrome 79.0.3945.117

### Description:
I had a model called KeyPerson but in Nova, it displays it as Key Keople.

### Steps To Reproduce:
- Create a table called key_persons
- Create a model called KeyPerson
- Add $public table = 'key_persons' to the Eloquent KeyPerson model class as Eloquent will guess 'key_people' for the table name
- Create Nova Resource KeyPerson
- Visit Nova Admin and see Key Keople on the sidebar,
- Click Key Keople and you will see Key Keople everywhere instead of Key Persons in Nova Admin

Thanks!

**Comment by jbrooksuk** [comment] 2020-01-13 12:45
This is correct because the correct pluralisation is "people".

**Comment by ziming** [comment] 2020-01-13 12:49
Look more carefully @jbrooksuk 

It displays Key **Keople**.

**Comment by jbrooksuk** [comment] 2020-01-13 13:04
Heh, sorry. It's one of those things that you read incorrectly.

https://www.mnn.com/lifestyle/arts-culture/stories/why-your-brain-can-read-jumbled-letters

**Comment by ziming** [comment] 2020-01-13 13:07
Thank you for reopening this

**Comment by davidhemphill** [comment] 2020-01-13 18:58
This is a bug in Laravel's string class.

**Comment by jbrooksuk** [comment] 2020-01-13 21:22
Sorry, also a duplicate of https://github.com/laravel/nova-issues/issues/2241

**Closed by jbrooksuk** 2020-01-13 21:22 UTC
