### ISSUE TITLE
Help bubble displays out of the screen in cards when it is in the last card in the raw

### ISSUE THREAD

**Issue by xoco70** [laravel/nova-issues#3060] opened 2020-11-18 15:44 UTC
- Laravel Version: 8.15.0
- Nova Version: v3.15.0
- PHP Version: 7.4
- Database Driver & Version: Postgres
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome

### Description:

When I set a help in a card like this: 

```
    public function cards(Request $request)
    {
        return [
            AutoconsoRatePerMonth::make()->onlyOnDetail(), //->help("Ca pourrait etre le taux de couverture, a confirmer"),
            EnergyPartition::make()->onlyOnDetail(),
            Savings::make()->onlyOnDetail()->help('Le montant peut être une estimation basé sur le tarif bleu d\'EDF'),
        ];

    }

```
It will display like this: 

![Screenshot from 2020-11-18 16-38-48](https://user-images.githubusercontent.com/5855577/99552313-261e2680-29bd-11eb-821a-e0744094e6bb.png)

User cannot see the full help. It will only happen when the last card on the right has the help tooltip

**Comment by crynobone** [comment] 2020-11-19 10:04
Duplicate of #2549

**Closed by crynobone** 2020-11-19 10:04 UTC
