### ISSUE TITLE
Little UI issue

### ISSUE THREAD

**Issue by riabiy** [laravel/nova-issues#5381] opened 2023-03-05 13:20 UTC
- Laravel Version: 9.52.4
- Nova Version: 4.22.1
- PHP Version: 8.1.8

### Description:

Seems like "Remember me" was "unspanned" and now `space-x-2` can't work anymore. 
Just replace with `mr-2`

<img width="1202" alt="Screenshot 2023-03-05 at 17 16 09" src="https://user-images.githubusercontent.com/124934838/222962869-6cac9aca-821a-4e58-b072-368037e3de5c.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:

Install 🙌

**Comment by crynobone** [comment] 2023-03-05 13:35
Duplicate of #5352 and will be available on the next release

**Closed by crynobone** 2023-03-05 13:35 UTC

**Comment by m-lotze** [comment] 2023-03-20 15:25
Seems to be broken again in v4.22.2. No space between checkbox and label.
