### ISSUE TITLE
Charts have inverted background

### ISSUE THREAD

**Issue by killgt** [laravel/nova-issues#2004] opened 2019-10-03 13:10 UTC
- Laravel Version: 6.1.0
- Nova Version: v2.4.0
- PHP Version: 7.3
- Browser type and version: Google Chrome

### Description

All the charts have the background on the wrong position, seems to be inverted:
![Captura de pantalla de 2019-10-03 15-07-11](https://user-images.githubusercontent.com/343407/66129195-bcdc2800-e5ef-11e9-8c74-c44fa24c8047.png)

**Comment by jbrooksuk** [comment] 2019-10-03 14:16
Duplicate of https://github.com/laravel/nova-issues/issues/1990

A fix has been made, but not released yet.

**Closed by jbrooksuk** 2019-10-03 14:16 UTC
