### ISSUE TITLE
Slower loading times since 2.0.4

### ISSUE THREAD

**Issue by devfrey** [laravel/nova-issues#1606] opened 2019-05-16 08:27 UTC
- Laravel Version: 5.8.16
- Nova Version: 2.0.4
- PHP Version: 7.2
- Operating System and Version: macOS Mojave
- Browser type and version: Chrome 74

### Description:
My Dusk tests were failing, because a minimum loading time of 500ms was introduced in v2.0.4. Why would you purposefully delay the loading of resources? I really don't mind a flashing loading spinner. In my opinion this is the wrong solution.

### Steps To Reproduce:
N/A

**Comment by orlyapps** [comment] 2019-05-16 09:10
Hello,
i can reproduce this 

- Laravel Version: 5.8.16
- Nova Version: 2.0.4
- PHP Version: 7.3
- Operating System and Version: macOS Mojave
- Browser type and version: Chrome 74

I have attached two screenshots of Nova 2.0.0 and 2.0.4
You can see a delay of 400ms between the XHR /actions and /count

<img width="1114" alt="Bildschirmfoto 2019-05-16 um 11 07 56" src="https://user-images.githubusercontent.com/5220826/57841636-369f8080-77cb-11e9-8de5-c6254632f57a.png">
<img width="1158" alt="Bildschirmfoto 2019-05-16 um 11 07 36" src="https://user-images.githubusercontent.com/5220826/57841637-369f8080-77cb-11e9-8b68-e02d74aaed08.png">

**Comment by devfrey** [comment] 2019-05-16 09:17
@orlyapps Thanks for posting your findings!

**Comment by dillingham** [comment] 2019-05-17 04:19
I’m not a fan of the delayed render
But my guess is it was needed to solve a loading state animation / flicker scenario. If you add a loader as people have requested and it takes 100ms.. it would look crappy.

**Comment by orlyapps** [comment] 2019-05-17 04:33
But 400ms more? Before this update i had no issues with animation flickering(?)

**Comment by dillingham** [comment] 2019-05-17 04:36
The flicker I’m referring to is hypothetical 
The loader was added to the table for long lasting requests

**Comment by davidhemphill** [comment] 2019-05-18 16:04
This is not a bug, but an intentional change inside of Nova. So I'm going to close it because of this. Here's some background though:

@dillingham is right on the reasoning behind the delay. The loading indicator was added so there is some feedback during long requests when doing things like searching, adding filters, paginating, etc. There is a minimum loading of 500ms before showing the content on the loading animation to keep the view from flashing. We do this in several other places already. There's probably a way we could make the view only show the loading animation *after* 500ms, but we just haven't gotten there yet. That would make it a smoother experience for sure.

The title is loaded at the same time as the resources, so it's subject to the same request being finished. I tried to avoid a jarring shift when the page title loads by making it take up its final space by default. 🤷‍♂ 

If your Dusk tests are failing because of this, it's because you're probably not waiting for the element with the correct `dusk` attribute to show. It's likely you're using arbitrary pauses (we do it too on the Nova Dusk test suite and have had to fix them). You would have to update your Dusk tests to wait for those elements to be in place.

As with all things Nova, if you add one thing, it's probably going to annoy someone else. And while I think overall the change is better UX, it could be improved and I'll be looking into making that even better.

**Closed by davidhemphill** 2019-05-18 16:04 UTC

**Comment by devfrey** [comment] 2019-05-18 16:20
Thanks for your extensive feedback @davidhemphill. I think it would indeed be best to show the animation only after 500ms, so the application feels as snappy as it can be.

Some background: my Dusk tests are based on Nova's test suite, so yes, I'm using the arbitrary pauses. I'll consider altering the tests to wait for the correct element to show.

Thanks again.

**Comment by orlyapps** [comment] 2019-05-20 06:43
Thanks for your feedback @davidhemphill 
In my opinion this makes the user interaction less snappy as before. 
How about reducing the waiting time to 300ms? Or make this an optional behavior that can be disabled? 

I have tested Nova with 200ms Minimum waiting time in Index.vue and Lense.vue and it feels _much_ better.

How about 300ms as a compromise? :)
When the server only takes 61ms to load the data - it really makes no sense to wait half a second.
