### ISSUE TITLE
Selecting a "BelongsTo" relation does not work during creation and editing

### ISSUE THREAD

**Issue by nicolalazzaro** [laravel/nova-issues#3638] opened 2021-11-17 08:27 UTC
- Laravel Version: 8.71.0
- Nova Version: 3.30.0
- PHP Version: 7.4.21
- Database Driver & Version: MySQL 5.7.34
- Operating System and Version: macOS Monterey 12.0.1
- Browser type and version: All browsers
- Reproduction Repository:

### Description:
The relation "BelongsTo" is only displayed when showing the entity (show) and in the table (index), when creating and editing the select is completely empty.

### Detailed steps to reproduce the issue on a fresh Nova installation:
posts
- id
- text
+ HasMany comments

comments
- id
- post_id
- text
+ BelongsTo post

### Screenshots
![Schermata 2021-11-17 alle 09 24 32](https://user-images.githubusercontent.com/26198330/142163043-180e6281-a5bb-498d-8c71-a0ba91357d23.png)
![Schermata 2021-11-17 alle 09 24 41](https://user-images.githubusercontent.com/26198330/142163047-91754136-4de7-4c88-aad6-0b5f6b3d8a07.png)
![Schermata 2021-11-17 alle 09 24 48](https://user-images.githubusercontent.com/26198330/142163048-fde32a61-71ff-4550-911a-c477e49ec617.png)
![Schermata 2021-11-17 alle 09 25 34](https://user-images.githubusercontent.com/26198330/142163053-e340ac42-174d-40b5-9446-5ac615bd3202.png)

**Comment by crynobone** [comment] 2021-11-17 08:31
Duplicate of #3637

**Closed by crynobone** 2021-11-17 08:31 UTC

**Comment by nicolalazzaro** [comment] 2021-11-17 18:29
The bug has been fixed. 

`src/Illuminate/Database/Query/Builder.php`
[https://github.com/laravel/framework/pull/39644/files](url)
