### ISSUE TITLE
The lens is not displayed when it is in the related resource.

### ISSUE THREAD

**Issue by YarinceP** [laravel/nova-issues#2367] opened 2020-02-20 16:28 UTC
- Laravel Version: 6.16.0
- Nova Version: 2.9
- PHP Version: 7.2
- Database Driver & Version:
- Operating System and Version: Windows 10 Pro
- Browser type and version: Google Chrome

### Description:
The lens is not displayed when it is in the related resource.

I have a resource "Beneficiarios" in the create a "Alumno" lens. This resource is shown in the detail view of the "Instituciones" resource using a HasMany Field.

My problem is that the "Alumno" lens is not shown in the detail view of the "Instituciones" resource using the HasMany fields to show my "Beneficiarios" resource.

What I can be doing wrong ?

Or is this really not a feature of Nova lenses?

### **Screenshots**
![Resource Beneficiarios](https://user-images.githubusercontent.com/28911286/74954260-6e75cd00-53c8-11ea-9bc5-e07864c9e087.png)

![Detail View Instituciones](https://user-images.githubusercontent.com/28911286/74954271-72a1ea80-53c8-11ea-8b6b-ecd4d461b520.png)
□ Red : Place where the lens dropdown should be displayed.

![Detail View Instituciones 2](https://user-images.githubusercontent.com/28911286/74954414-b3016880-53c8-11ea-98bd-885ac5a9eea4.png)
□ Red : HasMany Field
□ Purple: Place where the lens dropdown should be displayed.

### Steps To Reproduce:
-Create a resource Beneficiarios.
-Create a Alumno lens in the Beneficiariosresource.
-Create a resource Instituciones.
-Add a HasMany Field resource Beneficiarios in the Instituciones resource.

**Comment by davidhemphill** [comment] 2020-02-23 01:26
Duplicate of #2366

**Closed by davidhemphill** 2020-02-23 01:26 UTC
