### ISSUE TITLE
Whitelabel in v4

### ISSUE THREAD

**Issue by Pezhvak** [laravel/nova-issues#3964] opened 2022-04-12 19:48 UTC
- Laravel Version: 9.1
- Nova Version: 4.1
- PHP Version: 8.1

### Description:
Previously we could publish assets and modify the footer, but it seems it's not possible in V4.
How can i change the copyright section?

**Comment by crynobone** [comment] 2022-04-12 21:27
Duplicate of https://github.com/laravel/nova-issues/discussions/3892

**Closed by crynobone** 2022-04-12 21:27 UTC
