### ISSUE TITLE
Default values for Action fields are ignored when opening from table row button

### ISSUE THREAD

**Issue by puzzledmonkey** [laravel/nova-issues#3758] opened 2022-02-25 03:34 UTC
- Laravel Version: 8.81.0
- Nova Version: 3.31.0
- PHP Version: 7.4.26
- Database Driver & Version:
- Operating System and Version: Windows 10
- Browser type and version: Firefox

### Description:

Default values for Action fields are ignored when opening from table row button.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1) Create a new model and nova resource and add a row

2) Create a new action and set up fields with default(function() { ... }) values

```
public function fields() {
    return [Text::make('Test')->default(function ($request) {
        return 'Success';
    })];
}
```

3) Assign the action to the resource in the actions() function using showOnTableRow()

```
public function actions(Request $request) {
    return [ TestAction::make()->showOnTableRow() ];
}
```

4) Observe that when selecting the resource via tickbox and then launching the action from the action menu in the top right, the 'Test' field is populated with 'Success' as expected

5) Observe that when launching the action from the resource row button, the 'Test' field is not populated with any value.

The issue seems to be that in `Laravel\Nova\Fields\Field`, the `resolveDefaultValue` function is stopping the default value population due to this check:

```
if ($request->isCreateOrAttachRequest()
    || $request->isResourceIndexRequest()
    || $request->isResourceDetailRequest()
    || $request->isActionRequest()
)
```

**Comment by crynobone** [comment] 2022-02-25 04:14
Unable to reproduce the issue, see https://github.com/nova-issues/issue-3758/commit/cb6387ededf7effbdaac549cfe596ac31c111db3

https://user-images.githubusercontent.com/172966/155652441-bde593a0-0623-4446-9f5b-d4b9a36e6340.mp4

**Comment by puzzledmonkey** [comment] 2022-02-25 05:47
my apologies, you are right. this issue was coming from a nova extension (gabelbart/nova-toolbar-tools) and I didn't debug far enough. sorry for wasting your time.

**Comment by puzzledmonkey** [comment] 2022-02-25 06:15
sorry - i'm going to reopen this one as i don't think it's specific to that plugin.

there's one more step to add in order to get this problem to manifest - in app/Providers/NovaServiceProvider in boot() add the following code

```
Nova::serving(function () {
    app(NovaRequest::class);
});
```

then the popups on the row buttons should have no default values any more

**Comment by crynobone** [comment] 2022-02-25 06:22
`NovaRequest` only get resolved via Laravel IoC when handling controllers action, you definitely will have an issue resolving it earlier.

**Comment by puzzledmonkey** [comment] 2022-02-25 06:39
I see. If this is expected behaviour please just close this issue. Alternatively if there's a way to force the NovaRequest to re-parse when the controllers action resolves it, it might be useful?

**Comment by crynobone** [comment] 2022-02-25 06:50
You can write the following:

```php
Container::getInstance()->forgetInstance(NovaRequest::class);
```

**Comment by puzzledmonkey** [comment] 2022-02-25 07:24
Thank you. Could you see a downside to just including that line before the IoC controllers "proper" parsing happens?

**Closed** 2022-02-25 09:15 UTC
Labels: needs more info

**Comment by puzzledmonkey** [comment] 2022-02-25 09:17
Good point. Thanks for spending time here giving me all this help. I've contacted the author of the library with the info here too, so I hope that'll be fixed soon too. Cheers!
