### ISSUE TITLE
customization authenticate guard

### ISSUE THREAD

**Issue by youruan** [laravel/nova-issues#574] opened 2018-09-15 16:37 UTC
In a new project . i need customization Authenticate guard. i have to change the source like this in `src/Http/Controllers/LoginController.php` 

` public function __construct()
    {
        $this->middleware('nova.guest:' . self::getGuardName())->except('logout');
    }

   protected function guard()
    {
        return Auth::guard(self::getGuardName());
    }

    private static function getGuardName()
    {
        return config('auth.nova.guard', 'web');
    }
`

and change  `config/nova.php`  file:
`'middleware' => [
        'web',
        Authenticate::class . ':admin',
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],
`

`config/nova.php`  file:
`
 'nova' => [
        'guard' => 'admin',
        'passwords' => 'admins',
    ],
`
`
  'guards' => [
         //other guards....

        'admin' => [
            'driver' => 'session',
            'provider' => 'admins',
        ],

       //....
    ],
`

`
 'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
        'admins' => [
            'driver' => 'eloquent',
            'model' => App\AdminUser::class,
        ],
        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

  'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],

        'admins' => [
            'provider' => 'admins',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],
`

who have a batter way ? please reply with me . thanks

**Comment by dkulyk** [comment] 2018-09-15 19:04
Duplicate of #43

**Closed** 2018-09-17 16:47 UTC
