### ISSUE TITLE
Call to undefined method Laravel\\Nova\\Fields\\BelongsTo::buildAttachableQuery()

### ISSUE THREAD

**Issue by calvinmuller** [laravel/nova-issues#425] opened 2018-09-04 14:04 UTC
It would seem that if you have 2 relationships using one resource you encounter the above.

This is what I have
```
BelongsTo::make('Organisation') - the creator of the project organisation_id on table projects,
BelongsToMany::make('Organisations') - the organisations involved in the projects (organisation_projects) relationship
```
Upon trying to attach an Organisation via the BelongsToMany relationship - the above error is displayed on screen.

<img width="1608" alt="screen shot 2018-09-04 at 16 03 30" src="https://user-images.githubusercontent.com/755442/45036208-2fc94700-b05c-11e8-8423-04bdedb83023.png">

**Comment by ardyn** [comment] 2018-09-07 16:46
Same issue. Same setup. Perhaps we could group fields together that are to be displayed or not displayed on a particular page. Then we can just skip these groups if they are irrelevant to the current page. now each field is executed and then it is determined whether to be displayed or not.

**Comment by calvinmuller** [comment] 2018-09-12 09:12
I wonder if anyone even looks at these issues - it would seem not.

**Comment by leemillward** [comment] 2018-09-13 15:55
I'm encountering a similar problem.  I have the following:

```
HasMany::make('Properties', 'properties', 'App\Nova\Property') - a user owns many properties
BelongsToMany::make('Bookmarks', 'bookmarks', 'App\Nova\Property') - a user has bookmarked many properties
```

I got round the issue by creating a separate Resource for bookmarks linked to the same model, as below:

```
BelongsToMany::make('Bookmarks', 'bookmarks', 'App\Nova\BookmarkProperty') 
```

This model was given the label of "Bookmarked Properties".  This then allowed everything to work as intended.

A side effect of this however is that even when explicitly specifying the Resource to use, on index views where the Property model is used in a MorphTo relationship, the label of the model uses Bookmarked Properties rather than Properties.

**Comment by telkins** [comment] 2018-09-15 15:58
Just dropping in to say that I'm experiencing the same problem.  I have a resource called `Person` as there are many "people" in my application.  A single `Event` has many relationships that are either one or more people: an owner, participants, a moderator...things like that.  This is causing me grief and while @leemillward 's workaround might work, I don't want to have to create and maintain a million different resources that are all the same but just differ in name.  :-/

**Comment by andrewicarlson** [comment] 2018-09-28 00:11
I'm experiencing the same issue when using an abstract like 'Asset' even when defining with all options, such as the below:

```
BelongsToMany::make('Assets')
    ->fields(function() {
        return [
            Boolean::make('Featured'),
        ];
    })
    ->hideFromIndex(),
BelongsTo::make('Lifestyle Background Image', 'lifestyleSectionBgAsset', 'App\Nova\Asset')
    ->hideFromIndex(),
```

**Comment by telkins** [comment] 2018-10-01 17:31
I'm not sure who to "ping", but is there any traction on this?

This is a showstopper for my app...unless I try @leemillward 's workaround, which I'd rather avoid as I'd have to have 3+ Nova resource classes that are effectively the same.  And that's just to manage one of my resources.  There are other resources with similar "issues".

Any updates/information would be welcome.  Thx.  :-)

**Comment by telkins** [comment] 2018-10-01 17:56
I poked around just a little bit and I have some information that **may** be helpful to someone.

As I said before, I have, among others, the following Nova resources:
- Person
- Event

An event has the following relationships:
- owner (`BelongsTo`)
- participants (`BelongsToMany`)
- moderator (`BelongsTo`)

I can create a new Event and I can assign an owner, for example.  When I go to attach participants, however, I get the aforementioned error.  The error occurs in `Laravel\Nova\Http\Controllers\AttachableController::index()` when trying to call `$field->buildAttachableQuery()`.

I took a look at `$field` and it's **not** the participant field, as would be expected.  Rather, it's the owner field.  It's trying to call `buildAttachableQuery()` on a `BelongsTo` relationship field but that doesn't exist, of course.  It is, however, found on the `BelongsToMany` relationship field.

How these are getting messed up under the hood....I don't know.  I know the UI displays the expected/correct text.  That is, it says, "Participant" and "Choose participants".

I should also note that the participant field is `searchable()`.  I will remove owner and/or moderator and see if any adjustments make any difference.  I'll also drop `searchable()` and see if that has any impact.

**Comment by telkins** [comment] 2018-10-01 18:09
OK.  I played around a bit, as I said I would, removing one/both of the `BelongsTo` relationship fields.  I also removed `searchable()` from them all.

In the end, since I'd just read #317 , I tried to change the order.  It was owner, then participants.  When I switch to participants, then owner, all was good in the world.  I switch back, bad things happen.

So, it seems like this is the same as #317, as I mentioned.  I'm doing this with 1.1.4, btw.  I'll make a note there.  I can live with having to order certain ways (assuming there are no other issues), but it still shows that something's amiss, I think.

**Comment by calvinmuller** [comment] 2018-10-02 05:41
@telkins yeah I also got around it with the ordering but seems like a sort of a silly workaround.

It would seem these issues do fall on deaf ears unfortunately so I guess the ordering would then too be the solution & workaround.

**Comment by lucacri** [comment] 2018-10-10 16:04
+1 for this issue, resolved for now by changing the order

**Comment by dsampaolo** [comment] 2018-10-22 09:54
Same for me. Issue resolved by changing the order. Thank you @telkins.

**Comment by dkulyk** [comment] 2018-10-22 11:14
See #855

**Comment by robertvrabel** [comment] 2018-11-01 12:06
+1 ran into the same thing using a `BelongsTo::make('Application')` and `BelongsTo::make('Applications')` on the same resource.

When attaching applications, it errors with `Call to undefined method Laravel\\Nova\\Fields\\BelongsTo::buildAttachableQuery()`

**Comment by remipou** [comment] 2018-12-13 20:15
👍

**Comment by rapitkan** [comment] 2019-01-03 08:35
Same problem here. I have `BelongsTo` and `BelongsToMany` for a same resource. Putting `BelongsToMany` line first helps but it should only be a workaround not the final solution for the problem.

**Closed** 2019-01-15 17:19 UTC

**Comment by dillingham** [comment] 2019-02-02 15:02
I get this error with the following field definition, sub directory.

```php
use \App\Nova\Billing\User;
```
```php
BelongsToMany::make('Users', 'users', User::class)->searchable(),
BelongsTo::make('Owner', 'owner', User::class)->searchable(),
```
It works when I change the order
```php
BelongsToMany::make('Users', 'users', User::class)->searchable(),
BelongsTo::make('Owner', 'owner', User::class)->searchable(),
```

**Comment by dwyer14** [comment] 2019-02-11 04:05
@dkulyk Can you confirm whether or not this made it into v1.3.1? Still having issues with a `BelongsTo` followed by a `BelongsToMany` on the same model/resource. Thanks!

**Comment by dkulyk** [comment] 2019-02-11 13:42
I cannot guarantee something, because i don't know your case. But regression will be fixed in next release after v1.3.1

**Comment by rikless** [comment] 2019-02-12 08:30
@dkulyk still present on current release

**Comment by dkulyk** [comment] 2019-02-12 10:05
Please make repository with example of code.

**Comment by dwyer14** [comment] 2019-02-12 14:09
@dkulyk Actually, yesterday's release (v1.3.2) seems to have fixed the "`BelongsTo` w/ `BelongsToMany`" issue. Thanks!

**Comment by tennessine** [comment] 2020-02-22 21:16
comment all BelongsToMany lines and save, visit the resource, then uncomment the lines before.
Likes there're some cache. odd

**Comment by chucklin72** [comment] 2020-03-09 16:09
This breaks when you have a resource that you create outside of Nova, then try to edit in nova.
