### ISSUE TITLE
Multi Select Field with resolve using not selecting integers and strings

### ISSUE THREAD

**Issue by electrictomcat** [laravel/nova-issues#5898] opened 2023-09-21 00:05 UTC
- Laravel Version: 9.5.12
- Nova Version: 4.27.12
- PHP Version: 8.2
- Operating System and Version: MacOS 14
- Browser type and version: Chrome  116.0.5845.187

### Description:
When a multi select field has a mixture of integer and float values and you try and preselect both only the float values get selected.

### Detailed steps to reproduce the issue on a fresh Nova installation:
When a multiselect has the values:
1
1.5
2
2.5

And you try to use resolveUsing to preselect 1.5 & 2, it will only select 1.5 and then mistakenly delete the data once the form is submitted.

**Comment by crynobone** [comment] 2023-09-21 00:26
Duplicate of #5696

**Closed by crynobone** 2023-09-21 00:26 UTC
