### ISSUE TITLE
Currency error on Windows system

### ISSUE THREAD

**Issue by FaridAghili** [laravel/nova-issues#1062] opened 2018-11-29 14:06 UTC
- Laravel Version: 5,7,15
- Nova Version: 1.2.0
- PHP Version: 7.2.12

### Description:
As mentioned in PHP doc, money_format() is not available on Windows based systems:

> The function money_format() is only defined if the system has strfmon capabilities. For example, Windows does not, so money_format() is undefined in Windows.

http://php.net/manual/en/function.money-format.php

Useful links:
http://php.net/manual/en/numberformatter.formatcurrency.php
http://php.net/manual/en/numberformatter.formatcurrency.php
http://php.net/manual/en/function.number-format.php

**Comment by bonzai** [comment] 2018-11-29 15:46
Duplicate of #254

**Closed by bonzai** 2018-11-29 15:46 UTC
