### ISSUE TITLE
Select Component doesn't close and search not working

### ISSUE THREAD

**Issue by meyer59** [laravel/nova-issues#6271] opened 2024-03-11 21:05 UTC
I don't know if it's related to the fix but the Select doesn't work anymore.
Keeps open, cannot select a value nor search.
Nova v.4.32.16

![image](https://github.com/laravel/nova-issues/assets/9505463/1018d7ab-afe9-4f61-b80b-8e5621fbb4ce)

_Originally posted by @meyer59 in https://github.com/laravel/nova-issues/issues/6107#issuecomment-1981732038_

**Comment by crynobone** [comment] 2024-03-12 02:49
Duplicate of #6107

**Closed by crynobone** 2024-03-12 02:49 UTC
