### ISSUE TITLE
ConfirmActionModal closing when selecting date

### ISSUE THREAD

**Issue by orlyapps** [laravel/nova-issues#1101] opened 2018-12-06 09:59 UTC
- Laravel Version: 5.7.0
- Nova Version: 1.2.0
- PHP Version: 7.2.12

### Description:
ConfirmActionModal closed when i try to pick a year or month in the Datepicker.

### Steps To Reproduce:
1. Add a date field to an Action
```
    public function fields()
    {
        return [
            Date::make('from')->rules('required'),
            Date::make('to')->rules('required'),
        ];
    }
```
2. Try to pick a year or month in the Datepicker

**Comment by dkulyk** [comment] 2018-12-06 14:51
What is your browser/os?

**Comment by dkulyk** [comment] 2018-12-06 15:56
I could not reproduce on Chrome 70(Mac)/71(Win)/Edge(Latest, Win)

**Comment by bonzai** [comment] 2018-12-06 17:47
This has been fixed and will be included in the next release.

#887

**Closed by bonzai** 2018-12-06 17:47 UTC

**Comment by phuclh** [comment] 2019-06-28 03:41
I am using confirm modal and date time picker component for my custom tool, and it happens to me too. Everytime I click the arrow buttons or pick a month or year, it will close the modal. How can I fix it?

**Comment by h-zone** [comment] 2019-08-06 09:09
Well, it is not fixed at 2.0.9, php 7.3, Laravel 5.8.30
Please check it again

**Comment by jbrooksuk** [comment] 2019-08-06 09:23
It's fixed for me on MacOS under Safari and Chrome 76.

**Comment by h-zone** [comment] 2019-08-06 09:25
Windows 10, Firefox v.68.0.1/x64

**Comment by jbrooksuk** [comment] 2019-08-06 09:25
Have you re-ran `php artisan nova:publish`?

**Comment by h-zone** [comment] 2019-08-06 09:27
> 
> 
> Have you re-ran `php artisan nova:publish`?

Yes, updating is automated via composer.json

**Comment by h-zone** [comment] 2019-08-06 09:29
Hmm, another windows 10 machine is norm. Why me !?
