### ISSUE TITLE
[4.x] dependsOn doesn't work with default values

### ISSUE THREAD

**Issue by williamcruzme** [laravel/nova-issues#3937] opened 2022-04-11 05:50 UTC
Laravel Version: 8.83.7
Nova Version: 15.7.0
PHP Version: 8.0
Database Driver & Version: MySQL 8.0
Operating System and Version: macOS 12.3.1
Browser type and version: Chrome Version 100.0.4896.75 arm64

### Description:

With the fields:
```php
Boolean::make('Unlimited')
    ->default(true),

Number::make('How many times?', 'replays')
    ->dependsOn(
        ['unlimited'],
        function ($field, $request, $formData) {
            if ($formData->unlimited) {
                $field->hide();
            }
        }
    ),
```

Since the Boolean field has default true, it should hide the Number field instantly, but that only happens after change the Boolean field.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/22250407/162672511-0eb03a8d-a03f-4036-abd3-43de7be8e82d.png">

**Comment by crynobone** [comment] 2022-04-11 05:55
Duplicate of #3899

**Closed by crynobone** 2022-04-11 05:55 UTC
