### ISSUE TITLE
Need advanced pagination

### ISSUE THREAD

**Issue by keyur5390** [laravel/nova-issues#980] opened 2018-11-15 11:06 UTC
Currently there is a basic pagination feature with 'Next' & 'Previous' options. It is more convenient to the developers if nova supports advanced pagination option. 
If there are number of records with n number of pages, at that time if user wants to go to some specific page or want to jump directly to the last page then it should be useful to have advanced pagination with numbers and other options. 
Please suggest how to integrate it with nova admin,

**Comment by tristanbailey** [comment] 2018-11-15 12:14
Would love the normal laravel object pagination options too.

**Comment by dillingham** [comment] 2018-11-15 13:43
https://github.com/laravel/nova-issues/issues/316

**Comment by davidhemphill** [comment] 2018-11-15 16:00
Duplicate of #316

**Closed by davidhemphill** 2018-11-15 16:00 UTC
