### ISSUE TITLE
BelongsToMany loses selection when validation fails

### ISSUE THREAD

**Issue by seanareed** [laravel/nova-issues#2267] opened 2020-01-05 19:25 UTC
- Laravel Version: 5.8.36
- Nova Version: 2.9.2
- PHP Version: 7.2.26
- Operating System and Version: Ubuntu 16.04.6
- Browser type and version: Chrome 79, Firefox 71

### Description:

I'm having the exact issue as the original poster on #1576 but I'm bringing it up in a new ticket since that ticket has been closed. 

One poster on that thread indicated that the issue was resolved by Nova v2.4, but I've updated to 2.9 and it's still happening.

- I've run `php artisan nova:publish`
- I've run `config:clear`, `cache:clear`, `optimize:clear`
- I've cleared the browser cache and site data

The `->searchable()` trick seems to only work when attaching a new item, but not when updating an existing attached item.

Example code to recreate (this forces a validation fail just for demonstration):

```
BelongsToMany::make('Libraries')->rules('max:0'),
```

Fresh form:

![Screen Shot 2020-01-05 at 2 19 46 PM](https://user-images.githubusercontent.com/14617978/71784888-d4e48e80-2fc6-11ea-8995-21806596372b.png)

On validation fail:

![Screen Shot 2020-01-05 at 2 19 32 PM](https://user-images.githubusercontent.com/14617978/71784894-dd3cc980-2fc6-11ea-9f40-301763bc2ec0.png)

**Comment by renky** [comment] 2020-01-09 13:45
Did you recompile after publishing?
The fix was done in javascript, and only publishing vendor:nova doesn't help if you don't recompile...

**Comment by seanareed** [comment] 2020-01-10 00:37
@renky I attempted modifying and recompiling the Vue component myself after my original posting, but it consistently failed. Do you have some guidance on how to successfully recompile?

**Comment by seanareed** [comment] 2020-01-11 19:37
@renky I managed to get the recompile I've done the following, in this order:

- Deleted node_modules from both root and /nova
- Updated to latest Xcode for Catalina compatibility
- Run `yarn install` then `yarn prod` in project rood directory
- Run `yarn install` then `yarn prod` in nova directory
- Run `php artisan nova:publish` in root directory
- Cleared site data in browser
- Cleared browser cache

Behavior remains unchanged.

I also tried publishing first, then recompiling in both directories. No difference.

**Comment by antlusher** [comment] 2020-01-12 08:25
->rules(max:0)? Change it to max:255. Or just required.

**Comment by seanareed** [comment] 2020-01-12 13:56
@antlusher The `>rules(max:0)` is only for demo purposes to force the validation to fail. 

The issue is that the selected resource disappears from the select field (becomes no selection) when the validation fails (shown in the images).

My actual field with rules look like this:

```
BelongsToMany::make('Libraries')
    ->fields(function ($request) {
        return [
            Select::make('Library User Role', 'library_user_role_id')
                ->options(LibraryUserUtils::getLibraryUserRoleOptions())
                ->sortable()
                ->rules('required')
                ->displayUsingLabels(),
            Boolean::make('Primary')
                ->sortable()
                ->rules('nullable', function ($attribute, $value, $fail) use ($request) {
                    $id = $request->resourceId;
                    $library = $request->libraries;
                    $user = \App\User::find($id);
                    $pl = $user->primary_library();
                    if ($value && $pl && $library && $pl->id !== intval($library)) {
                    	return $fail('The ' . $attribute . ' '.
                            'library has already been selected ' .
                            'for user ' . $user->first_name . ' ' .
                            $user->last_name . '.');
                    }
                })
        ];
    })
```

**Comment by antlusher** [comment] 2020-01-13 12:59
@seanareed agh got ya. Sorry about my misunderstanding. Have you opened the Inspect tools, sounds like the JS is clearing the select DOM element. Be cool to supply a before and after screen of the DOM? Just suggestions. Ant

**Comment by seanareed** [comment] 2020-01-16 01:08
@renky Also, I upgraded to 2.9.2 by downloading the zip and replacing the entire nova directory. I wouldn't need to recompile anyway if using that approach, right?

**Comment by seanareed** [comment] 2020-01-16 01:30
@antlusher The HTML seems to look as though the "placeholder" option ("Choose Libraries") is already selected on the first page load, which I don't quite understand right off.

Here are screenshots of the page including the corresponding elements inspector when the Update view is first loaded and after the validation fails:

Fresh form:

![Screen Shot 2020-01-15 at 8 04 42 PM](https://user-images.githubusercontent.com/14617978/72485415-a5f3c700-37d5-11ea-8d1e-47719c07a59c.png)

On validation fail:
![Screen Shot 2020-01-15 at 8 05 08 PM](https://user-images.githubusercontent.com/14617978/72485425-ad1ad500-37d5-11ea-8cd9-a6ce6e4278ab.png)

**Comment by seanareed** [comment] 2020-01-19 15:52
I fixed this by modifying the nova source code and recompiling.

I based the solution on the comment here:

https://github.com/laravel/nova-issues/issues/1576#issuecomment-501105502

In `/nova/resources/js/views/UpdateAttached.vue` I added `:value="selectedResourceId"` to the `<select-control` tag and recompiled nova. That fixed it.

The selected BelongsToMany option no longer disappears when validation fails.

**Comment by seanareed** [comment] 2020-01-19 16:06
(Same change has to be made to `/nova/resources/js/views/Attach.vue` as well.)

**Comment by jbrooksuk** [comment] 2020-02-18 13:22
@seanareed would you mind making a PR to address this?

**Comment by jbrooksuk** [comment] 2020-02-18 13:24
Actually, this is a duplicate of https://github.com/laravel/nova-issues/issues/1898 (but still make a PR to address #1898).

**Closed by jbrooksuk** 2020-02-18 13:24 UTC
Labels: bug
