### ISSUE TITLE
Hover to button with custom color

### ISSUE THREAD

**Issue by suchoproduction** [laravel/nova-issues#4394] opened 2022-06-10 07:48 UTC
Laravel Version: 9.17.0
Nova Version: 4.8.1
PHP Version: 8.1.0
Database Driver & Version:
Operating System and Version: MacOS 12.3.1
Browser type and version: Google Chrome 102

### Description:

Custom color set in `./config/nova.php`
```
     'brand' => [
         'colors' => [
             "400" => "218, 35, 30, 0.5",
             "500" => "218, 35, 30",
             "600" => "218, 35, 30, 0.75",
         ]
     ],
```

After hover to button `hover:bg-primary-400` is background-color transparent
In `Nova 4.7.0` everything was fine

Default colors have no problem.

![Snímka obrazovky 2022-06-10 o 9 38 44](https://user-images.githubusercontent.com/6931349/173016988-659f9fa5-82bb-4b43-8707-fa250bb50519.png)

**Comment by bashgeek** [comment] 2022-06-10 07:56
Having the same issue with 4.7.1, was fine with 4.6.x

**Comment by mira-thakkar** [comment] 2022-06-10 12:32
Getting same issue with 4.8.1

**Comment by crynobone** [comment] 2022-06-10 13:36
This might be related to changes to Tailwind 3, will investigate.

**Comment by jjjrmy** [comment] 2022-06-10 15:56
Same issue on Login Button

**Comment by crynobone** [comment] 2022-06-12 05:47
Tailwind 3 introduces a new opacity option for all color variants causing `alpha/opacity` option to become invalid. A quick fix right now is to change `${R}, ${G}, ${B}, ${A}` to `${R}, ${G}, ${B}` for each `nova.brand.colors.*`

**Comment by jimmitjoo** [comment] 2022-06-20 15:39
Same issue for me when upgrading from 4.7 to 4.8 and upwards.

**Comment by gldrenthe89** [comment] 2022-06-21 17:55
Same issue here

**Comment by suchoproduction** [comment] 2022-06-22 06:01
Same issue in 4.10.0

**Comment by jimmitjoo** [comment] 2022-06-23 15:50
> Tailwind 3 introduces a new opacity option for all color variants causing `alpha/opacity` option to become invalid. A quick fix right now is to change `${R}, ${G}, ${B}, ${A}` to `${R}, ${G}, ${B}` for each `nova.brand.colors.*`

That does work as a temporary fix for me. Thank you!

Changed the brand colors like this:
```
'colors' => [
    "400" => "251,154,164",
    "500" => "238,43,71",
    "600" => "245,103,118",
]
```

**Comment by baszach** [comment] 2022-07-05 11:18
The problem only occurs when the opacity is set. For example ` "400" => "251,154,164",0.6`. Like @jimmitjoo said you can choose the color codes without opacity. For example `FF9900` with 50% opacity is the same as `F2BE72`. It's also more consistent to work with specific color codes and not opacity.

**Comment by henryavila** [comment] 2022-07-13 18:47
> "400" => "251,154,164",
>     "500" => "238,43,71",
>     "600" => "245,103,118",

This was working until yesterday, but no it wotking no more.
Anyone has any new clue about this?

**Comment by ramsha-mt** [comment] 2022-08-17 07:48
> > Tailwind 3 introduces a new opacity option for all color variants causing `alpha/opacity` option to become invalid. A quick fix right now is to change `${R}, ${G}, ${B}, ${A}` to `${R}, ${G}, ${B}` for each `nova.brand.colors.*`
> 
> That does work as a temporary fix for me. Thank you!
> 
> Changed the brand colors like this:
> 
> ```
> 'colors' => [
>     "400" => "251,154,164",
>     "500" => "238,43,71",
>     "600" => "245,103,118",
> ]
> ```

Could be a temporary fix but this needs fixing asap because the hover effect from buttons will be gone!!

**Comment by scramatte** [comment] 2022-08-18 18:18
Hi,

Same issue here. Please fix it asap.
Regards

**Comment by davidhemphill** [comment] 2022-08-19 21:40
This has been fixed and will be included in the next release. 👍

**Closed** 2022-08-19 21:39 UTC
Labels: pending

**Comment by jodhaakbar** [comment] 2022-09-06 02:36
still issue on nova `4.13.0`

**Comment by davidhemphill** [comment] 2022-09-06 20:08
I confirmed this to be working on a fresh Nova application running 4.13.0. If you still have the issue, please post a new one with all the details filled in so we can replicate the issue on our end. Thanks!
