### ISSUE TITLE
Datatable prefix not taken on model

### ISSUE THREAD

**Issue by PrestaSafe** [laravel/nova-issues#69] opened 2018-08-23 19:37 UTC
Prefixes table are not taking by the model. I need to put it manualy.
in my laravel,in my Invoice Model:
`protected $table = 'invoices';`
and the prefix is "erp_"

and i need to put:
`protected $table = 'erp_invoices';`
for working.

It's normal ?
Thanks

**Comment by guillaume23** [comment] 2018-08-23 20:42
Yes exact !
My migrations works so my préfix works but on the modal nova dont take the prefix. 
Message is database invoices (in my case) doesn't exists. If il put the prefix manuelly in the model it works fine.

**Comment by davidhemphill** [comment] 2018-10-26 17:46
Duplicate of #8

**Closed by davidhemphill** 2018-10-26 17:46 UTC
Labels: invalid
