### ISSUE TITLE
Can't login with username instead of email.

### ISSUE THREAD

**Issue by crumb1e** [laravel/nova-issues#110] opened 2018-08-24 08:23 UTC
When creating a user using the `php artisan nova:user` command, it says `Username / Email Address`, after creating a user with a username instead of an email address, I am unable to login to my nova backend as the field requires an email.

![screen shot 2018-08-24 at 09 17 24](https://user-images.githubusercontent.com/18497168/44573742-585d6100-a77f-11e8-80e2-8e56e40381f6.png)

![screen shot 2018-08-24 at 09 23 50](https://user-images.githubusercontent.com/18497168/44573774-762ac600-a77f-11e8-919d-f25926c0c74d.png)

**Comment by zeroseed** [comment] 2018-08-24 12:11
You need to change the Model
https://stackoverflow.com/a/51990653/3409182

Check this link , i’ve answer this same question

**Comment by m2de** [comment] 2018-08-25 12:16
I think the issue is more with the wording of the `artisan nova:user` prompt, which asks the user for a `Username or Email Address`, but out of the box a Username isn't actually supported.

**Comment by davidhemphill** [comment] 2018-09-19 22:27
This has been fixed and will be included in an upcoming release.

**Closed by davidhemphill** 2018-09-19 22:27 UTC

**Comment by cerw** [comment] 2018-11-14 04:52
@davidhemphill can you tell us which version has this fix?

**Comment by davidhemphill** [comment] 2018-11-15 04:07
Not sure, but the prompt only asks for email now.

**Comment by renky** [comment] 2019-03-08 13:50
sorry, but thats not a fix^^

**Comment by shirshak55** [comment] 2020-04-04 13:01
@davidhemphill any reason to close without fixing this issue?  Or there is no interest in fixing this issue just because most people use email field in User model?

```Illuminate\Foundation\Auth\AuthenticatesUsers@username()``` can be overridden so we can use 'username' as field. But in the login controller of Laravel Nova it doesn't have any way method etc. to override that username field. I think its better to add following code `Laravel\Nova\Http\Controllers\LoginController`

```
    protected function guard()
    {
        return config('nova.username','email'),
    } 
```

So if we add username in nova config file it will work via email out of fix. I don't even use email and use phone number so with this logic i can use `phone_number` also. Unfortunately i cannot PR due to fact i used it in client project so they don't give me github access.

Currently for those who wants to do it can do it like this.

Don't autoload the nova core service provider and create the own service provider lets say NovaCoreServiceProvider.

Override the method to 
```
  public function withAuthenticationRoutes($middleware = ['web'])
    {
        Route::namespace('Laravel\Nova\Http\Controllers')
            ->domain(config('nova.domain', null))
            ->middleware($middleware)
            ->prefix(Nova::path())
            ->group(function () {
                Route::get('/login', 'LoginController@showLoginForm');
               
                //////////////////////////////////////////////////////////////////////////
           
               // CHANGE THE BELOW CONTROLLER to our own controller like this
                Route::post('/login', \App\Http\Controller\NovaLoginController@login)->name('nova.login');
            });

        Route::namespace('Laravel\Nova\Http\Controllers')
            ->domain(config('nova.domain', null))
            ->middleware(config('nova.middleware', []))
            ->prefix(Nova::path())
            ->group(function () {
                Route::get('/logout', 'LoginController@logout')->name('nova.logout');
            });

        return $this;
    }
```

Create controller inside `App/Http/Controller/NovaLoginController` and make code look like this


```
// Clipped top part like namespace
class NovaLoginController extends \Laravel\Nova\Http\Controllers\LoginController{
  public function username(){
    return 'username'; // If u use phone number like me then return 'phone_number'
 }
}
```

I think thats all. And the good thing is even laravel nova gets updated the code will work.


If u like my work please support me :)
Thanks.
