### ISSUE TITLE
Error when building Nova 4.32.11 to enable Vue devtools

### ISSUE THREAD

**Issue by ProjectesFUAB** [laravel/nova-issues#6121] opened 2023-12-21 07:42 UTC
- Laravel Version: 10.10
- Nova Version: 4.32.11

### Description:
Building Nova following this instructions https://nova.laravel.com/docs/customization/frontend.html#vue-devtools get multiple erros like this

ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\www\tpv.local\postcss.config.js from C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\loaders.js not supported.
Instead change the require of postcss.config.js in C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\loaders.js to a dynamic import() which is available in all CommonJS modules.
    at module.exports (C:\www\tpv.local\vendor\laravel\nova\node_modules\import-fresh\index.js:32:59)
    at loadJs (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\loaders.js:16:18)
    at Explorer.loadFileContent (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\Explorer.js:84:32)
    at Explorer.createCosmiconfigResult (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\Explorer.js:89:36)
    at Explorer.loadSearchPlace (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\Explorer.js:70:31)
    at async Explorer.searchDirectory (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\Explorer.js:55:27)
    at async run (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\Explorer.js:35:22)
    at async cacheWrapper (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\cacheWrapper.js:16:18)
    at async cacheWrapper (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\cacheWrapper.js:16:18)
    at async cacheWrapper (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\cacheWrapper.js:16:18)
    at async cacheWrapper (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\cacheWrapper.js:16:18)
    at async cacheWrapper (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\cacheWrapper.js:16:18)
    at async cacheWrapper (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\cacheWrapper.js:16:18)
    at async Explorer.search (C:\www\tpv.local\vendor\laravel\nova\node_modules\cosmiconfig\dist\Explorer.js:27:20)
    at async loadConfig (C:\www\tpv.local\vendor\laravel\nova\node_modules\postcss-loader\dist\utils.js:68:16)
    at async Object.loader (C:\www\tpv.local\vendor\laravel\nova\node_modules\postcss-loader\dist\index.js:54:22)
    at processResult (C:\www\tpv.local\vendor\laravel\nova\node_modules\webpack\lib\NormalModule.js:764:19)
    at C:\www\tpv.local\vendor\laravel\nova\node_modules\webpack\lib\NormalModule.js:866:5
    at C:\www\tpv.local\vendor\laravel\nova\node_modules\loader-runner\lib\LoaderRunner.js:400:11
    at C:\www\tpv.local\vendor\laravel\nova\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (C:\www\tpv.local\vendor\laravel\nova\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\www\tpv.local\vendor\laravel\nova\node_modules\postcss-loader\dist\index.js:56:7)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 6 errors

### Detailed steps to reproduce the issue on a fresh Nova installation:
cp .\webpack.mix.js.dist .\webpack.mix.js
npm ci
npm run dev

**Comment by Muetze42** [comment] 2023-12-22 09:18
A a `postcss.config.js` file in the Nova root path:

```js
module.exports = {
  plugins: [
    require('autoprefixer'),
  ],
};
```

**Comment by davidhemphill** [comment] 2024-01-03 20:38
Closing since there's no way to reproduce this.

**Closed by davidhemphill** 2024-01-03 20:38 UTC
