### ISSUE TITLE
Not able to set showTrashedOption in FilterMenu.vue through Resource

### ISSUE THREAD

**Issue by schonhoff** [laravel/nova-issues#1355] opened 2019-02-13 07:07 UTC
- Laravel Version: 5.7.24
- Nova Version: 1.3.1
- PHP Version: 7.2.14
- Operating System and Version: WAMP Apache 2.4.27
- Browser type and version: Google Chrome 72.0.3626.96

### Description:
I'm not able to set the parameter showTrashedOption in FilterMenu.vue through a resource. I'm doing it because I want the user to be able to restore some resource. I'm using the indexQuery to list only trashed resources but the filter menu is showing up. The user shouldn't be allowed to use the filter menu in this case. That is why I don't want to show them the filter menu at all. After a lot of research I find a showTrashedOption in the FilterMenu.vue but I'm not able to set the parameter in the resource.

`<div v-if="softDeletes && showTrashedOption">`
Line 44 in FilterMenu.vue

### Steps To Reproduce:
I tried to implement a static method called showTrashedOption with return "false" in the resource and i tried a static attribute. 

So I don't know if I'm missing something or it isn't possible at the moment.

**Comment by bolechen** [comment] 2019-05-05 09:51
Duplicate of #333

**Comment by davidhemphill** [comment] 2019-05-14 04:37
Duplicate of #333

**Closed by davidhemphill** 2019-05-14 04:37 UTC
