### ISSUE TITLE
Place breaks with space in make method

### ISSUE THREAD

**Issue by dwyer14** [laravel/nova-issues#39] opened 2018-08-23 16:17 UTC
Nova 1.0.4
Adding a space in Place `make` method breaks functionality on the front end. This works:

```
    protected function addressFields()
    {
        return [
            Place::make('Line1', 'address_1')->hideFromIndex()
                ->secondAddressLine('address_2')
                ->postalCode('zipcode'),
            Text::make('Line 2', 'address_2')->hideFromIndex(),
            Text::make('City')->hideFromIndex(),
            Text::make('State')->hideFromIndex(),
            Text::make('Zipcode')->hideFromIndex(),
        ];
    }
```

This does not; notice space in `Place::make('Line 1', 'address_1')`:
```
    protected function addressFields()
    {
        return [
            Place::make('Line 1', 'address_1')->hideFromIndex()
                ->secondAddressLine('address_2')
                ->postalCode('zipcode'),
            Text::make('Line 2', 'address_2')->hideFromIndex(),
            Text::make('City')->hideFromIndex(),
            Text::make('State')->hideFromIndex(),
            Text::make('Zipcode')->hideFromIndex(),
        ];
    }
```

Getting the following error in console:
```
vendor.js?id=90728b2f4840cb3e821d:1 DOMException: Failed to execute 'querySelector' on 'Document': '#Line 1' is not a valid selector.
    at a.initializePlaces (http://twentyfor.test/nova-assets/app.js?id=0eb7c4bee79fd33bca51:1:722889)
    at a.mounted (http://twentyfor.test/nova-assets/app.js?id=0eb7c4bee79fd33bca51:1:722768)
    at we (http://twentyfor.test/nova-assets/vendor.js?id=90728b2f4840cb3e821d:1:389362)
    at Object.insert (http://twentyfor.test/nova-assets/vendor.js?id=90728b2f4840cb3e821d:1:397839)
    at x (http://twentyfor.test/nova-assets/vendor.js?id=90728b2f4840cb3e821d:1:430750)
    at a.__patch__ (http://twentyfor.test/nova-assets/vendor.js?id=90728b2f4840cb3e821d:1:432108)
    at a.t._update (http://twentyfor.test/nova-assets/vendor.js?id=90728b2f4840cb3e821d:1:406244)
    at a.<anonymous> (http://twentyfor.test/nova-assets/vendor.js?id=90728b2f4840cb3e821d:1:438649)
    at Ne.get (http://twentyfor.test/nova-assets/vendor.js?id=90728b2f4840cb3e821d:1:390583)
    at Ne.run (http://twentyfor.test/nova-assets/vendor.js?id=90728b2f4840cb3e821d:1:391467)
```

Maybe/kinda related, getting deprecation notices in Chrome, for unescaped `#` characters:
```
[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.
```

**Comment by DSpeichert** [comment] 2018-08-26 21:57
I can reproduce this issue.

**Comment by devmsh** [comment] 2018-08-27 00:57
This is because in `PlaceField.vue` the input id depend on the `field.name` and it's used in the `querySelector` in the same file witch did not support spaces.

You must modify this file and recompile the nova assets if its important to you right now

**Comment by dwyer14** [comment] 2018-08-27 02:06
@devmsh Yeah, got that. Just seems like it (Nova itself) should account for spaced field names. Not super-critical for me; updated the field temporarily and will watch for a native fix. Thanks though!

**Comment by davidhemphill** [comment] 2018-08-30 19:28
This has been fixed and will be included in an upcoming release.

**Closed by davidhemphill** 2018-08-30 19:28 UTC
