### ISSUE TITLE
MultiSelect fields visually deselecting when multiple options selected

### ISSUE THREAD

**Issue by electrictomcat** [laravel/nova-issues#5532] opened 2023-05-14 05:38 UTC
- Laravel Version: 10.10.1
- Nova Version: 4.24.2
- PHP Version: 8.2
- Database Driver & Version:
- Operating System and Version: Mac OS 13.4 Beta (22F5059b)
- Browser type and version: Chrome Version 112.0.5615.137

### Description:
A Multiselect field that is depended on and depends on other fields will appear to deselect when you select more than one item.
The selection is still active.

https://github.com/laravel/nova-issues/assets/16545651/a01b530c-ffb6-4e0c-a0b4-a70329f35b96

**Comment by crynobone** [comment] 2023-05-14 23:51
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment] 2023-05-15 05:39
Sorry, just realised this was fixed via laravel/nova#2455 and will be available in the next release.

**Closed by crynobone** 2023-05-15 05:39 UTC
Labels: needs more info

**Comment by sagearslan** [comment] 2023-05-16 05:19
Thanks @crynobone 👍  Do you have an eta for the next release?
