### ISSUE TITLE
Can't personalize properly translations including resources

### ISSUE THREAD

**Issue by mathieutu** [laravel/nova-issues#1128] opened 2018-12-13 12:59 UTC
Hi,
When showing translation with resource name, the singular name is never in the translation, and so we can't personalize the way it is in the label.

nova/resources/js/views/Create.vue:
`<heading class="mb-3">{{ __('New') }} {{ singularName }}</heading>`

Could we change them to something like:
`<heading class="mb-3">{{ __('New :resource', {'resource': singularName}) }}</heading>`

To let us translate it properly?

Or even better, let us customize the translation for the current resource. In the resource class, setting translations with methods.

Example of fails out of the box, in french: 
- `Nouveau Utilisateur` instead of `Nouvel utilisateur`
- `Nouveau Option` instead of `Nouvelle option`
- `Créer Utilisateur` instead of `Créer un utilisateur`
- `Créer Option` instead of `Ajouter une option`

I would be glad to make a PR, if only it was possible...

Thanks.
Matt'

**Comment by bonzai** [comment] 2018-12-13 13:08
Duplicate of #203

**Closed by bonzai** 2018-12-13 13:08 UTC
