### ISSUE TITLE
Direct navigation from one lens to another lens under same resource keeps old data

### ISSUE THREAD

**Issue by bomshteyn** [laravel/nova-issues#979] opened 2018-11-15 06:16 UTC
- Laravel Version: 5.7.13
- Nova Version: 1.1.7
- PHP Version: 7.2.11

### Description:
I have a resource with two lenses. If i navigate directly from one lens to the other by url without going back to parent resource the data on the page doesn't refresh.

### Steps To Reproduce:

- Create Resource
- Create two lenses
- Add links to them into the navigation menu
- Click on one then on another

**Comment by avrahamappel** [comment] 2018-11-15 15:15
Seems like there is no watcher for a change in the `lens` prop.

**Comment by dillingham** [comment] 2018-11-15 15:24
Confirmed, didn't notice it in my "Reports" dropdown of lenses

**Comment by davidhemphill** [comment] 2018-11-15 15:53
This has been fixed and will be included in an upcoming release.

**Comment by dillingham** [comment] 2018-12-01 18:35
@davidhemphill filters stay the same and don't refresh relating to this bug

**Comment by dillingham** [comment] 2018-12-01 18:37
@davidhemphill should I open a new issue?

**Comment by dillingham** [comment] 2018-12-01 18:37
@davidhemphill / @bonzai should I open a new issue?

**Comment by dillingham** [comment] 2018-12-02 23:11
@davidhemphill also navigating from main menu doesn't clear the filters

**Comment by jtallant** [comment] 2019-03-18 21:24
I'm still seeing filters carried over between lenses. Is this going to be fixed anytime soon?

**Comment by jtallant** [comment] 2019-03-18 21:40
More info:

Nova version: 1.3.2

Create two lenses.
Define a filter for and attach it to Lens A.
Click Lens A,
See filters in menu
Click Lens B
See Lens A filters in Lens B menu

This is a pretty big bug as now my lenses are all trash unless I hardcode the URLs (slower) in the the navigation bypassing vue router and remove the lens menu.

**Comment by dkulyk** [comment] 2019-03-18 22:07
@dillingham It fixed on 2.0.0
@jtallant Check it on 2.0.0 and make another issue if issue is present.

**Closed by dkulyk** 2019-03-18 22:07 UTC
Labels: bug

**Comment by jtallant** [comment] 2019-04-23 23:59
@davidhemphill @dkulyk updated to nova 2.0 and still have the same problem. The sidebar has 14 lens links on it and the filters still get carried over lens to lens. I'm still having to hardcode the URL and bypass Vue router forcing the whole SPA to load everything every time someone wants to go to a different lens which is mostly what they'll be doing in the app.

**Comment by elambro** [comment] 2019-05-07 07:44
https://github.com/laravel/nova-issues/issues/1573

**Comment by davidhemphill** [comment] 2019-05-08 17:44
This was fixed in v2.0 and am not able to reproduce the filter issue as you've described. For instance, I have two lenses, with `router-links` in the sidebar, and the data is refreshed and filtered as expected: 

http://davehe.mp/mUJhwH

What am I missing?
