### ISSUE TITLE
Searching on Detail page with Metrics does not refresh Metrics

### ISSUE THREAD

**Issue by gjsman** [laravel/nova-issues#955] opened 2018-11-08 23:28 UTC
- Laravel Version: 5.7
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:
If I have a metric (or two) on a detail page, and search for a different item in the same model and click it, the metrics will not update to the new model.

### Steps To Reproduce:
1. Create a Nova setup, with a Model 
2. Place a metric (in my case, a chart) on the Model linking to some dummy count specific to that model.
3. Go to the model detail page. In the search bar, search for a different model and click it. The page will update, but the metrics will not update.

**Comment by coreation** [comment] 2019-01-14 12:02
+1 For this, I thought I was missing an option, but then I came across this post.

**Comment by Milkhan** [comment] 2019-02-06 13:53
Also it does'nt refresh after you make some changes with actions.
### Steps To Reproduce:
1- Create a Nova action,
2- Create a metric and put both on a resource
(in my case Action was to change the status and metric to show status)
3- Select some rows and change the status with the statusChange action. 
You cant see a change on the metric unless you refresh the page.

**Comment by dkulyk** [comment] 2019-02-06 14:03
Why it should update metrics?

**Comment by Milkhan** [comment] 2019-02-06 14:06
@dkulyk Because lets say metrics show 15 users with inactive status. And the action changed 3 of them and there are 12 users with inactive status. How should one trigger the metric to be updated?

**Comment by coreation** [comment] 2019-02-06 14:41
+1, my use case is that I'd like to show metrics (a Trend) on my resource detail page with data specifically tailored to that resource.

**Comment by dkulyk** [comment] 2019-02-06 15:23
@Milkhan you can initiate refresh page from Action

**Comment by Milkhan** [comment] 2019-02-06 15:52
> @Milkhan you can initiate refresh page from Action

@dkulyk Blogadarju!

**Comment by coreation** [comment] 2019-02-06 16:03
@dkulyk Any tips for if you don't have any actions? My use case is that you're looking at a resource detail #1, where cards are depending on the resourceID. If you search in the top bar for resource #2, click on the search result, the cards remain the same, no new calls are done, yet the card data is dependant on the resource ID. 

At first I thought this was by design, but since you pass the resourceId to the cards themselves, it means that cards meant to be customizable based on the resource ID (careful assumption).

So is this a bug, or a feature request?

**Comment by coreation** [comment] 2019-03-10 15:51
It would be nice if someone could confirm if this is a bug or not. Looking in the code it appears that it is, the cards receive a resourceId, but when you search for and go to  a different resource, the cards themselves don't update. @dkulyk not sure if you're the person to ask but if this is a bug, it would be nice to mark it as such and eventually we (or I) can work on a proposed fix?

**Comment by coreation** [comment] 2019-03-10 19:32
For anyone wanting to fix this themselves, it's really simple. Just add a watch statement in the vue components of the metrics:
* ValueMetric
* TrendMetric
* PartitionMetric

Since the components accept the resourceId as a property, I think it's fair to say that this - not updating the data when the resourceId changes - is a bug, not a feature request.

Add the following piece of code to the vue component and rebuild your project. Then you'll notice that when you go from one detail to another, your metrics will update as well.

```
watch: {
        resourceId() {
            this.fetch();
        }
    },
```

**Comment by gjsman** [comment] 2019-03-28 16:23
@taylorotwell can you merge this simple fix?

**Comment by coreation** [comment] 2019-03-28 16:39
@gjsman i don't think there's a PR yet though? If there isn't I can make one, it's something very small.

**Comment by gjsman** [comment] 2019-03-28 16:43
Right. That would be great @coreation !

**Comment by coreation** [comment] 2019-03-28 17:02
@gjsman but i can't because it's a private repository obviously :D so i think the hassle is far smaller for them to just take the above solution than to give me access and make the changes.

**Comment by gjsman** [comment] 2019-03-28 17:39
@coreation Right. At least I mentioned taylorotwell, hopefully he can do something.

Also, is there a place to report illegal/mistaken Laravel Nova uploads? It doesn't take long using GitHub search to find things like this: https://github.com/cleverjack/Laravel_Nova/tree/master/nova

**Comment by gjsman** [comment] 2019-03-29 01:28
@coreation Hi, I just added that into the Vue controllers (without error), but it still isn't refreshing the metrics. You said to rebuild the project. Am I missing something with that step?

**Comment by admench** [comment] 2019-04-01 16:38
I'm getting the same issue here: Clicking on a link to a different model will not refresh the resource value cards, only a hard page refresh repopulates the cards with the correct values from the DB.

**Comment by fobin** [comment] 2019-04-02 07:25
Same here. It also on first load the path is not completely visible. It's fixed by switching the filter or resizing window. 
![image](https://user-images.githubusercontent.com/1096951/55383771-a3b7c900-5531-11e9-96b1-68ba9f383e3d.png)

**Comment by coreation** [comment] 2019-04-02 07:31
@gjsman I put that watcher directly into the Metrics Vue components (i.e. nova/resources/js/components/Metrics/ValueMetric.vue). Then you have to rebuild your front-end as described in the [documentation of Nova](https://nova.laravel.com/docs/2.0/customization/tools.html), the recompiling of the front-end code is all the way down the bottom.

**Comment by davidhemphill** [comment] 2019-06-28 19:45
This has been fixed and will be included in the next release. 👍

**Closed by davidhemphill** 2019-06-28 19:45 UTC
