### ISSUE TITLE
Per Page pagination filter not working

### ISSUE THREAD

**Issue by emilianotisato** [laravel/nova-issues#1514] opened 2019-04-11 22:26 UTC
- Laravel Version: 5.8.2
- Nova Version: 2.0.1
- PHP Version: 7.1.23
- Operating System and Version: macOS 10.14.3
- Browser type and version: google chrome ( Version 72.0.3626.119 (Build official) (64 bits) )

### Description:
When you have more than 25 resource items, and you change from the select (image attached) to 50 or 100 per page, no error is throw in the javascript console, the url in the browser do change to my_resource_per_page=100 but the index remains with 25...

### Steps To Reproduce:
1) Have more than 25 resource seeded in your db
2) go to the index of that resource
3) change the amount of "per page" items to 50 or 100

### Extra info
I am in a fresh install with no extra nova components, no filter package added... 

![Screenshot from 2019-04-11 17-38-27](https://user-images.githubusercontent.com/18596215/55997617-c0b27180-5c80-11e9-9320-123557170065.png)

**Comment by emilianotisato** [comment] 2019-04-11 22:55
I found that in the `/nova/src/Http/Requests/ResourceIndexRequest.php`, in the `perPage` property is always returning 25... in case is of any help

**Comment by SerjoA** [comment] 2019-04-17 02:14
i have the same issue, also no additional filters added

**Comment by dkulyk** [comment] 2019-04-22 20:37
This has been fixed and will be included in the next release.

**Comment by davidhemphill** [comment] 2019-05-01 16:15
I had to revert the merged PR as it introduced an infinite loop of refreshes on detail views.

I however, was not able to reproduce the original issue with the information you provided. The amount of items in the display is updated correctly when I use the perPage filter.

**Comment by emilianotisato** [comment] 2019-05-02 01:42
@dkulyk Can you tell me in witch file/s was the problem so at least I can do a local fix?

@davidhemphill Thanks, I do not understand, I did again a totally fresh install and just seeded 100 users, and I keep not seeing all he records in the display. Maybe is browser related?? I am using chrome 73.0.3683.103

**Comment by dkulyk** [comment] 2019-05-02 01:48
@emilianotisato https://github.com/laravel/nova/pull/391/commits/eb7efdbfd17e9e8db5970ea7a0e4235531569c63
It will be fixed if you will remove `this.initializePerPageFromQueryString()` in this places.

But it's not final fix.

**Comment by sam-g-roberts** [comment] 2019-05-02 14:15
I'm getting this error as well with the same version of laravel and nova.

Custom filters and the trashed filter works but the per page filter does not change the number of pages returned

**Comment by WebZenitude** [comment] 2019-05-02 14:49
Update done from Nova 2.0.2 to Nova 2.0.3.
At first, pagination from one page to another seems to work.
But my MacBook begins again to use 100% CPU.
So the infinite loop could be still there.
As soon as I stop my local dev env, CPU charge comes back to normal.
So ?
@davidhemphill

**Comment by emilianotisato** [comment] 2019-05-02 19:01
@dkulyk, @davidhemphill  
In case is of any use...

I find that it works with nova 2.0.0, but it breaks after (including) nova 2.0.1

So I am looking at the differences, and in nova 2.0.1 you update the package.json changing the version of laravel-nova dependency from 1.0.6 to 1.0.7

When I went and see the changes in the version 1.0.7 in did there is a pull request for the perPage feature: https://github.com/laravel/nova-js/pull/8

Maybe there is the error?

**Comment by sam-g-roberts** [comment] 2019-05-03 15:14
Can confirm this is still an issue within laravel nova 2.0.3

**Comment by emilianotisato** [comment] 2019-05-03 15:41
@sam-g-roberts Yes, I did try it in 2.0.3 and is still an issue. I fix it in my local installation removing the `currentPerPage()` method as I mention before.

**Comment by turzaizsolt** [comment] 2019-05-04 08:17
@emilianotisato I tried your temporary fix and it works for the main index list but has a very strange behaviour on the lens pages. 
Dose it work for you on lens pages?

**Comment by emilianotisato** [comment] 2019-05-06 02:21
@turzaizsolt I did not use Lens in my project. For sure is some similar function in the `Lens.vue` file...

Can you describe a litle better what you mean by "strange behaviour"? It is something new or is the perPage not working???

**Comment by turzaizsolt** [comment] 2019-05-06 10:03
@emilianotisato Strange behaviour as when I open a lens page and change the per page value the pagination links (next and previous) became inactive.

**Closed** 2019-05-10 20:10 UTC
Labels: bug

**Comment by rvanbaalen** [comment] 2019-05-20 21:38
I update to 2.0.5 just now and the pagination still doesn't do anything. It's stuck on 25 records per page.

**Comment by adronitis** [comment] 2019-05-22 07:16
I have the same issue still with the latest version of Nova and running Laravel 5.8. Not sure why this issue is closed?

**Comment by loekwetzels** [comment] 2019-05-22 07:24
I've had this issue since nova 2.0.1 but it has been fixed for me in 2.0.5. Did you guys do
`php artisan nova:publish` as the [docs say](https://nova.laravel.com/docs/2.0/installation.html#updating-nova)?

**Comment by rvanbaalen** [comment] 2019-05-22 12:19
Confirmed what @loekwetzels just posted. Apparently I forgot to execute `php artisan nova:publish`.

After running the command, the pagination issue has been resolved! 🎉

**Comment by aliwesome** [comment] 2021-02-15 12:52
Can confirm this is still an issue within laravel nova 2.31.1

**Comment by crynobone** [comment] 2021-02-15 13:09
We no longer provide bug fixes to Laravel Nova 2.x, please upgrade Laravel Nova 3 as soon as possible.

**Comment by aliwesome** [comment] 2021-02-15 13:11
@crynobone I made a mistake mentioning the version. 
I meant v3.21.0

**Comment by crynobone** [comment] 2021-02-15 13:15
Then please create a new issue with complete description based on your usage and reproducing code if possible. 

We doesn't reopen 2 years old issue as many things has already changed.
