### ISSUE TITLE
Laravel\Nova\PerformsValidation - messed TValidationRule template param

### ISSUE THREAD

**Issue by vognev** [laravel/nova-issues#5459] opened 2023-04-07 10:09 UTC
- Laravel Version: not relevant
- Nova Version: 4.22.2
- PHP Version: not relevant
- Database Driver & Version: not relevant
- Operating System and Version: not relevant
- Browser type and version: not relevant
- Reproduction Repository: https://psalm.dev/r/89c875d422

### Description:

TValidationRule template param of mentioned trait seems broken and causing psalm to throw a fatal error when analyzing codebaze.

**Comment by crynobone** [comment] 2023-04-07 10:31
Duplicate of #5448

**Closed** 2023-04-07 10:31 UTC
