### ISSUE TITLE
Place attribute long and latitude options

### ISSUE THREAD

**Issue by larsjanssen6** [laravel/nova-issues#884] opened 2018-10-24 05:23 UTC
hi,

Please add `long` and `latitude` to the `Place` field. The
information comes back from `algolia` but there is no option to 
set it. 

Right now I have done this manually but it would be nice if
it could be in the core. 

Example:

```
Place::make('address')
              ->city('city')
              ->lng('lng')
              ->lat('lat'),

Text::make('address'),
Text::make('city'),
Text::make('lng'),
Text::make('lat'),
```

Thx

**Comment by davidhemphill** [comment] 2018-10-24 07:29
Duplicate of #218

**Closed by davidhemphill** 2018-10-24 07:29 UTC
