### ISSUE TITLE
Nova doesn't respect ordering by scout

### ISSUE THREAD

**Issue by approached** [laravel/nova-issues#1836] opened 2019-08-19 10:51 UTC
- Laravel Version: 5.8.29
- Nova Version: v2.0.11
- PHP Version: 7.2.19
- Database Driver and Version: 10.3.15-MariaDB
- Operating System and Version: not necessary
- Browser type and version: not necessary
- Reproduction Repository: not necessary

### Description

Nova doesn't respect ordering by scout. It used instead the last query ordering.

### Steps To Reproduce

Just search for something without the order function. 

### Fixing 
```php
<?php

    /**
     * Build an "index" query for the given resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  string  $search
     * @param  array  $filters
     * @param  array  $orderings
     * @param  string  $withTrashed
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public static function buildIndexQuery(NovaRequest $request, $query, $search = null,
                                           array $filters = [], array $orderings = [],
                                           $withTrashed = TrashedStatus::DEFAULT)
    {
        return static::applyOrderings($request, static::applyFilters(
            $request, static::initializeQuery($request, $query, $search, $withTrashed), $filters
        ), $orderings)->tap(function ($query) use ($request) {
            static::indexQuery($request, $query->with(static::$with));
        });
    }

    /**
     * Apply any applicable orderings to the query.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @param \Illuminate\Database\Eloquent\Builder   $query
     * @param array                                   $orderings
     * @return \Illuminate\Database\Eloquent\Builder
     */
    protected static function applyOrderings(NovaRequest $request, $query, array $orderings)
    {
        if (!empty($orderings)) {
            foreach ($orderings as $column => $direction) {
                $query->orderBy($column, $direction);
            }

            return $query;
        }

        // if query has search without order, so than we will search results by score
        if ($request->has('search') && !empty($request->get('search'))) {
            return $query;
        }

        // if query has order get parameter, so than we use default from resource
        if (property_exists(static::class, 'orderBy')) {
            foreach (static::$orderBy as $column => $direction) {
                $query->orderBy($column, $direction);
            }

            return $query;
        }

        // use last order
        return empty($query->orders)
            ? $query->latest($query->getModel()->getQualifiedKeyName())
            : $query;
    }

**Comment by approached** [comment] 2019-08-19 10:52
Fixing code has a implementation with default order from: #156

**Comment by davidhemphill** [comment] 2019-08-19 19:46
Duplicate of #801

**Closed by davidhemphill** 2019-08-19 19:46 UTC
