### ISSUE TITLE
Enable creation only from relation

### ISSUE THREAD

**Issue by MatanYadaev** [laravel/nova-issues#3177] opened 2021-01-18 15:05 UTC
I have 2 resources:
- `UserResource`
- `SettingResource`

`Setting` has a `HasMany` relation to `User`.

I want to allow creation of a setting only from the "user details" page. Currently it's impossible, I must allow creation of a setting from both "settings index" page and "user details" page.

## Example

This will work but creation will be allowed on both pages:
```php
class SettingPolicy
{
  public function create(User $user): bool
  {
    return true;
  }
}
````

```php
class UserPolicy
{
  public function addSetting(User $user): bool
  {
    return true;
  }
}
````

This won't work on any page. The expected behavior is to allow creation only from the "user details" page only:
```php
class SettingPolicy
{
  public function create(User $user): bool
  {
    return false;
  }
}
````

```php
class UserPolicy
{
  public function addSetting(User $user): bool
  {
    return true;
  }
}
````

**Comment by crynobone** [comment] 2021-01-18 23:49
Duplicate of #3140

**Comment by davidhemphill** [comment] 2021-01-18 23:49
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Closed by davidhemphill** 2021-01-18 23:49 UTC
Labels: next-series, request

**Comment by MatanYadaev** [comment] 2021-01-19 08:33
@crynobone Do you have any workaround suggestions? I must disallow creation directly from the resource.
