### ISSUE TITLE
undefined offset:0 present when both customizing partition labels and customizing partition colors,and use translator function to translate labels

### ISSUE THREAD

**Issue by zmj888** [laravel/nova-issues#2852] opened 2020-09-10 07:35 UTC
- Laravel Version: 7.28.1
- Nova Version: 3.9.2
- PHP Version: 7.4.5
- Operating System and Version: mac os 10.13.6

### Description:
When both customizing partition labels and customizing partition colors,and use translator function to translate labels,  "undefined offset:0" will present ,
flowing is my calculate function :

```
public function calculate(NovaRequest $request)
    {
        $array = ['unconfirmed'=>'grey','confirmed'=>'black','cancelled'=>'grey',
            'delivered'=>'blue','denied'=>'red','signed'=>'green','refunded'=>'orange','shipped'=>'green',
            'translated'=>'green'];
        return $this->count($request, Order::class, 'state')
            ->colors($array)
            ->label(function ($value) {
            return __('states.'.$value);
        });

   }
```

**Comment by crynobone** [comment] 2020-10-24 14:04
Duplicate of #1876, but there's an additional issue pending next release.

**Closed by crynobone** 2020-10-24 14:04 UTC
