### ISSUE TITLE
PHP 8.1 Deprecated

### ISSUE THREAD

**Issue by martio** [laravel/nova-issues#3720] opened 2022-01-30 11:09 UTC
- Laravel Version: 8.81.0
- Nova Version: 3.30.0
- PHP Version: 8.1

### Description:

The app reports warinings...

```
PHP Deprecated:  Return type of Laravel\Nova\Actions\Action::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/nova/src/Actions/Action.php on line 736
PHP Deprecated:  Return type of Laravel\Nova\Resource::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/nova/src/Resource.php on line 546
PHP Deprecated:  Return type of Laravel\Nova\Element::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/nova/src/Element.php on line 78
PHP Deprecated:  Return type of Laravel\Nova\Filters\Filter::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/nova/src/Filters/Filter.php on line 96
```

**Comment by bobab12** [comment] 2022-02-03 05:38
Same problem here.

**Comment by crynobone** [comment] 2022-02-04 01:58
Duplicate of #3713, Next patch release would be on the 8th of February.

**Closed by crynobone** 2022-02-04 01:58 UTC
