### ISSUE TITLE
Panel only showing when viewing content.

### ISSUE THREAD

**Issue by kentsigurdsen** [laravel/nova-issues#501] opened 2018-09-09 22:53 UTC
Hello. 

I have created panels for nicer views when viewing the contant. 

However the content will not show with panels when creating. Can this be fixed?

**Comment by fhusquinet** [comment] 2018-09-10 06:54
This is the expected behaviour according to the documentation. I would also like to have that possibility when creating/editing a resource.

**Comment by bonzai** [comment] 2018-09-10 08:28
#29

**Comment by dillingham** [comment] 2018-09-15 16:57
https://github.com/laravel/nova-issues/issues/338

**Comment by davidhemphill** [comment] 2018-09-24 19:03
Duplicate of #29

**Closed by davidhemphill** 2018-09-24 19:03 UTC
