### ISSUE TITLE
Booleans have a styling glitch on the 'peeking' tooltip.

### ISSUE THREAD

**Issue by avinashv** [laravel/nova-issues#5611] opened 2023-06-10 09:28 UTC
- Laravel Version: 10.13.5
- Nova Version: 4.25.1
- PHP Version: 8.2

### Description:
When 'peeking' at a resource, the tooltip has a styling glitch for boolean fields: the icon is under the label for it. Attached screenshot shows the issue.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create two resources, one of which is related to the other. Add a bool and add `->showWhenPeeking()` to the field, and then it should be visible.

<img width="402" alt="peeking styling bug" src="https://github.com/laravel/nova-issues/assets/11396/5ce7c119-8aaf-460d-9600-988c0250723c">

**Comment by crynobone** [comment] 2023-06-11 09:51
Duplicate of #4916

**Closed by crynobone** 2023-06-11 09:51 UTC
