### ISSUE TITLE
Custom Tool Resource make Update / Delete button disappear in detail view

### ISSUE THREAD

**Issue by noxickon** [laravel/nova-issues#5962] opened 2023-10-12 12:57 UTC
- Laravel Version: 10.24.0
- Nova Version: 4.27.13
- PHP Version: 8.1.0
- Browser type and version: Any browser on the newst version 

### Description:
If you create a Custom Resource Tool and then want to include it, the Update and Delete action buttons are no longer displayed if you put it as first field.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create a new Laravel Projekt
- Add Laravel Nova
- Add a basic ressource (i just use `php artisan nova:resource Test`)
- Add a Custom-Tool `php artisan nova:resource-tool test/noxickon`
- Say to all yes what the creation command ask
- Add the Custom-Tool to your Resource as first Field
- Action Buttons dissapear 

If you dont add the Custom-Tool as first Field, all work fine but as first Field it will disable these buttons. Is there any solution or work arround to fix this? Becuase i want the Custom Tool as first field. (see Images)

I hope the report fits so far and thanks in advance.

I will here now send the resource file, the resource tool i will not copy file by file because i have nothing change on the created folder:
Test.php (Resource)
```php
<?php

namespace App\Nova;

use App\Model\Test;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Http\Requests\NovaRequest;
use Test\Noxickon\Noxickon;

class Test extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var class-string<\App\Test>
     */
    public static $model = Test::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @return array
     */
    public function fields(NovaRequest $request)
    {
        return [
            /* let the action buttons disappear */
            Noxickon::make(),

            ID::make()->sortable(),

             /* Work fine nothing will disappear */
            Noxickon::make(),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @return array
     */
    public function cards(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @return array
     */
    public function filters(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @return array
     */
    public function lenses(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @return array
     */
    public function actions(NovaRequest $request)
    {
        return [];
    }
}
```

Without custom tool: 
![withoud_custom_tool](https://github.com/laravel/nova-issues/assets/59997219/88780486-4a6c-48b3-9512-3fd4c6d1f530)

With first field is custom tool
![with_first_field_custom_tool](https://github.com/laravel/nova-issues/assets/59997219/0cb84306-8980-4be0-8a9b-cf0a9911d8b7)

With last field is custom tool
![with_last_field_custom_tool](https://github.com/laravel/nova-issues/assets/59997219/f8cedd0c-0327-4f8d-afc8-5587a1d29ce7)

**Comment by crynobone** [comment] 2023-10-16 00:49
Duplicate of https://github.com/laravel/nova-issues/discussions/4870

**Closed by crynobone** 2023-10-16 00:49 UTC
