### ISSUE TITLE
Query keeps pagination when using filters

### ISSUE THREAD

**Issue by RazmikSaghoyan** [laravel/nova-issues#2734] opened 2020-07-10 07:00 UTC
- Laravel Version: 7
- Nova Version: 3
- PHP Version: 7.2

### **Steps to Reproduce:**

- Open a resource
- Go to the second page
- Use a filter where you have less than the per-page limit but you know you should have results
- You have an empty table
- When you use the filter, the query keeps the limit 26 offset 25 from the pagination and returns an empty table even if you have results

**Comment by jbrooksuk** [comment] 2020-07-13 14:57
@davidhemphill I think we've discussed this issue previously, but I can't remember the decision we made?

**Comment by navidnadali** [comment] 2021-01-06 07:18
Hi @jbrooksuk @davidhemphill @crynobone is there any plans for this? I think due to our use case we are coming up against it a lot where filtering shows an empty table due to offset not being reset

**Comment by crynobone** [comment] 2021-01-06 08:23
@navidnadali I marked it as discussion so that we can discussed what's the suitable "Expected Behavior" for this issue, if it's something that the team comfortable with then we could come out with a solution.

**Closed** 2021-01-26 21:19 UTC
Labels: discussion
