### ISSUE TITLE
[Laravel 5.8, Nova 2.0.3] Selection on index page get lost when go to a different page using pagination links

### ISSUE THREAD

**Issue by good-system** [laravel/nova-issues#1615] opened 2019-05-20 19:39 UTC
- Laravel Version: 5.8.17
- Nova Version: 2.0.3
- PHP Version: 7.1.29
- Operating System and Version: Ubuntu 18.04.1 
- Browser type and version: Chrome 74.0.3729.131 (Mac)
- Reproduction Repository: N/A

### Description:

When selecting items on index page by checking boxes for each one, or "Select All", or "Select All Matching" (no filter), selection appear to work.  When navigating to different pages using paginator at the bottom of the index page, the previous selection would always be lost.

**Comment by dillingham** [comment] 2019-05-21 13:45
Duplicate https://github.com/laravel/nova-issues/issues/1097

**Comment by dkulyk** [comment] 2019-05-22 12:06
Duplicate of #1097

**Closed by dkulyk** 2019-05-22 12:06 UTC
Labels: duplicate
