### ISSUE TITLE
Action Date field breaks, closes the modal while selecting date / changing month in CHROME only

### ISSUE THREAD

**Issue by shradhabanerjee** [laravel/nova-issues#1870] opened 2019-08-29 12:54 UTC
- Laravel Version: 5.8
- Nova Version: 2.0.11
- PHP Version: 7.2.20
- Operating System and Version: MacOS Mojave 10.14.6 
- Browser type and version: Chrome Version 76.0.3809.100

### Description

Refers to issue : https://github.com/laravel/nova-issues/issues/760 : which has been resolved on Safari, Firefox only it seems. The issue is still present on chrome browser. On action modal, selecting a date with Date field or changing the month, the background modal closes and the calendar remains floating on the page.

Updated Nova to latest version. Did nova:publish --force too.

### Steps To Reproduce

1. Create a Action Modal on a resource
2. Add Date field on the action modal
3. Select some random date
4. Change the month
5. The modal disappears
6. If you select date from floating calendar, produces `Uncaught TypeError: Cannot read property 'value' of undefined` in the console.

<img width="490" alt="Screenshot 2019-08-28 at 11 31 14 PM" src="https://user-images.githubusercontent.com/46675689/63941522-7c860900-ca89-11e9-8c0e-282d301f280f.png">

<img width="459" alt="Screenshot 2019-08-29 at 2 45 20 PM" src="https://user-images.githubusercontent.com/46675689/63941566-86a80780-ca89-11e9-9862-53b616f5d481.png">

**Comment by jbrooksuk** [comment] 2019-09-02 08:42
Duplicate of https://github.com/laravel/nova-issues/issues/1834

**Closed by jbrooksuk** 2019-09-02 08:42 UTC
