### ISSUE TITLE
Custom resource tool causes edit and action buttons to dissapear

### ISSUE THREAD

**Issue by gpanos** [laravel/nova-issues#5063] opened 2022-11-15 17:21 UTC
- Laravel Version: 9.*
- Nova Version: 4.18.2 
- PHP Version: 8.1
- Database Driver & Version: MySql 8

### Description:
When adding a custom resource tool in my resources as the first field in the fields method: 

```php
    public function fields(NovaRequest $request): array
    {
        return [
            FlightCalendar::make(), // custom tool

            ID::make()->sortable(),
           // more fields
       ];
    }
```
The edit and action buttons next to the page title are gone. 
The resource with the tool: 
![Screen Shot 2022-11-15 at 6 18 24 PM](https://user-images.githubusercontent.com/12728267/201984641-4a2aa0f7-a91e-4438-99ac-b8db7adbb56b.png)
The resource without the tool: 
![Screen Shot 2022-11-15 at 6 19 30 PM](https://user-images.githubusercontent.com/12728267/201984795-81d1adaf-324c-4f8e-9f85-480d22a5400b.png)

Seems that if I move the tool under the ID field then the buttons are back but my tool renders after the detail panel at the buttom of the page.
![Screen Shot 2022-11-15 at 6 20 52 PM](https://user-images.githubusercontent.com/12728267/201985036-3f7ce1d7-d07f-4a73-be4b-34cf246af570.png)

**Comment by crynobone** [comment] 2022-11-15 22:12
Duplicate of https://github.com/laravel/nova-issues/discussions/4870

**Closed by crynobone** 2022-11-15 22:12 UTC

**Comment by stephan-v** [comment] 2023-07-07 11:46
Running into this as well and it makes no sense. This should be re-opened. You mention a duplicate but this is a different issue. The duplicate you mention is about a HasMany field but when it comes to a custom tool you should be able to render it before the fields.

When I move my custom tool field to the bottom suddenly the edit button appears again. 

This is simply a bug.
