### ISSUE TITLE
Nova Themes not applied to Login

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1554] opened 2019-04-29 13:01 UTC
- Laravel Version: 5.8
- Nova Version: 2.0
- PHP Version: 7.2

### Description:
Assets created with php artisan nova:theme are not loaded on the login page, therefore the custom theme is not applied to the login. In my opinion the theme should also be applied to the login page.

### Steps To Reproduce:
Create a theme and see Nova's default theme on login

### Not a request
This was marked as request and closed https://github.com/laravel/nova-issues/issues/823
Was reported 7 months ago
But it's a bug not a feature opinion difference. Themes need to apply to login as logos do.

**Comment by m-lotze** [comment] 2019-04-30 09:40
My workaround for now is this:

- create a `theme.css` or `theme.scss` in `resources/css` 
- use laravel-mix to publish it `public/css`
- copy `vendor/laravel/nova/resources/views/layout.blade.php` and `vendor/laravel/nova/resources/views/auth/layout.blade.php` to `resources/views/vendor/nova`
- add `<link rel="stylesheet" href="{{ mix('css/theme.css') }}">` to both views after the `<link rel="stylesheet" href="{{ mix('app.css', 'vendor/nova') }}">`

The composer package approach is good for tools and fields. For just a css theme it is a bit overkill in my opinion. I would prefer a config option with the path to the minified css.

**Comment by dillingham** [comment] 2019-04-30 10:24
Workaround doesn’t work for me

I have multiple projects using one theme. 
I have one project with multiple instances of nova. 
Theme & composer makes it usable and simple. 
Doing what you said doesn’t. 
This needs to be fixed not worked around.

**Comment by m-lotze** [comment] 2019-04-30 14:01
Sure this needs a fix. But this would require quite a bit of refactoring of nova, especially the handling of styles and scripts. dont see that happening in the near future.

**Comment by dillingham** [comment] 2019-04-30 14:06
I didnt ask you @m-lotze :)

**Comment by dillingham** [comment] 2019-04-30 14:08
It just needs to include a css file in the login blade template.. not rocket science :)

**Comment by m-lotze** [comment] 2019-04-30 14:37
its not that easy. e.g. `nova-api/styles/*` routes are currently auth-protected. also a theme is basically the same as a custom tool or a custom field. and these are not even booted on `/login`.

**Comment by dillingham** [comment] 2019-04-30 14:49
its pretty easy man....... 

- Add a themeStyles() Nova method
- Appends css files Nova::$themeCss
- Loop them on login.blade.php
- Loop them on layout.blade.php

Doesn't change any authorized files
Doesn't break any existing themes

Upgrading would be simple: 
Change Nova::styles to Nova::themeStyles

**Comment by m-lotze** [comment] 2019-04-30 15:02
nope ... add a `dd('test');` in your ThemeServiceProvider.php - you will see that `boot()` ist not even called on `/login`

**Comment by dillingham** [comment] 2019-04-30 15:07
@m-lotze ok well whatever, needs to be fixed 👍

**Comment by davidhemphill** [comment] 2019-05-01 20:15
Duplicate of #823

**Closed by davidhemphill** 2019-05-01 20:15 UTC
