### ISSUE TITLE
Double Header DropDownMenu It is a worsening of the user experience when Actions is Empty

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#6091] opened 2023-12-08 16:09 UTC
- Laravel Version: 9.52.16
- Nova Version: 4.32.9
- PHP Version: 8.1.26

### Description:

Has any configuration variable or function been added to remove this new addition, which in my case significantly worsens the user experience? All of my users are complaining about this.

### Detailed steps to reproduce the issue on a fresh Nova installation:
![image](https://github.com/laravel/nova-issues/assets/5731295/ec83a911-18c1-489d-8f76-8b0160bc0c9f)

**Comment by mstaack** [comment] 2023-12-12 12:07
same as https://github.com/laravel/nova-issues/issues/6101

**Comment by davidhemphill** [comment] 2023-12-12 19:05
Duplicate of #6101

**Closed by davidhemphill** 2023-12-12 19:05 UTC
