### ISSUE TITLE
Custom attribute not sortable

### ISSUE THREAD

**Issue by jwjcmw** [laravel/nova-issues#85] opened 2018-08-23 22:09 UTC
It looks like if you have custom attributes on your model, you can include them in your index for a resource and set them to sortable, but it throws an error if you try sort on them.  I realize that this is because sorting is done at the eloquent level, but it would be very useful to have the ability to sort custom attributes (or the computed fields, which do seem to recognize that they aren't sortable as stated in the docs).

**Comment by andgith** [comment] 2018-08-24 16:25
It would be nice if you could sort by relationship count which can only be done using computed fields.

**Comment by bonzai** [comment] 2018-08-24 16:36
@andgith: It's possible. Just overwrite the `indexQuery` method of your resource. For example:

```php
    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->withCount('users');
    }
```

And then in your `fields` method:

```php
	Text::make('Users Count')->sortable(),
```

**Comment by davidhemphill** [comment] 2018-09-12 20:11
This would be really difficult to ever get working without breaking pagination. Gonna close this for now, but will revisit if we can think of a better way to do that.

**Closed by davidhemphill** 2018-09-12 20:11 UTC

**Comment by DavidNgugi** [comment] 2018-10-18 16:00
Hi, just use a callback in a Text field and a blade template in your resources file like this `is confirmed` column

``` php
Text::make('Is Confirmed', 'confirmed_at', function () {

                $bg_color = 'bg-primary';
                $bg_color = ( is_null($this->confirmed_at) ) ? 'bg-danger' : 'bg-success';

                return view('nova.partials.groups-is_confirmed', [
                    'bg_color' => $bg_color
                ])->render();
            })
                ->asHtml()
                ->sortable()
                ->exceptOnForms(),
```

Here's the `resources/views/nova/partials/groups-is_confirmed.blade.php` file I'm referring to in the code:

``` blade
<span class="{{ $bg_color }} inline-block rounded-full w-2 h-2"></span>
```

**Comment by pelmered** [comment] 2019-08-19 14:23
Would be great if you could pass the column name that you want to use for sorting. 

For example:
```
            Text::make('Where', function () {
                return $this->postal_code.', '.$this->city;
            })->sortable($this->postal_code),
```
This would sort on the `postal_code` column.

**Comment by Klaviatur** [comment] 2019-10-30 11:12
> @andgith: It's possible. Just overwrite the `indexQuery` method of your resource. For example:
> 
> ```
> public static function indexQuery(NovaRequest $request, $query)
> {
>     return $query->withCount('users');
> }
> ```
> 
> And then in your `fields` method:
> 
> ```
> Number::make('Users Count')->sortable()->onlyOnIndex(),
> ```

Just in case someone struggles with translation like I just did. The count is referenced by an underscore:

```
Number::make(__('Users Count'), 'users_count')->sortable()->onlyOnIndex(),
```

**Comment by MannikJ** [comment] 2020-01-24 10:57
> @andgith: It's possible. Just overwrite the `indexQuery` method of your resource. For example:
> 
> ```
> public static function indexQuery(NovaRequest $request, $query)
> {
>     return $query->withCount('users');
> }
> ```
> 
> And then in your `fields` method:
> 
> ```
> Number::make('Users Count')->sortable()->onlyOnIndex(),
> ```

This does not work, because nova prefixes the column with the resources table name. How can I avoid that?

**Comment by philipbaginski** [comment] 2020-02-06 11:18
> Would be great if you could pass the column name that you want to use for sorting.
> 
> For example:
> 
> ```
>             Text::make('Where', function () {
>                 return $this->postal_code.', '.$this->city;
>             })->sortable('postal_code'),
> ```
> 
> This would sort on the `postal_code` column.

It does not work for me. I need to sort computed field.

**Comment by CiprianOpreaPrestimedia** [comment] 2020-02-11 10:23
You can try this (It works for Bagde field)

`
Text::make('Where', 'postal_code', function () {
         return $this->postal_code.', '.$this->city;
})->sortable(),

`

**Comment by philipbaginski** [comment] 2020-02-11 10:57
Thanks a lot! It works when you add "postal_code" after "Where". Without "postal_code" (only "Where") it does not work - as they wrote in Nova docs:

Text::make('Name', function () {
    return $this->first_name.' '.$this->last_name;
}),

"... Since they are not associated with a database column, computed fields may not be sortable... "

They have to change docs :-)

**Comment by CiprianOpreaPrestimedia** [comment] 2020-02-11 12:22
You're welcome!

**Comment by wittchen** [comment] 2020-08-03 14:31
> You can try this (It works for Bagde field)
> 
> ```
> Text::make('Where', 'postal_code', function () {
>          return $this->postal_code.', '.$this->city;
> })->sortable(),
> ```

this works perfectly, thanks!

in my case:
Text::make('Name', 'name', function () {
    return "<a href='".$this->uriKey().'/'.$this->id."'>{$this->name}</a>";
})->asHtml()->sortable(),
