### ISSUE TITLE
Customizing Dashboards

### ISSUE THREAD

**Issue by codegor** [laravel/nova-issues#2971] opened 2020-10-18 20:06 UTC
- Laravel Version: 8.1
- Nova Version: 3.12.1
- PHP Version: 7.4.2
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://nova.laravel.com/docs/3.0/customization/dashboards.html

### Description:
- PreviousNova Version: 3.8.3

Customizing Dashboards:
public static function label()
public static function uriKey()

can you revert to previus non static variant?

public function label()
public function uriKey()

because after this update I cannot generate dynamic url Key and label, but I need to do this!
thank you

**Comment by crynobone** [comment] 2020-10-19 00:26
```
public static function label()
public static function uriKey()
```

This method already existed since `v2.1.0` and `v3.0.0`, see https://github.com/laravel/nova/commit/c4139728fe510c65fd8a99f654adf067e6dacf4e

---

Reproducing repository means the most basic code that others can view and debug the issue, you might understand what you want to say but others will find it hard to translate and will have to make assumptions. 

I'm closing this since available options should already be enough for customisation and what you asking is a potential breaking change. Feel free to ask further in one of many Laravel discussion chat and forum.

**Closed by crynobone** 2020-10-19 00:26 UTC

**Comment by codegor** [comment] 2020-10-19 15:30
Yes this method was but it was not STATIC! in version 3.8.3 it was non static, which made it possible to dynamically assign url and label.

I have a single class, which create dashboard for every admin in my app, and when I create dashboard in NovaServiceProvider I only assign email and id (from email and id I generate url and label for dashboard) of admin and I have receive an instance of dashboard for each admin (admins is variable, I dont know who will be admin in future)

After I have updated to v3.12.1 that methods became static and today I cannot dynamic generate dashboards for each admin.

Can You help with this? Can you return to non static methods?

Code below was worked before update, but after not, so it is very sad...

```
use App\User;
use Illuminate\Support\Str;
use Laravel\Nova\{AuthorizedToSee, Element, Metable, Makeable, ProxiesCanSeeToGate};
use App\Nova\Metrics;

class AdminDashboard extends Element {
        use AuthorizedToSee, Metable, Makeable, ProxiesCanSeeToGate;
	
	public $name = null;
	public $admin= null;
	public $email = null;
	
	public function setAdmin($Admin) {
		$this->admin= $Admin;
		return $this;
	}
	
	public function setName($name) {
		$this->name = $name;
		return $this;
	}
	
	public function setEmail($email) {
		$this->email = $email;
		return $this;
	}
	
	/**
	 * Get the cards for the dashboard.
	 *
	 * @return array
	 */
	public function cards() {
		return [
                   (new Metrics\....),
                   ......
		];
	}
	
	/**
	 * Get the displayable name of the dashboard.
	 *
	 * @return string
	 */
	public function label() {
		return $this->$name;
	}
	
	/**
	 * Get the URI key for the dashboard.
	 *
	 * @return string
	 */
	publicfunction uriKey() {
		return Str::slug($this->label(), '-', null).'-'.str_replace('@', '_', strtolower($this->email));
	}

}



use Laravel\Nova\NovaApplicationServiceProvider;

class NovaServiceProvider extends NovaApplicationServiceProvider {

    .........

    /**
	 * Get the extra dashboards that should be displayed on the Nova dashboard.
	 *
	 * @return array
	 */
	protected function dashboards() {
		$admins = User::admins()->get();
		$res = [];
		foreach ($admins as $admin) {
			$res[] = (new AdminDashboard)->setEmail($admin->email)->setAdmin($admin->uuid)->setName($admin->firstname);
		}
		
		return $res;
	}
}
```

**Comment by codegor** [comment] 2020-10-19 15:31
Can you reopen this issue?

**Comment by crynobone** [comment] 2020-10-20 08:36
> Yes this method was but it was not STATIC! in version 3.8.3 it was non static, which made it possible to dynamically assign url and label.

https://github.com/laravel/nova/blob/v3.8.3/src/Dashboard.php
https://github.com/laravel/nova/blob/v3.8.2/src/Dashboard.php

Both class clearly showing it as public static, there no reason to reopen this.

**Comment by davidhemphill** [comment] 2020-10-26 15:28
The `uriKey` and `label` methods have both been `static` since they were created. We would not have introduced a breaking change in the middle of a major release.

**Comment by codegor** [comment] 2020-10-26 18:11
Ok. But true is that - after update a have a error. 
Could you add ability to generate dashboards like in that code?

https://github.com/laravel/nova-issues/issues/2978

**Comment by alberto-bottarini** [comment] 2021-01-05 17:09
Take a look at: https://github.com/laravel/nova-issues/issues/3151
