### ISSUE TITLE
Date filter popup close randomly

### ISSUE THREAD

**Issue by Perh0rd** [laravel/nova-issues#3037] opened 2020-11-11 00:08 UTC
- Laravel Version: 7.29.3
- Nova Version: 3.15.0
- PHP Version: 7.4
- Database Driver & Version: Mysql 8
- Operating System and Version: Ubuntu 18
- Browser type and version: Chrome 86.0.4240.183
- Reproduction Repository: Private

### Description:

Clicking on date filter make the popup filter to close popup, which make difficult to filter by dates, this is random, but happens often. It happens on some ressources, some not and then to all, and then some others, very randomly.

### Detailed steps to reproduce the issue on a fresh Nova installation:

https://bit.ly/32xmAay

**Comment by crynobone** [comment] 2020-11-11 00:16
> It happens on some resources

Is there a pattern where we can reproduce the issue. E.g: Date filter combine with Select Filter, or only occurred when resource has more than one Date filter etc. 

And what's available in resources that doesn't have the issue?

**Comment by Perh0rd** [comment] 2020-11-11 14:43
@crynobone  Hi , and thank you for your answer.

Here what I do for you : 

I setup a fresh brand new nova setup with last version 3.15.0 and Laravel 7, it's accessible here, with login _nova@xpedigo.com_ and pwd _nova_

Here is a video also : https://ttprivatenew.s3.amazonaws.com/pulse/paul-xpedigo/attachments/15214527/TinyTake11-11-2020-09-35-36.mp4 of the bug reproduced in this environnement.

As you can see it's very random, and we have the same in our app, but it happens more often with ressources with a lot of relationships (joins) so far I notice.

Thank you for your help.

**Comment by Perh0rd** [comment] 2020-11-11 14:52
Here another sample in the provided app : https://ttprivatenew.s3.amazonaws.com/pulse/paul-xpedigo/attachments/15214644/TinyTake11-11-2020-09-48-47.mp4

And here a sample in our current app : https://ttprivatenew.s3.amazonaws.com/pulse/paul-xpedigo/attachments/15214686/TinyTake11-11-2020-09-52-02.mp4

**Comment by Perh0rd** [comment] 2020-11-11 14:53
I updated my comments above link to demo app was missing.

**Comment by crynobone** [comment] 2020-11-12 02:46
Thank you for providing the sample app. I tried it for around 20 minutes trying to replicate the issue on Chrome, Safari and Firefox but wasn't able to. 

> but it happens more often with resources with a lot of relationships (joins) so far I notice.

At this point this seem to be an issue with state on JavaScript so having relationship should have no affect.

**Comment by Perh0rd** [comment] 2020-11-12 04:37
Why it happens more on some ressources than others ? The thing I know for sure , it's our team really struggle to filter by date properly on some ressources. What kind of approach can we have to fix this? In the demo I have provided it shows up rarely but it shows up. Why ? I have no idea.

**Comment by Perh0rd** [comment] 2020-11-12 04:37
Thx for your help

**Comment by Perh0rd** [comment] 2020-11-12 04:42
I have noticed it closes sometimes when the top loading bluebar when you use boolean filter or page has just finished loaded or is about to finish and I filter by dates. But maybe its coincidence.

**Comment by Perh0rd** [comment] 2020-11-12 04:45
And other fact , the problem never occurs on mobile.

**Comment by crynobone** [comment] 2020-11-12 04:48
Does the problem on happens on Chrome or do you have seen it happen on other browser as well (other than mobile).

**Comment by Perh0rd** [comment] 2020-11-12 04:57
So far everybody uses chrome, I myself have tested only on Chrome

**Comment by Perh0rd** [comment] 2020-11-12 05:17
Tested on chrome and firefox, problem not here this time. Very strange... The only diff is Im not on remote desktop but locally... I suspect a problem with rdp , messing around with js event.

**Comment by Perh0rd** [comment] 2020-11-12 13:25
@crynobone  I finally reproduced it on my laptop too not remotely, and I found why it happens. Nothing to do with rdp.

So here is the problem shown on  detail on the demo app I have provided : https://ttprivatenew.s3.amazonaws.com/pulse/paul-xpedigo/attachments/15224423/TinyTake12-11-2020-08-22-59.mp4

As you can see, it's because a e.stopPropagation/e.preventDefault is missing somehow and actually, while the user is clicking the cursor in the input but just above the month selection of the datepicker, it click on the "Month" which leads to the close of the popup.

**Comment by Perh0rd** [comment] 2020-11-12 13:30
Here another demo on our own app this time , as you can see if I click on the top border :https://ttprivatenew.s3.amazonaws.com/pulse/paul-xpedigo/attachments/15224537/TinyTake12-11-2020-08-30-07.mp4, it works, but if I click near the bottom border it closes.... Thx for your help and  hope you can fix this soon :).

**Comment by crynobone** [comment] 2020-11-12 14:03
I still can't replicate with click, if I do long click and drag then yes that would happen as you described.

We don't have any custom event listener for `flatpckr` on `onOpen` event, only `onChange` and `onClose`. What I can only do right now is send a PR to bump `flatpckr` to latest version and see if that's help.

**Comment by Perh0rd** [comment] 2020-11-12 14:13
I have tested on 3 different machines with last chrome version using https://laravel.xpedigo.devand  the bug is here with a simple click. Do you think it's possible to find a quick fix for this in our side? Because as I said the team using the app struggle with dates filter and we have a lot of complains. It impacts numbers of users internally here, and I here them complains every day. I have no idea how to prevent this bug as it's internal to nova.  

Here I just tested in in a brand new laptop with fresh installed on chrome : https://ttprivatenew.s3.amazonaws.com/pulse/paul-xpedigo/attachments/15224893/TinyTake12-11-2020-09-10-47.mp4 the bug is here, click or drag and drop, the fact is, that it should not close the "popup" while user select a month.

Is that possible to disable month selection and only use arrow somehow as quick workaround?

@davidhemphill This is what I talked in my previous email.

**Comment by Perh0rd** [comment] 2020-11-12 14:24
Basically the problem is this, behavior should be avoided, why closing the filter popup when click on month or year selection.  :https://ttprivatenew.s3.amazonaws.com/pulse/paul-xpedigo/attachments/15224991/TinyTake12-11-2020-09-24-09.mp4 by avoiding that, this bug will indeed disappear.

**Comment by Perh0rd** [comment] 2020-11-12 14:38
Maybe let us the option to set as "static" as it was before.

**Comment by Perh0rd** [comment] 2020-11-12 14:54
Ugly workaround but, adding a margin bottom helps : https://ttprivatenew.s3.amazonaws.com/pulse/paul-xpedigo/attachments/15225215/TinyTake12-11-2020-09-53-28.mp4, I hope in a future we can have the choice of what we had before to have static month or not, it will avoid this error, or even better, do not close the popup filter while selecting a Month or Year, as mentioned above.

**Comment by crynobone** [comment] 2020-11-18 07:06
Seems to be related to flatpickr/flatpickr#2286 and fixed via flatpickr/flatpickr#2304 

We'll update the dependencies when the new release is available.

**Closed** 2020-12-21 03:05 UTC
Labels: bug
