### ISSUE TITLE
MorphTo field completely disappears on index / detail, when policy is denying access

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2023] opened 2019-10-09 08:33 UTC
Laravel Version: 5.8.24
Nova Version: 2.0.6
PHP Version: 7.2.10
Database Driver and Version: MySQL 5.7.23
Operating System and Version: Windows 10 (64 bits)
Browser type and version: Chrome 76 (64 bits)

Description
I've got a morphTo field in a User resource that display which department it manages. In some cases the user does not have access (policy) to view this organizatiol layer (which i want). When this happens, so when a policy denies access, morphTo displays nothing. The table row is missing a table cell.

![nova-morphto-bug](https://user-images.githubusercontent.com/5418196/66464893-25a82200-ea80-11e9-85b0-32601e27e14e.jpg)

Expected result
I just want to show an empty table cell.

**Comment by jbrooksuk** [comment] 2019-10-09 09:47
It looks like you're running an older version of Nova, we're now on [v2.4.0](https://nova.laravel.com/releases). Can you update and try again, please.

**Comment by Lastwisher** [comment] 2019-10-09 12:36
i have issue when i try to add morpTo field its trying to reach models morpTo function which is not exists.
MorphTo::make('Source')->types([
               Payment::class
           ])
Normally its have to reach source() releation. Any ideas ?

**Comment by preliot** [comment] 2019-10-09 13:45
Just updated to 2.4.0, still an issue @jbrooksuk

**Comment by jbrooksuk** [comment] 2019-10-09 15:02
@preliot can you provide a copy of your policy, please? I've confirmed the issue when there is a `viewAny` method in a policy.

**Comment by preliot** [comment] 2019-10-09 15:16
Do you need a specific piece or the whole thing? 

Confirmed your findings. Removing the viewAny method reveals the related resource.

**Comment by jbrooksuk** [comment] 2019-10-09 15:17
> Confirmed your findings. Removing the viewAny method reveals the related resource.

That's enough for me, thanks.

I'll have a think about how we can handle this better.

**Comment by jbrooksuk** [comment] 2019-10-09 15:18
Actually, saying that... what's your `viewAny` method doing exactly? Why would it allow some rows to show?

**Comment by preliot** [comment] 2019-10-09 15:26
What you are seeing in my screenshot are actually two policies at work:

row 1) Policy for department (access granted)
row 2) Policy for client (access denied)

Hope this clarifies it for you.

**Comment by jbrooksuk** [comment] 2019-10-09 15:27
Of course 🤦‍♂ it's a morphs field, sorry. Interesting. Leave it with us!

**Comment by preliot** [comment] 2019-10-09 15:29
Well it is the end of a work day... here in Europe at least!

**Comment by preliot** [comment] 2020-05-21 06:03
Laravel Version: 7.11.0
Nova Version: 3.6.0
PHP Version: 7.2.19
Database Driver & Version: mysqlm 5.7.24
Operating System and Version: windows 10
Browser type and version: chrome 81 (64 bits)

I've recently updated everything and the behaviour has changed. Now the resource is showing (although a policy forbids it). When a user clicks on the specific client, (s)he gets a 404.

Would be nice if a policy denies access, an empty cell is presented.

**Comment by skoyah** [comment] 2020-07-22 10:35
This is a real pain. We also use the MorphTo and It is counter intuitive from the user perspective to have a link just to find out that you cant actually visit the page. 

Would be great if we could have this ASAP working on Nova. Hopefully it will be available for 2.X

**Comment by crynobone** [comment] 2020-11-19 11:33
Closing this as duplicate of #2677 

As for Laravel Nova 2, we no longer releasing bug fixes so please upgrade to v3.

**Closed by crynobone** 2020-11-19 11:33 UTC
Labels: bug
