### ISSUE TITLE
Another user has updated this resource since this page was loaded. Please refresh the page and try again.？

### ISSUE THREAD

**Issue by imlida** [laravel/nova-issues#408] opened 2018-09-03 08:56 UTC
Another user has updated this resource since this page was loaded. Please refresh the page and try again.

why?

**Comment by thannaske** [comment] 2018-09-03 09:55
Because you would overwrite the changes the other user made without knowing what he did. Usually you don't want that.

**Comment by davidhemphill** [comment] 2018-09-04 03:07
@imlida This repo is for bug reports and feature requests. Do you have an issue/bug related to that feature?

**Comment by krns** [comment] 2018-09-17 10:54
We also had this problem (only in our production environment). The `updated_at` timestamp is always one second ahead of the `_retrieved_at` timestamp.

Looks like a duplicate of #236

**Comment by davidhemphill** [comment] 2018-09-18 17:15
Closing since OP hasn't replied back.

**Comment by taylorotwell** [comment] 2018-09-19 15:00
Since we can't recreate this, it is probably a system / server clock issue. Do you have a way to reliably recreate it on our end?

**Closed by taylorotwell** 2018-09-19 15:00 UTC

**Comment by pehbehbeh** [comment] 2018-09-20 16:28
We came up with a possible solution here: https://github.com/laravel/nova-issues/issues/601#issuecomment-423247397

**Comment by pr-baernholdt** [comment] 2018-10-15 09:34
I have the same issue on a shared hosting for one of our small projects, and this is not a possible solution for us.

As Nova is targeting small to medium projects only, there might be some other people who don't want to pay much for servers and have the same problem like us.

Does that mean even if either server or the client's clock is a few seconds incorrect they cannot update any resource?

**Comment by reppair** [comment] 2019-10-08 23:48
same problem..

**Comment by pleone** [comment] 2019-11-21 08:39
same issue on a shared hosting.

**Comment by rikless** [comment] 2019-11-21 09:08
same problem

**Comment by preliot** [comment] 2019-11-21 13:50
I've had the same issue sometimes and did not understood the cause...until now. In my test environment i use test seeders. In some cases i also change changed_at / updated_at with this:

```php
$createdAt = $faker->dateTimeThisYear();
$updatedInterval = new DateInterval('P' . rand(1,99) . 'D');
$updatedAt = $createdAt->add($updatedInterval);
```
This will sometimes create a date in the future and therefore trigger the 'Another user has updated this resource since....' message. 

(Note: not the same cause as posted issue, but might be usefull for other users)

**Comment by k2idev** [comment] 2020-02-04 13:50
I can confirm what preliot wrote. 
Had the same issue ("another user has...") and it was solved by not setting the created_at and updated_at values in the seeder.

**Comment by nlappe** [comment] 2020-07-01 21:36
i had a similar problem when tinkering some data together (in artisan tinker) and it was a strange combination of Timezone hazzle between artisan, php and nova (and probably the servers Timezone). 

Long story short - it wrote my german client time into the DB (for whatever reason) by using Model::create() in tinker on the server via SSH and the server runs at UTC. So basically, my Model was updated 2hrs in the future. 

I guess in my specific case it was some strange Timezone sideffects with no real error case besides test data hacking. So if anyone has the same Situation - just call it a day and just try it again the next day :)

**Comment by BeiAduo** [comment] 2023-01-15 01:22
I just change  config/app.php ,   'timezone' => 'UTC',  to     'timezone' => 'America/Los_Angeles', 

How to fix it ?

**Comment by eComEvo** [comment] 2024-04-09 20:38
This is also happening with my setup and I found a solution to it.

In my case, when a user logs into the Nova dashboard, their user cannot be updated again due to this error until some time has passed. No matter how many times I reload the page, it doesn't resolve it so I'm not sure what the time requirement is.

This only seems to be an issue when MySQL's timezone isn't aligned with the app's timezone. If you change your app timezone to anything other than UTC, you may get this error.

I took these steps to fix this issue...

Created a helper function to convert PHP's named timezones into a MySQL friendly offset timezone and dropped that into `helpers.php` which I registered in `composer.json`:
```
if (!function_exists('convert_named_timezone')) {
    function convert_named_timezone(string $timezone): string
    {
        $now = Carbon::now($timezone);

        // Get the offset in seconds and convert it to hours.
        $offer_in_seconds = $now->offset;
        $offer_in_hours = $offer_in_seconds / 3600;

        // Format the offset for MySQL (+HH:MM or -HH:MM).
        return sprintf(
            "%+03d:%02d",
            $offer_in_hours,
            abs(($offer_in_seconds % 3600) / 60)
        );
    }
}
```

Then add this to the `boot` method of `AppServiceProvider` to ensure the timezone is set on first boot of the application lifecycle:
```
public function boot(): void
{
    $this->app->booted(function () {
        \DB::statement("SET time_zone=?", [convert_named_timezone(config('app.timezone'))]);
    });
}
```

Then create new event listener `SetDatabaseTimezone`:
```
namespace App\Listeners;

use Illuminate\Database\Events\ConnectionEvent;

class SetDatabaseTimezone
{
    /**
     * Handle the event.
     *
     * @param  \Illuminate\Database\Events\ConnectionEvent  $event
     * @return void
     */
    public function handle(ConnectionEvent $event): void
    {
        if ($event->connection->getDriverName() === 'mysql') {
            $event->connection->statement("SET time_zone=?", [convert_named_timezone(config('app.timezone'))]);
        }
    }
}
```

Then listen for new connection events in the `EventServiceProvider` to ensure any new mysql connections have the correct timezone set automatically:
```
protected $listen = [
    \Illuminate\Database\Events\ConnectionEvent::class => [
        \App\Listeners\SetDatabaseTimezone::class,
    ],
];
```

Note that the timezone offset conversion is only needed if you are using named timezones like `America/New_York` which not all MySQL instances support.

**Comment by eComEvo** [comment] 2024-04-09 20:39
This is also happening with my setup and I found a solution to it.

In my case, when a user logs into the Nova dashboard, their user cannot be updated again due to this error until some time has passed because the date is in the future.

This only seems to be an issue when MySQL's timezone isn't aligned with the app's timezone. If you change your app timezone to anything other than UTC, you may get this error.

I took these steps to fix this issue...

Created a helper function to convert PHP's named timezones into a MySQL friendly offset timezone and dropped that into `helpers.php` which I registered in `composer.json`:
```
if (!function_exists('convert_named_timezone')) {
    function convert_named_timezone(string $timezone): string
    {
        $now = Carbon::now($timezone);

        // Get the offset in seconds and convert it to hours.
        $offer_in_seconds = $now->offset;
        $offer_in_hours = $offer_in_seconds / 3600;

        // Format the offset for MySQL (+HH:MM or -HH:MM).
        return sprintf(
            "%+03d:%02d",
            $offer_in_hours,
            abs(($offer_in_seconds % 3600) / 60)
        );
    }
}
```

Then add this to the `boot` method of `AppServiceProvider` to ensure the timezone is set on first boot of the application lifecycle:
```
public function boot(): void
{
    $this->app->booted(function () {
        \DB::statement("SET time_zone=?", [convert_named_timezone(config('app.timezone'))]);
    });
}
```

Then create new event listener `SetDatabaseTimezone`:
```
namespace App\Listeners;

use Illuminate\Database\Events\ConnectionEvent;

class SetDatabaseTimezone
{
    /**
     * Handle the event.
     *
     * @param  \Illuminate\Database\Events\ConnectionEvent  $event
     * @return void
     */
    public function handle(ConnectionEvent $event): void
    {
        if ($event->connection->getDriverName() === 'mysql') {
            $event->connection->statement("SET time_zone=?", [convert_named_timezone(config('app.timezone'))]);
        }
    }
}
```

Then listen for new connection events in the `EventServiceProvider` to ensure any new mysql connections have the correct timezone set automatically:
```
protected $listen = [
    \Illuminate\Database\Events\ConnectionEvent::class => [
        \App\Listeners\SetDatabaseTimezone::class,
    ],
];
```

Note that the timezone offset conversion is only needed if you are using named timezones like `America/New_York` which not all MySQL instances support.

**Comment by bastones** [comment] 2025-05-01 17:44
I'm sick and tired of the BS with this company. This is a **BUG** with Laravel Nova, but thanks to the culture of arrogance and narcissism that Taylor has embedded within Laravel LLC, it is always the customer's fault. The server clock is in sync, and yet Laravel Nova incessantly throws "Another user has updated this resource" errors. Still my fault though, right? Couldn't have anything to do with Nova... your customers are just stupid, right?

Never mind. It's not like we're paying for this software.

Thanks for your continued arrogance. 👍

**Comment by pleone** [comment] 2025-05-03 01:24
This post of @bastones it's not spam. It's actually the reason why I left Nova many years ago.
Arrogance and toxic behavior. 

8 Years and nothing changed. LoL.

> I'm sick and tired of the BS with this company. This is a **BUG** with Laravel Nova, but thanks to the culture of arrogance and narcissism that Taylor has embedded within Laravel LLC, it is always the customer's fault. The server clock is in sync, and yet Laravel Nova incessantly throws "Another user has updated this resource" errors. Still my fault though, right? Couldn't have anything to do with Nova... your customers are just stupid, right?
> 
> Never mind. It's not like we're paying for this software.
> 
> Thanks for your continued arrogance. 👍

**Comment by crynobone** [comment] 2025-05-03 02:13
Sorry but we are more interested to serve our customers that find Nova useful and we do 100% agree Laravel Nova is not for everyone. 

There's no fool proof solution for this issue at the moment and we will solve it if there's one.

**Comment by bastones** [comment] 2025-07-25 03:18
> Sorry but we are more interested to serve our customers that find Nova useful and we do 100% agree Laravel Nova is not for everyone.
> 
> There's no fool proof solution for this issue at the moment and we will solve it if there's one.

Find your god damn manners and stop lying to us.

You are only interested in insulting your customers with your company's obnoxious superiority complex. When you say **"we are more interested to serve our customers that find Nova useful"**, what you are really telling us is that you are a narcissist.

Everything I said was entirely accurate, and your response was a mirror example. You won't understand what the problem is. Narcissists never do.

**Comment by bastones** [comment] 2025-07-25 03:26
@crynobone

My suggestion to you is to refrain from responding any further, unless you are keen to cause more reputational damage. Not responding would have been less harmful, because all you've done is provided yet another example of Laravel, LLC being toxic.
