### ISSUE TITLE
DateTime with format() and pickerFormat() combined

### ISSUE THREAD

**Issue by Ilyes512** [laravel/nova-issues#2037] opened 2019-10-12 21:33 UTC
I already tried getting an answer on [Larachat Slack](https://larachat.co), but since the channel is completely dead... BTW, I (we) have a PRO Nova license, it says I can mail, but I hate mail. I prefer using any other form of communication like (Github) issues or chat.

So back to the problem I have. I have already wasted a complete day breaking my head on why the below doesn't work!

I got the fallowing date time field:
```
DateTime
    ::make('foobar')
    ->format('DD-MM-YYYY HH:mm:ss') // https://momentjs.com/docs/#/parsing/string-format/
    ->pickerFormat('d-m-Y H:i:S') // https://flatpickr.js.org/formatting/
    ->rules('required', 'date_format:Y-m-d H:i:s')
    ->firstDayOfWeek(1)
```

Momentjs does not recognise the date. I get a warning after changing the date in console:

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
```

It seems like momentjs is not getting the format? But I am clearly setting it in the nova resource and so it should get passed to vue, and so on? right?

Removing `->pickerFormat()` allows me to save the date, but without displaying it the way I want in the picker.

I might be doing it completely wrong, so if someone could produce a working example of a DateTime filed with format and pickerFormat then that would be great as well.

**Comment by Ilyes512** [comment] 2019-10-14 16:14
So I found the problem and I know how to fix it. It requires a change in this repo first https://github.com/laravel/nova-js for which I will create a pull request shortly. The other change is needed in the DateTimeField (form) vue component. How can I make a pull request for that? Should I just explain the changes I made as it’s pretty minimal (passing a second argument to a function call).

**Comment by Ilyes512** [comment] 2019-10-28 15:01
Ok @jbrooksuk I made the git patch... how can I share that with you? I added it to a secret gist... should I just add the link here?

**Comment by jbrooksuk** [comment] 2019-10-30 09:25
Sure! Or, you can submit it to the [laravel/nova](https://github.com/laravel/nova) repo.

**Comment by Ilyes512** [comment] 2019-10-30 09:36
Get a 404 on that... Someone else on my team used his GitHub account to get access. Are you saying he should be able to see the repo?

**Comment by jbrooksuk** [comment] 2019-10-30 09:37
That's correct! You can also transfer the repo access if you need to (you can then transfer it back).

**Comment by JasonStainton** [comment] 2019-11-22 10:12
Just ran into this issue too and think I've come to the same realisation as @Ilyes512 with the need to set flatpickr's `altFormat` for visual display format. I should have checked here first before digging into it 🙄 
It's only a visual change so I can live without it but it'd be a nice to have 😉

**Comment by Ilyes512** [comment] 2019-11-22 11:11
Yup, I will make a pr this weekend. Haven’t forgotten it :)

**Comment by davi5e** [comment] 2020-02-11 22:25
I also had this problem and had to change `DateTimePicker.vue`, but what I did was this:

```diff
diff --git a/nova/resources/js/components/DateTimePicker.vue b/nova/resources/js/components/DateTimePicker.vue
index 97c3f81..1b01b88 100644
--- a/nova/resources/js/components/DateTimePicker.vue
+++ b/nova/resources/js/components/DateTimePicker.vue
@@ -59,7 +59,9 @@ export default {
         enableSeconds: this.enableSeconds,
         onClose: this.onChange,
         onChange: this.onChange,
-        dateFormat: this.dateFormat,
+        altInput: true,
+        altFormat: this.dateFormat,
+        dateFormat: 'Y-m-d H:i:S',
         allowInput: true,
         // static: true,
         time_24hr: !this.twelveHourTime,
```

Like so, minimal changes are necessary. I just did not understand why it's taking so long for a definitive solution... I'll need to apply this patch every time Nova has a new release until some solution gets merged...

**Comment by pleone** [comment] 2020-05-21 16:47
Same issue here, any update oh this?
Very bad design btw, on the docs its written that ->format and ->pickerFormat are both DISPLAY format and not actually the date format.
Sigh!

**Closed** 2020-07-20 15:50 UTC
Labels: bug

**Comment by davide-casiraghi** [comment] 2020-10-08 08:01
I don't get why this issue has been closed since the bug is still there.
I'm experiencing the same problem now with Nova version 3.

**Comment by crynobone** [comment] 2020-10-08 08:12
@davide-casiraghi if you have the problem now that might mean there another issue related to this. Please create a new issue with explaination and reproducing code to allow us to replicate your problem.
