### ISSUE TITLE
Date Field format d/m/Y displays as Y-m-d

### ISSUE THREAD

**Issue by RicardoRamirezR** [laravel/nova-issues#44] opened 2018-08-23 16:39 UTC
using:
```php
    Date::make('Birthday')->format('d/m/Y'),
```
seems to ignore format, it displays ```Y-m-d```

**Comment by RicardoRamirezR** [comment] 2018-08-23 20:38
Got it working using:
```php
Date::make('Birthday')->resolveUsing(function ($date) {                
    return $date->format('d/m/Y');
}),
```
But not for editing.

**Comment by jameslkingsley** [comment] 2018-08-24 06:52
It's using Moment's' date/time formatting, see https://momentjs.com/docs/#/displaying

**Comment by RicardoRamirezR** [comment] 2018-08-24 14:53
No luck @jameslkingsley  
```php
Date::make('Birthday')->format('MMM'),
```
Shows ```YYYY-MM-DD```

**Comment by kevinpijning** [comment] 2018-08-26 20:39
Got the same issue, but my entire edit page stopped working with the solution from @RicardoRamirezR  :(

**Comment by RicardoRamirezR** [comment] 2018-08-26 21:12
@kevinpijning the ```date```should be a ```Carbon``` instance

**Comment by kevinpijning** [comment] 2018-08-26 21:13
Yes, i casted them in my model

**Comment by kevinpijning** [comment] 2018-08-26 21:28
@RicardoRamirezR Updated from 1.0.5 to 1.0.6 and now the edit page saves again, thanks for your help!

Still weird the normal format method does not work.

**Comment by daguilarm** [comment] 2018-08-28 18:58
Any solution for the editing view?

**Comment by RicardoRamirezR** [comment] 2018-08-28 19:48
Actually, even it is displayed as Y-m-d while editing, you can edit it as other format, I wrote it as d/m/Y and the record was updated successfully.

**Comment by daguilarm** [comment] 2018-08-30 11:27
The problem is with flatpickr... I trying to customize it, but no luck at the moment.

**Comment by RicardoRamirezR** [comment] 2018-08-30 13:56
@daguilarm here the problem is when editing it shows an incorrect format even before the calendar popup is shown

**Comment by rokde** [comment] 2018-09-04 09:42
Using the momentjs display formatting solves the problem for DateTime fields as well. But wouldn't it be nice we can still use php date formatting and Nove translates it itself into momentJs formatting stuff?

**Comment by RicardoRamirezR** [comment] 2018-09-04 13:59
Just updated to 1.0.9 the issue is still there.

**Comment by daguilarm** [comment] 2018-09-05 08:35
Updated to 10.0.12 and still not working...

**Comment by mvdnbrk** [comment] 2018-09-14 09:39
In `/nova-api/{model}/{id}`:

```json
{  
   ...
   "resource":{  
      "fields":[  
          {  
            "component":"date",
            ...
         },
         {  
            "component":"date-time",
            ...
            "format":"dddd, DD MMMM YYYY, HH:mm"
         },
        ...
   }
}
```

Where the `date-time` component has a format attribute, the `date` attribute has not.

**Comment by mvdnbrk** [comment] 2018-09-20 19:45
@taylorotwell This issue persists in version 1.1.0. The format attribute now *is* passed within the JSON response. The value stays represented as YYYY-MM-DD.

**Comment by RicardoRamirezR** [comment] 2018-09-20 20:28
@mvdnbrk is not released yet

**Comment by RicardoRamirezR** [comment] 2018-09-20 23:17
Nova v1.1.1:
```php
Date::make('Dead')->format('DD/MM/YYYY'),
```
The date is displayed perfect. 

Wait... if `dead` is `null` is shows `Invalid date`  and when editing the format is `YYYY-MM-DD`

**Comment by dwyer14** [comment] 2018-09-21 01:32
I'm assuming `YYYY-MM-DD` is intentional when editing, but opened #628 for the "Invalid date" issue.

**Comment by costaevangelista** [comment] 2018-09-26 18:10
Add the $casts in the model, so you will solve the problem.

protected $casts =[
        'birthday'=> 'date:d/m/Y'
    ];

ready soon! Ver. Laravel Nova 1.1.3

**Comment by RicardoRamirezR** [comment] 2018-10-01 21:54
@costaevangelista nope!

**Comment by dwyer14** [comment] 2018-10-01 23:30
Working as expected for me; `null` dates are now a "—".

**Comment by RicardoRamirezR** [comment] 2018-10-02 00:13
@alexbowers, yep.

In my model:
```php
protected $casts =[
    'birthday' => 'date:d/m/Y',
];
```
In the Nova resource:
```php
Date::make('Birthday'),

Date::make('Birthday')->format('DD/MM/YYYY'),
```
it displays:
![image](https://user-images.githubusercontent.com/6526545/46322224-502de800-c5ad-11e8-9ff7-a41e847be667.png)

and when editing:
![image](https://user-images.githubusercontent.com/6526545/46322256-7ce1ff80-c5ad-11e8-8890-d2b4956944da.png)

The popup calendar also set the date in YYYY-MM-DD

Hope this helps.

**Comment by RicardoRamirezR** [comment] 2018-10-02 00:15
@dwyer14 same here! `null` as `--`

**Comment by virp** [comment] 2018-10-17 04:10
In DateTimePicker.vue component, "dateFormat" props default value is `Y-m-d H:i:S`. From DateField.vue passed hardcoded `Y-m-d`, from DateTimeField.vue nothing passed to DateTimePicker. I think an additional method is needed to transfer the format for editing field, like `Date::make('Birthday')->format('DD/MM/YYYY')->editFormat('d/m/Y')`

**Comment by koenhendriks** [comment] 2018-11-26 20:21
Still not fixed in v1.1.8 ?

It works when displaying but not when editing or updating....

Using

```php
 Date::make('planned_on')->format('DD-MM-YYYY')
```

I get the following in the index:

![screenshot from 2018-11-26 21-18-48](https://user-images.githubusercontent.com/4124579/49039720-e0109c80-f1c0-11e8-8da0-89897d35a3d6.png)

But when editing:

![image](https://user-images.githubusercontent.com/4124579/49039733-e69f1400-f1c0-11e8-988c-23511ff35f71.png)

Is this because of the MomentJS and Carbon differences?

**Comment by carloshc** [comment] 2018-11-26 22:40
Still not fixed in current version (1.1.8) and, for us, the lack of these fix is really hard to explain to our client that uses Nova admin interface.

**Comment by larsjanssen6** [comment] 2018-12-13 09:18
Still not fixed in v1.2.1

**Comment by Fawzanm** [comment] 2019-01-09 02:08
Still not fixed in v1.3.0

**Comment by koenhendriks** [comment] 2019-01-09 13:15
> Fixed in upcoming release.

@taylorotwell Could you please take a look at this again? It is still not fixed. Please reopen this issue.

**Comment by gpressutto5** [comment] 2019-02-02 22:39
![image](https://user-images.githubusercontent.com/12385501/52170073-aa40e480-272a-11e9-82e6-898cc05e74b2.png)

![image](https://user-images.githubusercontent.com/12385501/52170071-96957e00-272a-11e9-8d0d-b3ec19f4815b.png)
Using nova v1.3.1

**Comment by mauricehofman** [comment] 2019-02-11 18:30
For me `->format('DD-MM-YYYY'),` is working on v1.3.1

**Comment by mvnobrega** [comment] 2019-02-15 19:54
Still not fixed

DD/MM/YYYY hh:mm 

hour and minute not showing.

**Comment by lasseeee** [comment] 2019-02-16 14:11
Also facing this issue, no luck with any of the above proposed fixes.

**Comment by dddeeemmmooonnn** [comment] 2019-02-20 03:23
I copied it https://novapackages.com/packages/enmaboya/nova-russian-datepicker
in my custom field and changed the format to what I wanted

**Comment by lehuizi** [comment] 2019-03-02 21:44
Still not fixed in 2.0

**Comment by massiws** [comment] 2019-03-05 15:25
Nova v1.3.2.

This issue may be not related (only) to _Date_ fields, but `format()` method also doesn't apply to other fields, for example, _Currency_ fields:
```php
Currency::make(__('Price'),  'price')
    ->min(0)
    ->format('%.2n')
    ->rules('nullable', 'numeric'),
```
This is correctly formatted on index and detail views, but still wrong on edit view.

**Comment by denvit** [comment] 2019-04-10 10:54
You have to use Moment.js formats, because nova fields are created with as vuejs components. So for example: ->format('YYYY-MM-DD HH:mm:ss')

![datetime-formating](https://user-images.githubusercontent.com/858347/55873350-b6647a80-5b8f-11e9-8a85-0baeb40476f2.png)

**Comment by JordanDinsdale** [comment] 2019-04-10 11:44
I am using that format in my resource but it isn't being applied to the datepicker field when I want to create an instance of my model.

```
Text::make('Name')
    ->sortable()
    ->rules('required', 'max:255'),

Date::make('Start Date')->format('DD/MM/YYYY')->sortable(),

   Date::make('End Date')->format('DD/MM/YYYY')->sortable(),
```

![Screen Shot 2019-04-10 at 12 42 49](https://user-images.githubusercontent.com/24391738/55875988-6afd9c80-5b8e-11e9-994e-ae2fd437d597.png)

**Comment by wvervuurt** [comment] 2019-05-15 22:33
Same here, under Nova 2, the passed date format is not respected on Create and Update forms. The format is being applied correctly on Index and Detail views. 

I suppose this has to get fixed on the JavaScript side of things. As a work-around, you might be able to define a custom Field that leverages the native DatePicker but adds some trickery to apply the configured date(time) format.

**Comment by mauricehofman** [comment] 2019-05-29 17:49
@RicardoRamirezR Did you eventually find a fix for this ?

**Comment by mauricehofman** [comment] 2019-05-29 18:56
So here is a really **dirty** solution:

```
    <script>
        setTimeout(function(){
          Object.values(document.getElementsByClassName('flatpickr-input')).forEach(element => {
            flatpickr(element,{
              format: "d-m-Y",
              altFormat: "d-m-Y",
              altInput: true,
              defaultDate: element.value,
            });
          })
        }, 2000);
    </script>
```
Even more dirty: add this to views/vendor/nova/footer.blade.php

Definitely not the best way to go, but i did learn that _flatpickr_ is the problem here. It looks to me that this is a fixable bug..

**Comment by royduin** [comment] 2019-07-11 08:29
@davidhemphill, can you look into this? It's still an issue in the latest release: 2.0.9

**Comment by davidhemphill** [comment] 2019-07-12 05:17
I'm working on an update that'll allow you to pass options to the flatpickr instance.

**Closed by davidhemphill** 2019-07-12 05:17 UTC
Labels: request

**Comment by royduin** [comment] 2019-07-12 06:57
Awesome, any ETA on that? Will it be in the next release?

**Comment by renalpha** [comment] 2019-09-30 12:08
This is still not fixed.

**Comment by pleone** [comment] 2019-12-09 10:12
I don't undestand how to properly format a date in form edit.
@davidhemphill @taylorotwell can you provide some info please?

It must be in dday/month/year format.
Thanks

**Comment by SquareBeard** [comment] 2019-12-09 10:49
Here is how I got it working.

In the model:
```php
protected $casts = [
    'starts_at'=> 'date:d/m/Y',
];

public function setStartsAtAttribute($value)
{
    $this->attributes['starts_at'] = $value === null ? null : Carbon::createFromFormat('d/m/Y', $value);
}
```

In the Nova resource:
```php
Date::make('Start date', 'starts_at')
	->format('DD/MM/YYYY')
	->hideWhenCreating()
	->hideWhenUpdating(),

Date::make('Start date', 'starts_at', function ($value) {
	return $value->format('d/m/Y');
})
	->format('DD/MM/YYYY')
	->pickerFormat('d/m/Y')
	->hideFromIndex()
	->hideFromDetail(),
```

It requires way too much code than it should be it seems to work fine for me like that.

**Comment by MENtechmedia** [comment] 2019-12-10 14:28
This is still not working. Please provide a fix. People are paying for this stuff.

**Comment by trollfalgar** [comment] 2020-01-22 19:38
I now use this component, which replaces Nova's DateTime:
https://packagist.org/packages/techouse/intl-date-time

Works perfectly!

**Comment by royduin** [comment] 2020-01-29 15:53
Can someone give an example how to get this working? It seems like the formatting in the frontend is working now, when I use these (can't imagine a case where `format` is different from `pickerFormat`):
```
->format('DD-MM-YYYY')
->pickerFormat('d-m-Y')
->firstDayOfWeek(1)
```
I'm getting the Dutch date notation. But when saving it in `$table->date('column')` causes a `Incorrect date value` error from MySQL. Using `'date:d-m-Y'` to cast the attribute doesn't seem to do a thing.

**Comment by jimwhiteside** [comment] 2020-03-26 16:38
For what it's worth to the next person - after many hours spent on this issue ... @royduin was close, but it didn't offer a complete solution for us, as the underlying model was also manipulated outside of Nova, so the `setDateAttribute` was triggering all sorts of problems with parsing the date.

Instead, the solution (for us) was to convert from Carbon to a formatted string when the Nova field instantiates (overriding the base Date field's `__construct()` method, and converting back again before updating the model (via `->fillUsing()`):

```
Date::make('Date', 'date', function ($value) {
    // `Date::__contruct()` default is to return $value->format('Y-m-d') which isn't understood by flatpickr
    // Note that it won't work if we try to move this closure to `resolveUsing()` which seems to be ignored :|
    return $value;
})
    ->rules('required', 'date')
    ->fillUsing(
        /**
            * Hydrate the given attribute on the model based on the incoming request.
            * Overrides Laravel\Nova\Fields\Field::fillAttributeFromRequest()
            * so that we pass a good Carbon object back to the model depending on where the value came from
            *
            * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
            * @param  object  $model
            * @param  string  $attribute
            * @param  string  $requestAttribute
            * @return void
            */
        function (NovaRequest $request, object $model, string $attribute, string $requestAttribute) {
            if ($value = Carbon::parse($request[$requestAttribute])) {
                // Probably an unchanged value from the model, e.g. `2020-04-03T23:00:00.000000Z`
                // Note that this value is UTC, we need to convert it to local,
                // presumably so that Laravel can convert it back!
                $value->tz = config('app.timezone');
                $model->{$attribute} = $value;
            } else {
                // Assume it's the output of flatpickr, so convert the flatpickr output back to a Carbon date.
                // Format must match that set in `pickerFormat()`
                $model->{$attribute} = Carbon::createFromFormat('d-m-Y', $request[$requestAttribute]);
            }
        }
    )
    ->format('DD-MM-YYYY') // display format on index / detail - https://momentjs.com/docs/#/parsing/string-format/
    ->pickerFormat('d-m-Y'), // format passed to flatpickr - https://flatpickr.js.org/formatting/
```

**Comment by royduin** [comment] 2020-05-27 13:21
Please re-open @davidhemphill

**Comment by origami1024** [comment] 2020-08-03 00:29
I had a painful struggle to set DD-MM-YYYY format on edit pages. Thing that helped me, that hasn't been mentioned is ->pickerDisplayFormat(), which sets alt-format for the picker.
Relevant piece of code (for clarity):
```
Date::make('Start Date', 'start_date')
                    ->sortable()
                    ->rules('required', 'date', 'before_or_equal:end_date', 'after_or_equal:now')
                    ->pickerDisplayFormat('d-m-Y')
                    ->format('DD-MM-YYYY')
                    ->pickerFormat('d-m-Y'),
```

**Comment by cre-mer** [comment] 2020-09-09 20:36
> Still not fixed
> 
> DD/MM/YYYY hh:mm
> 
> hour and minute not showing.

Try using DateTime field to show hours and minutes

**Comment by didix16** [comment] 2021-02-16 11:58
@origami1024 pickerDisplayFormat() does not exists for me

**Comment by crynobone** [comment] 2021-02-16 12:12
`pickerDisplayFormat()` exists on Laravel Nova 3, we no longer provide any bug fixes to Laravel Nova 2 or lower.
