### ISSUE TITLE
Edit button redirects to Detail screen instead of Edit form

### ISSUE THREAD

**Issue by Mihkel100** [laravel/nova-issues#6020] opened 2023-11-06 10:19 UTC
- Laravel Version: 10.30.1
- Nova Version: 4.29.2
- PHP Version: 8.2

### Description:
Clicking on "Edit" does not open edit form but resource detail screen. 
When I mouse over edit button, it shows the correct url ending with "/edit".

The problem started since Nova version 4.29.1

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Open a Resource
2. Click on "Edit" button

**Comment by crynobone** [comment] 2023-11-06 11:29
Duplicate of #6019

**Closed by crynobone** 2023-11-06 11:29 UTC
