### ISSUE TITLE
nova asks for abandoned package (moontoast/math)

### ISSUE THREAD

**Issue by CSenshi** [laravel/nova-issues#3316] opened 2021-04-01 20:18 UTC
- Laravel Version: 8.12
- Nova Version: 3.22
- PHP Version: 8.0

### Description:
This message from composer is well known for everyone:
`Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.`

Reason it was not fixed (as I remember) was that Nova requires this because it is used via `ramsey/uuid`, but while looking on the composer file of `ramsey/uuid` (https://github.com/ramsey/uuid/blob/master/composer.json), we can find that it is required in dev only. So why does nova requires it on both dev and prod? Maybe let's just remove it?

**Comment by crynobone** [comment] 2021-04-02 00:41
We'll consider this on the next-series. However as for now it's still safe to use `moontoast/math` as mentioned by Ramsey himself, https://github.com/laravel/nova-issues/issues/2270#issuecomment-583044259

Duplicate of #3054 #2990 #2894 #2523 #2270

**Closed by crynobone** 2021-04-02 00:41 UTC

**Comment by rvanbaalen** [comment] 2021-11-02 13:53
@crynobone Any update on this? Updated to the latest `laravel/nova` and it still has `moontoast/math` as a dependency.

**Comment by crynobone** [comment] 2021-11-02 13:56
implemented for Nova 4.

**Comment by rvanbaalen** [comment] 2021-11-02 13:59
Oh wow.. did this introduce a breaking change that it couldn't be pushed in a 3.x update for Nova?

**Comment by crynobone** [comment] 2021-11-02 14:10
Nova 3 still support Laravel 7 which doesn't support ramsey/uuid package without moontoast/math package.

You should also aware that @ramsey manages both ramsey/uuid and moontoast/math

**Comment by rvanbaalen** [comment] 2021-11-02 14:11
Thank you for this info. I'll go and have a look at Nova 4 and it's possible release date.
