### ISSUE TITLE
Pickerformat issue

### ISSUE THREAD

**Issue by dtannen** [laravel/nova-issues#1889] opened 2019-09-04 16:47 UTC
- Nova Version: v2.2.0

### Description

Date was set as "1999-06-13"
Date::make('DOB', 'dob')->rules('required', 'date_format:Y-m-d')->format('MM-DD-YYYY')

I changed to: 

Date::make('DOB', 'dob')->rules('required', 'date_format:m-d-Y')->pickerFormat('m-d-Y')->format('MM-DD-YYYY'),

and now the same date shows as "07-09-2024"

when I try to save the date, I get a rawCreateFromFormat Carbon error.

How can we set the picker format and field format for Date to m-D-Y and still have it save properly to MYSQL?  Do I need an onSave for every model?

**Comment by jbrooksuk** [comment] 2019-09-05 10:12
I've confirmed this, but I'm unsure why it's happening.

GIven the same example you posted above, I can see the Vue props are:

![image](https://user-images.githubusercontent.com/246103/64333150-dfb5f500-cfcd-11e9-8a4f-ee99db8d738b.png)

In this, we can see that the `value` is what we expect but the formatted value on the picker is incorrect.

**Comment by jbrooksuk** [comment] 2019-09-05 10:31
It looks like it's related to https://github.com/flatpickr/flatpickr/issues/853

**Comment by conormx** [comment] 2019-09-12 06:46
> It looks like it's related to [flatpickr/flatpickr#853](https://github.com/flatpickr/flatpickr/issues/853)

Flatpickr have stated the requirements of setting the dateFormat is that the value passed matches. 
The issue here is in Date.php or DateTime.php the format of the value is hardcoded to 'Y-m-d' or 'Y-m-d H:i:s'.

Having spent a few days working around and attempting to fix this I'm a little stumped.

The only solution I can come up with which is straight forward is a Carbon date format function to set the value format as it is passed to vue which MUST provide data in the correct flatpickr format.

The not straight forward solution is to parse the pickerFormat and convert the string to a PHP Datetime/Carbon supported string so that the format of the data passed to Vue matches the flatpickr's expected format.

**Comment by conormx** [comment] 2019-10-14 00:37
@jbrooksuk @davidhemphill Any chance you guys can have a look or provide an update on this one? Would love to be able to format our dates not in Y-m-d. (Australian Date user here).

**Comment by m-lotze** [comment] 2019-10-16 09:54
Same problem here. Second problem ist that the datepicker is not localized, but it should be.

**Comment by Ilyes512** [comment] 2019-10-28 19:39
I think this can be fixed with altInput. See https://github.com/laravel/nova-issues/issues/2037

**Comment by trollfalgar** [comment] 2020-01-22 19:37
I now use this component, which replaces Nova's DateTime:
https://packagist.org/packages/techouse/intl-date-time

Works perfectly!

**Closed** 2020-07-20 15:50 UTC
Labels: bug
