### ISSUE TITLE
Trix field duplicate content

### ISSUE THREAD

**Issue by zetrider** [laravel/nova-issues#5328] opened 2023-02-17 06:51 UTC
- Laravel Version: 9.52.0
- Nova Version: 4.22.0
- PHP Version: 8.1.14
- Browser type and version: Chrome 109.0.5414.119 (Official Build) (x86_64)

### Description:
Editing an element with a Trix field displays the content twice in the Trix field.

### Detailed steps to reproduce the issue on a fresh Nova installation:
In the Trix.vue file, in the initialize method, insertHTML adds rather than replaces the content in the input:
1. `<input type="hidden" :name="name" :id="uid" :value="value" />`
2. `this.$refs.theEditor.editor.insertHTML(this.value)`

**Comment by crynobone** [comment] 2023-02-17 07:03
Duplicate of #5303 and will be available on next release

**Closed by crynobone** 2023-02-17 07:03 UTC
