### ISSUE TITLE
N+1 query in index page with belongsTo fields

### ISSUE THREAD

**Issue by huoding** [laravel/nova-issues#1204] opened 2019-01-08 03:39 UTC
- Laravel Version: 5.7.19
- Nova Version: 1.3.0
- PHP Version: 7.1.23

### Description:
N+1 query in index page with many belongsTo fields, many sql are executed!
I have used $with attr in the resource, but it is invalid.

### Steps To Reproduce:
![2222](https://user-images.githubusercontent.com/3479812/50808576-261d5c00-133a-11e9-87c4-529dcea9dccb.png)

**Comment by bonzai** [comment] 2019-01-08 08:07
Duplicate of #112

**Closed by bonzai** 2019-01-08 08:07 UTC
