### ISSUE TITLE
Override BelongsTo field name has no effect on edit page

### ISSUE THREAD

**Issue by GingerNinjaNicko** [laravel/nova-issues#2231] opened 2019-12-18 10:43 UTC
We have two BelongsTo fields relating to our User class for createdBy and updatedBy.
When we get to the edit page, the label is the class' name rather than the name provided.
Works fine on the view page.
Code and screenshot provided.

Code:
```php
BelongsTo::make('Created By','createdBy', User::class),
BelongsTo::make('Updated By','updatedBy', User::class),
```

Screenshot:
![image](https://user-images.githubusercontent.com/24656076/71079055-6c9e4c00-2182-11ea-8e7d-b139f3801499.png)

**Comment by jbrooksuk** [comment] 2019-12-18 11:08
Duplicate of https://github.com/laravel/nova-issues/issues/773

**Closed by jbrooksuk** 2019-12-18 11:08 UTC
