### ISSUE TITLE
Field BelongsTo label not appearing on Edit Screen

### ISSUE THREAD

**Issue by reado** [laravel/nova-issues#717] opened 2018-09-27 22:09 UTC
Is there a reason why the BelongsTo field isn't showing the label on the Edit screen for a model?

Following [this post](https://github.com/laravel/nova-issues/issues/505) I was able to change my field definition to
```
BelongsTo::make('Question', 'Question', 'App\Nova\Question'),

BelongsTo::make('Next Question', 'nextQuestion', 'App\Nova\Question'),
```
which worked great on the Display and Index but when I look at it on the Edit page I still only see the Class definition name

<img width="908" alt="screen shot 2018-09-27 at 6 08 34 pm" src="https://user-images.githubusercontent.com/235169/46177326-7affff80-c280-11e8-818a-65c20588765e.png">

Any suggestions?

**Comment by bonzai** [comment] 2018-09-27 22:33
#526

**Comment by davidhemphill** [comment] 2018-09-28 11:29
Duplicate of #526

**Closed by davidhemphill** 2018-09-28 11:29 UTC
