### ISSUE TITLE
Tag field doesn't use relatableXxxxx methods

### ISSUE THREAD

**Issue by puzzledmonkey** [laravel/nova-issues#5120] opened 2022-11-27 11:44 UTC
- Laravel Version: 9.41.0
- Nova Version: 4.19.3
- PHP Version: 8.1.6
- Database Driver & Version: mysql
- Operating System and Version: windows
- Browser type and version: n/a
- Reproduction Repository: n/a

### Description:

Tag fields do not call resource's relatableXxxx methods when generating queries to populate the options list

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a Resource 'Group' with a with some filterable field (eg 'active')
2. Create a Resource 'Staff' with a BelongsToMany relationship on Group
3. In the Staff resource fields(), make a Tag field and add a relatableGroups or relatableQuery method to filter the Groups.
4. Observe the relatable* method isn't being called and no filtering occurs.

**Comment by crynobone** [comment] 2022-11-28 01:20
Duplicate of https://github.com/laravel/nova-issues/discussions/5097

**Closed by crynobone** 2022-11-28 01:20 UTC
