### ISSUE TITLE
Please add descriptive class names to fields etc.

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#2218] opened 2019-12-11 17:29 UTC
Every nova field, filter, etc should have a descriptive classname on the outer element, like e.g. `nova-field-belongsto` so that tweaking the styling of these elements is more easy and maintainable than relying on selectors like `[data-testid$="-select"]`

**Comment by davidhemphill** [comment] 2019-12-11 17:43
Duplicate of #617

**Closed by davidhemphill** 2019-12-11 17:43 UTC

**Comment by bernhardh** [comment] 2019-12-20 15:56
@davidhemphill 
Yes, its an dublicate and still no progress on it since 1 year and 2 months, even though it isn't a big deal at all, which you could resolve probably within 15 minutes. Its by the way the same issue as #1892 and probably a lot of other current and future issues.

**Comment by davidhemphill** [comment] 2019-12-21 17:24
@bernhardh Appreciate the helpful response. laravel/nova#763 was opened 10 days ago to offer a solution to this.

**Comment by bernhardh** [comment] 2019-12-23 08:44
Good to read that there is a progress (btw the link you mentioned shows me a 404 error). Thank you for your efforts.

**Comment by jbrooksuk** [comment] 2019-12-23 09:32
@bernhardh you need to link your Nova account to GitHub to be able to see the Nova repo; http://nova.laravel.com/settings#github

**Comment by bernhardh** [comment] 2019-12-23 09:34
Thank you. Didn't get that. Now i see it.
