### ISSUE TITLE
Direct navigation from one lens to another lens under same resource keeps old data

### ISSUE THREAD

**Issue by elambro** [laravel/nova-issues#1573] opened 2019-05-07 07:43 UTC
- Laravel Version: 5.8.15
- Nova Version: 2.0.3
- PHP Version: 7.3

### Description:
I have a resource with two lenses. If i navigate directly from one lens to the other by url without going back to parent resource the data on the page doesn't refresh.

### Steps To Reproduce:

- Create Resource
- Create two lenses
- Add links to them into the navigation menu
- Click on one then on another

**Comment by davidhemphill** [comment] 2019-05-08 17:41
This was fixed in v2.0 and am not able to reproduce the issue as you've described. For instance, I have two lenses, with `router-links` in the sidebar, and the data is refreshed as expected: 

![lens](https://user-images.githubusercontent.com/58970/57395721-74c6ef80-718e-11e9-8f3f-dca1746c8a28.gif)

What am I missing?

**Closed by davidhemphill** 2019-05-08 17:41 UTC

**Comment by merlin-41** [comment] 2020-11-11 06:09
> This was fixed in v2.0 and am not able to reproduce the issue as you've described. For instance, I have two lenses, with `router-links` in the sidebar, and the data is refreshed as expected:
> 
> ![lens](https://user-images.githubusercontent.com/58970/57395721-74c6ef80-718e-11e9-8f3f-dca1746c8a28.gif)
> 
> What am I missing?

How you show the lenses in the sidebar with lenses group?

**Comment by dwightwatson** [comment] 2021-09-22 06:53
Apologies to sidetrack - but how are you adding lenses to the sidebar? I can't find this in the docs.
