### ISSUE TITLE
Action::downloadURL does not down the current file

### ISSUE THREAD

**Issue by zsoltjanes** [laravel/nova-issues#6110] opened 2023-12-15 12:48 UTC
- Laravel Version: 10.37.3
- Nova Version: 4.32.10
- PHP Version: 8.1.0
- Database Driver & Version: mysql
- Operating System and Version: win 10 x64

### Description:
Action::downloadURL does not download the given file, if I dd() inside the handleUsing function it does not shown.

**Comment by davidhemphill** [comment] 2023-12-16 15:34
Duplicate of #6100

**Closed by davidhemphill** 2023-12-16 15:34 UTC
