### ISSUE TITLE
`displayUsing` for `DateTime` field is broken again

### ISSUE THREAD

**Issue by marijoo** [laravel/nova-issues#4684] opened 2022-08-11 09:31 UTC
- Laravel Version: 8.x
- Nova Version: 4.12.14
- PHP Version: 8.0

### Description:

In the release notes for 4.12.14 a fix for "an issue with Date and DateTime fields not using the correct value for display" was released. In fact this breaks the correct use of `displayUsing` for `DateTime` again that was [fixed earlier](https://github.com/laravel/nova-issues/discussions/3929#discussioncomment-2607539). When using `displayUsing` the field will be left blank.

Downgrading to 4.12.13 fixes the issue.

**Comment by crynobone** [comment] 2022-08-11 09:37
Duplicate of #4665, has been fixed but pending next release.

**Closed by crynobone** 2022-08-11 09:37 UTC
