### ISSUE TITLE
Wrong scope in Image preview callback

### ISSUE THREAD

**Issue by jwahdatehagh** [laravel/nova-issues#248] opened 2018-08-27 14:12 UTC
I get a wrong value for `$this` in the preview callback for the Image field.
 
<img width="442" alt="screen shot 2018-08-27 at 16 08 53" src="https://user-images.githubusercontent.com/2725836/44664512-bf934380-aa13-11e8-9c11-4ac35a681d18.png">

I get the current eloquent model instance but according to the documentation i should be able to retrieve the field value via `$this->value`. Is my implementation wrong, or is the documentation wrong?

Thanks!

**Comment by tschmidiger** [comment] 2018-08-27 17:57
Duplicate of #41

**Closed** 2018-08-27 19:46 UTC
