### ISSUE TITLE
Translation Order Problem

### ISSUE THREAD

**Issue by christophrumpel** [laravel/nova-issues#1260] opened 2019-01-22 09:52 UTC
- Laravel Version: 5.7.21
- Nova Version: 1.3.1
- PHP Version: 7.2
- Operating System and Version: macOS 10.14.2

### Description:

Right now, translatable strings are tightly coupled with the English language.
This gets specifically a problem when multiple strings get connected like here:

```
<slot> {{ __('Attach') }} {{ singularName }} </slot>
```

In a language like German, this construct does not work anymore, because the translated string for `attach` would be placed after the resource name. (e.g. "Veranstaltung anhängen") I guess this will be similar in other languages as well.

So I was wondering if it would be possible to get rid of translations where multiple translations get combined. Two ideas that came to my head:

**1. We could use placeholders in the translation and pass the resource name (for example) to the translation file. There we could place it where we want it to be in the string.**

```
'attach_resouce' => ':RESOURCE: anhängen',
```
The downside here, I think those placeholders only work for the PHP array translation and not the JSON ones.

**2. Would it be possible to use the dynamic value to create a custom translation key like:**

```
<slot> {{ __('Attach_'.$singularName) }} </slot>
```

And then I could create a translation for `Attach_Event` and define the whole string in there in the translated version. I have to say I haven't tried that yet. Just want to start a discussion about it.

The downside I see here is that you need to create a translation for every new resource. This would only work if we could define fallback translations.

### Steps To Reproduce:

* Create another language file
* Translate strings
* Change app language
* Check Nova translations

In my case, I was referring to the `attach` buttons which you get when you have a many-to-many relationship and when you want to attach a model to another one.

**Comment by bonzai** [comment] 2019-01-22 09:58
I'm working on it (but no ETA).

Duplicate of #203

**Closed by bonzai** 2019-01-22 09:58 UTC

**Comment by christophrumpel** [comment] 2019-01-22 10:01
Oh didn't see that conversation. Thanks 👍
