### ISSUE TITLE
Search not working on a BelongsTo relationship in an Action

### ISSUE THREAD

**Issue by aa146214** [laravel/nova-issues#6305] opened 2024-03-25 13:13 UTC
- Laravel Version: 10
- Nova Version: 4.33.0
- PHP Version: 8.2.10
- Database Driver & Version: Mysql 5.8
- Operating System and Version: 8.0.31-0ubuntu0.20.04.2
- Browser type and version: Latest on all browsers tested
- Reproduction Repository: https://github.com/###/###

### Description:
![screenshot (2)](https://github.com/laravel/nova-issues/assets/4972737/dc5a4052-12da-4a57-993c-a261f8a46c5b)

### Detailed steps to reproduce the issue on a fresh Nova installation:

public function fields(NovaRequest $request): array {
    return [
        BelongsTo::make('Class', 'programme', Programme::class)
            ->required()
            ->rules('required')
            ->searchable()
    ]
}
etc

If I remove ->searchable() then it works, however this is not usable for us.

Because there may be hundreds/thousands of programmes.

We can't include them all in a dropdown list, hence search.

This was working on a previous Nova version 4.31, updated and now not working

**Comment by aa146214** [comment] 2024-03-25 13:45
It started happening on exactly Nova 4.32.7

**Comment by Arturas0** [comment] 2024-03-26 07:25
Issue for for bug was created 2 weeks ago: https://github.com/laravel/nova-issues/issues/6276. Looks like fix should arrive in next release.

**Comment by marijoo** [comment] 2024-03-26 16:53
> It started happening on exactly Nova 4.32.7

It started with [4.32.16](https://nova.laravel.com/releases/4.32.16) – I guess with this commit:

- Fix SearchInput backdrop z-index issue when using action modals.

**Comment by crynobone** [comment] 2024-03-26 23:56
Duplicate of https://github.com/laravel/nova-issues/issues/6276 and should be fixed in `4.33.1`

**Closed by crynobone** 2024-03-26 23:56 UTC
