### ISSUE TITLE
Nova submitting Headings on related models

### ISSUE THREAD

**Issue by pierrepavlov** [laravel/nova-issues#4902] opened 2022-10-12 08:07 UTC
- Laravel Version: 9.35.1
- Nova Version: 4.15.2
- PHP Version: 8.1.7
- Database Driver & Version:
- Operating System and Version: Mac OS 12.4
- Browser type and version: Brave 1.44.108
- Reproduction Repository: https://github.com/pierrepavlov/nova-headings

### Description:
Nova tried to submit Headings as input. In this case it happens when you try to save a model that has a HasOne-relation that has Headings.

This has been discussed recently but it's probably only been solved on specific cases like these:
https://github.com/laravel/nova-issues/issues/4874
https://github.com/laravel/nova-issues/issues/4846

### Detailed steps to reproduce the issue on a fresh Nova installation:
See repository to reproduce on a fresh installation or do the following. I've described how I reproduced it.
1. Create a table to be used for a HasOne-relation (user_profiles) to the some model (user).
2. Add the relation to the model.
```
// app/Models/User.php
public function userProfile()
{
    return $this->hasOne(UserProfile::class);
}
```
3. Create the Nova resources for the models. (User and UserProfile)
4. Add the HasOne-field to the model.
```
// app/Nova/User.php
HasOne::make('User profile')
```

5. Add a Heading to the related model (UserProfile)
```
Heading::make('This is my heading that is being posted when I update my user'),
``` 
6. Navigate to a User in Nova and create a profile.
7. Now try to edit the User in Nova (/nova/resources/users/1/edit) when the HasOne-relation is being loaded on the same view.

**Comment by crynobone** [comment] 2022-10-12 08:24
Duplicate of #4874

You can use the following workaround until 4.16.0 release.

```php
Heading::make('This is my heading that is being posted when I update my user', 'dummy_attribute'),
```

**Closed** 2022-10-12 08:24 UTC

**Comment by pierrepavlov** [comment] 2022-10-12 08:46
@crynobone Okay, thanks! When till 4.16.0 be released? Need to know if it's worth going through our entire project to update this or just wait.

**Comment by pierrepavlov** [comment] 2022-10-12 11:52
@crynobone Did you mean that we need to actually add this attribute to the model for your workaround to work? Just adding the second parameter results in the same problem.
