### ISSUE TITLE
Search input not working in select field for actions

### ISSUE THREAD

**Issue by guybrun** [laravel/nova-issues#6276] opened 2024-03-13 08:00 UTC
- Laravel Version: 10.48.2
- Nova Version: 4.32.16
- PHP Version: 8.2.7
- Database Driver & Version:
- Operating System and Version: Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
- Browser type and version: Chrome.122.0.6261.129 (Official Build) (64-bit)

### Description:
Updated to Nova version 4.32.16 and discovered that the search input field does not work for select field which is searchable() in actions,

It is not possible to type in the Search input field.

Take a look at uploaded screenshot.
![nova-4-32-16-bug](https://github.com/laravel/nova-issues/assets/11294565/5634d851-1e81-4f33-883f-02863c6f29fd)

**Comment by crynobone** [comment] 2024-03-13 08:09
Fixed in 4.33.0

**Comment by guybrun** [comment] 2024-03-13 11:27
I updated to 4.33.0, but still same issue

**Comment by guybrun** [comment] 2024-03-13 11:28
> Fixed in 4.33.0
I updated to 4.33.0, but still same issue

**Comment by potsky** [comment] 2024-03-13 13:28
Same problem and behavior.
#6257 has fixed the global freeze but not the belongsTo freeze

**Comment by meyer59** [comment] 2024-03-13 14:00
i have opened the same issues Dec 13 and reopen one a few days ago. How arogant they are, they keep closing my issues but the problem is still here https://github.com/laravel/nova-issues/issues/6271 https://github.com/laravel/nova-issues/issues/6107

**Comment by potsky** [comment] 2024-03-13 15:14
> i have opened the same issues Dec 13 and reopen one a few days ago. How arogant they are, they keep closing my issues but the problem is still here #6271 #6107

_Arogant_ I don't know, but bugs are part of the development process 😇 Even if we pay for Nova, there will always be some bugs. This is normal.

We just need to be constructive to help them to find and fix bugs. I know this is annoying, my sales team of 10 people is currently blocked due to this bug, they cannot import electrical powers and consumption of French companies but we can just wait for the Nova team to fix the problem.

The actual bug is a common regression in Nova on BelongsTo fields. It was already the case on December #6113 then after it works agains and finally not!

**Comment by animena** [comment] 2024-03-14 09:54
same issue here, and blocking me from deadline, looks like I have to modify the code until this one is fixed

**Comment by goldmerc** [comment] 2024-03-14 13:05
+ 1, updating to 4.33.0 doesn't fix the issue. Non searchable selects work fine but searchable ones start expanded and don't allow me to make a selection. I have to tab out or press escape.

**Comment by puzzledmonkey** [comment] 2024-03-16 00:15
same issue here.

honestly, sorry to bring this up as i'm sure everyone agrees, but if this has been an issue since 4.32.16, why is it not already in your dusk test cases - specifically the "BelongsTo searchable in an Action popup" case that STILL causes this issue on 4.33.0?

it's quite frustrating that we cannot rely on simple functionality like this in a paid product such as Nova.

**Comment by mostafaznv** [comment] 2024-03-17 13:55
I believe this issue is related to #6242 
I reported it a couple of days ago, and while they released some fixes, the problem persists.

Please refer to that issue for a detailed explanation, including a reproduction repository and a video demonstrating the problem.

**Closed** 2024-03-18 15:17 UTC

**Comment by potsky** [comment] 2024-03-21 13:00
> Sorry, I'm confused. I'm sure something similar was fixed in v4.33.0 but almost almost unanimously people here are saying this particular issue isn't fixed.
> 
> 
> 
> @crynobone has marked this as `fix incoming`, does that means there's a fix coming in v4.33.1?
> 
> 
> 
> I'm running v4.33.0 and am unable to focus on the search field when using `searchable` on the `Select` nova field type. I can also confirm this issue doesn't occur in v4.32.11

This is not fixed in v4.33.0 We certainly have to wait for the next version.

**Comment by puzzledmonkey** [comment] 2024-03-24 00:04
Hey @crynobone or @davidhemphill is there any ETA on getting this fix released? You've previously released point releases with single bug fixes, and this issue is really breaking functionality. Is there any chance of making a point release to fix this issue in particular?
