### ISSUE TITLE
Menu items and dashboard cards are duplicated each page reload if using swoole

### ISSUE THREAD

**Issue by ZengDaWei** [laravel/nova-issues#2867] opened 2020-09-16 07:12 UTC
- Laravel Version: 7.28.1
- Nova Version: 3.9.1
- PHP Version: 7.4.9
- Database Driver & Version: mysql 8.0.20
- Operating System and Version: Ubuntu 18.04.4 LTS
- Browser type and version: Chrome 85.0.4183.102

### Description:
Menu items and dashboard cards are duplicated each page reload if using swoole, And I read this issue: 
https://github.com/laravel/nova-issues/issues/1013，But it didn't seem to work for me

The issue looks like this

### Detailed steps to reproduce the issue on a fresh Nova installation:
![image](https://user-images.githubusercontent.com/44629601/93304184-2ec47600-f82f-11ea-9252-bebece9d781c.png)

Under normal PHP services, Nova sometimes runs a little slow, so I use swoole to speed it up.

**Steps To Reproduce**:
Install swoole php-extension and package swooletw/laravel-swoole (v2.6.67).
Run laravel php artisan swoole:http start.
Go to Nova dashboard and reload page

**Comment by davidhemphill** [comment] 2020-09-18 15:27
Duplicate of #1013

**Closed by davidhemphill** 2020-09-18 15:27 UTC
