### ISSUE TITLE
Feature Request: Implement Searchable Select Filters for Improved Usability

### ISSUE THREAD

**Issue by nastoychev** [laravel/nova-issues#6461] opened 2024-07-11 10:02 UTC
### Discussed in https://github.com/laravel/nova-issues/discussions/6448

<div type='discussions-op-text'>

<sup>Originally posted by **nastoychev** June 26, 2024</sup>
There is no built-in support for creating searchable filter components. Having searchable  filters would greatly enhance the usability and efficiency of the application, especially when dealing with large datasets.

We propose the introduction of a searchable filter logic which we can apply like:

```php
    public function filters(NovaRequest $request): array {
        return [
            SomeCustomSelectFilter::make()->searchable()
        ];
    }
```

It should look at the end similar to SelectField::make(...)->filterable()->searchable() and I guess you can reuse this Vue component.

Please note, we prefer searchable components that display all options, not just a single input field, which start showing options as we type. Thank you!

✅ The right searchable way! 🥇 
![Screenshot 2024-06-26 171250](https://github.com/laravel/nova-issues/assets/41673191/b10e0fbb-3ed8-4e68-8313-33514229ca72)
</div>

**Comment by crynobone** [comment] 2024-07-11 10:53
Duplicate of https://github.com/laravel/nova-issues/discussions/6448

**Closed by crynobone** 2024-07-11 10:53 UTC
