### ISSUE TITLE
displayUsing and resolveUsing don't get called for empty values, breaks sorting.

### ISSUE THREAD

**Issue by anderly** [laravel/nova-issues#2198] opened 2019-12-04 16:54 UTC
- Laravel Version: 6.6.0
- Nova Version: 2.8.0
- PHP Version: 7.3
- Database Driver & Version: mariadb
- Operating System and Version: OS X Catalina
- Browser type and version: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

### Description:

See #1277 and #1599 for reference. Not sure if this is by design or if there is a workaround, but I would like to be able to use displayUsing/resolveUsing even when the $value is NULL/empty.

### Steps To Reproduce:

Both scenarios below using `displayUsing` and `resolveUsing` break when sorting.

```php
    Badge::make('Agreement', 'agreement_file')
        ->displayUsing(function ($agreement) {
                return empty($agreement) ? 'danger' : 'success';
        })
        ->labels([
                 'danger' => 'Missing',
                'success' => 'On File',
        ])->sortable()->onlyOnIndex(),
```

OR

```php
    Badge::make('Agreement', 'agreement_file')
        ->resolveUsing(function ($agreement) {
                return empty($agreement) ? 'danger' : 'success';
        })
        ->labels([
                 'danger' => 'Missing',
                'success' => 'On File',
        ])->sortable()->onlyOnIndex(),
```

If the agreement_file column is NULL for a given record, this doesn't get called and then sorting breaks and provides a front-end error "Error trying to find [type] inside the field's type mapping."

**Comment by jbrooksuk** [comment] 2019-12-05 10:16
Duplicate of https://github.com/laravel/nova-issues/issues/1901

**Closed by jbrooksuk** 2019-12-05 10:16 UTC
