### ISSUE TITLE
Action result is ignored when selecting all matching resources

### ISSUE THREAD

**Issue by wfeller** [laravel/nova-issues#326] opened 2018-08-29 18:20 UTC
I'm trying to make a download action.

It works when when I manually select a few items or click select all.

When I "select all matching", the static::download() returned gets ignored and I get the default message saying "The action ran successfully!".

It seems to come from the chunks() method in ActionRequest :
![image](https://user-images.githubusercontent.com/21337627/44806601-b054f700-abc7-11e8-8989-88cb0887035f.png)

There's a similar issue when chunking actions, only the last result (download) gets returned (so when you have multiple downloads, you only get the last one instead of getting them all one by one).

![image](https://user-images.githubusercontent.com/21337627/44807063-e34bba80-abc8-11e8-9e54-818858379007.png)

**Comment by alexbowers** [comment] 2018-09-26 11:50
I have managed to reproduce this:

Simple reproduction:

Have an action return the `Action::message("My message here");`

When you choose "Select all matching" 
![image](https://user-images.githubusercontent.com/842974/46078010-be784200-c18a-11e8-93c5-5cf62f975b0d.png)

it will not return the response you expect.

If you choose "Select All", or individual items, it will.

**Comment by rorymcdaniel** [comment] 2018-09-27 00:10
I'm seeing the exact same thing. I used Xdebug to trace it though and the response from the action class appears to be sent correctly. It looks as though the problem may be in the Vue component that handles the action response, though I'm not sure why. 

The entire collection was correctly passed to the handle method in my action class.

**Comment by dwyer14** [comment] 2018-11-21 18:52
+1, kind of a gnarly bug...cripples our ability to run a full export of a resource.

Also—and sorry, slightly off-topic—I'm curious about the reasoning for both options (Select All vs. Select All Matching). If I understand this correctly, Select All checks the currently visible items—that is, the items on the active page. Since pagination results are a pretty volatile thing (eg, sorting, searching and filtering would all change what's on page x), what sort of use case is there for Select All? For me, I can't think of an instance where I would _not_ want to use Select All Matching.

Can somebody enlighten me with an example, where you would want to select based on visible/page results?

**Comment by dillingham** [comment] 2018-11-28 15:43
+1

**Comment by Fawzanm** [comment] 2018-12-04 01:20
I have the same issue while using the ZIpper package to download files. It works fine for manually selected fields. When I do 'Select All Matching' option it just ignores the handle() and show the default Action Message.

**Comment by dwyer14** [comment] 2018-12-07 17:48
@davidhemphill Is this something that's on your radar for the next release or two? Every user on our platform has asked about this bug; it's a pretty essential part of what we're building. I will likely need to build out a workaround if this isn't going to see a fix within the next week or two.

Not as urgent, but I would also +1 @dillingham's #1095 to remove the "Select All Matching" option.

**Comment by Fawzanm** [comment] 2018-12-08 01:31
@davidhemphill I also have the same issue as @dwyer14. My clients have started to complain. Atleast a minor fix like removing that 'Select All Matching' would do for now..

**Comment by dkulyk** [comment] 2019-01-09 22:55
PR was sent to upstream.

**Comment by arjasco** [comment] 2019-01-15 19:11
@davidhemphill Will this be released in 1.3.1? I appreciate the hard work resolving these issues. It's just a little frustrating having so many work arounds.

**Comment by dkulyk** [comment] 2019-01-15 19:21
PR was sent to upstream

**Comment by dkulyk** [comment] 2019-01-15 19:22
PR is waiting to review

**Closed** 2019-01-28 18:23 UTC
Labels: bug

**Comment by rominronin** [comment] 2019-05-20 11:03
Is it possible to get a patch for this?
Thanks!

**Comment by marijoo** [comment] 2020-06-22 08:39
> This has been fixed and will be included in the next release.
> By default will returns result from last chunk.

Are you sure? This is still bugging me. 🤔

**Comment by marijoo** [comment] 2020-06-22 10:07
Okay, it’s working now, but imho the docs should be updated. Nova processes actions in chunks (200 records each by default). We built an export feature and returned a `Action::download` in the `handle` method of our action [like stated in the docs](https://nova.laravel.com/docs/3.0/actions/defining-actions.html#action-responses), which worked fine until we hit the mark of 200 records.

There is an undocumented method `handleResults` that is called once all chunks have been processed. So now we are doing something like this and everything is working again:

```
protected $filename;

public function handle(ActionFields $fields, Collection $models)
{
    // Create temporary file $this->filename if it does not exist and append export data for each record.
    // If you have 500 records this will be called 3 times with a chunk size of 200. 
}

public function handleResult(ActionFields $fields, $results)
{
    // All chunks have finished processing, our file is fully built – NOW return the download response.
    return Action::download(
        route('data-export.download', ['file' => $this->filename], false),
        $this->name
    );
}
```

**Comment by Egnaro** [comment] 2021-04-21 21:41
Been banging my head against the wall on this. Glad I finally found this thread and the info about handleResult(). Would definitely be nice to have this documented more clearly.
