### ISSUE TITLE
Filters and Page on index view are lost after update or create

### ISSUE THREAD

**Issue by scramatte** [laravel/nova-issues#6379] opened 2024-05-10 10:17 UTC
- Laravel Version: 10
- Nova Version: 4.33
- PHP Version: 8.0
- Database Driver & Version: Postgres 
- Operating System and Version: Debian 11
- Browser type and version: Any

Filters and Page on index view are lost after update or create

Regards

**Comment by crynobone** [comment] 2024-05-10 11:56
Duplicate of https://github.com/laravel/nova-issues/discussions/4673

**Closed by crynobone** 2024-05-10 11:56 UTC
