### ISSUE TITLE
Z-Index On Search with Modals

### ISSUE THREAD

**Issue by jjjrmy** [laravel/nova-issues#4399] opened 2022-06-10 16:46 UTC
- Nova Version: 4.8.1

<img width="548" alt="Screen Shot 2022-06-10 at 12 45 38" src="https://user-images.githubusercontent.com/1609800/173113374-ebc118be-4f9f-4ad1-badc-ba5df0c52e36.png">

The Search Bar is not behind the modal's backdrop

**Comment by crynobone** [comment] 2022-06-10 23:25
Duplicate of #4393

**Closed by crynobone** 2022-06-10 23:25 UTC
