### ISSUE TITLE
Changed default behaviour with new version

### ISSUE THREAD

**Issue by danutavadanei** [laravel/nova-issues#5324] opened 2023-02-16 08:58 UTC
- Laravel Version: 9.51
- Nova Version: v4.21.0 (Silver Surfer) 
- PHP Version: 8.2
- Database Driver & Version: mysql
- Operating System and Version: linux

### Description:

From version v4.20.2 (Silver Surfer) to version v4.21.0 (Silver Surfer)  the default behavior of HasOne, HasManyThrough and HasOneThrough has changed without documentation instructions in how to revert. I expect this to be related to #5245 as I was using the behavior @chimit was using.

Please share instructions in how to have the previous default behavior with the new version as I couldn't find anything documented. I also made a diff in the HasOne field of the two versions and couldn't find any differences so is probably deeper.

Now:
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/13782979/219317298-13b539bb-9704-401b-94b7-5ac923dcf2fb.png">

Before:
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/13782979/219317548-28d323fd-e02f-4431-81a6-7dabe4e781fa.png">

**Comment by crynobone** [comment] 2023-02-16 09:03
The related issue was marked as a bug and the changes is the new expected behaviour without configurable options. We don't document it due to reason mentioned above.

**Closed by crynobone** 2023-02-16 09:03 UTC

**Comment by danutavadanei** [comment] 2023-02-16 09:04
@crynobone This is not a pleasant situation. I thought this is the default and I've built behavior over this for the last couple of months.

**Comment by danutavadanei** [comment] 2023-02-16 09:06
@crynobone Anyway, I could fix it with HasManyTrough relation but the create button is missing. I checked and there is no policy registered and authorizable is false. Maybe that is a bug than?

**Comment by crynobone** [comment] 2023-02-16 09:07
Sorry but the issue experienced by @chimit is valid and there no way to aboud repeated nested relationship with such usage.

**Comment by crynobone** [comment] 2023-02-16 09:15
> HasManyTrough relation but the create button is missing. I checked and there is no policy registered and authorizable is false. Maybe that is a bug then?

HasManyThrough expected behavior for Laravel Nova 4 is read-only.
