### ISSUE TITLE
issue in currency field with php 7.4.1

### ISSUE THREAD

**Issue by maherelgamil** [laravel/nova-issues#2319] opened 2020-02-01 03:01 UTC
- Laravel Version: 6.13.1
- Nova Version: 2.9.4
- PHP Version: 7.4.1
- Database Driver & Version:
- Operating System and Version: MacOS Catalonia
- Browser type and version: chrome, any version

### Description:
Currency field use `money_formate` function that's deprecated in php v7.4.1

```
Function money_format() is deprecated {"userId":725,"exception":"[object] (ErrorException(code: 0): Function money_format() is deprecated at /Code/project/vendor/laravel/nova/src/Fields/Currency.php:27) |  
 
```
![image](https://user-images.githubusercontent.com/6294478/73936324-3f049200-48eb-11ea-87ba-28c81b2d8c2c.png)

Please review it

**Comment by jbrooksuk** [comment] 2020-02-07 11:21
Duplicate of https://github.com/laravel/nova-issues/issues/2089

**Closed by jbrooksuk** 2020-02-07 11:21 UTC
