### ISSUE TITLE
Bug on version 4.24.1 by nova Actionable

### ISSUE THREAD

**Issue by erth5** [laravel/nova-issues#5522] opened 2023-05-10 11:38 UTC
- Laravel Version: 10.8 (latest)
- Nova Version: 4.24.1
- PHP Version: 8.1
- Database Driver & Version: mysql:latest
- Operating System and Version: windows
- Browser type and version: Firefox

There are a bug in the Laravel-Framework by reading the config locale exists since version 4.24.1 of Laravel nova. Version 4.23.0 is error free.
Visible by opening "Action Details" on a Model which use "Actionable": unknown error
I checked that the error not caused by spatie/laravel-translatable

Heres the error log:
[nova_bug_details.txt](https://github.com/laravel/nova-issues/files/11441320/nova_bug_details.txt)

    "require": {
        "php": "^8.1",
        "darkaonline/l5-swagger": "^8.5",
        "directorytree/ldaprecord": "^2.20",
        "fields/string-limit": "@dev",
        "guzzlehttp/guzzle": "^7.5",
        "inertiajs/inertia-laravel": "^0.6.8",
        "influxdata/influxdb-client-php": "^3.3",
        "laravel/framework": "^10.8",
        "laravel/jetstream": "^3.1",
        "laravel/nova": "4.23.0",
        "laravel/sanctum": "^3.2",
        "laravel/telescope": "^4.14",
        "laravel/tinker": "^2.8",
        "lorisleiva/laravel-actions": "^2.5",
        "maatwebsite/laravel-nova-excel": "^1.3",
        "opcodesio/log-viewer": "^2.4",
        "psr/simple-cache": "2.0",
        "spatie/laravel-permission": "^5.10",
        "spatie/laravel-tags": "^4.3",
        "spatie/laravel-translatable": "^6.5",
        "stepanenko3/nova-cards": "^1.9",
        "tightenco/ziggy": "^1.0",
        "timwassenburg/laravel-pivot-table-generator": "^1.0",
        "timwassenburg/laravel-service-generator": "^1.0"
    },
    "require-dev": {
        "apih/laravel-route-list-web": "^1.1",
        "fakerphp/faker": "^1.9.1",
        "joshgaber/novaunit": "^3.1",
        "laravel/dusk": "^7.7",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"

**Comment by crynobone** [comment] 2023-05-10 11:44
Duplicate of #5514 and will be fixed in upcoming release.

**Closed by crynobone** 2023-05-10 11:44 UTC
