### ISSUE TITLE
Bug: $perPageViaRelationship = 5 and 'pagination' => 'links', option in config/nova.php cause incorrect page count on resource table.

### ISSUE THREAD

**Issue by anderly** [laravel/nova-issues#1448] opened 2019-03-13 20:47 UTC
- Laravel Version: 5.8.4
- Nova Version: 2.0.0
- PHP Version: 7.2
- Operating System and Version: Windows 10
- Browser type and version: Chrome 72.0.3626.121

### Description:

When using the `'pagination' => 'links',` option in `config/nova.php`, the default `public static $perPageViaRelationship = 5;` in `Laravel\Nova\Resource.php` breaks the pagination links and page counts because it is colliding with the `perPage` option.

### Steps To Reproduce:

1. Set `'pagination' => 'links',` option in `config/nova.php`
2. Setup a parent resource with a HasMany child resource. Add 12 child models.
3. Navigate to the parent resource and then view the child resources.
4. The page count should be 3. However, you can only navigate to pages 1 and 2.

**Comment by dkulyk** [comment] 2019-03-13 23:07
Duplicate of https://github.com/laravel/nova-issues/issues/1408

**Closed by dkulyk** 2019-03-13 23:07 UTC
Labels: duplicate

**Comment by anderly** [comment] 2019-03-13 23:10
@dkulyk my bad, didn't see #1408.
