### ISSUE TITLE
Laravel Nova does not support MySQL <= 5.6

### ISSUE THREAD

**Issue by JonoB** [laravel/nova-issues#1691] opened 2019-06-20 13:21 UTC
- Laravel Version: 5.8.23
- Nova Version: 2.0.6
- PHP Version: 7.3.1
- Operating System and Version: Homestead, Ubuntu 18.04
- Browser type and version: Chrome
- Reproduction Repository: n/a

### Description:
The second migration in the Laravel Nova requires a `json` column, which is only supported in MySQL 5.7+. This requirement is not mentioned in the documentation: https://nova.laravel.com/docs/1.0/installation.html#requirements

Can you we change this to a text column instead, or is json explicitly needed?

### Steps To Reproduce:
Install Nova with MySQL 5.6

**Comment by dkulyk** [comment] 2019-06-20 23:19
Duplicate of https://github.com/laravel/nova-issues/issues/1671

**Closed by dkulyk** 2019-06-20 23:19 UTC

**Comment by davidhemphill** [comment] 2019-06-24 20:04
Hi Jonty! We'll be releasing a fix that sets those fields to the correct ones.

**Comment by desaintflorent** [comment] 2019-06-25 11:21
Hi @davidhemphill , do you have any date in mind ? I'm waiting for this fix too.

**Comment by davidhemphill** [comment] 2019-06-25 21:06
Just pushed the release, so you should be able to update to it right now. 👍
