### ISSUE TITLE
Select All Matching will show delete button

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#3105] opened 2020-12-07 02:57 UTC
- Laravel Version: 7
- Nova Version: 3.16
- PHP Version: 7.4

```
public function authorizedToDelete(Request $request)
    {
        return false;
    }
```

this will disable delete button but when using select all matching will show the delete button

<img width="1084" alt="Screen Shot 2020-12-07 at 09 55 27" src="https://user-images.githubusercontent.com/1090413/101304280-842e8300-3872-11eb-94d6-ea250bcc3e0a.png">
<img width="1082" alt="Screen Shot 2020-12-07 at 09 55 18" src="https://user-images.githubusercontent.com/1090413/101304291-88f33700-3872-11eb-9288-0c2f6061e94b.png">

**Comment by crynobone** [comment] 2020-12-07 08:08
Duplicate of #3089 and #322

**Comment by davidhemphill** [comment] 2020-12-07 08:08
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Closed by crynobone** 2020-12-07 08:08 UTC
