### ISSUE TITLE
PerPageOptions are not being respected

### ISSUE THREAD

**Issue by gavinhewitt** [laravel/nova-issues#1935] opened 2019-09-13 21:35 UTC
- Laravel Version: 5.8.35
- Nova Version: 2.3.0

### Description

If you change the $perPageOptions setting it does not seem to work everywhere.

### Steps To Reproduce

Change it to public static $perPageOptions = [100];

Not sure if it's a bug or something only on my end, but I have a 'Company' resource, and for that resource also a Lens. For some strange reason the lens does correctly show 100 results, but the resource itself will still show the default 25. Weird.

Whoops, looks like duplicate of #1851

**Comment by jbrooksuk** [comment] 2019-09-24 07:23
Closed as duplicate of #1851

**Closed by jbrooksuk** 2019-09-24 07:23 UTC
