### ISSUE TITLE
withBreadcrumbs visual glitch 

### ISSUE THREAD

**Issue by beshoo** [laravel/nova-issues#5661] opened 2023-06-29 15:32 UTC
- Laravel Version: 10.x
- Nova Version: v4.26.1 (Silver Surfer)
- PHP Version: 8.x
- Database Driver & Version: Mysql
- Operating System and Version: Linux
- Browser type and version: Chrome

### Description:
As you can see in the screenshot

![image](https://github.com/laravel/nova-issues/assets/4635115/c66f89c6-9edb-4bc3-8c6d-8c1126bf5fa1)

**Comment by beshoo** [comment] 2023-06-29 16:39
I think this is the problem here : ![image](https://github.com/laravel/nova-issues/assets/4635115/4e5e916f-9fdb-4ea1-b4dd-a26523192f79)

**Comment by davidhemphill** [comment] 2023-06-30 03:15
Closing because there's not enough information to replicate your issue. Feel free to open a new issue, but fill out the issue template and ideally provide a reproduction repository.

**Closed by davidhemphill** 2023-06-30 03:15 UTC
