### ISSUE TITLE
HelpText file field type HasOne not work

### ISSUE THREAD

**Issue by leonardyrj** [laravel/nova-issues#5666] opened 2023-06-30 16:07 UTC
Laravel Version: 9
Nova Version: 4.25.1
PHP Version: 8.2

### Description:
In the file field type, it still does not appear when it is a hasOne relationship

**Comment by davidhemphill** [comment] 2023-07-02 05:09
Closing because there's not enough information to replicate your issue. Feel free to open a new issue, but fill out the issue template and ideally provide a reproduction repository.

**Closed by davidhemphill** 2023-07-02 05:09 UTC
