### ISSUE TITLE
Can't load nova-assets and nova-api from domain.com/laravelapps/

### ISSUE THREAD

**Issue by halimtuhu66** [laravel/nova-issues#603] opened 2018-09-19 10:48 UTC
I've create laravel projects on locals that has a vhost with domain name (ex. mylocaldomain.com). and my laravel apps is in `mylocaldomain.com/laravelnova` ... 
my problem is, nova-assets and nova-api is not found and always send request with url `mylocaldomain.com/nova-assets` and `mylocaldomain.com/nova-api`.
is there a way to make nova-assets go to `mylocaldomain.com/laravelnova/nova-assets` ?

sorry for my bad english

**Comment by AegirLeet** [comment] 2018-09-19 11:19
#471 same problem?

**Comment by halimtuhu66** [comment] 2018-09-19 13:39
ah yes thank you for your fast response...

**Comment by alexbowers** [comment] 2018-09-24 18:57
Duplicate of #471

**Closed by alexbowers** 2018-09-24 18:57 UTC
