### ISSUE TITLE
Localization issue in other language.

### ISSUE THREAD

**Issue by mingyoung** [laravel/nova-issues#682] opened 2018-09-26 02:13 UTC
When I translate to Chinese, there should not add space between two words. It should be `创建角色`.

![image](https://user-images.githubusercontent.com/6228858/46053023-9d582700-c173-11e8-8b66-4b167dd66daa.png)

P.S. The meaning is `Create Role`.

Thanks.

**Comment by mgmbh** [comment] 2018-09-26 07:06
Similar in other languages where the verb and the resource should be flipped.

![image](https://user-images.githubusercontent.com/9266504/46062423-0a66bf00-c16a-11e8-8c5b-3a183a6c5f2f.png)

Should be "User erstellen" instead of "Erstellen User".
If we could use the :resource placeholder in this string like we can in "The :resource was created!" that'd be great!

**Comment by YassineGherbi** [comment] 2018-09-28 22:37
#203

**Comment by alexbowers** [comment] 2018-09-29 18:06
Duplicate of #203

**Closed by alexbowers** 2018-09-29 18:06 UTC
Labels: request
