### ISSUE TITLE
Unable to use repeater fields in a resource Action

### ISSUE THREAD

**Issue by roarkmccolgan** [laravel/nova-issues#6002] opened 2023-10-30 09:40 UTC
- Laravel Version: 9.52.16
- Nova Version: 4.28.0
- PHP Version:8.1.15
- Database Driver & Version: Mysql 8
- Operating System and Version: 
- Browser type and version: Mac Ventura 13.3

### Description:
Cannot use repeater field in Action.
Would like to be able to use repeater field as a field in an actions modal. If you try, an exception is thrown:

```
"Laravel\\Nova\\Fields\\Repeater\\Presets\\JSON::set(): Argument #3 ($model) must be of type Illuminate\\Database\\Eloquent\\Model, Laravel\\Nova\\Support\\Fluent given, called in /vendor/laravel/nova/src/Fields/Repeater.php on line 197"
```

What I would expect to happen is for the repeater field to submit the array of values of the repeater field for me to use as needed in the handle method of the action.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create an action
- Create repeater field.
- Use the repeater field in the action
- Run the action

**Comment by crynobone** [comment] 2023-10-30 09:51
Duplicate of https://github.com/laravel/nova-issues/discussions/5921

**Closed by crynobone** 2023-10-30 09:51 UTC
