### ISSUE TITLE
Computed field relationship properties only available as array

### ISSUE THREAD

**Issue by stuartcusackie** [laravel/nova-issues#826] opened 2018-10-10 10:30 UTC
- Laravel Version: 5.7.8
- Nova Version: 1.1.4
- PHP Version: 7.2.9

### Description:

I usually access properties using the arrow syntax, e.g. `$post->category->slug`, but this does not work for a related model in a computed field's callback.

### Steps To Reproduce:

+ Doesn't work: Set up a computed field that accesses a related model's properties using **arrows**: 

The below callback works fine on the index or view page, but if you attempt to save the model then you will get the error: **"Trying to access a property 'slug' of a non-object"**

**$this->category->slug** - this is the problem

```
Text::make('Link', function () {
      $url = "/blog/" . $this->category->slug . "/" . $this->slug;
      return "<a href='" . $url . "'>Link</a>";
 })->asHtml()
```

+ Does work: Set up a computed field that accesses a related model's properties using **array keys**: 

The below callback works fine with all Nova operations.

**$this->category['slug']** - this is the solution (not ideal)

```
Text::make('Link', function () {
      $url = "/blog/" . $this->category['slug']  . "/" . $this->slug;
      return "<a href='" . $url . "'>Link</a>";
 })->asHtml()
```

**Comment by dkulyk** [comment] 2018-10-11 19:32
Try to use `$this->resource->category->slug`

**Comment by stuartcusackie** [comment] 2018-10-12 08:53
> Try to use `$this->resource->category->slug`

Same error I'm afraid.

**Comment by stuartcusackie** [comment] 2018-10-12 13:45
Well this is just a simple example. It's a quick way for me to access the public view of the resource. A post in this example.

If I exclude it, as you've suggested, then I've lost a useful feature. If I avoid it by using array keys then yes, it will work in this case, but for future projects I might get stuck on the same problem. 

It seems like a bug and I'm reporting it because I hope Nova will be something I will work with a lot in future.

**Comment by dillingham** [comment] 2018-10-12 15:13
I would assume any computed fields would be generated with model events 
Aka, when post is saving, make a slug with category etc
Im not sure if lack of arrow syntax is or isn't a bug. Was just curious of your usecase :)
In your case if you want the link, you could also make a [accessor ](https://laravel.com/docs/5.7/eloquent-mutators#defining-an-accessor) on the post model

**Comment by stuartcusackie** [comment] 2018-10-12 15:28
@dillingham 

Thanks again. I just tested using your accessor code there and it still produces the same error unless I switch it to uses array keys for the related model: **"Trying to access a property 'slug' of a non-object"**

Seems like a bug.

**Comment by dillingham** [comment] 2018-10-12 15:30
Eager load the relationship or change category to category() this doesnt seem like a bug lol

**Comment by stuartcusackie** [comment] 2018-10-12 15:36
@dillingham 

It's already eager loaded, and using brackets wouldn't be the normal way of retrieving a one-to-one related model.

**Comment by dillingham** [comment] 2018-10-12 15:37
not a bug

**Comment by edward-rw** [comment] 2018-10-13 10:54
@stuartcusackie I am having the same issue.

I have an order with a computed total_price `$order->total_price` accessor from the Order model using `getTotalPriceAttribute`(among other computed accessors). I would like for them to show on the order-list, that works fine. But as soon as I attempt to update the order it gives me an error of it not finding any of the underlying properties and accessors that generates the `total_price` attribute.

As soon as I remove the Models/Order accessors from the Nova/Order field definition, I can hit save again without errors.

**Comment by robbplo** [comment] 2018-11-21 13:57
I'm having this issue as well. I'm attempting to use a computed field to display a total price attribute, which is calculated using a bunch of properties on my App\Offer model. First i tried to use an accessor on the model class but this didn't work. Extracting the code to the closure in the computed field also did not work.

Seems like somewhere in the process of updating a model within Nova, a model will be instantiated with no values. I tried dumping the model at the point of failure and it did not have any attributes filled.

**Comment by amosmos** [comment] 2019-01-01 16:10
@dillingham - the computed field is shown on the form by default. No need to hide it.

But it still causes an error when updating. Using array notation worked for me.

**Comment by shradhabanerjee** [comment] 2019-04-25 13:10
@amosmos , using array notation as in what exactly ? Array while calling the eager loaded variable ?

**Comment by amosmos** [comment] 2019-06-24 10:23
> @amosmos , using array notation as in what exactly ? Array while calling the eager loaded variable ?

No, while setting a computed field on a model and using a relationship in it.

**Comment by davidhemphill** [comment] 2019-06-28 19:53
The reason you're seeing this is because computed fields are sometimes resolved in places other than index and detail views. To get around this, you need to explicitly check that the relation is available. Here are some ways of doing that:

```php
$this->when($this->user, function () {
    return Text::make('User Link', function () {
        $url = "/nova/users/" . $this->user->id;
        return "<a href='" . $url . "'>Link</a>";
    })->asHtml();
}),

Text::make('User Link', function () {
    $url = "/nova/users/" . optional($this->user)->id;
    return "<a href='" . $url . "'>Link</a>";
})->asHtml(),
```

**Closed by davidhemphill** 2019-06-28 19:53 UTC

**Comment by amosmos** [comment] 2019-07-22 21:54
@davidhemphill  Makes sense! I will check this.

Just for my curiosity - where are more places that the model computed fields are resolved other than index and detail views?
