### ISSUE TITLE
When creating a new item, it doesn't autofill timestamps

### ISSUE THREAD

**Issue by TonnyORG** [laravel/nova-issues#642] opened 2018-09-22 07:57 UTC
Creating a new item from a Nova resource (UI) with the `created_at` and `updated_at` fields (DateTime) doesn't set a default value on these columns as it does when you create a new record from your app using the model directly.

**Comment by TonnyORG** [comment] 2018-09-23 02:16
@dillingham but I'm not looking to hide them, I expect them to have a "default" value (current date/time) when I create the resource as it does in the app.

**Comment by dillingham** [comment] 2018-09-23 02:26
@TonnyORG 

```php
DateTime::make('Created At')->withMeta(['value' => now()->format('Y-m-d h:m:s')]),
```

**Comment by TonnyORG** [comment] 2018-09-23 02:56
@dillingham yeah that one doesn't really work for me. I'm looking to replicate the same behavior that Eloquent does when you perform `[Model]::create(['prop' => 'value']);`.

When you do that `created_at` and `updated_at` values are filled by default with the current datetime. With your solution, it overrides the timestamps stored in the form with "now" datetime in the form.

**Comment by dillingham** [comment] 2018-09-23 03:03
Dude, you can have it autofill with my first answer, or enable it to be edited with my second

**Comment by dillingham** [comment] 2018-09-23 03:04
You mean you literally want it to do what it already does?

**Comment by alexbowers** [comment] 2018-09-24 17:29
It should do this already. Can you provide a simple example that isn't working so it can be reproduced?

**Comment by davidhemphill** [comment] 2018-09-27 17:21
Closing since we don't have example to work from and it's been a few days.

**Comment by TonnyORG** [comment] 2018-10-01 02:56
@davidhemphill @alexbowers sorry last week has been very busy for me.

Creating a "Car" through the UI without even touching the timestamp fields, then it creates a record with "null" value on these 3 columns. Here is a sample model and nova model:

```php
<?php

namespace App\Vehicle;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use App\Make;

class Car extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'deleted_at',
        'updated_at',
    ];
}
```

```php
<?php

namespace App\Nova\Vehicle;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\DateTime;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;

use App\Nova\Resource;

class Car extends Resource
{
    public static $model = 'App\Vehicle\Car';

    public function fields(Request $request)
    {
        return [
            ID::make()
                ->sortable(),

            Text::make('Name')
                ->sortable(),

            DateTime::make('Created At')
                ->hideFromIndex(),

            DateTime::make('Updated At')
                ->hideFromIndex(),

            DateTime::make('Deleted At')
                ->hideFromIndex(),
        ];
    }
}
```

**Comment by davidhemphill** [comment] 2018-10-02 02:53
I can verify this behavior is correct but I wouldn't call it a bug. You're intentionally setting the value to zero if you submit it empty without it being required.

**Closed by davidhemphill** 2018-10-02 02:53 UTC

**Comment by dillingham** [comment] 2019-07-13 14:32
Set it as a default value on the model in your resource.
```php
public static function newModel()
{
    $model = new static::$model;
    $model->setAttribute('created_at', now());
    $model->setAttribute('updated_at', now());
    return $model;
}
```
Will populate the current date for saving
