### ISSUE TITLE
BelongsTo label does not respect 

### ISSUE THREAD

**Issue by bcorcoran** [laravel/nova-issues#2236] opened 2019-12-19 22:06 UTC
- Laravel Version: 6.8.0
- Nova Version: 2.9.2

### Description:
#870 tried to fix this but it either regressed or was never included in any release.

To reiterate: 
The left column label while editing a resource that has a BelongsTo field is incorrectly based only off the resource it is referencing when you provide a custom label.

In my case, I am self-referencing a model via parent_id and want to allow the user to specify the parent item, but it's not clear what the dropdown is for since it only uses the resource itself to generate the label. This doesn't match the behavior anywhere else that I can tell.

```
BelongsTo::make(__('Parent Item'), 'parent', self::class)
                ->nullable()
                ->searchable(),
```

Assuming `self::class` is `Plumbus`, the left label is "Plumbus", not "Parent Item".

**Comment by jbrooksuk** [comment] 2019-12-20 10:09
Duplicate of https://github.com/laravel/nova-issues/issues/773.

There is a PR open on this already :)

**Closed by jbrooksuk** 2019-12-20 10:09 UTC

**Comment by bcorcoran** [comment] 2019-12-20 17:51
Thanks! I tried searching but never found 773.
