### ISSUE TITLE
`Index/FileField` show error when image is null

### ISSUE THREAD

**Issue by xiCO2k** [laravel/nova-issues#4903] opened 2022-10-12 10:45 UTC
- Laravel Version: 9.35.1
- Nova Version: 4.15.2
- PHP Version: 8.1.11
- Operating System and Version: MacOS 
- Browser type and version: Chrome 106

### Description:

When there is a `Image::make('Picture')` but this field is `null` it shows like this on `Index`:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/823088/195322634-fb7de36c-0f5d-4451-920d-86e576334dbb.png">

It probably misses the same condition that is available on `Detail`:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/823088/195323036-83d82b86-1b0b-40b2-8e94-26e63cfda53b.png">

Thanks,
Francisco

**Comment by crynobone** [comment] 2022-10-12 11:27
Duplicate of #4856 and will be available on next release.

**Closed by crynobone** 2022-10-12 11:27 UTC
