### ISSUE TITLE
Show menuItem/ Section/ Group depending on policies

### ISSUE THREAD

**Issue by riskmate-ac** [laravel/nova-issues#4050] opened 2022-04-20 06:59 UTC
- Laravel Version: 9.9.0
- Nova Version: 4.2.3
- PHP Version: 8.1.4

### Description:
Hi all,

using Nova I like the (new) function to create your own sidebar menu (https://nova.laravel.com/docs/4.0/customization/menus.html#customizing-the-main-menu). What I did not see is the ability to show menuItem/ Group/ Section based on policy returns (e. g. only show the User menuItem if the Auth-User returns true on viewAny in UserPolicy).

I saw that is is possible to append the **canSee** method to **tools** that are registered in the NovaServiceProvider though it does not see to be possible to do this with the menu entities. Laravel then tells me it has no clue how to handle the call to an undefined method.

In case I did not miss anything, wouldn't that kind of break the idea of a customized sidebar menu for everyone that has more than one role/ one access dimension being assigned to Nova users?

Happy to hear from you how you deal with that (potential) issue.

Thanks!

### Detailed steps to reproduce the issue on a fresh Nova installation:
Excerpt:
```
 MenuSection::make('Dashboard')->path('/dashboards/main')->icon('chart-bar'),

                MenuSection::make('Administration', [
                        MenuGroup::make('User Management', [
                            MenuItem::resource(User::class)->canSee(return ...),
```
Could be assigned to Sections, Groups or Items. So far it does not work on any of them.

**Comment by crynobone** [comment] 2022-04-20 08:57
Duplicate of https://github.com/laravel/nova-issues/discussions/3933

**Closed by crynobone** 2022-04-20 08:57 UTC
