### ISSUE TITLE
Relative routes for nova-api

### ISSUE THREAD

**Issue by martianatwork** [laravel/nova-issues#2965] opened 2020-10-15 14:24 UTC
- Laravel Version: 8.1.1
- Nova Version: 3.12.0
- PHP Version: 7.4
- Database Driver & Version: NA
- Operating System and Version: Linux
- Browser type and version: NA
- Reproduction Repository: NA

### TLDR:
Server `nova-api` and similar routes under `nova.path` or provide a way to change their paths

### Description:

As world is moving towards SPA and Microservices, hardcoded routes like this makes it hard to use nova in multiple services where they have their own admin panels.

We have two microservices under single domain with their own paths, hosted using kubernetes and ambassador with single authentication service. 
As Laravel has recently introduced Sanctum i believe in future people will start using similar stack for their microservices.

We can change the nova url and vendor folders url for this services.
But routes like nova-api, nova-vendor and similar routes are served from domain root instead of the `nova.path` 
which is impossible to have under the same domain with two different nova services.

it will be helpful if we server `nova-api` and similar routes from `nova.path` or give ability to change this path.

I have read the other issues about this like #471
We purchased nova because it makes our life easier, as @jbrooksuk mentioned in #471 to patch nova. is just not acceptable as we will have to patch every time there's a major or minor release which comes every month.
why is it so hard to understand what your customers want?
I dont wish to be mean but I dont understand why you guys are so stubborn about doing a simple change. 
It doesn't matter how stubborn you guys are one day you will fix this issue. it has to be fixed.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Our 2 micro-services are like this
1. DOMAIN/service1
2. DOMAIN/service2

When we visit `DOMAIN/service1/nova` it will call `DOMAIN/nova-api` instead of  `DOMAIN/service1/nova-api`

**Comment by davidhemphill** [comment] 2020-10-15 15:00
Duplicate of #471

We're not going to do this at this time, because it's not recommended to run Laravel from a subfolder. This would also require deeper changes requiring specific URI segments. 😃

**Closed by davidhemphill** 2020-10-15 15:00 UTC

**Comment by miks** [comment] 2021-02-09 09:28
Are there any plans for this? We have a lot of customers who have micro-sites under the main domain (for example SEO purposes). We are currently moving to Nova from our legacy CMS but this seems like a total dealbreaker.

**Comment by cliche23** [comment] 2021-02-09 09:34
Yes, also interested if there are any plans for this yet since it is becoming more and more a common thing. Why is it considered a bad practice to run Laravel in a subfolder?

**Comment by crynobone** [comment] 2021-02-09 10:46
You can serve Nova under a path however serving Laravel under a subfolder is never recommended, and there no plan to change this.

**Comment by martianatwork** [comment] 2021-02-09 10:51
@miks try this package
I got it working in my pipeline 
You just have to register nova routes under same path as well

https://github.com/illuminatech/override-build

I will post a gist link here when I get sometime for future reference.

**Comment by miks** [comment] 2021-02-09 12:14
@crynobone how can you differentiate whether www.example.com/foo (and subsequently www.example.com/foo/nova) is a directory or path?
We have a lot of Laravel applications served from path and had no problems with that. But it came as a surprise when we deployed our first Nova application to production under path and after trying to authorize we got 404 (there is no problem with frontend, it just works) as Nova is trying to load data from hardcoded /nova-api/.

**Comment by crynobone** [comment] 2021-02-09 12:18
> We have a lot of Laravel applications served from path and had no problems with that. 

Good if you can do it. However, you need to understand that Laravel itself doesn't officially support it. See https://github.com/laravel/framework/issues/32236#issuecomment-692546842

**Comment by cliche23** [comment] 2021-02-09 12:24
@crynobone Actually documentation doesn't explicitly say that it is not supported and I think we should distinguish between directories and paths.It is perfectly normal to have a site under a certain path and these situations are not rare (as already stated above)
