### ISSUE TITLE
"An option named "no-interaction" already exists." on nova:tool

### ISSUE THREAD

**Issue by Tarpsvo** [laravel/nova-issues#2714] opened 2020-06-29 14:05 UTC
- Laravel Version: 7.17.2
- Nova Version: 3.7.0
- PHP Version: 7.4.7
- Database Driver & Version: MySQL
- Operating System and Version: MacOS 10.15.3

### Description:

As described in https://github.com/laravel/nova/pull/901, `nova:tool` command now always throws the error `An option named "no-interaction" already exists.`

### Detailed steps to reproduce the issue on a fresh Nova installation:

Install Nova 3.7.0. Run `php artisan nova:tool`

**Comment by davidhemphill** [comment] 2020-06-29 15:04
Duplicate of #2707

**Closed by davidhemphill** 2020-06-29 15:04 UTC
