### ISSUE TITLE
Call to undefined method stdClass::forceFill()

### ISSUE THREAD

**Issue by Patryk48** [laravel/nova-issues#5662] opened 2023-06-29 20:39 UTC
Laravel Version: 10.10.0
Nova Version: 4.0.0
PHP Version: 8.1
Description:
{
    "message": "Call to undefined method stdClass::forceFill()",
    "exception": "Error",
    "file": "/var/www/html/vendor/laravel/nova/src/Fields/Field.php",
    "line": 492,'
}
Related Issue: https://github.com/laravel/nova-issues/issues/5654

**Comment by crynobone** [comment] 2023-06-30 22:16
Duplicate of https://github.com/laravel/nova-issues/discussions/5650

**Closed** 2023-06-30 22:16 UTC

**Comment by Patryk48** [comment] 2023-07-03 13:54
@crynobone problem still exist unnecesary :(  :( :(
