### ISSUE TITLE
Ability to configurable auth layout title

### ISSUE THREAD

**Issue by pavinthan** [laravel/nova-issues#858] opened 2018-10-19 03:23 UTC
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2.8

### Description:
It's hardcoded now, please make it configurable with `{{ Nova::name() }}`

`vendor/laravel/nova/resources/views/layout.blade.php` -> `{{ Nova::name() }}`
`vendor/laravel/nova/resources/views/auth/layout.blade.php` -> *Laravel Nova*

**Comment by bonzai** [comment] 2018-10-19 07:50
Duplicate of #522.

**Closed** 2018-10-24 07:37 UTC
