### ISSUE TITLE
money_format() error

### ISSUE THREAD

**Issue by yangjisen** [laravel/nova-issues#2343] opened 2020-02-11 10:18 UTC
- Laravel Version: 6.14.0
- Nova Version: 2.10.1
- PHP Version: 7.3.12
- Database Driver & Version: mysql8.0
- Operating System and Version:  windows 7
- Browser type and version: 
- Reproduction Repository: https://github.com/laravel/nova-issues

### Description:
```
message: "Call to undefined function Laravel\Nova\Fields\money_format()"
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: ".....\vendor\laravel\nova\src\Fields\Currency.php"
line: 27
```
```
    public function __construct($name, $attribute = null, $resolveCallback = null)
    {
        parent::__construct($name, $attribute, $resolveCallback);

        $this->step('0.01')->displayUsing(function ($value) {
            return ! is_null($value) ? money_format($this->format ?? '%i', $value) : null;
        });
    }
```

@see https://www.php.net/manual/en/function.money-format.php
Note:
The function money_format() is only defined if the system has strfmon capabilities. For example, Windows does not, so money_format() is undefined in Windows.

### Steps To Reproduce:
none

**Comment by jbrooksuk** [comment] 2020-02-11 11:44
Duplicate of an issue where we have a PR open already :)

**Closed by jbrooksuk** 2020-02-11 11:44 UTC
