### ISSUE TITLE
Saving resource with custom primaryKey throws error on redirect to resource detail view

### ISSUE THREAD

**Issue by randelsr** [laravel/nova-issues#610] opened 2018-09-19 20:13 UTC
I have a resource that has an enumerated primaryKey, eg tier_id of the tiers table.

When I save this resource via Nova, the resource properly saves to the database, but when Nova redirects to the new resource detail view, I receive the following:

[2018-09-19 18:39:29] local.ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" (SQL: select * from "tiers" where "tiers"."tier_id" = undefined limit 1) ...

Maybe on save, it's not obtaining the new resource's proper ID from the api?

When I try this with a standard object with primaryKey 'id' everything works fine..

**Comment by randelsr** [comment] 2018-09-19 20:40
https://github.com/laravel/nova-issues/issues/189

**Comment by dkulyk** [comment] 2019-01-13 15:20
Duplicate of https://github.com/laravel/nova-issues/issues/1124

**Comment by dkulyk** [comment] 2019-01-15 17:35
This has been fixed and will be included in the next release.

**Closed** 2019-01-15 17:34 UTC

**Comment by iSWORD** [comment] 2019-01-15 23:00
Any idea when the next release coming out? It should fix a couple issues I'm having.
