### ISSUE TITLE
Add "accept" attribute to File upload Field to filter-out file on OS level

### ISSUE THREAD

**Issue by lptn** [laravel/nova-issues#1645] opened 2019-05-31 06:38 UTC
Documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept

**Comment by FrittenKeeZ** [comment] 2019-06-03 13:45
I already suggested this https://github.com/laravel/nova-issues/issues/1345

**Comment by davidhemphill** [comment] 2019-06-10 16:17
Duplicate of #1345

**Closed by davidhemphill** 2019-06-10 16:17 UTC
Labels: request
