### ISSUE TITLE
DateTime field in dark mode.

### ISSUE THREAD

**Issue by philipbaginski** [laravel/nova-issues#4086] opened 2022-04-23 07:32 UTC
Laravel Version: 9.8.1
Nova Version: 4.2.5 (Silver Surfer)
PHP Version: 8.0.3
Database Driver & Version: MySql 5.7.24
Operating System and Version: Windows NT (10.0 - build 18363 (Windows 10))
Browser type and version: Google Chrome 100.0.4896.88

Description:

It looks like in dark mode the icon of DateTime field is not visible.

Detailed steps to reproduce the issue on a fresh Nova installation:

Place DateTime field into the resource, switch to dark mode, go to create or update view.

**Comment by crynobone** [comment] 2022-04-23 12:04
Duplicate of #4074

**Closed by crynobone** 2022-04-23 12:04 UTC
