### ISSUE TITLE
how to dependent dropdown in laravel nova? 

### ISSUE THREAD

**Issue by bhargavraviya** [laravel/nova-issues#3711] opened 2022-01-17 13:10 UTC
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment] 2022-01-17 13:49
Duplicate of #1470

**Closed by crynobone** 2022-01-17 13:49 UTC

**Comment by bhargavraviya** [comment] 2022-01-17 13:56
> Duplicate of #1470
using of package 
https://github.com/orlyapps/nova-belongsto-depend

https://stackoverflow.com/questions/70742378/how-to-create-dependent-dropdown-in-laravel-nova

There are laravel Nova package how to create dependent dropdown in above package used in package laravel 8.4 version and laravel nova 3.26.1 Version
