### ISSUE TITLE
Detaching a BelongsToMany row removes all relations to that model

### ISSUE THREAD

**Issue by mattias-persson** [laravel/nova-issues#2182] opened 2019-11-28 09:45 UTC
- Laravel Version: 6.6.0
- Nova Version: 2.8.0
- PHP Version: 7.3.9
- Database Driver & Version: MariaDB 10.2.14
- Operating System and Version: MacOS Mojave 10.14.6
- Browser type and version: Chrome 78.0
- Reproduction Repository: 

### Description:
I have an `Item` model with a `belongsToMany` relationship to an `Option` model with a few pivot fields. It's possible to attach multiple relationships to the same model, but with different pivot values. The pivot table also has an incrementing ID field. But when trying to detach one of these rows, all relations to that model are removed.

### Steps To Reproduce:
1. Create a belongsToMany relationship with some pivot field and add the Nova field to the model.
2. Attach multiple relations to the same model.
3. Detach one of them and verify that all are removed.

This is also mentioned in https://github.com/laravel/nova-issues/issues/1131#issuecomment-450204018 (see bullet 2).

**Comment by davidhemphill** [comment] 2019-12-05 18:22
Pivot tables need to have a unique ID field to avoid this behavior. This is by design.

**Comment by mattias-persson** [comment] 2019-12-06 08:26
> Pivot tables need to have a unique ID field to avoid this behavior. This is by design.

As I wrote, the pivot table also has an incrementing ID field. I've tried adding it to the invokable fields class I've defined for the BelongsToMany setup, but that doesn't help. It still used the ID of the target `Option` class rather than the pivot ID. Am I doing something wrong in my setup here?

**Comment by davidhemphill** [comment] 2019-12-07 23:26
My bad, I misread. I'll take another look at this.

**Comment by annejan89** [comment] 2019-12-09 14:27
+1 on this. Happens also when editing relations to change pivot data. The 'edit-attached' links in Nova are all the same. Even with an unique identifier in the pivot table. How to force this?

/nova/resources/orderlist/1/edit-attached/products/1?viaRelationship=Products

**Comment by tomscholz** [comment] 2020-01-15 12:48
There is likely going to be a bug in your schema. You could try to use a different primary key using a custom pivot class.

**Comment by mattias-persson** [comment] 2020-01-15 14:05
@tomscholz How do you mean? Why should I have to use a different primary key for this to work? Please elaborate.

**Comment by mattias-persson** [comment] 2020-06-22 08:20
@davidhemphill Any updates on this? It's causing us a bit of drama.

**Comment by BenWalters** [comment] 2020-08-27 08:25
It would seem that this has been fixed in the v3.x series. 👍

**Comment by crynobone** [comment] 2020-11-06 07:18
@BenWalters thank you for confirming that it has been fixed in v3. 

Unfortunately, Nova 2.x is no longer supported and you should upgrade to 3.x.

**Closed by crynobone** 2020-11-06 07:18 UTC
