### ISSUE TITLE
Dropdown of BelongsTo fields is "disabled" on actions modal since version 4.32.6

### ISSUE THREAD

**Issue by potsky** [laravel/nova-issues#6113] opened 2023-12-18 17:39 UTC
- Laravel Version: 10.37.3
- Nova Version: 4.32.7
- PHP Version: 8.2.12
- Database Driver & Version: PGSQL 14
- Operating System and Version: sail
- Browser type and version: Safari, Chrome, Arc...
- Reproduction Repository: -

### Description:

- Select models in a list
- Run action with fields and at least one BelongsTo
- The dropdown of a `BelongsTo` field is displayed correctly when Nova version <= 4.32.6
  <img width="737" alt="4 32 6" src="https://github.com/laravel/nova-issues/assets/408237/adae1f1e-622e-4c24-b4f1-742be3e37abd">
- The dropdown is already opened and not selectable for Nova version >= 4.32.7 (Tested until 4.32.10 included)
  ![4 32 7](https://github.com/laravel/nova-issues/assets/408237/96ae82c3-2f54-4313-9cdd-b3c233b049a5)

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Install Jetstream to have a dependency vastly
- Use an action with fields like this on `User` for example:
```php
    public function fields(NovaRequest $request): array
    {
        return [
            BelongsTo::make(__('Invited team'), 'team', Team::class)
                ->required()
                ->rules('required')
                ->searchable()
                ->withSubtitles(),
        ];
    }
```

**Comment by davidhemphill** [comment] 2023-12-19 18:23
Duplicate of #6097

**Closed by davidhemphill** 2023-12-19 18:23 UTC
