### ISSUE TITLE
Not able to toggle sortable fields more than twice 

### ISSUE THREAD

**Issue by milewski** [laravel/nova-issues#2510] opened 2020-04-14 11:49 UTC
- Laravel Version: 7
- Nova Version: 3.3.2

Clicking on any sortable field you are only able to toggle it twice, ASC, DESC, and then it is stuck... a third click won't do anything

![image](https://user-images.githubusercontent.com/2874967/79221786-06ec7300-7e89-11ea-9ff2-db24b17f5a5e.png)

**Comment by jbrooksuk** [comment] 2020-04-14 13:05
Duplicate of https://github.com/laravel/nova-issues/issues/2503

**Closed** 2020-04-14 13:12 UTC
