### ISSUE TITLE
Authorization does not apply on custom menu

### ISSUE THREAD

**Issue by oskobri** [laravel/nova-issues#3908] opened 2022-04-08 15:27 UTC
- Laravel Version: 9.7.0
- Nova Version: 4.0.3
- PHP Version: 8.1

### Description:
When Using custom menu (MenuItem or MenuSection), authorization does not apply to Resource. So if user cannot viewAny resources, it's still visible in the menu.

**Comment by nchicas** [comment] 2022-04-08 15:37
I think this is mentioned in the docs, Nova won't use viewAny anymore.

**Comment by nchicas** [comment] 2022-04-08 15:39
From docs:

Nova 4 introduce the following tweaks to authorization order / precedence:

Authorizing if a user can view a resource no longer depends on the viewAny permission.

**Comment by crynobone** [comment] 2022-04-08 15:44
@nchicas that just means viewing a resource detail no longer check for view any policy.

**Comment by crynobone** [comment] 2022-04-08 15:51
Duplicate of https://github.com/laravel/nova-issues/issues/3832

Will look into this once bugs with 4.x drops down.

**Closed** 2022-04-08 15:51 UTC
