### ISSUE TITLE
OS dark mode and Nova light mode visual problem in Index grid content

### ISSUE THREAD

**Issue by wamesro** [laravel/nova-issues#5233] opened 2023-01-13 07:34 UTC
- Laravel Version: 9.47.0
- Nova Version: 4.20.2
- PHP Version: 8.2.0
- Operating System and Version: MacOS 12.6.2
- Browser type and version: Chrome 109.0.5414.87

### Description:
If I have dark mode set in the OS and I set light mode in Laravel Nova, then the Index in the Grid displays dark content. When I switch the OS to Light mode, everything works normally.

![scrnli_13- 1- 2023 8-33-31](https://user-images.githubusercontent.com/5340873/212263415-cc999816-3960-4c06-a001-e5fd83dca264.png)

**Comment by crynobone** [comment] 2023-01-13 07:36
Duplicate of #5230

**Closed** 2023-01-13 07:36 UTC
