### ISSUE TITLE
 hasMany Inline field validation

### ISSUE THREAD

**Issue by abdulSF** [laravel/nova-issues#3451] opened 2021-06-21 12:42 UTC
On the following code. I am using hasMany with inline relation. But when I add validation on fields in "BundlePublications". It is not working.

// Bundle Resource
HasMany::make('Bundle Product', 'BundlePublications',
\App\Nova\BundlePublication::class)
->inline(),

//BundlePublications Resource
Number::make('Quantity', 'qty')->rules('required'),

**Comment by crynobone** [comment] 2021-06-21 12:54
Duplicate of #3443

**Closed** 2021-06-21 12:54 UTC
