### ISSUE TITLE
Search parameter being ignored when running action

### ISSUE THREAD

**Issue by armando-moreira** [laravel/nova-issues#5796] opened 2023-08-10 08:11 UTC
- Laravel Version: 10.13.5
- Nova Version: 4.25.1
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version: MacOS Ventura 13.5
- Browser type and version: Chrome Version 115.0.5790.170 
- Reproduction Repository: https://github.com/tonyputi/example-nova-app

### Description:

The search parameter is being ignored when running an action and selecting all resources on a resource that includes a standalone action. It's visible in the request that the query param is not being included for the search.
When a search is applied and the page is refreshed (note that the search is already applied in the URL) then the search is being included in the next action request (please see videos).
Note: This issue only happens when the resource includes at least one standalone action.

https://github.com/laravel/nova-issues/assets/125274786/7f639aa6-6c9e-49d3-8403-60eeb4b3d855

https://github.com/laravel/nova-issues/assets/125274786/c172c549-5d09-43d5-b548-924afcc8d785

### Detailed steps to reproduce the issue on a fresh Nova installation:
Please use the repo provider to easy reproduce the issue.
To see the issue:
- Create a couple of Posts using factory
- Search e.g. by type
- Select all resources and run the action
- All resources will be updated (including the ones outside the search)

To see the issue not happening after removing standalone action:
- Remove the `UpdateTitleStandAlone::make()` from Post resource in the actions array
- Run the above steps again
- Only the resources within the search will be updated

**Comment by crynobone** [comment] 2023-08-10 08:18
Duplicate of #5759

**Closed by crynobone** 2023-08-10 08:18 UTC

**Comment by filipposallemi** [comment] 2023-08-10 08:19
I have the same issue

**Comment by armando-moreira** [comment] 2023-08-10 08:24
@davidhemphill Why is this being closed? How is it possible that this has been marked as `not planned`?
This Issue is way better explained that the one marked as duplicated.

**Comment by crynobone** [comment] 2023-08-10 08:43
@armando-moreira Because it's a duplicate of #5759 and that issue still opened.

![CleanShot 2023-08-10 at 16 42 58](https://github.com/laravel/nova-issues/assets/172966/9a718d81-bd3f-412d-bf2d-148f25253c01)

**Comment by crynobone** [comment] 2023-09-18 13:46
Bug has been fixed and pending next release.
