### ISSUE TITLE
Laravel Nova + polymorphic Tags: when attaching "no morph map defined"

### ISSUE THREAD

**Issue by wivaku** [laravel/nova-issues#3623] opened 2021-11-06 12:28 UTC
- Laravel Version: 8.69.0
- Nova Version: 3.30.0
- PHP Version: 8.0.12

### Description:

When using `Tag` example (polymorphic many-to-many) and `enforceMorphMap` Laravel does not have an issue but Laravel Nova does (during attach / detach).

### Detailed steps to reproduce the issue on a fresh Nova installation:

See details in [Stackoverflow post](https://stackoverflow.com/questions/69863504/laravel-nova-polymorphic-tags-when-attaching-no-morph-map-defined). 

Related to [this issue](https://github.com/laravel/nova-issues/issues/3547)?
It is unclear what the resolution / workaround is.

**Comment by crynobone** [comment] 2021-11-06 12:33
duplicate of #3547

**Closed by crynobone** 2021-11-06 12:33 UTC

**Comment by wivaku** [comment] 2021-11-06 12:54
So indeed a duplicate. As mentioned, not sure what the resolution / workaround is.

**Comment by wivaku** [comment] 2021-11-07 10:33
Now using `morphMap` instead of `enforceMorphMap` and this works. 
Not sure why the documented one does not work.

**Comment by crynobone** [comment] 2021-11-08 08:38
See https://github.com/laravel/nova-issues/discussions/3626
