### ISSUE TITLE
File/Image field does not use previewUrl on detail and form views

### ISSUE THREAD

**Issue by m2de** [laravel/nova-issues#645] opened 2018-09-22 15:04 UTC
The `Image` field contains methods to generate both a `thumbnailUrl` and a `previewUrl` field. I was expecting the thumbnail to be used on Index views and the preview to be used on Detail and Form views, however the thumbnail url is used in all three views meaning I can't optimise images correctly for each view?

Please let me know if that makes sense or if you need any further details. Thank you.

**Comment by bonzai** [comment] 2018-09-22 15:56
#42

**Comment by m2de** [comment] 2018-09-22 16:52
Apologies, I did search the issues but didn't come across the referenced issue 42. Thanks for linking it @bonzai

**Comment by alexbowers** [comment] 2018-09-24 18:48
Duplicate of #42

**Closed by alexbowers** 2018-09-24 18:48 UTC
