### ISSUE TITLE
MorphTo loses it's selection when validation errors

### ISSUE THREAD

**Issue by robderijk** [laravel/nova-issues#2160] opened 2019-11-18 20:10 UTC
- Laravel Version: v6.5.1
- Nova Version: v2.7.1
- PHP Version: 7.2.0
- Database Driver & Version: Mysql 5.7
- Operating System and Version: MacOS 10.15.1
- Browser type and version: Chrome 78.0.3904.97

### Description:
Same as #1576 but then with the MorphTo field. If there's a validation error somewhere in the form the morphto value is reset.

**Comment by jbrooksuk** [comment] 2019-12-05 10:18
Duplicate of https://github.com/laravel/nova-issues/issues/1898

**Closed by jbrooksuk** 2019-12-05 10:18 UTC
