### ISSUE TITLE
Inconsistent Heading styling

### ISSUE THREAD

**Issue by markwalet** [laravel/nova-issues#1431] opened 2019-03-11 11:30 UTC
- Laravel Version: 5.8
- Nova Version: 2.0

### Description:
The margin/padding of the Heading field is inconsistent on the detail page vs create/edit pages.

Screenshots:

**Edit form**
![image](https://user-images.githubusercontent.com/11446771/54120833-133a0d00-43f9-11e9-9b28-6a9f4d6e285c.png)

**Detail page**
![image](https://user-images.githubusercontent.com/11446771/54120888-3b297080-43f9-11e9-8c4a-8e86011c8b1d.png)

The main problem here is the side margin of the Heading field on the detail page. I think the blue-ish background should stretch all the way. And the text should be in the same indentation as the other fields.

### Steps To Reproduce:

- Fresh install
- Create resource
- Add `Heading` field.

**Comment by dkulyk** [comment] 2019-03-11 11:38
Duplicate of https://github.com/laravel/nova-issues/issues/1337

**Closed by dkulyk** 2019-03-11 11:38 UTC
Labels: duplicate
