### ISSUE TITLE
Wrong singularization/pluralization of labels

### ISSUE THREAD

**Issue by netpok** [laravel/nova-issues#2304] opened 2020-01-26 08:42 UTC
- Laravel Version: 6.12.0
- Nova Version: 2.9.4
- PHP Version: 7.4.1

### Description:
Nova is using `Str::plural` to pluralize the labels. This method is using doctrine/inflector which does not support pluralization of multiple words.

This results in various effects:
 - the `ExampleData` resource will have a label of `Example Datas`
 - the `NaturalPerson` resource will have a label of  `Natural Neoples`

The solution would be to only pluralize the last word.

### Steps To Reproduce:
1. Create a resource named ExampleData or NaturalPerson
2. Check the result:
![image](https://user-images.githubusercontent.com/6945600/73132800-1691b380-4020-11ea-8dd5-28e7f15ee67c.png)

**Comment by davidhemphill** [comment] 2020-01-27 18:26
Duplicate of #2241

**Closed by davidhemphill** 2020-01-27 18:26 UTC
