### ISSUE TITLE
displayUsing() on BelongsTo field to doesn't seem to work with Laravel 5.8.11 and Nova 2.0.1

### ISSUE THREAD

**Issue by mikecornille** [laravel/nova-issues#1511] opened 2019-04-10 13:56 UTC
Its works with 5.8.11 and Nova 2.0.0.   

When I try to use: 
`BelongsTo::make('Location')->displayUsing(function ($location_id) {
            return $location_id['city'];
}),`

...with nova 2.0.1 it doesn't work, 2.0.0 it worked.

**Comment by LorenzoSapora** [comment] 2019-04-24 12:41
I just hit this, after upgrading. Very odd, considering 2.0.1 is only a minor bug fix, and from the changelog doesn't touch belongsto.

**Comment by jbrooksuk** [comment] 2019-08-07 10:44
Confirmed in v2.0.9. This is because the `resolveForDisplay` method is overwritten to do nothing. I don't know why this is the case though.

**Comment by kgp43** [comment] 2019-09-14 20:29
What is the status on this? It's still an issue.

**Comment by jbrooksuk** [comment] 2019-09-24 15:06
The PR hasn't yet been merged. There's an outstanding query.

**Closed** 2019-10-15 19:31 UTC
Labels: bug, pending
