### ISSUE TITLE
[BUG] ResourceCountController should respect database connection

### ISSUE THREAD

**Issue by bastien-phi** [laravel/nova-issues#1272] opened 2019-01-24 11:08 UTC
- Laravel Version: 5.7.22
- Nova Version: 1.3.1
- PHP Version: 7.2
- Operating System and Version: Ubuntu 18.04

### Description:
The request `/nova-api/{resource}/count` fails when the resource refers to a model stored in non-default database.
The result is `Illuminate\Database\QueryException` with message `SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "users" does not exist`

### Steps To Reproduce:

Create a model User with a connection which is not the default one.
```php
class User extends Model {
  protected $connection = 'not-default';
}
```
Create the Nova resource associated with this model.
```php
class UserResource extends Resource {
  public static $model = \App\User::class;

  public function fields(Request $request)
  {
    return [ID::make()];
  }
}
```
Browse http://app.test/nova/resources/users. The exception is shown in toast message.

I fixed it localy, I would be glad to share if needed.

**Comment by bonzai** [comment] 2019-01-24 11:21
Duplicate of #1258

**Closed by bonzai** 2019-01-24 11:21 UTC
