### ISSUE TITLE
CodeMirror integration only shows to line 11 until clicked

### ISSUE THREAD

**Issue by ralphschindler** [laravel/nova-issues#1197] opened 2019-01-04 19:36 UTC
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.2.13

### Description:

On detail pages, when using `Code` fields, for large code blocks it only shows to line 11. That field then requires to be clicked into to show the remaining part of the value.

A solution is documented on the CodeMirror issue tracker:
https://github.com/codemirror/CodeMirror/issues/2469
(there are also links to others having the issue in other projects)

In JS, it seems like an `editor.refresh()` may fix the issue.

### Steps To Reproduce:

Add a `Code` field that has a large HTML value. Go to detail page.

**Comment by bonzai** [comment] 2019-01-04 19:56
Duplicate of #1160

**Closed by bonzai** 2019-01-04 19:56 UTC
