### ISSUE TITLE
Metrics $refreshWhenFiltersChange not working on lenses

### ISSUE THREAD

**Issue by tonyputi** [laravel/nova-issues#5185] opened 2022-12-27 13:51 UTC
- Laravel Version: 9.45.1
- Nova Version: 4.19.5
- PHP Version: 8.1.13
- Database Driver & Version: MySQL 8.0 / MariaDB 10.0
- Operating System and Version: Ventura 13.1
- Browser type and version: Chrome 108.0.5359.124
- Reproduction Repository: https://github.com/###/###

### Description:
Metrics are not reacting on $refreshWhenFiltersChange when defined on metrics:

### Detailed steps to reproduce the issue on a fresh Nova installation:
The problem is related to the `LensMetricRequest` specifically on the `availableMetrics` that is not implementing the `setAvailableFilters` call.

With the following implementation everything looks working as expected:
```
    /**
     * Get all of the possible metrics for the request.
     *
     * @return \Illuminate\Support\Collection
     */
    public function availableMetrics()
    {
        $lens = $this->lens();

        return $lens->availableCards($this)
            ->whereInstanceOf(Metric::class)
            ->map(function ($metric) use ($lens) {
                /** @var \Laravel\Nova\Metrics\Metric $metric */
                if ($metric->refreshWhenFiltersChange === true) {
                    $request = LensRequest::createFromBase($this);

                    return $metric->setAvailableFilters($lens->availableFilters($request));
                }

                return $metric;
            });
    }
```

I know this is not a bug but since the metrics are reacting on filter change for resources I don't see the point why should not work on lenses as well

**Comment by crynobone** [comment] 2022-12-27 14:17
Duplicate of https://github.com/laravel/nova-issues/discussions/5133#discussioncomment-4279148

**Closed by crynobone** 2022-12-27 14:17 UTC
