### ISSUE TITLE
Can't create a new Tool

### ISSUE THREAD

**Issue by falko100** [laravel/nova-issues#4595] opened 2022-07-19 08:34 UTC
- Laravel Version: 9.20.0
- Nova Version: 4.12.6
- PHP Version: 8.1.7
- Database Driver & Version: Mysql 8
- Operating System and Version: MacOS
- Browser type and version: Chrome 103.0.5060.114
- Reproduction Repository: None yet.

### Description:
I try to create a new Tool: `php artisan nova:tool coddin/test-tool`.
I say yes to everything;

```
ERROR in ./resources/js/pages/Tool.vue
Module build failed (from ./node_modules/vue-loader/dist/index.js):
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.loader (/Users/falkowoudstra/PhpstormProjects/project-name/nova-components/TestTool/node_modules/vue-loader/dist/index.js:70:34)

webpack compiled with 1 error
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
It does work on a clean installation, but I can't figure this out.

**Comment by crynobone** [comment] 2022-07-19 10:32
Duplicate of https://github.com/laravel/nova-issues/discussions/4549

**Closed by crynobone** 2022-07-19 10:32 UTC
