### ISSUE TITLE
Relatable queries are not applied on field filters (filterable)

### ISSUE THREAD

**Issue by piljac1** [laravel/nova-issues#5645] opened 2023-06-26 19:12 UTC
- Laravel Version: 9.42.0
- Nova Version: 4.21.0
- PHP Version: 8.1.20
- Database Driver & Version: MySQL 8.0.33
- Operating System and Version: macOS Monterey 12.6.1
- Browser type and version: Chrome 114.0.5735.133
- Reproduction Repository: To be provided if necessary

### Description:

Relatable queries don't seem to be applied on filters generated by the `filterable()` method on a field.

### Detailed steps to reproduce the issue on a fresh Nova installation:

I have a `Product` resource with the following relatable query (which works on forms) : 

```php
public static function relatableUsers(NovaRequest $request, $query, $field)
{
    if ($field->attribute === 'auditor') {
        return $query->whereIn('role', [Role::SuperAdmin, Role::Admin, Role::Auditor]);
    }

    return $query;
}
```

And the following field : 

```php
BelongsTo::make(__('Auditor'), 'auditor', User::class)
    ->filterable()
    ->nullable()
    ->showOnPreview()
```

Only super-admins, admins and auditors are shown in the form select, but ALL users are shown in the related filter select.

**Comment by crynobone** [comment] 2023-06-27 01:35
Duplicate of #5097

**Closed by crynobone** 2023-06-27 01:35 UTC
