### ISSUE TITLE
deletable(false) on Image filed update

### ISSUE THREAD

**Issue by rikless** [laravel/nova-issues#2524] opened 2020-04-17 08:34 UTC
- Laravel Version: 7.5
- Nova Version: v3.4.0 
- PHP Version: 7.4

### Description:

On Image filed, when using` ->deletable(false)`, the image can't be updated (button is not available anymore)

```php
Image::make('Image', 'img')->disk(config('settings.disk_name'))
                        ->disableDownload()->hideFromIndex()->deletable(false)
                        ->maxWidth(200)
                        ->rules('image', 'mimes:jpg,jpeg,png', 'between:1,50240'),
```

**Comment by dkulyk** [comment] 2020-04-17 10:37
Maybe related to https://github.com/laravel/nova-issues/issues/2521

**Comment by rikless** [comment] 2020-04-17 12:49
Oh yes, maybe. In your case, do you have it on `update` page ?

**Comment by davidhemphill** [comment] 2020-04-17 19:24
Duplicate of https://github.com/laravel/nova-issues/issues/2521

**Closed by davidhemphill** 2020-04-17 19:24 UTC
