### ISSUE TITLE
Trix Field not looking good in dark mode.

### ISSUE THREAD

**Issue by xiCO2k** [laravel/nova-issues#4913] opened 2022-10-13 15:43 UTC
Found out this issue on a resource form.

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/823088/195643033-98048c67-d01c-4df6-9c1b-059f020d2502.png">

Thanks,
Francisco

**Comment by crynobone** [comment] 2022-10-13 22:48
Duplicate of https://github.com/laravel/nova-issues/discussions/3955

**Closed by crynobone** 2022-10-13 22:48 UTC
