### ISSUE TITLE
Getting resource id when loading resource details, to customize the options from filter menu.

### ISSUE THREAD

**Issue by frital** [laravel/nova-issues#2005] opened 2019-10-04 02:56 UTC
When i load a detail page from one resource, i need to customize the options in the menu from the filter.
Example: in an user details page, i have a hasMany Role field, that listed the Roles from the user. How i can customize the menu, so that only appears only the Roles that the user have?
In the Filter class, the request object injected by the "option" method don't have the resource id. (user id in this example)

I know that in "indexQuery" method, on Resource abstract class, the "NovaRequest" object have the id (accessible by `$request->get('viaResourceId')`). But how can i access this value in the "option" method in the filter class?

Resource class:

```php
public static function indexQuery(NovaRequest $request, $query)
{
    if ($request->has('viaResourceId') && !empty($request->get('viaResourceId')))
        $resource_id = $request->get('viaResourceId'); // here i know the id

    return $query;
}
```

Filter class:

```php
public function options(Request $request)
{
    // i need to know the resource id here, customize the options

    return Role::all()->pluck('id', 'title')->toArray();
}
```

I read in issue  [#1650](https://github.com/laravel/nova-issues/issues/1650) that @davidhemphill mentioned that where possible, but how? (and the issue are closed).

Thanks a lot for the help.

**Comment by jbrooksuk** [comment] 2019-10-10 11:32
is this a duplicate of https://github.com/laravel/nova-issues/issues/1910?

**Comment by bredmor** [comment] 2019-10-11 14:11
> is this a duplicate of #1910?

No, @frital is discussing [filters](https://nova.laravel.com/docs/2.0/filters/), which are loaded with a separate request that does not receive any parameters like resource IDs.

I am also looking for a way to do this.

**Comment by jbrooksuk** [comment] 2019-12-04 15:55
Just noticed that this is a duplicate of https://github.com/laravel/nova-issues/issues/1964

**Closed by jbrooksuk** 2019-12-04 15:55 UTC
