### ISSUE TITLE
Frontend UTF-8 Encoding Doesn't Work

### ISSUE THREAD

**Issue by LoopForYou** [laravel/nova-issues#1100] opened 2018-12-06 03:13 UTC
- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version: 7.2.10

### Description:
Characters such as **&** show as **`&amp;`**

![utf-8 bug](https://user-images.githubusercontent.com/34870243/49558751-31fca500-f8da-11e8-9e15-55d17f1d1ed2.png)

I have verified `<meta charset="utf-8"> ` is indeed on the page source
![utf-8 meta](https://user-images.githubusercontent.com/34870243/49558835-79833100-f8da-11e8-8bba-6885c9d83e63.png)

### Steps To Reproduce:
1. Fresh install of Larval Nova on Laravel 5.7.15
2. Create a resource via CLI command with `php artisan nova:resource Post`
3. On the Post resource try to add an entry
4. Button next to '**Create Post**' button you will see invalid button named '**Create &amp; Add Another'**

**Comment by dkulyk** [comment] 2018-12-06 09:05
Duplicate of #961

**Comment by dillingham** [comment] 2018-12-06 11:56
Not a duplicate if they are closed?

**Comment by dkulyk** [comment] 2018-12-06 16:36
It was fixed in v1.1.8.

**Comment by LoopForYou** [comment] 2018-12-06 16:43
Okay fine. I just did a fresh install and it works. That is weird. I guess ill have to figure it out then. Thanks

**Closed** 2018-12-06 17:42 UTC
