### ISSUE TITLE
Using the "showCreateRelationButton" button overrides relationship selection options

### ISSUE THREAD

**Issue by Jigsaw5279** [laravel/nova-issues#4250] opened 2022-05-15 19:29 UTC
**Steps to reproduce:**

- Create two Models with a `belongsTo` relationship (e.g. User belongsTo Team)
- Setup the relationship in Nova using the `showCreateRelationButton`
- Use the Nova UI to create a new instance of the dependant Model (User)
- Use the `+` to create a new dependable Model (Team)

**Expected Behavior:**

The dropdown now also shows the newly created record, along with all previously existing ones.

**Actual Behavior:**

The dropdown now only contains the newly created record

**Comment by crynobone** [comment] 2022-05-15 22:24
Duplicate of #3472

**Closed by crynobone** 2022-05-15 22:24 UTC
