### ISSUE TITLE
Action model filtering

### ISSUE THREAD

**Issue by wfeller** [laravel/nova-issues#129] opened 2018-08-24 12:36 UTC
I want to make an action that just starts a download for selected resources (I'm creating a zip file containing the data for all the selected resources).

The problem is that the models that I select get filtered and none are left, even when I use the canRun() method and return true all the time.

I think the problem comes from the ActionModelCollection->filterByResourceAuthorization method that requires that the user is allowed to update the resource before running the action, which I don't require (or delete the resource for Destructive Actions).

Would it be possible to remove this automatic filtering or make it optional? Especially since it's possible to add a canRun callback for customized filtering.

![image](https://user-images.githubusercontent.com/21337627/44584893-bd7a7c00-a7aa-11e8-9fda-d1327da6d156.png)

**Comment by GuidoHendriks** [comment] 2018-08-24 12:50
Duplicate of https://github.com/laravel/nova-issues/issues/114?

**Comment by davidhemphill** [comment] 2018-10-07 17:17
Duplicate of #114

**Closed by davidhemphill** 2018-10-07 17:17 UTC
