### ISSUE TITLE
Font with Cyrillic symbols

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#1652] opened 2019-06-05 07:37 UTC
Curently https://fonts.googleapis.com/css?family=Nunito don't support Cyrillic symbols.

Some other not very nice and very extra bold (for links) font is used instead for Cyrillic.
![image](https://user-images.githubusercontent.com/38257723/58938505-a1fec180-877d-11e9-91ba-bbe3e574b5aa.png)

![image](https://user-images.githubusercontent.com/38257723/58938537-b80c8200-877d-11e9-8174-8405af9df774.png)

Here is your favorite font with Cyrillic support: https://github.com/alexeiva/NunitoFont/releases/tag/v3.500

**Comment by 4n70w4** [comment] 2019-06-14 08:55
Workaround:

1) Download https://github.com/alexeiva/NunitoFont/releases/download/v3.500/Nunito.zip
2) Extract to public/fonts/Nunito
3) Save https://gist.github.com/4n70w4/8ef4d3247797c36b8f0a0f99d3c464b5 as public/css/nunito-cyrillic-fix.css
4) Add `Nova::style('nova-style', public_path('css/nunito-cyrillic-fix.css'));` to `\App\Providers\NovaServiceProvider::boot()`

Result:

![image](https://user-images.githubusercontent.com/38257723/59496949-2c8ca280-8e9b-11e9-81e5-9eb5f006c596.png)
![image](https://user-images.githubusercontent.com/38257723/59496970-37dfce00-8e9b-11e9-85d2-8d1374c41d10.png)

**Comment by jbrooksuk** [comment] 2019-07-31 14:58
Confirmed that Nunito doesn't support Cyrillic symbols. It looks like the text is falling through the font stack. I'm guessing you're on Windows?

**Comment by ihorvorotnov** [comment] 2019-07-31 19:12
Nunito version used in Nova (and probably Telescope) does not support Cyrillic. Personally, I'm redefining the font globally to "system" font stack.

**Comment by jbrooksuk** [comment] 2019-08-01 08:12
Nova does list `system` in its font stack, so really it's done the right thing here. 

I'm going to close the issue, as I believe we're doing the right thing here, but pinging @davidhemphill just in case.

**Comment by ihorvorotnov** [comment] 2019-08-01 10:21
It does, but Nunito comes first and it is linked from Google Fonts without Cyrillic subset. Thus, if you just clean install Nova and change locale to (e.g.) Russian, all Cyrillic strings **look different** from Latin. Latin are in Nunito, Cyrillic - the first from system stack. That's the behavior you describe as "doing right thing" and in reality it's something that isn't right. What I am doing is removing Nunito support completely, so all strings are rendered with the same (system) font which has full support of non-Latin characters. This way entire UI is consistent.

**Comment by jbrooksuk** [comment] 2019-08-01 11:11
I think one thing we could do is replace Nunito with [Nunito Sans](https://fonts.google.com/specimen/Nunito+Sans), which I believe does support Cyrillic. This change wouldn't affect the look of Nova either.

**Comment by ihorvorotnov** [comment] 2019-08-01 11:39
It looks like Google's version still does not have Cyrillic support for Nunito Sans either. This is a standard issue with Google Fonts, they don't update them regularly, happened to me many times with many fonts (I usually end up finding latest versions of the fonts from their original authors and serving them myself):

![Screen Shot 2019-08-01 at 14 37 14](https://user-images.githubusercontent.com/1066083/62290483-231ac200-b46a-11e9-8b7b-0576b2f6221d.jpg)

**Comment by jbrooksuk** [comment] 2019-08-05 15:32
I've opened an issue at https://github.com/google/fonts/issues/2102 to see if they'll update the font. If you could give it a 👍 that'd be great.

For now, I'd suggest creating a custom theme with a different font.

**Comment by 4n70w4** [comment] 2019-08-05 16:11
@jbrooksuk https://github.com/googlefonts/nunito/pull/16

**Comment by jbrooksuk** [comment] 2019-08-07 08:21
Google Fonts have [replied to a tweet](https://twitter.com/googlefonts/status/1158855710094049285) I sent them asking when Nunito will be updated. The reason that it's not been updating is that there are hinting issues which have blocked the release.

I've asked them if they have an ETA for when the issues will be resolved.

**Comment by Lednerb** [comment] 2019-09-21 08:05
Also linking my [response here from #1993](https://github.com/laravel/nova-issues/issues/1933#issuecomment-533777764):

Please include the fonts locally, so they will be shipped with nova and don't require connections to google servers. That's not a best practice for a admin dashboard.

**Comment by jbrooksuk** [comment] 2019-10-03 14:42
I've asked for an update on this.

**Comment by ihorvorotnov** [comment] 2019-10-05 14:23
@jbrooksuk Thanks for the update. Good to know you're keeping an eye on this.

**Comment by jbrooksuk** [comment] 2019-10-30 08:47
I've asked to see if there is anything we can do to help.

**Comment by jbrooksuk** [comment] 2019-11-15 09:00
Nunito now supports Cyrillic over google fonts. Can you please try again?

**Closed** 2019-11-15 09:03 UTC
Labels: bug
