### ISSUE TITLE
Uncaught ReferenceError: CreateNova is not defined

### ISSUE THREAD

**Issue by frddl** [laravel/nova-issues#3174] opened 2021-01-16 18:19 UTC
- Laravel Version: 8.21.0
- Nova Version: 3.18.0
- PHP Version: 7.3

![image](https://user-images.githubusercontent.com/16150999/104819625-27968e80-5848-11eb-98b0-7a711ec0c1bb.png)

### Description:
I get this right at /admin route, which is my nova path.
Tried to `npm install` and `npm run dev` inside nova folder, then deleting `public/vendor/nova` and publishing nova assets once again. Didn't help.

**Comment by crynobone** [comment] 2021-01-17 02:32
Can you provide a reproducing step? Because the default installation process should just be `php artisan nova:publish`.

**Comment by frddl** [comment] 2021-01-17 12:04
> Can you provide a reproducing step? Because the default installation process should just be `php artisan nova:publish`.

Unfortunately I cannot, because this was after I mirgated the project from my local machine to the server. Issue disappeared after reinstalling nova.

**Comment by crynobone** [comment] 2021-01-18 00:18
Closing this for now as not reproducible (it could been just a bad deployment). However feel free to recreate a new issue if anyone can come out with more details.

**Closed by crynobone** 2021-01-18 00:18 UTC
Labels: needs more info

**Comment by ugurdnlr** [comment] 2023-11-29 11:27
is there any update ?

**Comment by ahmed-tahoon** [comment] 2023-12-11 10:38
any update


> is there any update ?

**Comment by muhzak** [comment] 2024-01-15 22:05
Also awaiting update.
