### ISSUE TITLE
"Update Resource" results in 404 when the name of PK is not "id"

### ISSUE THREAD

**Issue by luost26** [laravel/nova-issues#1227] opened 2019-01-13 06:40 UTC
- Laravel Version: 5.7.20
- Nova Version: 1.3.0
- PHP Version: 7.1.3

### Description:
If the name of a resource's primary key is not "id" ("user_id", "student_id", "identifier" for example), updating the resource will result in 404. 
<img width="1098" alt="wx20190113-143430 2x" src="https://user-images.githubusercontent.com/45375360/51082362-79c7e500-1740-11e9-8fec-64bb64ba0715.png">

If I rename the primary key column to "id", the problem disappears.

**Comment by luost26** [comment] 2019-01-13 11:17
The problem can be settled by adding following code to the model class

```php
    protected $appends = ['id'];

    public function getIdAttribute()
    {
        return $this->{$this->primaryKey};
    }
```

**Comment by rovansteen** [comment] 2019-01-13 11:31
Did you define the key attribute properly on your model?

**Comment by dkulyk** [comment] 2019-01-13 15:21
Duplicate of https://github.com/laravel/nova-issues/issues/1124

**Closed** 2019-01-15 17:34 UTC
