### ISSUE TITLE
Declaration of indexQuery Builder causes runtime error

### ISSUE THREAD

**Issue by CitizenBeta** [laravel/nova-issues#2961] opened 2020-10-12 20:12 UTC
- Laravel Version: 8.9.0
- Nova Version: 3.12.1
- PHP Version: 7.4

### Description:
Adding "Builder $query" to make declaration causes an error.

### Detailed steps to reproduce the issue on a fresh Nova installation:

See screenshot.
![Screenshot from 2020-10-12 16-08-21](https://user-images.githubusercontent.com/595049/95786512-b756fa80-0ca5-11eb-94a9-9b0037881220.png)

**Comment by crynobone** [comment] 2020-10-12 23:59
You should import the class.

```php
use Illuminate\Database\Eloquent\Builder;
```

**Comment by CitizenBeta** [comment] 2020-10-13 00:31
![Screenshot from 2020-10-12 20-31-13](https://user-images.githubusercontent.com/595049/95801914-e7b09000-0cc9-11eb-80f1-dccf667974a8.png)

**Comment by crynobone** [comment] 2020-10-13 00:44
@CitizenBeta my suggestion should be done on `app/Nova/User.php` and not `app/Models/User.php`.

**Comment by CitizenBeta** [comment] 2020-10-13 00:56
@crynobone it's in the nova resource as well. It looks like for some reason it is detecting it as inconsistent with the parent function. Which is strange because the base function has it:

`trait PerformsQueries
{
    /**
     * Build an "index" query for the given resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  string  $search
     * @param  array  $filters
     * @param  array  $orderings
     * @param  string  $withTrashed
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public static function buildIndexQuery(NovaRequest $request, $query, $search = null,
                                      array $filters = [], array $orderings = [],
                                      $withTrashed = TrashedStatus::DEFAULT)
    {
        return static::applyOrderings(static::applyFilters(
            $request, static::initializeQuery($request, $query, $search, $withTrashed), $filters
        ), $orderings)->tap(function ($query) use ($request) {
            static::indexQuery($request, $query->with(static::$with));
        });
    }`

**Comment by crynobone** [comment] 2020-10-13 00:59
Please provide full reproducing code to prove your issue, I can't reproduce it based on my use case.

**Comment by CitizenBeta** [comment] 2020-10-13 01:03
```
use Illuminate\Database\Eloquent\Builder;
use App\Nova\Resource;

class Competition extends Resource
{

/**
     * Build an "index" query for the given resource.
     *
     * @param NovaRequest $request
     * @param Builder $query
     * @return Builder
     */
    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query;
    }
```

**Comment by crynobone** [comment] 2020-10-13 01:19
Sorry @CitizenBeta 

Finally understood the issue, it's a PHP errors and can't be fixed without causing major breaking changes to all Nova customers. 

You have to deal with PHPStorm suggesting to add typehint when it shouldn't need to do so at the moment.

**Closed by crynobone** 2020-10-13 01:19 UTC
Labels: needs more info

**Comment by CitizenBeta** [comment] 2020-10-13 14:25
`Finally understood the issue, it's a PHP errors and can't be fixed without causing major breaking changes (since we need to still support PHP 7.2 and 7.3).`

What does that mean? What's the change that would be necessary?
