### ISSUE TITLE
Date field does not save

### ISSUE THREAD

**Issue by alexinside** [laravel/nova-issues#2863] opened 2020-09-14 09:44 UTC
app/Client.php:
`    protected $guarded = [];
    protected $casts = [
        'birthday' => 'date', // needed for Nova
    ];`

app/Nova/Client.php
`            Date::make('Birthday')
                ->rules( 'max:254', 'required')->hideFromIndex(),`

in migration:
`            $table->date('birthday')->nullable();
`

BUG:
Whenever I submit — if the client already has birthday in DB — the birthday is reverted. 
Whenever I submit — if the client already has null birthday in DB — error in form: «The Birthday field is required.»

Other fields work OK.

**Comment by maxddev** [comment] 2020-09-14 10:05
https://github.com/laravel/nova-issues/issues/2853

**Comment by davidhemphill** [comment] 2020-09-16 14:50
Duplicate of #2853

**Closed by davidhemphill** 2020-09-16 14:50 UTC
