### ISSUE TITLE
DateTime Picker date Format is wrong

### ISSUE THREAD

**Issue by Elshaden** [laravel/nova-issues#4670] opened 2022-08-07 07:47 UTC
- Laravel Version: 9.#.#
- Nova Version: 4.12.14
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: chrome
- Reproduction Repository: https://github.com/###/###

### Description:
I am as probably all non Americans, frustrated with  the Time Picker, date format. it is M/D/YYYY, this format is only used in one country in the whole world, USA. the rest of us use D/M/YYYY.

So is there a simple out of the box way to tell Nova Time Picker that I am not American. and please show my date as it should for the rest of the world.

**Comment by crynobone** [comment] 2022-08-07 11:53
Duplicate of #4665, has been fixed but pending next release.

**Closed by crynobone** 2022-08-07 11:53 UTC
