### ISSUE TITLE
Slow loading time for styles and javascript

### ISSUE THREAD

**Issue by genesiscz** [laravel/nova-issues#2599] opened 2020-05-11 19:14 UTC
- Nova Version: 6.1.0
- PHP Version: 7.4.0
- Database Driver & Version: MySQL
- Operating System and Version: Debian 8
- Browser type and version: Chrome 

So I was digging more because I felt the whole Nova is loading slow. That could be a combination of a lot of requests that need to be booted, Debugbar, Telescope (which I disabled for nova paths but still), maybe some leaks I need to address. But what makes no sense for me is the way Nova loads custom Javascript and CSS, even framework/Nova related.

First of all I tried to start caching these with CacheControl as provided in this issue: https://github.com/laravel/nova-issues/issues/2117

That kinda worked and made the third and futher loading times much faster. To test it, i disabled debugbar and telescope. Maybe it gets booted up, but it's disabled. 
Without cache its 9s as Finish, DomContentLoaded 4.06. Quite terrible. 
With cache its 7.8s, 1.73. Not great not terrible.
![image](https://user-images.githubusercontent.com/1512353/81601974-17323800-93cc-11ea-8fb2-260f77177ca8.png)

But I wanted to get rid of the framework booting with every request to styles or javascript (why is it even needed anyway?) and I tried replacing Nova.php's availableStyles & availableScripts to try how fast would it be if I just copy the css, js in one go to public directory and just point to them directly.

    public static function availableStyles(Request $request)
    {
        @mkdir(public_path("css/nova"));
        foreach(static::$styles as $name => $path) {
            $script = file_get_contents($path);
            if (!$script) {
                die($path." with name".$name);
            }
            $script = file_put_contents(public_path("css/nova/".$name.".css"), $script);

        }
        return static::$styles;
    }
    public static function availableScripts(Request $request)
    {
 
        foreach(static::$scripts as $name => $path) {
            $script = file_get_contents($path);
            if (!$script) {
                die($path." with name".$name);
            }
            $script = file_put_contents(public_path("js/nova/".$name.".js"), $script);

        }
        return static::$scripts;
    }

nova/resources/views/layout.blade.php was then changed as following:

```diff
-<script src="/nova-api/scripts/{{ $name }}"></script>
+<script src="{{url("js/nova/$name.js")}}"></script>

-<link rel="stylesheet" href="/nova-api/styles/{{ $name }}">
+<link rel="stylesheet" href="css/nova/{{ $name }}.css">

```

With this approach, it takes 7.6s to finish and 1.47 for DomLoad. That's not a such speed up but definitelly helps for a smoother feel, even thought it's copying the files with every request.
![image](https://user-images.githubusercontent.com/1512353/81602280-958eda00-93cc-11ea-81be-12a21007147b.png)

I know that the copying approach is not ideal, but it makes a point. It's quite easy to change the current approach to just collect the list of resources, cache their js/css and if filemtime changes, you can copy them again. 

What do you think?

**Comment by genesiscz** [comment] 2020-05-11 19:19
On a side note, is there a way to speed up the app as a whole? It is painfully slow to load all the components: 
![image](https://user-images.githubusercontent.com/1512353/81602501-06ce8d00-93cd-11ea-9428-976dd78e74da.png)

```
APP_DEBUG=false
TELESCOPE_ENABLED=false
DEBUGBAR_ENABLED=false
```

**Comment by izi-dev** [comment] 2020-05-25 19:42
@genesiscz  The same happens to me, this works for me
https://github.com/laravel/nova-issues/issues/1146

**Comment by genesiscz** [comment] 2020-05-28 19:11
Nice! This should be an official way tho

**Comment by jbrooksuk** [comment] 2020-07-20 12:48
Appears to be a duplicate of #1146?

**Closed by jbrooksuk** 2020-07-20 12:48 UTC

**Comment by genesiscz** [comment] 2020-07-21 02:03
> Appears to be a duplicate of #1146?

Yes, but it was not resolved and I wanted to propose how it could work better than it currently is. It is handled better, but definitely not perfectly. It still hits the points, makes the queries, and takes long to load.

**Comment by monaye** [comment] 2022-06-07 05:27
I am having the same issue. I think third-party assets should be publishable just like the Nova assets so they can serve static assets without hitting a Laravel app.
