### ISSUE TITLE
Sorting on specific attribute names not working

### ISSUE THREAD

**Issue by franzdumfart** [laravel/nova-issues#133] opened 2018-08-24 13:37 UTC
Seems like sorting isn't possible on specific attribute names. In my case: `key` and `value`.

```
Text::make('key')->sortable(),
Text::make('value')->sortable(),
```

Sorting buttons are missing:
![screen shot 2018-08-24 at 15 33 20](https://user-images.githubusercontent.com/1145410/44587500-69c06080-a7b3-11e8-8f5d-46686897ea6f.png)
Other field names are working without a problem.

**Comment by v1nk0** [comment] 2018-08-24 19:10
I have the same problem with fields named `end` and `date`.

**Comment by sleicester** [comment] 2018-08-27 19:15
I also experienced the same issue with `date`

**Comment by caseysprague** [comment] 2018-08-27 22:07
I'm seeing the same issue with `end`.

**Comment by mizmiz** [comment] 2018-08-29 20:19
Same for `sort` on Nova 1.0.8.

The problem is in `nova/src/Fields/Field.php` on Line 435.  Turns out `is_callable('sort')` returns `true`.

Possible solution: 
```
public function computed()
{
    return (is_callable($this->attribute) && !is_string($this->attribute)) ||
           $this->attribute == 'ComputedField';
}
```

**Comment by manelgavalda** [comment] 2018-09-06 15:01
Same for `url` on Nova 1.0.12

**Comment by mizmiz** [comment] 2018-09-06 15:09
@taylorotwell Hey Taylor, please include the fix in the next release.

**Comment by joselara** [comment] 2018-09-17 16:52
Same issue with the column name "value".

**Comment by davidhemphill** [comment] 2018-09-17 17:54
This has been fixed and will be included in an upcoming release.

**Closed by davidhemphill** 2018-09-17 17:54 UTC
