### ISSUE TITLE
Modal's fields not displayed as full width when "fullWidth" and "Stacked" layouts are enabled

### ISSUE THREAD

**Issue by mikkellindblom** [laravel/nova-issues#5124] opened 2022-11-28 13:29 UTC
- Laravel Version: 9.41.0
- Nova Version: 4.19.3
- PHP Version: 8.0.2

### Description:
When using ``->stacked()->fullWidth()`` fields are not forced to fill the width of the container, as the field container has class ```md:w-4/5```.

<img width="719" alt="Screenshot 2022-11-28 at 14 28 24" src="https://user-images.githubusercontent.com/5261690/204289472-5794931c-f586-4209-ae4c-7138ffb8d8a7.png">

**Comment by crynobone** [comment] 2022-11-29 00:14
This is a tricky issue to crack, all the components rely heavily on Tailwind Responsive API, and it is currently not working since the "container" is still the whole screen. Duplicate of #4916

**Comment by caseydwyer** [comment] 2023-02-06 09:58
+1, and a small note to clarify on the title, here...I don't think this is limited to modals. Eg, on the edit page of a resource where both `stacked()` and `fullWidth()` have been applied, that same `md:w-4/5` is still showing up and overriding the `w-full`.

**Closed** 2023-08-05 00:55 UTC
Labels: bug
