### ISSUE TITLE
Attachment on BelongsToMany relationship are not using relationship's defined foreign keys

### ISSUE THREAD

**Issue by ilyasfoo** [laravel/nova-issues#336] opened 2018-08-30 03:22 UTC
Version: v1.0.8

**Model:**

```php
class User extends Model
{
    public function industries()
    {
        return $this->belongsToMany(
            'App\Industry',  // Related
            'user_industry', // Pivot table
            'user_id',       // Foreign pivot key
            'focus_code',    // Related pivot key
            'user_id',       // Parent key
            'focus_code'     // Related key
        );
    }
}
```

**Resource:**
```php
class User extends Resource
{
    public static $model = 'App\\User';
    public function fields(Request $request)
    {
        return [
            BelongsToMany::make('Industries', 'industries'),
        ];
    }
}
```

Attaching with the usual eloquent query uses defined keys as expected:
`App\User::find(1)->industries()->attach(App\Industry::find(1))`

![image](https://user-images.githubusercontent.com/3747241/44827581-47609400-ac46-11e8-801b-98b8a4a5349b.png)

Attaching through nova **does not** use the defined keys:

![image](https://user-images.githubusercontent.com/3747241/44827775-3c5a3380-ac47-11e8-9130-5db75890b7a1.png)

**Comment by ilyasfoo** [comment] 2018-08-30 06:04
Probably related to #109

**Comment by DrLongGhost** [comment] 2018-09-02 19:13
I'm struggling with this issue as well. I have similar code to @ilyasfoo. The code and belongsToMany relationship works when viewing the data. (With the caveat that I needed to use the workaround noted in #189 to support primaryKeys other than "id").

When I try to create a new Resource and include BelongsTo::make('DeviceLocation', 'devicelocation') in my fields() it correctly creates a select box that has the list of available choices via my non-standardly named join table. But as soon as I click Create it throws the following error:

```
{
    "message": "Method Illuminate\\Database\\Query\\Builder::getForeignKey does not exist.",
    "exception": "BadMethodCallException",
    "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
    "line": 2816,
    "trace": [
        {
            "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
            "line": 1286,
            "function": "__call",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
```

If I may vent for a moment, it seems like there are a lot of bugs in Nova at the moment around not supporting database schemas that deviate from the conventions that Nova assumes to be in place, even though everything is done correctly in Eloquent. This makes it extremely difficult to use at the moment and I have a bit of buyer's remorse due to Nova perhaps being unusable in its current state.

If anyone has a workaround for this, similar to the workaround @loren138 posted for #189 or an ETA on a fix, it would be much appreciated.

**Comment by turzaizsolt** [comment] 2018-11-01 11:09
I'm also struggling with this issue as well. Anyone has a workaround for this?

**Comment by internetztube** [comment] 2018-11-03 17:15
Same problem here.

**Comment by omarfathy13** [comment] 2018-11-09 15:04
+1

**Comment by davidhemphill** [comment] 2018-11-29 21:09
Duplicate of #109

**Closed by davidhemphill** 2018-11-29 21:09 UTC
