### ISSUE TITLE
Filters showing false positives due to resource_page not resetting in the querystring

### ISSUE THREAD

**Issue by latwelve** [laravel/nova-issues#3519] opened 2021-08-20 13:35 UTC
- Laravel Version: 8x
- Nova Version: 3x
- PHP Version: 8x

### Description:
There is a bug if you create a filter to apply different scopes for example:

```
    public function apply(Request $request, $query, $value)
    {
        if( $value == BookingStatus::ACTIVE) {
            return $query->statusActive();
        }
        if( $value == BookingStatus::CANCELLED) {
            return $query->statusCancelled();
        }
...

```

### Detailed steps to reproduce the issue on a fresh Nova installation:
Populate a DB with 500 resources with a status of active and 10 with a status of cancelled
Create a filter for 2 scopes or any other query to define 2 different result lists.

If I browse the unfiltered results and get to page 10 lets say and then filter by "cancelled" it will show no results because cancelled only has 1 page of results and the resource_page querystring is still showing page10.. removing this or resetting it to =1 shows the intended functionality.

**Comment by crynobone** [comment] 2021-08-20 16:29
Duplicate of #2734

**Closed by crynobone** 2021-08-20 16:29 UTC
