### ISSUE TITLE
Laravel Nova 4 in Dark Mode problem with TRIX UI 

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#4094] opened 2022-04-25 00:49 UTC
Laravel Version: 9.9.0
Nova Version: 4.2.3
PHP Version: 8.1.4
Database Driver & Version: MYSQL 5.7
Operating System and Version: Ubuntu 20.04.4 LTS
Browser type and version: Brave Versión 1.37.116 Chromium: 100.0.4896.127 (64 bits)

![image](https://user-images.githubusercontent.com/5731295/165004204-5f6a48fc-f2e7-43e1-a7e2-4bb66c5f3976.png)

ANOTHER PROBLEM TRIX EMPTY VALUE WITH REPLICATE

![image](https://user-images.githubusercontent.com/5731295/165004845-47293516-35e0-4c3f-b1d1-89d72fc3dafb.png)

**Comment by crynobone** [comment] 2022-04-25 01:40
Duplicate of https://github.com/laravel/nova-issues/discussions/3955

**Closed by crynobone** 2022-04-25 01:40 UTC
