### ISSUE TITLE
Incorrect Timezone for Value Metrics

### ISSUE THREAD

**Issue by mislam** [laravel/nova-issues#2019] opened 2019-10-08 17:38 UTC
- Laravel Version: 6.1.0
- Nova Version: 2.4.0
- PHP Version: 7.3.4
- Database Driver and Version: MySQL 5.7.25
- Operating System and Version: macOS 10.14.5
- Browser type and version: Google Chrome
- Reproduction Repository: None

### Description

The **Value Metrics** does not honor user's browser timezone. But it does that for the **Trend Metrics**. I checked inside `src/Metrics/Trend.php` in the `aggregate` function. It takes account for the timezone. But inside `src/Metrics/Value.php` there is no indication for timezone. Therefore, the Value Metrics always uses the default UTC only.

**Comment by jbrooksuk** [comment] 2019-10-08 17:54
Duplicate of https://github.com/laravel/nova-issues/issues/1827

A fix is ready, but not deployed yet.

**Closed by jbrooksuk** 2019-10-08 17:54 UTC

**Comment by davidhemphill** [comment] 2019-10-16 02:36
Please post a new issue if there's a new issue with the metrics calculations so we can track it there.

**Comment by mislam** [comment] 2019-10-16 02:48
> Please post a new issue if there's a new issue with the metrics calculations so we can track it there.

Posted #2044
