### ISSUE TITLE
Policies being ignored on initial load

### ISSUE THREAD

**Issue by JHeigle** [laravel/nova-issues#2780] opened 2020-08-03 15:58 UTC
- Laravel Version: 7.22.4
- Nova Version: 3.8.2
- PHP Version: 7.3.17

### Description:
Added a policy to check number of records in a table. If the table has any records it should not allow to user to create more, hiding the create resource button. This works after refresh, but this has to be done manually since navigation is handled with vue. Seems like the policies are being ignored/bypassed. Nova doesnt support its components being modified, but seems like something nova should be able to handle. Anything I'm missing?

**Comment by atmediauk** [comment] 2020-08-03 16:43
Nice, I had just created an example of this issue and was about to post it. If it helps reproduce see - https://github.com/atmediauk/nova-issue-1

**Comment by atmediauk** [comment] 2020-08-20 18:59
Any update/ advice on this would be appreciated as its still an issue we're coming up against. @jbrooksuk @davidhemphill 

On the nova discord it was suggested that setting manual redirects on the resource ```redirectAfterCreate```, ```redirectAfterUpdate``` might help force a policy refresh but that didnt work for us unfortunately :(

In the case of our app. The workflow is as follows:

1. User updates their settings
2. The settings are added as an $appended accessor to their User model.
3. Based on the current settings the user then has/ does not have access to certain parts of the app via policies.

As outlined by @JHeigle without a hard refresh the latest policy is not applied. This means the create button is shown when it shouldn't be and vice versa.

**Comment by davidhemphill** [comment] 2020-09-09 16:56
Duplicate of #1893

**Closed by davidhemphill** 2020-09-09 16:56 UTC
