### ISSUE TITLE
Default search should be case insentitive

### ISSUE THREAD

**Issue by rwdim** [laravel/nova-issues#509] opened 2018-09-10 13:29 UTC
When we search for users in the User resource (or any), it finds Brian, but not brian... Search should be case-insensitive by default (ilike vs like).  

This applies to Scout searches as well if possible.

**Comment by chescos** [comment] 2018-09-10 15:59
Are you using MySQL or PostgreSQL?

**Comment by rwdim** [comment] 2018-09-10 16:40
PostgreSQL

**Comment by rwdim** [comment] 2018-09-12 13:08
I did not.. Its on my list but low..

Tried indexQuery and that doesnt seem to get called.. I pushed it back on my list to look into. Later.

**Comment by rwdim** [comment] 2018-09-14 04:36
Excellent info.. I'll look into it.. thx!

**Comment by taylorotwell** [comment] 2018-09-19 20:36
Fixed in upcoming release.

**Closed by taylorotwell** 2018-09-19 20:36 UTC

**Comment by fede91it** [comment] 2019-02-07 10:53
The issue is still present if you search onto json columns.

The collation set on the table/column is case insensitive.

**Comment by chrisswany** [comment] 2019-03-13 21:26
Still an issue for me on 1.3.2 with Maria DB and Mysql.

**Comment by AbanoubNassem** [comment] 2020-02-05 13:35
any news , or work around this issue ?

**Comment by f-liva** [comment] 2020-02-05 15:07
From September 2018 no news
