### ISSUE TITLE
BelongsTo update uses wrong key

### ISSUE THREAD

**Issue by hjelmdal** [laravel/nova-issues#1468] opened 2019-03-22 01:21 UTC
- Laravel Version: 5.8.5
- Nova Version: 2.0.0
- PHP Version: 7.2.2
- Operating System and Version: Mac OS X Mojave
- Browser type and version: Chrome latest

### Description:
When defining a BelongsTo relation in Nova with custom key pairs the relation breaks on updating the relation, because Nova simply attaches it to the related Primary Key and does not look at the Model configuration. 

### Steps To Reproduce:
Define a Player Model
Define a Club Model with an id and club_id

Make a BelongsTo relation on the Player Model
´´´
return $this->BelongsTo(Club::class,'club_id','club_id');
´´´ 

Try to manually create a model of each in database and attach them

Try updating the Nova Player model and the relation dissapears --> looking in the database the relation is now updated with the Club Models id instead of club_id as intended.

**Comment by dkulyk** [comment] 2019-03-22 06:49
Duplicate of https://github.com/laravel/nova-issues/issues/1342

**Closed by dkulyk** 2019-03-22 06:49 UTC
Labels: duplicate
