### ISSUE TITLE
Date field is broken

### ISSUE THREAD

**Issue by orkhanahmadov** [laravel/nova-issues#2853] opened 2020-09-10 12:27 UTC
- Laravel Version: 8.0.3
- Nova Version: 3.9.2
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 8
- Operating System and Version: MacOS
- Browser type and version: Firefox 80

### Description:
Date fields does send value to backend. 

### Detailed steps to reproduce the issue on a fresh Nova installation:
Here's date field with "required" and "date" rules

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/7041590/92728582-3dafb200-f371-11ea-836a-a151f0e9edf6.png">

Date is set but submitting form shows that Nova sends that field empty:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/7041590/92728746-98490e00-f371-11ea-88ff-6e292de4752f.png">

Selecting date from datepicker throws error in console:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/7041590/92728818-b57ddc80-f371-11ea-8427-e56900fec73c.png">

**Comment by origami1024** [comment] 2020-09-10 14:57
I have this error on Trix field.
The error in chrome console, appears not on submit, but just on typing anything. On chrome and firefox error text is a bit different, on chrome its "TypeError: Cannot read property 'value' of undefined".

**Comment by maxddev** [comment] 2020-09-10 17:12
Can confirm, my Trix fields are suddenly broken with the same error, without changing anything.

**Comment by remxcode** [comment] 2020-09-11 08:43
It seems the reason is this [commit](https://github.com/laravel/nova-js/commit/2ab5cbc2980f6ee10831444292e619c32f2e230e)

**Comment by abdullahnaseer** [comment] 2020-09-11 10:14
Same Issue

**Comment by andreisusanu** [comment] 2020-09-11 11:05
This also affects updating existing Date values.

**Comment by orkhanahmadov** [comment] 2020-09-12 12:46
So the last working, reliable version was `3.8.*`, but that one does not work with Laravel 8.
To go to the working state, we need to downgrade Laravel and every Laravel 8 specific package.

This is so annoying.

**Comment by adojck** [comment] 2020-09-14 11:21
Same here, Date and Trix fields does not work properly. Is there some temporary fix for this? Or is it the only way to get it working to downgrade to `3.8.*`?

**Comment by ykag** [comment] 2020-09-14 12:33
Also having this problem with the latest Nova, on Laravel 7.

**Comment by rikless** [comment] 2020-09-14 12:51
@davidhemphill @driesvints is there a workaround ATM please ?

**Comment by ykag** [comment] 2020-09-14 13:37
Same issue here, Laravel 7, latest version of Nova, also suspect the merge pull request mentioned above is to blame.

**Comment by davidhemphill** [comment] 2020-09-14 18:04
Just pushed a fix to the Date field inside of v3.9.3 👍

**Closed by davidhemphill** 2020-09-14 18:04 UTC

**Comment by davidhemphill** [comment] 2020-09-14 18:11
Also pushed v3.9.4 to address the regression in `Trix` fields. 👍

**Comment by lukas-cierra** [comment] 2020-09-15 10:33
Still having the problem, that the date field is broken. 

- Laravel 8.2.0
- Nova 3.9.4

Anybody else have still this problem?

**Comment by orkhanahmadov** [comment] 2020-09-15 10:53
@lukas-cierra make sure you publish updated nova assets every time you upgrade/downgrade Nova:
```
php artisan nova:publish
```

**Comment by lukas-cierra** [comment] 2020-09-15 10:58
> @lukas-cierra make sure you publish updated nova assets every time you upgrade/downgrade Nova:
> 
> ```
> php artisan nova:publish
> ```

Thanks, that solved the issue 😊

**Comment by larsjanssen6** [comment] 2020-10-25 11:13
I still have this problem. Nova version `3.9`.

**Comment by jrodas4044** [comment] 2020-11-17 03:45
i had the same problem but In nova version 3.15 the bug is fixed

**Comment by comes** [comment] 2020-12-04 19:42
same here. nova 3.16.3

**Comment by ThaDaVos** [comment] 2021-03-23 13:11
It's also broken on 2.12 - but instead of sending no value - it sends the old value to the backend - never updating it...
