### ISSUE TITLE
Customize Metric Color

### ISSUE THREAD

**Issue by mingyoung** [laravel/nova-issues#738] opened 2018-09-29 07:53 UTC
![image](https://user-images.githubusercontent.com/6228858/46242799-6433e700-c3ff-11e8-96d4-fe692d2b29b5.png)

For example, The status `Success` Should be customized to green. :)

**Comment by bonzai** [comment] 2018-09-29 10:16
Duplicate of #306.

**Closed** 2018-09-29 14:13 UTC

**Comment by alexbowers** [comment] 2018-09-29 17:55
Duplicate of #306
