### ISSUE TITLE
2 new tab on view and update action

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#6126] opened 2023-12-22 07:39 UTC
- Laravel Version: 10.10
- Nova Version: 4.32.11
- PHP Version: 8.1

when click view / update with ctrl / command button will open 2 new tab instead of 1

dont have this issue when clicking the index row using ctrl / command

**Comment by crynobone** [comment] 2024-02-12 23:38
Duplicate of #6083

**Closed by crynobone** 2024-02-12 23:38 UTC
