### ISSUE TITLE
Dependent Fields Not Working On Action Fields

### ISSUE THREAD

**Issue by infinitypaul** [laravel/nova-issues#3959] opened 2022-04-12 11:46 UTC
Laravel Version: 9.7.0
Nova Version: 4.1.0
PHP Version: 8.1
Database Driver & Version: mysql 8
Operating System and Version: macos 12.3
Browser type and version: chrome 100

### Description:
Using Dependent field on action has a few bug,  clicking on the dependent field, the other fields dissapear

### Detailed steps to reproduce the issue on a fresh Nova installation:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/15332137/162952869-3fec51ac-d469-4a9d-a8eb-5de6761abbea.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/15332137/162952906-649cc538-1b47-4cd4-b215-265d74ee52d4.png">

On selecting Gift, the other select field dissapears
<img width="751" alt="image" src="https://user-images.githubusercontent.com/15332137/162953028-b8c6389c-f900-4aeb-8bb3-d6cdbef4d693.png">

Here is the code
<img width="846" alt="image" src="https://user-images.githubusercontent.com/15332137/162953092-71b27c6b-90e7-4ec6-a0c2-7c5a94fd1b2d.png">

**Comment by crynobone** [comment] 2022-04-12 11:50
Duplicate of https://github.com/laravel/nova-issues/discussions/3931

**Closed by crynobone** 2022-04-12 11:50 UTC
