### ISSUE TITLE
Metrics\Trend::count() pass $column to $dateColumn atttribute of Metrics\Trend::aggregate()

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#2085] opened 2019-10-28 09:58 UTC
- Nova Version: 2.5.0

```php
protected function aggregate($request, $model, $unit, $function, $column, $dateColumn = null)
```

```php
public function count($request, $model, $unit, $column = null) ...
return $this->aggregate($request, $model, $unit, 'count', $resource->getQualifiedKeyName(), $column);
```

Why is `$column in count()` passed to the `$dateColumn in aggregate(),` but not the `$column`?

Is it a logical error or a variable naming error?

**Comment by davidhemphill** [comment] 2019-10-28 15:29
Closing since there doesn't seem to be an issue described here. Please use the Pull Request template, filling out all of the necessary details to reproduce the issue. Thanks!

**Closed by davidhemphill** 2019-10-28 15:29 UTC
