### ISSUE TITLE
Nova 4: Create user button points to wrong URL

### ISSUE THREAD

**Issue by GerwinV** [laravel/nova-issues#3838] opened 2022-04-06 09:31 UTC
- Laravel Version: 9.7.0
- Nova Version: 4.0.0
- PHP Version: 8.0.2
- Operating System and Version: MacOS
- Browser type and version: Firefox

### Description:
Creating a new user leads to /users/new which renders a 404.
![Schermafbeelding 2022-04-06 om 11 27 03](https://user-images.githubusercontent.com/5094978/161944265-6c2109ac-9a36-4123-bf42-d9208676510d.png)

Users are on resources/users and when I manually change the url to resources/users/new I get to the right page.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Go to resources > users
2. click on 'create user'

Edit: Ok so there is one change I made in: `config/nova.php` which causes the issue:

```
/*
    |--------------------------------------------------------------------------
    | Nova Path
    |--------------------------------------------------------------------------
    |
    | This is the URI path where Nova will be accessible from. Feel free to
    | change this path to anything you like. Note that this URI will not
    | affect Nova's internal API routes which aren't exposed to users.
    |
    */

    'path' => '/nova',
```

I change this path to '/'. After this the problem appears.

_So on a fresh install it works, after editing the path, it doesnt._

**Comment by GerwinV** [comment] 2022-04-06 09:38
This also applies for the `show` and `edit` view.

**Comment by crynobone** [comment] 2022-04-06 09:42
Submit reproducing code to this issue.

**Comment by GerwinV** [comment] 2022-04-06 09:47
@crynobone added one change I did that caused the problem in the opening post of this issue.

So it occurs when the path is changed as stated in the opening post.

**Comment by crynobone** [comment] 2022-04-06 09:49
Duplicate of #3811 

PR has been made but is pending review.

**Closed by crynobone** 2022-04-06 09:49 UTC
Labels: needs more info
