### ISSUE TITLE
Inline Actions: Property or method "actionsEndpoint" is not defined

### ISSUE THREAD

**Issue by dndeus** [laravel/nova-issues#2989] opened 2020-10-24 23:20 UTC
- Laravel Version: 7.x
- Nova Version: 3.13.0
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: MacOs

### Description:
Triggering an inline action when the confirmation modal opens an a vue warning occurred that the property  "actionsEndpoint" is not defined

<img width="1060" alt="Screenshot 2020-10-25 at 2 13 26 AM" src="https://user-images.githubusercontent.com/1295790/97095491-a70d2b00-1668-11eb-8875-ae2786154313.png">

**Comment by crynobone** [comment] 2020-10-25 13:46
![CleanShot 2020-10-25 at 21 42 01](https://user-images.githubusercontent.com/172966/97108880-4420a000-170b-11eb-8379-d114cc6f8466.gif)

I'm unable to replicate the issue and it seem `vendor.js` in the screenshot isn't equal to Laravel Nova 3.13.0:

```json
{
    "/app.js": "/app.js?id=d8d1c17c79297e8f206f",
    "/app.css": "/app.css?id=0b758c2722665b3fefc1",
    "/vendor.js": "/vendor.js?id=3097eff3fea5a307a5a0",
    "/manifest.js": "/manifest.js?id=2d315777967b6001bcf1"
}
```

**Comment by dndeus** [comment] 2020-10-25 14:16
That's bizarre. I did do e fresh nova:publish and still getting the same error

**Comment by crynobone** [comment] 2020-10-26 00:19
Please provide a reproducing code (preferably from a fresh Nova installation) to move forward with this.

**Comment by crynobone** [comment] 2020-11-03 09:01
Closing this for now, I would assume this is most likely usage issue instead of a bug with Laravel Nova.

**Comment by JoshMoreno** [comment] 2021-07-09 01:00
@crynobone It only happens when you [recompile nova's assets to enable vue devtools](https://nova.laravel.com/docs/3.0/customization/frontend.html#vue-devtools) since it's a warning. Vue doesn't show warnings in production. I'm using the latest `3.27.0`.

`InlineActionSelector.vue` has a prop called `endpoint`, but is using `actionsEndpoint` which it doesn't have.

In `resources/js/components/Index/InlineActionSelector.vue`
```vue
-:endpoint="actionsEndpoint"
+:endpoint="endpoint"
```

**Closed** 2021-07-13 05:19 UTC
Labels: bug
