### ISSUE TITLE
Incorrect style for text and other fields in 4.32.16

### ISSUE THREAD

**Issue by msucevan** [laravel/nova-issues#6268] opened 2024-03-10 00:47 UTC
- Laravel Version: #.#.#
- Nova Version: 4.32.16
- PHP Version: 8.2
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
Upgrading to Nova 4.32.16 change the input fields style

- Nova 4.32.15
<img width="1295" alt="image" src="https://github.com/laravel/nova-issues/assets/57497646/3564ee9a-9556-4810-bbea-6b0b1ff301f4">

- Nova 4.32.16
<img width="1257" alt="image" src="https://github.com/laravel/nova-issues/assets/57497646/3410a5bf-59c5-4def-837d-c82d0b453575">

### Detailed steps to reproduce the issue on a fresh Nova installation:
If you want reproduce the issue on a fresh Nova installation please refer to this [repo](https://github.com/msucevan/nova-issue) that was created for another submitted [issue](https://github.com/laravel/nova-issues/issues/6229)

**Comment by webard** [comment] 2024-03-10 09:52
I think it is related to my issue: https://github.com/laravel/nova-issues/issues/6258
It is marked as completed, so probably we waiting for release.

**Comment by crynobone** [comment] 2024-03-11 04:08
Duplicate of https://github.com/laravel/nova-issues/issues/6258

**Closed by crynobone** 2024-03-11 04:08 UTC
