### ISSUE TITLE
Nova branding dark mode did not change the color of the SVG logo

### ISSUE THREAD

**Issue by beshoo** [laravel/nova-issues#5642] opened 2023-06-23 11:03 UTC
The SVG appears to function properly when in dark mode upon logging in, as seen in this image: 
![image](https://github.com/laravel/nova-issues/assets/4635115/10ddf60c-f83f-4bc3-bcd6-d97bd091dbaf)

However, upon logging out, there seems to be an issue, as shown in this image: 

![image](https://github.com/laravel/nova-issues/assets/4635115/f16bf4ea-1b0c-4b09-a038-7261ab467c81)

**Comment by davidhemphill** [comment] 2023-06-24 21:37
Closing because there's not enough information to replicate your issue. Feel free to open a new issue, but fill out the issue template and ideally provided a reproduction repository.

**Closed by davidhemphill** 2023-06-24 21:37 UTC
Labels: needs more info

**Comment by beshoo** [comment] 2023-06-25 01:36
1. Log in to Nova panel.
2. Change the light mode to dark mode.
3. Nova will automatically change the SVG logo fill to dark mode. If the logo is dark, it will become brighter.

Now, when you log out of the panel, you will be redirected to the login form, and the dark mode will be remain the active mode. 

However, please note that Nova will change the logo fill back to the light mode version.

Nova 4.x latest
Php 8.x

**Comment by crynobone** [comment] 2024-08-16 14:40
@rhino-corey see https://laracasts.com/series/laravel-nova-mastery-2023-edition/episodes/3?autoplay=true
