### ISSUE TITLE
Multiple resources with the same name in different namespaces

### ISSUE THREAD

**Issue by bonzai** [laravel/nova-issues#21] opened 2018-08-23 15:15 UTC
- Nova Version: 1.0.5

### Description:

Nova doesn't handle same resource name in different namespaces.

Let's say I've the following resources:

```
/app/Nova/Resources/Plan/Translation.php
/app/Nova/Resources/Theme/Translation.php
/app/Nova/Resources/Plan.php
/app/Nova/Resources/Theme.php
```

It's working for the `Plan` resource, but the `Theme/Translation` resource is trying to load the `Plan` resource (on the details screen of the `Theme` resource):

```
[...]
#2 /.../nova/src/Fields/BelongsTo.php(133): Illuminate\\Database\\Eloquent\\Model->__call('plan', Array)
#3 /.../vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Laravel\\Nova\\Fields\\BelongsTo->resolve(Object(App\\Themes\\ThemeTranslation))
[...]
```

There's probably a bug in the `resolve` method. If the names are unique:
- `app/Nova/Resources/Plan/Translation` → `app/Nova/Resources/PlanTranslation`
- `app/Nova/Resources/Theme/Translation` → `app/Nova/Resources/ThemeTranslation`

everything's fine.

## /app/Nova/Resources/Plan.php

```php
namespace App\Nova\Resources;

use App\Nova\Resource;
use Illuminate\Http\Request;
use App\Billing\Plan as PlanModel;
use App\Nova\Resources\Plan\Translation;

class Plan extends Resource
{
    public static $model = PlanModel::class;

    public function fields(Request $request)
    {
        return [
            HasMany::make('Translations', 'translations', Translation::class),
        ];
    }
}
```

## /app/Nova/Resources/Plan/Translation.php

```php
namespace App\Nova\Resources\Plan;

use App\Nova\Resource;
use App\Nova\Resources\Plan;
use Illuminate\Http\Request;
use App\Billing\PlanTranslation as PlanTranslationModel;

class Translation extends Resource
{
    public static $model = PlanTranslationModel::class;

    public function fields(Request $request)
    {
        return [
            BelongsTo::make('Plan', 'plan', Plan::class),
        ];
    }
}
```

## /app/Nova/Resources/Theme.php

```php
namespace App\Nova\Resources;

use App\Nova\Resource;
use Illuminate\Http\Request;
use App\Themes\Theme as ThemeModel;
use App\Nova\Resources\Theme\Translation;

class Theme extends Resource
{
    public static $model = ThemeModel::class;

    public function fields(Request $request)
    {
        return [
            HasMany::make('Translations', 'translations', Translation::class),
        ];
    }
}
```

## /app/Nova/Resources/Theme/Translation.php

```php
namespace App\Nova\Resources\Theme;

use App\Nova\Resource;
use Illuminate\Http\Request;
use App\Nova\Resources\Theme;
use App\Themes\ThemeTranslation as ThemeTranslationModel;

class Translation extends Resource
{
    public static $model = ThemeTranslationModel::class;

    public function fields(Request $request)
    {
        return [
            BelongsTo::make('Theme', 'theme', Theme::class),
        ];
    }
}
```

**Comment by lesterchan** [comment] 2018-08-25 16:36
I am on 1.0.6 and this issue still persists!

**Comment by TonnyORG** [comment] 2018-09-22 07:59
v1.1.3 and this is still an issue.

**Comment by ThomHurks** [comment] 2018-12-08 15:56
I think I have the same issue. I created a Nova resource called "Script" and I got all kinds of weird "Undefined index" errors. I had to rename it "Script2" and then all was fine.

**Comment by bonzai** [comment] 2018-12-08 16:11
You can try overwriting `uriKey` method:

```php
/**
 * Get the URI key for the resource.
 *
 * @return string
 */
public static function uriKey()
{
    return 'skript';
}
```

**Comment by ThomHurks** [comment] 2018-12-08 16:18
@bonzai Changing the ```uriKey``` to something else is indeed a better workaround than renaming the file to "Script2.php", thanks! Would be nice if the Nova devs could fix this for real though ;) It seems there's not much activity on the Nova issue tracker?

**Comment by dkulyk** [comment] 2019-01-13 15:35
All activity in the private repository.

I think it issue cannot be fixed. Different projects have different namespaces. 
I used:
 - `\App\Nova\`
 - `\App\Nova\Resources\`
 - `\Package\Nova\`
 - `\Package\Resources\`
 - `\Package\Nova\Resources\`

For resolving this issue you can override `uriKey` method as @bonzay has said.

@bonzai, you may close an issue or make a PR? :)

**Comment by dkulyk** [comment] 2019-02-26 09:00
This is not a bug. You can override `uriKey` method in a resource for change default behavior

**Closed by dkulyk** 2019-02-26 09:00 UTC
