### ISSUE TITLE
Value returned by displayUsing from a datetime field is not displayed on index

### ISSUE THREAD

**Issue by daniouyea** [laravel/nova-issues#4685] opened 2022-08-11 10:19 UTC
- Laravel Version: 9.24.0
- Nova Version: 4.12.14
- PHP Version: 8.0.5

### Description:
Value returned by displayUsing from a datetime field is not displayed on index.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a resource with a datetime field.
```
DateTime::make('Date')
    ->onlyOnIndex()
    ->displayUsing(fn ($value) => "test"),
```
The field is shown empty.

**Comment by crynobone** [comment] 2022-08-11 10:28
Duplicate of https://github.com/laravel/nova-issues/issues/4665, has been fixed but pending next release.

**Closed by crynobone** 2022-08-11 10:28 UTC
