### ISSUE TITLE
Policies not working for custom navigation menu

### ISSUE THREAD

**Issue by SupchickCode** [laravel/nova-issues#4069] opened 2022-04-21 12:37 UTC
- Laravel Version:8.65
- Nova Version: 4.2.3
- PHP Version: 7.4
- Database Driver & mysql 5.7
- Operating System and Version: elementary os 5.1

### Description:
Policy dosent work  when we edit navigation bar like in docs (`https://nova.laravel.com/docs/4.0/customization/menus.html`)

On first img we can see only 8 menu items (cause this auth user can see only this items) We use default navbar from `the box`
![photo_2022-04-21_15-26-29](https://user-images.githubusercontent.com/58991461/164457729-c0487c24-d818-4c36-8529-a12767ed10e4.jpg)

On second img we see how in NovaServiceProvider i use custom nova menu
![image](https://user-images.githubusercontent.com/58991461/164458321-f373a1dc-5378-4c2a-8590-b175057b39ed.png)

And finally on the 3rd picture we can see after use custom nova menu all politicians were ignored
![image](https://user-images.githubusercontent.com/58991461/164458728-39d39d92-e36a-43c5-810d-a73b8713f258.png)

Of course, we cannot follow this link to the menu, which means that the policy for requesting a resource is working, but there is no menu item display

**Comment by crynobone** [comment] 2022-04-21 12:51
Duplicate of https://github.com/laravel/nova-issues/discussions/3933

**Closed by crynobone** 2022-04-21 12:51 UTC
