### ISSUE TITLE
Showing the panes when editing

### ISSUE THREAD

**Issue by sergionader** [laravel/nova-issues#712] opened 2018-09-27 16:38 UTC
Is there a way of showing the panels when editing? 
In my case, they only show when in the view mode. 
Thank you!
Sergio Nader

**Comment by dillingham** [comment] 2018-09-27 16:47
Search the issues before asking questions

**Comment by dillingham** [comment] 2018-09-27 17:02
This doesn't seem to be an issue. This is a question.
Maybe join the [Discord chat ](https://discord.gg/DgdFRpd) or [Larachat slack](https://larachat.co/slack) or ask on [stackoverflow](https://stackoverflow.com/questions/tagged/laravel-nova)
All of those options have people willing to help and answer questions! 😄

**Comment by davidhemphill** [comment] 2018-09-27 20:01
Duplicate of #29

**Closed by davidhemphill** 2018-09-27 20:01 UTC
