### ISSUE TITLE
DateTime field displayUsing not setting displayedAs

### ISSUE THREAD

**Issue by jeffreyzant** [laravel/nova-issues#4681] opened 2022-08-10 08:03 UTC
- Laravel Version: 9.23.0
- Nova Version: 4.12.14
- PHP Version: 8.1.2

### Description:
The overrwritten method resolveUsingDisplayCallback inside the DateTime class does not implement the logic to set the displayedAs value as defined inside the base Field class. This results in a null value when using the ->displayUsing method.

```php
// Field.php
protected function resolveUsingDisplayCallback($value, $resource, $attribute)
{
    $this->usesCustomizedDisplay = true;
    $this->displayedAs = call_user_func($this->displayCallback, $value, $resource, $attribute);
}

// DateTime.php
protected function resolveUsingDisplayCallback($value, $resource, $attribute)
{
    $this->usesCustomizedDisplay = true;

    if ($value instanceof DateTimeInterface) {
        $this->originalValue = $value instanceof CarbonInterface
            ? $value->toIso8601String()
            : $value->format(DateTimeInterface::ATOM);
    }

    $this->value = call_user_func($this->displayCallback, $value, $resource, $attribute);
}
```

### Possible solution:
I believe the DateTime field should call the parent method for the resolveDisplayUsingCallback. For example:

```php
// DateTime.php
protected function resolveUsingDisplayCallback($value, $resource, $attribute)
{
    if ($value instanceof DateTimeInterface) {
        $this->originalValue = $value instanceof CarbonInterface
            ? $value->toIso8601String()
            : $value->format(DateTimeInterface::ATOM);
    }

    parent::resolveUsingDisplayCallback($value, $resource, $attribute);
}
```

**Comment by crynobone** [comment] 2022-08-10 08:05
Duplicate of #4665, has been fixed but pending next release.

**Closed by crynobone** 2022-08-10 08:05 UTC
