### ISSUE TITLE
ActionController erroring on custom relations

### ISSUE THREAD

**Issue by ragingdave** [laravel/nova-issues#3007] opened 2020-10-29 12:31 UTC
- Laravel Version: 8.10.0
- Nova Version: 3.14
- PHP Version: 7.4.3

### Description:
A recent change is causing an error when a relation isn't using the primary key as part of a relation. This isn't a requirement in laravel itself, and there are likely certain business reasons (or legacy application reasons) where a relation, for instance a HasMany relation, where the key being used on the related resource isn't the primary.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Have a model that relates on the non-primary key.
Example:
Product HasMany Prices where prices doesn't use the primary key of either model, but a secondary key for both.

Price:
id, sku, price

Product:
id, sku, name

Product:
```
public function prices() {
    return $this->hasMany(Price::class, 'sku', 'sku');
}
```
This results in an error because a recent change causes the ActionController to ultimately use whereKey, which will look up the resource based on the primary key and not the configured relation as it did before.

**Comment by ragingdave** [comment] 2020-10-29 12:33
I will add that it would delegate entirely to the relation so it allows other customizations on the relation as well as it did before. For example there is a package that enables some minimal composite key functionality that works currently (for the most part) in Nova, and I'm worried that moving more towards manual lookup could break something like that.

**Comment by crynobone** [comment] 2020-10-29 14:33
I feel there some missing information here.

> Product HasMany Prices where prices doesn't use the primary key of either model, but a secondary key for both.

Mapping the relations via secondary should still be possible as you still have `id`, and `whereKey` will be able to find `getKeyName` as long as it used by the model. Would be best if you share how you configure the Model properties for both models, and resources file.

> I will add that it would delegate entirely to the relation so it allows other customizations on the relation as well as it did before.

Customizations is what make the software powerful, what we're lacking right now is having enough tests to cover various use cases, and this usage is not tested right now, and that the reason why I wanted to document this properly so we can build proper tests to cover the scenario.

**Comment by ragingdave** [comment] 2020-10-29 15:04
I can certainly provide some more concrete specifics. So I have a product with price records associated to it. The issue at least for my specific example, is that when whereKey is called, the id passed is null from the following request:

```
/nova-api/prices/actions?relationshipType=hasMany&viaRelationship=prices&viaResource=products&viaResourceId=93385
```

This is a bit more complex example, as the prices model comes from a legacy source and uses a composite key. That specific customization doesn't have to do with this specific relation as the relation is configured as:

```
return $this->hasMany(Price::class, 'sku_key', 'sku');
```

This is all on secondary keys and if I specifically remove the composite key configuration on the price model and make the model act as though it's just a standard model, it does in fact work. HOWEVER, the id passed to whereKey is still null. This ends up making a db call, for a random model that's just first in the list. I'm also wondering if this could cause an issue for when the db has no records at all, as the load of a model would be null.

I will say part of the issue I'm having is that my whereKey override to account for a legacy (non-standard) db composite keys is partly at fault and what brought this to my attention, but is a breaking change for a minor version bump. I'm also not sure what exactly was wrong with the original implementation or if maybe a different fix would work instead of this.

**Comment by crynobone** [comment] 2020-10-30 00:03
Can't fully replicate the issue without proper example. 

```
return $this->hasMany(Price::class, 'sku_key', 'sku');
```

Were does this come from? The `sku_key` is not mentioned in the original post. 

As I mention earlier we need to be able to build an replicated example so that we can have our tests covered for the scenario. Solving `whereKey` is simple, but without tests to ensure code are working and prevent future problem are more important, which why I'm asking a lot of question. 

![image](https://user-images.githubusercontent.com/172966/97644681-eb903080-1a85-11eb-9495-3ed32e9046d0.png)

This what I got so far and adding the following doesn't seem to catch any error:

```php
$resource = $request->newResourceWith(
            ($request->viaRelationship()
                ? $request->findParentModel()->first()
                : $request->findModelQuery()->first()) ?? $request->model()
        );
```

But then again, removing it also works fine. So would like more detail in order to close this ticket.

**Comment by ragingdave** [comment] 2020-10-30 16:16
Sorry about the discrepancy I pulled directly from my actual code rather than just typing from memory. In terms of sku vs sku_key, that was just a mistake from my memory but is irrelevant for a difference. The core of it was about the primary vs secondary keys being used for the relation but based on what I found upon further investigation, turns out to be the extraneous db call that loads a model that potentially doesn't exist.

The source of my issue was partly due to my overriding of whereKey to cover the specialty composite key functionality I have to support. The reason I reported it was due to the BC that added a query without a valid id causing an issue in my previously working code. I believe if that is resolved, then perhaps my code will end up working fine as well. 

If possible, would I be able to test against the code you are adding to see if that resolves my issue? It's not to be selfish but to see if other deep customizations akin to mine would work.

**Comment by crynobone** [comment] 2020-11-02 02:14
> If possible, would I be able to test against the code you are adding to see if that resolves my issue? It's not to be selfish but to see if other deep customizations akin to mine would work.

After further checking the changes just invalid. Since you don't actually want to receive the parent resource. 

> The source of my issue was partly due to my overriding of whereKey to cover the specialty composite key functionality I have to support.

Can you share some code related to this. I'm unable to proceed at the moment as I unable to reproduce the error.

**Comment by ragingdave** [comment] 2020-11-02 13:50
Like I said it's specific to my implementation and assuming that id couldn't be null. The specific issue happens around here in my overridden whereKey method on a custom Builder:

```
    public function whereKey($id)
    {
        if (is_array($this->model->getKeyName())) {
             ... MORE CODE HERE ...
            $parts = explode($this->model->getCompositeKeySeparator(), $id);
// IN THE FOREACH IT WILL BLOW UP ON NULL AS $parts IS EMPTY
            foreach ($this->model->getKeyName() as $ndx => $k) {
                $this->query->where($k, $parts[$ndx]);
            }

            return $this;
        }

        return parent::whereKey($id);
    }
```
There is other code and implementation details that I'm not sure if I should/can share, but basically this and quite a bit more code allow a model to have a composite primary key and be addressed accordingly. We basically use the model as one might think by using an array for defining the primaryKey property.

Again I would say that it's not my specific overrides at least in this case, but the fact that whereKey was being called and a model was being looked up from the db at all when there was no reason to.

**Closed** 2020-11-04 15:44 UTC
Labels: needs more info
