### ISSUE TITLE
Allowing to align fields hirzentally

### ISSUE THREAD

**Issue by avifatal** [laravel/nova-issues#3228] opened 2021-02-06 07:07 UTC
Hi,
What would it need to suuport something like:

![image](https://user-images.githubusercontent.com/12430740/107111691-a769b480-685a-11eb-871e-a82385f42a38.png)

Tow different fields at the same row

Thanks

**Comment by crynobone** [comment] 2021-02-06 07:12
Duplicate of #3192

**Closed** 2021-02-06 07:12 UTC
