### ISSUE TITLE
Current page doesn't update once you delete all records on that page

### ISSUE THREAD

**Issue by AdamFullstripe** [laravel/nova-issues#865] opened 2018-10-20 08:08 UTC
Hello guys,

I want to report a bug:
We got classical Users, Posts situation: User hasMany Posts, Post BelongsTo User. 
I am on the User detail page and clicking through pagination on Posts Card and let say that I decide to delete all Posts from my last pagination page (let say that the last page of Posts has number 5). When I delete last Post from page 5, Nova should show me Posts from page 4. Instead, Nova shows me an empty page with an option to create a new Post.

I understand that searchquery result for page 5 is now empty, but you know, It shouldn't work like that.

Thank you

**Comment by bonzai** [comment] 2018-10-20 20:14
Duplicate of #464.

**Closed** 2018-10-24 07:36 UTC
