### ISSUE TITLE
BelongsToMany Relationsship if "created" method in policy returns false

### ISSUE THREAD

**Issue by jkniest** [laravel/nova-issues#567] opened 2018-09-14 16:07 UTC
Hey,

I have a "belongsToMany" relationsship between two models. But if one of the models has a policy and the "created" method returns false, the attach button disappears from the other model / nova page.

Model 1 (for example User)
- Has a policy
    - "created" method returns false
    - "attachCompany" method returns true
    - "attachAnyCompany" method also returns true
- Has a "belongsToMany" relationship with "Company"

Model 2 (company)
- Has no policy at all
- Has a "belongsToMany" relationship with "user".

---

If the created method on the user model returns true:

<img width="1264" alt="bildschirmfoto 2018-09-14 um 18 06 40" src="https://user-images.githubusercontent.com/15618191/45561827-f2796c00-b848-11e8-82ce-af58fe442129.png">

And if the created method returns "false":

<img width="1210" alt="bildschirmfoto 2018-09-14 um 18 07 29" src="https://user-images.githubusercontent.com/15618191/45561868-0f15a400-b849-11e8-8228-6b14036e10b6.png">

Thanks for you hard work!

**Comment by jsphpl** [comment] 2018-09-18 10:05
Related to / duplicate of #111, #247

**Closed** 2018-09-18 13:21 UTC
