### ISSUE TITLE
Disable action logging for models without Actionable trait

### ISSUE THREAD

**Issue by mikkellindblom** [laravel/nova-issues#4415] opened 2022-06-13 13:20 UTC
- Laravel Version: 9.17.0
- Nova Version: 4.8.1
- PHP Version: 8.0

### Description:

"Update" and "Create" events are saved in the Action log for models without the ```Laravel\Nova\Actions\Actionable``` trait. This behaviour is unexpected in my opinion. Currently there is no way to disable action logging for specific models.

**Comment by vFire** [comment] 2022-06-13 20:47
Agree

**Comment by crynobone** [comment] 2022-06-15 02:52
Marking this as "Idea & Feature Request" since it changes the expected behavior of Nova. "Unexpected" as it may it still is the current behavior.

**Closed as completed** 2022-06-15 02:52 UTC
