### ISSUE TITLE
locale thousand separator in metrics

### ISSUE THREAD

**Issue by NormanHuth** [laravel/nova-issues#3165] opened 2021-01-14 03:58 UTC
- Laravel Version: 8.21.0
- Nova Version: 3.19.1
- PHP Version: 7.4

The thousand separator in the metrics is not correct. How to change it? (We have a dot for it and not a comma)
```php
    public function calculate(NovaRequest $request)
    {
        return $this->count($request, TwitchUser::class)->format([
            'spaceSeparated' => true,
            'mantissa'       => 0,
        ]);
    }
```

**Comment by crynobone** [comment] 2021-01-14 05:08
Shouldn't it follow https://nova.laravel.com/docs/3.0/metrics/defining-metrics.html#value-result-formatting

**Comment by NormanHuth** [comment] 2021-01-14 05:27
The result with `->format('0,0')` is wrong:
192,525

The result with `->format('0.0')` is wrong too:
192,525.0

Correct would be:
192.525

**Comment by crynobone** [comment] 2021-01-14 11:48
Duplicate of #2869 but looking at sending a PR today.

**Closed by crynobone** 2021-01-14 11:48 UTC
Labels: discussion, needs more info

**Comment by marijoo** [comment] 2021-01-25 08:24
@NormanHuth Don't you have to use the _old format_? See https://numbrojs.com/old-format.html

**Comment by NormanHuth** [comment] 2021-01-25 08:45
@marijoo After all, the old and the new did not work. (Linked in the [docs](https://nova.laravel.com/docs/3.0/metrics/defining-metrics.html#value-result-formatting) is the old). But that should have been fixed in the last update:

> **v3.20.0**
> Nova now includes all default languages for its Numbro dependency. [#1168](https://github.com/laravel/nova/pull/1168)

I keep the project up to date, but I haven't tested it yet. I hope that you just have to change locale...
