### ISSUE TITLE
Nova isn't truly compatible with custom domains

### ISSUE THREAD

**Issue by brenjt** [laravel/nova-issues#2820] opened 2020-08-26 15:39 UTC
- Laravel Version: 7
- Nova Version: All version
- PHP Version: 7.4

Nova isn't truly compatible with custom domains. 

This method is the culprit. It doesn't take the domain, if set, into account.
```
   /**
     * Determine if the given request is intended for Nova.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    protected function isNovaRequest($request)
    {
        $path = trim(Nova::path(), '/') ?: '/';

        return $request->is($path) ||
               $request->is(trim($path.'/*', '/')) ||
               $request->is('nova-api/*') ||
               $request->is('nova-vendor/*');
    }
```

To reproduce use a custom domain and a base path like so:

```env
NOVA_DOMAIN_NAME=subdomain.somesite.com
NOVA_GUARD=admins
```

```php
/// config/nova.php
'path' => '/',
```

When redirecting users on the main app to the their dashboard, which is at the root of the main domain `somesite.com`. Nova gets loaded and then determines that you are not logged in and redirects you back to the login page.

**Comment by milewski** [comment] 2020-08-27 04:12
I think this happens because your root domain cookies are not shared with your subdomain cookies.. therefre whoever is logged in your root domain is not on any subdomains hance login again

**Comment by davidhemphill** [comment] 2020-08-27 15:48
I believe @milewski is correct here. The cookie domain needs to be just the root domain for this to work, so closing since it's on the user-end. Feel free to reply if you can demonstrate a bug after ensuring that. Thanks!

**Closed by davidhemphill** 2020-08-27 15:48 UTC

**Comment by brenjt** [comment] 2020-08-27 16:07
Cookies didn't actually have anything to do with this bug. 

The `NovaCoreServiceProvider` is loaded everywhere in the application due to the `composer.json` configuration

```
"extra": {
    "laravel": {
        "providers": [
            "Laravel\\Nova\\NovaCoreServiceProvider"
        ],
    }
}
```
So this'll load on my main domain and my subdomain. `somesite.com` and `subdomain.somesite.com`

The boot method then loads the ServeNova middleware

```
public function boot()
{
    ....
    Route::middlewareGroup('nova', config('nova.middleware', []));

    $this->app->make(HttpKernel::class)
                    ->pushMiddleware(ServeNova::class);
}
```

That middleware will detect if the current request is for nova
```
public function handle($request, $next)
{
    if ($this->isNovaRequest($request)) {
        app()->register(NovaServiceProvider::class);

        NovaServiceProviderRegistered::dispatch();
    }

    return $next($request);
}
```

My environment has separate domains with both having a root page that requires authentication via different authentication guards. 

```
APP_URL=http://somesite.com <- uses the users auth guard
NOVA_DOMAIN_NAME=subdomain.somesite.com <- uses the admins auth guard
```

This site (http://somesite.com) has the following urls
- `/` user dashboard
- `/login` user login

Nova (http://subdomain.somesite.com) has the same urls
- `/` nova dashboard
- `/login` nova login

The `isNovaRequest` inside the `ServeNova` middleware doesn't take into account the domain so Nova thinks the root path is a part of Nova and proceeds to load the `NovaServiceProvider` which in turn loads the routes and auth guard checks. It sees that I am not authenticated via the `admins` auth guard and therefore redirects me to `/login`. `/login` isn't a part of the `isNovaRequest` logic so it determines that it is not a Nova request and loads my login page.

Rinse and repeat. Each time a user logs in, Nova thinks it should load on the `somesite.com/`and kicks my user out and back to the login page.

Hopefully that helps illustrate the problem better.

**Comment by brenjt** [comment] 2020-09-04 16:42
@davidhemphill Please look over this again. I'd love to have this fixed

**Comment by ThaDaVos** [comment] 2021-05-06 11:49
@davidhemphill  - please look at this again as it's unrelated to any cookies stuff and is really cumbersome... this needs to be fixed...

**Comment by crynobone** [comment] 2021-05-06 13:19
https://github.com/nova-issues/issue-2820/commit/bdfc60e06a8efdb6403483244e06b7d523b89f23

1. From the example I added `APP_DOMAIN_NAME` environment variable and have `app.domain` configuration.
2. It is best to register each route under its own `Route::domain()`

https://user-images.githubusercontent.com/172966/117304810-bd663000-aeb0-11eb-986b-c77dd830b22e.mp4

**Comment by ThaDaVos** [comment] 2021-05-06 14:33
@crynobone is this an example for the issue?

**Comment by ThaDaVos** [comment] 2021-05-06 14:34
We expect a fix like the following - this will (hopefully) disable  Laravel Nova on the routes with a different domain then configured - we still have issues with some ValidationException catcher somewhere:
![image](https://user-images.githubusercontent.com/5251028/117316430-e4a90700-ae88-11eb-8ad7-ea77341b6f5c.png)

**Comment by crynobone** [comment] 2021-05-06 14:42
That method seem outdated, are you using latest Nova version?

**Comment by ThaDaVos** [comment] 2021-05-06 14:46
No, it's on Nova 2 as we're stuck on Laravel 6 LTS (Company Policy to use LTS)

**Comment by crynobone** [comment] 2021-05-06 14:48
Laravel Nova 2 no longer received any bug fixes. Please upgrade to Nova 3 as soon as possible.

**Comment by ThaDaVos** [comment] 2021-05-06 14:49
@crynobone - we can't as we're waiting for the next LTS - but still as far as I know it's still in issue in Nova 3 - I made the screenshot in a Nova 2 project as I had it currently open

**Comment by crynobone** [comment] 2021-05-06 14:54
I just made a repository above to show that it is indeed can be done with Laravel Nova 3. 

If you can create a reproducing application on Laravel Nova 3 I can look at it again but otherwise there nothing to be done for this.

**Comment by 7ammer** [comment] 2024-02-20 11:18
This is an issue in v4 btw.
