### ISSUE TITLE
UserMenu issue into mobile version

### ISSUE THREAD

**Issue by andreapollastri** [laravel/nova-issues#4483] opened 2022-06-26 15:35 UTC
- Laravel Version: 9.18.0
- Nova Version: 4.10.1
- PHP Version: 8.1.7
- Database Driver & Version: MySql 8
- Operating System and Version: Mac Os 12.4
- Browser type and version: Google Chrome 103.0.5060.53

### Description:
When Nova runs in "mobile" version I was not able to open and view User Menu (as image attached here: [https://ibb.co/DrqbsNj](https://ibb.co/DrqbsNj)). I tried also to test it via iPhone and the issue is the same.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Open Nova
- Resize reducing browser window (until Nova changes its layout in mobile version)
- Open Hamburger Main Menu
- Click on User Menu

**Comment by crynobone** [comment] 2022-06-27 02:15
As far as I can tell this has is a duplicate of #4434 and fixes has been merged but not yet released.

![CleanShot 2022-06-21 at 10 16 02](https://user-images.githubusercontent.com/172966/174703709-df95f02a-6fe4-465b-a8f9-81ddee4e9aa0.gif)

**Closed by crynobone** 2022-06-27 02:15 UTC
