### ISSUE TITLE
Custom field can't resolve 'form-backend-validation', 'vuex' and '@inertiajs/inertia' 

### ISSUE THREAD

**Issue by vaites** [laravel/nova-issues#3940] opened 2022-04-11 09:00 UTC
- Laravel Version: 9.7.0
- Nova Version: 4.1.0
- PHP Version: 8.1.3
- Database Driver & Version: MySQL 8.0
- Operating System and Version: Windows 10
- Browser type and version: Microsoft Edge 100
- Reproduction Repository: https://github.com/###/###

### Description:

Calling `npm run dev` fails on custom field because Laravel Nova's dependencies can't be resolved:

```
ERROR in ../../vendor/laravel/nova/resources/js/mixins/HandlesFormRequest.js 1:0-49
Module not found: Error: Can't resolve 'form-backend-validation' in 'C:\Develop\htdocs\nova\vendor\laravel\nova\resources\js\mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/HandlesValidationErrors.js 1:0-49
Module not found: Error: Can't resolve 'form-backend-validation' in 'C:\Develop\htdocs\nova\vendor\laravel\nova\resources\js\mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/PreventsFormAbandonment.js 7:0-48
Module not found: Error: Can't resolve 'vuex' in 'C:\Develop\htdocs\nova\vendor\laravel\nova\resources\js\mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/PreventsFormAbandonment.js 8:0-45
Module not found: Error: Can't resolve '@inertiajs/inertia' in 'C:\Develop\htdocs\nova\vendor\laravel\nova\resources\js\mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/PreventsModalAbandonment.js 7:0-48
Module not found: Error: Can't resolve 'vuex' in 'C:\Develop\htdocs\nova\vendor\laravel\nova\resources\js\mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/packages.js 13:0-49
Module not found: Error: Can't resolve 'form-backend-validation' in 'C:\Develop\htdocs\nova\vendor\laravel\nova\resources\js\mixins'
```

I tried installing these dependencies on field's dependencies but the result is the same.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a new field (answer _yes_ to all questions):

```
php artisan nova:field test/field
cd nova-components/Field
npm run dev
```

I had to rename `mix.js` to `nova-mix.js` to solve [this bug](https://github.com/laravel/nova-issues/issues/3844).

**Comment by crynobone** [comment] 2022-04-11 09:11
Duplicate of #3856

**Closed by crynobone** 2022-04-11 09:11 UTC

**Comment by vaites** [comment] 2022-04-11 09:29
Thanks @crynobone. Sorry for the duplicate. Will take a look to the solution posted there.

**Comment by stonkeep** [comment] 2022-04-26 20:21
Any solution?

**Comment by classicalguss** [comment] 2023-06-17 13:07
Any solution? A lot of duplicates, and a lot of closing, and yet no solution.

**Comment by crynobone** [comment] 2023-06-17 13:23
The Custom Field documentation already show the solution, check the requirement related to `npm` usage.

If anyone else have a new issue, create a new bug report with reproducing steps and code.
