### ISSUE TITLE
nova:tool command fails due to no-interaction option

### ISSUE THREAD

**Issue by gurgentil** [laravel/nova-issues#2707] opened 2020-06-26 21:39 UTC
- Laravel Version: 7.9
- Nova Version: 3.7

The latest release 3.7, `Added --no-interaction option to make:tool command to speed up process. #901` broke the `php artisan nova:tool` command. It fails with the message "An option named 'no-interaction' already exists."

**Comment by davidhemphill** [comment] 2020-06-29 15:03
Duplicate of #2714

**Comment by bfinlay** [comment] 2020-06-30 17:29
This also interferes with `php artisan list --format=xml` which returns the same error message `An option named 'no-interaction' already exists.`.

Verified by changing ToolCommand.php line 20 from
`protected $signature = 'nova:tool {name} {--no-interaction : Do not ask any interactive question.}';`

to 
`protected $signature = 'nova:tool {name} {--no-interaction-nova : Do not ask any interactive question.}';`

and re-running `php artisan list --format=xml` which runs without error after the change.

The command `php artisan list --format=xml` is used by PHPStorm when adding artisan to "Command Line Tool Support", so this results in breaking the PHPStorm "run anywhere" support.

![image](https://user-images.githubusercontent.com/1757856/86157676-609a2c00-bacd-11ea-96c9-3da6d7b8ffcd.png)

**Comment by davidhemphill** [comment] 2020-06-30 21:38
This has been fixed and will be included in the next release. 👍

**Closed by davidhemphill** 2020-06-30 21:38 UTC

**Comment by davidhemphill** [comment] 2020-06-30 21:51
Just pushed latest version with fix!

**Comment by bfinlay** [comment] 2020-06-30 21:58
Verified 
* `composer update`, `
* verified 3.7.1 installed and verified ToolComand.php was updated
* verified `php artisan list --format=xml` works
