### ISSUE TITLE
4.22.0 Trix duplicates the content every save

### ISSUE THREAD

**Issue by xuchunyang** [laravel/nova-issues#5333] opened 2023-02-18 08:28 UTC
- Laravel Version: 9.52.0
- Nova Version: 4.22.0
- PHP Version: 8.2.0
- Database Driver & Version: mysql 8
- Operating System and Version: #.#
- Browser type and version: Chrome 109.0.5414.119
- Reproduction Repository: https://github.com/###/###

### Description:

Trix duplicates contents whenever saves

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a Post model and migration

```
        Schema::create('posts', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->longText('body');
            $table->timestamps();
        });
```

2. Create a Nova resource for the model via `php artisan nova:resource Post`

```
        return [
            ID::make()->sortable(),
            Text::make('title'),
            Trix::make('body'),
        ];
```

3. Change the content of the body and save, the content gets duplicated

https://user-images.githubusercontent.com/4550353/219850276-2901b4cc-7fdb-43b2-aa98-6294caadfdcd.mp4

**Comment by xuchunyang** [comment] 2023-02-18 08:33
Note that Nova 4.21.0 + Laravel 9 works fine.

**Comment by crynobone** [comment] 2023-02-18 08:52
Duplicate of #5303 and will be available on next release.

**Closed** 2023-02-18 08:53 UTC
