### ISSUE TITLE
Tag field should apply `withSubtitles` props.

### ISSUE THREAD

**Issue by mrleblanc101** [laravel/nova-issues#4970] opened 2022-10-25 23:55 UTC
- Laravel Version: 9.34.0
- Nova Version: 4.17.0
- PHP Version: 8.1
- Database Driver & Version: mariadb 10.4
- Operating System and Version: macOS 12.6
- Browser type and version: Chrome 105

### Description:
When I select an option from the autocomplete, I have a Chrome window likeif i tried to exit the page.
Also is the `No additionnal information` line necessary ? Feels like this should display the subtitle but should be hidden if there is no subtitle.
![2022-10-25 19 52 32](https://user-images.githubusercontent.com/17392251/197903061-20138771-4875-42db-95a7-dbcd8747940a.gif)

**Comment by mrleblanc101** [comment] 2022-10-26 00:12
Also is the `No additionnal information` line necessary ? Feels like this should display the subtitle but should be hidden if there is no subtitle.
I can open a seperate issue just for that if needed.
![Capture d’écran, le 2022-10-25 à 20 11 31](https://user-images.githubusercontent.com/17392251/197904876-f93244ff-0440-4c2a-ad03-a86d72f53214.png)

**Comment by crynobone** [comment] 2022-10-26 06:16
Duplicate of #4969 

Also the secondary line is consistent with using `BelongsToMany::searchable()`

**Comment by mrleblanc101** [comment] 2022-10-26 12:45
@crynobone I have nothing against the secondary line, but it should only be displayed when there is a $subtitle defined. That's how it work for searchable

**Closed** 2022-10-26 15:09 UTC
Labels: bug
