### ISSUE TITLE
Caret color on dark mode is not visible

### ISSUE THREAD

**Issue by jamesblackwell** [laravel/nova-issues#5146] opened 2022-12-08 10:53 UTC
- Laravel Version: 9.43.0
- Nova Version: 4.19.4
- PHP Version: 8.1.3
- Operating System and Version: Mac 12.5.1
- Browser type and version: Chrome 107.0.5304.121

### Description:
Cursor is too dark to see in a markdown field:

<img width="221" alt="image" src="https://user-images.githubusercontent.com/1156154/206428644-eae6749c-04aa-4592-97d5-17dad6bebbcd.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:

Install nova, enable dark mode and you will not be able to the cursor

**Comment by crynobone** [comment] 2022-12-08 11:02
Duplicate of #5047

**Closed by crynobone** 2022-12-08 11:02 UTC
